### ISSUE TITLE
Upstream Kubernetes Deprecation: Controller Manager & Scheduler show as Unhealthy in clusters that do not have component status for them (Azure, Tectonic among others)

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11496]
**Rancher versions:** 2.0 master 2/20

**Steps to Reproduce:**
1.  Create a Azure AKE cluster
2.  Wait for it to activate and go to dashboard

**Results:**  The Controller Manager and Scheduler stay in unhealthy state.
![image](https://user-images.githubusercontent.com/11514927/36444885-c156ba80-1639-11e8-84a2-5872d5e1f8a8.png)

gz#11712
gz#12343

**Comment by nathan-jenan-rancher** [comment]
This is a bug with Azure that we can't fix ourselves, here is the issue we opened with them:

https://github.com/Azure/AKS/issues/173

**Comment by JasonvanBrackel** [comment]
This appears to be an upsteam kubernetes issue, that is affecting AKS by proxy affecting Rancher.

@nathan-jenan-rancher linked to this https://github.com/kubernetes/kubernetes/issues/19570 in the conversation on https://github.com/Azure/AKS/issues/173.  This is complicated by the fact that componentstatus is broken and likely be deprecated before it's fixed.

See https://github.com/kubernetes/features/issues/553
and
https://github.com/kubernetes/kubernetes/issues/18610

**Comment by codedevote** [comment]
As far as Is understand, there is currently no way to create an AKS cluster using rancher that will actually work as expected due to this issue. Is there any workaround or advice on how to overcome this limitation?

**Comment by JasonvanBrackel** [comment]
@codedevote These clusters are fully functional, the health reporting what is wrong.  If you were to create an AKS cluster from the Azure Portal and import it into rancher, this cluster would be completely functional, but the controller manager and scheduler will show unhealthy in Rancher.  Rancher can still manage workload on the cluster as designed.

**Comment by hadifarnoud** [comment]
I'm not on Azure and still have the same issue

**Comment by JasonvanBrackel** [comment]
It's a Kubernetes problem.  It's surfaced by any implementation that do not host the scheduler and the kubeapi-server on the same node.  The underlying code makes incorrect assumptions around this layout as it's calling localhost in areas where that's no longer a sound assumptions.  It doesn't surface on most implementation as most implementations use a traditional Kubernetes "master" node, but it's not a requirement.  Hetzner is likely architected similar to Azure in that manner to surface there error.

**Comment by ablekh** [comment]
@JasonvanBrackel Would you have any thoughts/advice/help on https://github.com/rancher/rancher/issues/15986#issuecomment-469015564? Thank you in advance!

**Comment by Mapiac** [comment]
We are also not on Azure, AWS and Digital Ocean (in our case DO) and also experience this. If truly there is no resolution and the crux of the issue is with K8s, could the UI dashboard code could be modified to have a flag, or something..as opposed to a huge red 'Unhealthy Scheduler' alert warning.

**Comment by fareshan** [comment]
I have the same issue with K8s on IBM

**Comment by iboware** [comment]
Rancher 2.4.1 Kubernetes Version: v1.16.7 AKS still having the same problem.

![image](https://user-images.githubusercontent.com/180098/78518834-d9853280-77c1-11ea-8525-b8d0016a0056.png)

**Comment by timosur** [comment]
Would be nice to have something like a switch here, that you can hide it if you want. It is a little bit annoying to get all these big red errors all the time.

**Comment by hadifarnoud** [comment]
errors are important @timosur

**Comment by jtherin** [comment]
@hadifarnoud not this one because it's based on incorrect assumptions of kubernetes itself.

**Comment by mitchellmaler** [comment]
If you look under the linked issue I logged #28023 upstream Kubernetes is deprecating the component status API. We recently upgraded to 1.17.9 which moves the controller-manager and scheduler to the secure port by default (disabling the insecure one) which now component status will fail. Since most clusters come with built in monitoring or you deploy Prometheus (or others) you should already have alerts and monitoring setup. The better approach would be to have a way to disable this UI health check so that way users and admins are not confused since it is a false issue. Then hopefully in the future re-work this health check to take advantage of another source (prometheus or something).

**Comment by dhawaldenny** [comment]
@superseb , is there any way to disable/hide/grayout these warnings in the Rancher UI? If not Any ETA for the same?

**Comment by niulin** [comment]
If the upstream API is deprecated, at least we should be able to mute the alert on the UI. Getting this big, always on red alert on the front page is really uncomfortable...

**Comment by xiaopengfeik8s** [comment]
##master
##kubectl get cs
Warning: v1 ComponentStatus is deprecated in v1.19+
NAME                 STATUS      MESSAGE                                                                                       ERROR
scheduler            Unhealthy   Get "http://127.0.0.1:10251/healthz": dial tcp 127.0.0.1:10251: connect: connection refused   
controller-manager   Unhealthy   Get "http://127.0.0.1:10252/healthz": dial tcp 127.0.0.1:10252: connect: connection refused   
etcd-0               Healthy     {"health":"true"} 

cd /etc/kubernetes/manifests
vi kube-scheduler.yaml
   # - --port=0

vi kube-controller-manager.yaml
   # - --port=0

##master and all worker
systemctl restart kubelet.service

##master
##kubectl get cs
Warning: v1 ComponentStatus is deprecated in v1.19+
NAME                 STATUS    MESSAGE             ERROR
scheduler            Healthy   ok                  
controller-manager   Healthy   ok                  
etcd-0               Healthy   {"health":"true"}  



It works, in my way....


![image](https://user-images.githubusercontent.com/56220568/95007096-3d3bcb80-063e-11eb-9733-36a554d148d1.png)

**Comment by bmalynovytch** [comment]
> **It works, in my way....**

Confirmed !

**Comment by mitchellmaler** [comment]
@xiaopengfeik8s Your workaround does fix the rancher UI but that is enabling the insecure deprecated port in the control-plane components which isn't best practice and it will be removed in a later version of Kubernetes.

**Comment by maggieliu** [comment]
related to: https://github.com/rancher/rancher/issues/24203

**Comment by dwaiba** [comment]
This issue for controller and scheduler unhealthy in Rancher UI on different host especially for AKS is persisting for v1.18.8 for Rancher 2.5.2 too

**Comment by deniseschannon** [comment]
As k8s is moving away from component status, we will still have it in within Rancher for the k8s distros that support it (for example, RKE). Currently, component status is added to the cluster config and we report on it's health regardless if component status exists for those k8s clusters. 

In v2.5+ which uses a k8s 1.19+ client-go, we will be hiding the deprecation logs around component status so that it doesn't flood the logs. (https://github.com/rancher/rancher/issues/28943)

This will only hide the deprecation logs, but does not solve the issue with the UI showing unhealthy when a k8s distribution doesn't use component status. We have introduced the ability to detect k8s distros with logic from https://github.com/rancher/kubernetes-provider-detector and can use use this to detect the type of k8s distribution, whether Rancher provisions it or if it's an imported cluster. 

We will introduce a setting that will identify which cluster types use component status for which components. It will be a comma separated list that identifies the cluster type and which specific component statuses exist.

For example
```
RKE, EKS, AKS=api-server
```
With the example, RKE and EKS are using component status for all options, where as AKS only uses component status for api-server.

Based on the cluster type, we will add the component status to the cluster config so that it reports the health of the component status. If teh cluster type is not on the list, it will not add the component status and the UI should grey it out if there is no component status.

**Comment by srgvg** [comment]
This issue shows also with Scaleway managed Kubernetes (Kapsule)

**Comment by izaac** [comment]
This is also the case for kubeadm and minikube

**Comment by smnmtzgr** [comment]
@deniseschannon thanks for describing the solution. When will this be merged/in which rancher version will this be available?

**Comment by mohag** [comment]
An option to check the status of deployments directly instead of using componentstatus might work for some cluster types (e.g. kubeadm) as well... (Maybe a label or annotation on the pods that gets discovered and the gets used instead of componentstatus if it is present) (It won't work for AKS (where those components are not visible), but it will work for cases where HTTP is switched off and the components are running as pods)

**Comment by nitrogear** [comment]
Looks like kube-controller and scheduler status is disabled when cluster.provider == "azureaks"
https://github.com/rancher/ui/pull/2976/files
Wondering if it's possible to do the same if cluster.provider == "imported"?

**Comment by ekristen** [comment]
IBM Cloud K8s clusters seem to have this issue as well.

**Comment by nitrogear** [comment]
Is it possible to modify https://github.com/rancher/ui/blob/master/lib/shared/addon/utils/constants.js#L645 in running installation and replace "tencenttke" with "imported" to temporary disable alerts?

**Comment by nitrogear** [comment]
Found a workaround to disable checking status:
1. Enter docker container with rancher
2. Open for editing file /usr/share/rancher/ui/engines-dist/monitoring/assets/engine-XXX.js
3. Find code
```
hideManagerAndSchedulerStatus:Ember.computed("cluster.provider",function(){var e=Ember.get(this,"cluster.provider")
return t.default.GRAY_OUT_SCHEDULER_STATUS_PROVIDERS.indexOf(e)>-1})
```
4. Replace with
```
hideManagerAndSchedulerStatus:Ember.computed("cluster.provider",function(){var e=Ember.get(this,"cluster.provider")
return true})
```

Not ideal, because monitoring for scheduler and controller manager is disabled for all cluster. Will post updates if can disable it only imported cluster type only

**Comment by nitrogear** [comment]
More accurate solution:
1. Enter docker container with rancher
2. Open for editing file /usr/share/rancher/ui/assets/vendor-b6fe2bee7d805b67cfdacf9d6f4cd5f8.js
3. Find code
```
GRAY_OUT_SCHEDULER_STATUS_PROVIDERS=["azureaks","tencenttke"]
```
4. Replace with
```
GRAY_OUT_SCHEDULER_STATUS_PROVIDERS=["azureaks","tencenttke","import"]
```

**Comment by afrouzMashaykhi** [comment]
@nitrogear it doesn't work in 2.4.8 any specific version?

**Comment by nitrogear** [comment]
@afrouzMashaykhi it doesn't work in any version I tried: 2.4.2, 2.4.11, 2.5.4

**Comment by supersaeyan** [comment]
Same issue with Kind clusters.

Only 18.2 image works kindest/node:v1.18.2@sha256:7b27a6d0f2517ff88ba444025beae41491b016bc6af573ba467b70c5e8e0d85f

I have tried 18.6 and latest stable 19.1, both have the same error.

**Comment by Napsty** [comment]
Visualization of the cluster's health state is important and I appreciate that Rancher is showing this on the cluster page in the UI. However as Kubernetes moves away from the componentstatuses (deprecated in 1.19, later removed, see https://github.com/kubernetes/kubernetes/pull/93570) how will you "monitor" the health of the cluster components in the future?

The status of etcd can be monitored using the Kube API (see https://github.com/kubernetes/kubernetes/pull/93570#issuecomment-777272611) but according to documentation only starting with k8s 1.20+. For controller-manager and scheduler I have not yet found any working health endpoint. Is there actually a way to properly monitor these?

**Comment by enhendrickson** [comment]
@izaac @paynejacob @sowmyav27 - still having this issue with 2.5.x Rancher with imported AKS clusters.  Any idea when this will be resolved?   Even a simple override setting in the UI  that allows me to do the same thing that happens when I provision from Rancher to AKS.  Basically, ignoring the status and graying them out for n/a components.  Do you know when/what version something will be done to resolve this issue?

**Comment by ChrML** [comment]
Still having this issue with AKS k8s 1.19 imported cluster.

Seems this is no longer an upstream issue, since the upstream feature is being deprecated.

**Comment by deniseschannon** [comment]
@paynejacob please make sure this is resolved for imported clusters and newly provisioned AKS clusters.

**Comment by slickwarren** [comment]
<img width="1404" alt="Screen Shot 2021-05-11 at 2 47 00 PM" src="https://user-images.githubusercontent.com/16691014/117889060-c6b41b80-b267-11eb-95f8-5c2a290f3dc8.png">
<img width="1385" alt="Screen Shot 2021-05-11 at 2 46 53 PM" src="https://user-images.githubusercontent.com/16691014/117889062-c87ddf00-b267-11eb-9c52-8e031745e6f0.png">
It appears that in a hosted cluster, scheduler and controller manager show as `Not Applicable` but on the imported setup, they appear as healthy.

**Comment by slickwarren** [comment]
reopening for the above issue

**Comment by earthquakesan** [comment]
I have the same issue on minikube:

```
$ minikube version
minikube version
minikube version: v1.18.1
commit: 09ee84d530de4a92f00f1c5dbc34cead092b95bc

$ kubectl get no
NAME       STATUS   ROLES                  AGE   VERSION
minikube   Ready    control-plane,master   10d   v1.20.2

k -n cattle-system get po -l app=rancher -o go-template='{{range .items}}{{range .spec.containers}}{{.image}}{{"\n"}}{{end}}{{end}}'
rancher/rancher:v2.5.8
rancher/rancher:v2.5.8
rancher/rancher:v2.5.8
```

![image](https://user-images.githubusercontent.com/1092829/118365139-c6838b00-b59b-11eb-8c45-44dae43eb33d.png)

**Comment by paynejacob** [comment]
@westlywright Testing this the api is properly removing the controller manager and scheduler cluster component statues.  Can we update the ui to grey them out if they are not returned?

**Comment by slargo** [comment]
We have solved the issue by removing the line - --port=0 in the /kubernetes/manifests for the controller and scheduler, so the  metrics are exposed in the not secure port too. 
kubectl get clusterstatuses goes well and the Rancher UI green :)

**Comment by mohag** [comment]
> We have solved the issue by removing the line - --port=0 in the /kubernetes/manifests for the controller and scheduler, so the metrics are exposed in the not secure port too.
> kubectl get clusterstatuses goes well and the Rancher UI green :)

The ability to serve a non-secure port will removed in Kubernetes 1.22...
See kubernetes/kubernetes#96216 and kubernetes/kubernetes#96345

**Comment by slickwarren** [comment]
I'm still able to reproduce this on master-629146a3fbbc8d5677aecece78e627580dd7c95d-head (after the changes to UI were merged)
* aks imported cluster has all green checkmarks
* aks hosted has `controller manager` and `scheduler` greyed out, marked as `not applicable`

**Comment by slickwarren** [comment]
on master-head (5d49b92)
hosted and imported AKS clusters now have the same UI for controller manager & scheduler `Not Applicable`
<img width="1329" alt="Screen Shot 2021-06-01 at 3 44 18 PM" src="https://user-images.githubusercontent.com/16691014/120399123-3f9b1600-c2f0-11eb-825e-b207a84a40bd.png">

I also verified that other cluster types are behaving as expected (node drivers/EKS have all active, k3s has etcd `not applicable`)

**Comment by edqallen** [comment]
This issue is present currently on fresh self-hosted K8S v1.21.1 clusters imported into Rancher 2.5.7.

**Comment by MichelZ** [comment]
This issue has a 2.6 milestone attached, so it‘s not in 2.5.7.
There is a linked backport issue which states a 2.5.10 release.
So this needs some more patience :)

**Comment by edqallen** [comment]
Thanks for the heads-up @MichelZ .  I didn't notice the 2.6 milestone, just the "it's fixed" messages and closed status.

**Comment by quangthe** [comment]
Thanks @MichelZ 

I have the same issue when importing Tencent TKE cluster (1.18.6) into Rancher. 
Do you know when the 2.5.10 will be released? :)

**Comment by MichelZ** [comment]
Unfortunately not.
As far as I can tell it _looks_ like releases are done roughly every 2 months.
2.5.8 was released May 6th, that means 2.5.9 roughly in July and would put 2.5.10 roughly in the September time frame?

Here are the milestones to track:
https://github.com/rancher/rancher/milestone/238 - v2.5.10
https://github.com/rancher/rancher/milestone/186 - v2.6

**Comment by wpwoodjr** [comment]
I'm seeing this on a Rancher "local" cluster hosted on AKS.  Is that expected, will it be fixed by 2.5.10 also?
![image](https://user-images.githubusercontent.com/6633152/123475823-f1fd8a80-d5c9-11eb-98a5-0a9baaf36d86.png)

**Comment by w3blogfr** [comment]
Hello, I would have to know some details about the fix you are working on it.
what will be the final solution?

1. Will you fix it by detecting automatically provider (based on list of Provider)? 
2. Will will detect if compoment are enabled or not during the cluster importation
3. Or will you offer the possibibility to the user to disable individually component and make it "Not Available" ? may be via edit cluster and adding some label or annotation?

Thanks for your work.

**Comment by mshearer76** [comment]
Yes, it would be nice to know what the implementation will be. We actually implemented our own workaround so we'd prefer not to lose the ability to use these healthchecks in an imported cluster.  We created a microservice that runs as a daemonset on the control plane which listens on 127.0.0.1:10252 for the controller manager health and 127.0.0.1:10251 for the scheduler health. We then used the Kubernetes go client to assesses the health of each component and return 200 if it's OK and 500 if it's not.  This has been working flawlessly in production on Kubernetes 1.18.8 and Rancher 2.5.9. I know the componentstatus API will be completely removed by 1.25 so it would be nice if the cattle-cluster-agent could do something similar using it's own API.

**Comment by mohag** [comment]
Problem still present (for kubeadm deployed clusters) in 2.5.11.

(It did go away on imported AKS clusters though.

Imported AKS cluster:
![image](https://user-images.githubusercontent.com/1136567/145441058-44095876-d902-4494-9a25-be793162f441.png)

Kubeadm cluster:
![image](https://user-images.githubusercontent.com/1136567/145441171-1a669071-8c47-424c-b362-654354cae745.png)
(component-statuses check the insecure port, which is disabled)
