### ISSUE TITLE
API List page the UI will show new keys & old keys (on refresh) set to Never

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12450]
**Rancher versions:** 2.0 master 4/2

**Steps to Reproduce:**
1.  Go to API keys page
2.  Add a new key and set it to expire a day from now (notice UI shows it as Never)
3.  Refresh the browser

**Results:**  All keys flash the proper Expires times, but then go to Never.

**Comment by loganhz** [comment]
Server sends a `resource.change` with empty `expiresAt`. It should be fixed in server side.

**Comment by prachidamle** [comment]
hey @loganhz I tried reproducing this issue on latest master 07/07 and I dont see this issue happening.
Do you still see this happening, if yes can you let me know your steps to reproduce?

Also is there an API that fails to send the data in resource.change? how can I see which API is getting called for this.

**Comment by loganhz** [comment]
Yes, I still see this happening on master 06/07.

Steps to reproduce:
1. Open Chrome dev tool. Select `Network` tab in dev tool. Select `WS` section under `Network` tab.
2. Go to API & Key page  `https://localhost/apikeys`
3. You will be able to see a `subscribe?sockId=1` websocket in dev tool.
4. Click the `subscribe?sockId=1`. There will be a `Frames` tab. It shows all of the events sent from server.
5. Click `Add Key`, input a description and select `A day from now`.
6. Click `Create` 
7. Click `Close` once you see the created key
8. In the table, the `expires` field of the newly created key is `Never`. It's wrong. It should be `Tomorrow`
9. Check the `frame` in dev tool. And find the one with name `resource.change`.
10. You will find the `expiresAt` field is `empty` in the frame.

![image](https://user-images.githubusercontent.com/21168270/41133046-4ac6cc30-6af7-11e8-8adf-8381fd6b92d4.png)

Note: if you click `View API` of this key. The `expiresAt` is `2018-06-09T00:34:25Z`. This is why it is working if users refresh browsers after creation

**Comment by prachidamle** [comment]
@loganhz If the API POST /v3/token that creates the API key, sends back the "expiresAt" in the response, wont UI show that?

I see that the POST /v3/token response was missing the "expiresAt" - but after fixing that, I still see UI showing it as "Never" - so now even if API is sending back correct data, we still need the resource.change  fix? Can Ui read it from API response?

<img width="1564" alt="screen shot 2018-06-11 at 3 01 50 pm" src="https://user-images.githubusercontent.com/1470602/41259500-ad869a10-6d88-11e8-8fc4-69687c5cd2bf.png">

**Comment by loganhz** [comment]
hi @prachidamle  UI is reading from both API response and `resource.change`. The data from  API was overridden by the data from websocket. I think we still need to fix the `resource.change` event. All of other resources work like that.

**Comment by sangeethah** [comment]
Tested with build form master - Jun 13

API List page the UI will show "Expires" as expected.
