### ISSUE TITLE
Project logging not working & cannot remove

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#13039]
**Rancher versions:**
rancher/server: master 4/24

2 issues w/ project logging -- **A)** logging not writing to target, and **B)** unable to remove log target once set.
1 issue w/ cluster logging (maybe related to project logging issues) -- **C)** When both project & cluster logging enabled, log entries from project are written twice w/ cluster log program name

**Steps to Reproduce (A):**
No cluster logging enabled
Enable project logging to syslog target
Deploy workload in project w/ custom log path
Write lines to log file

**Results:**
No logging output to target. 

```E0424 20:05:25.232560       1 generic_controller.go:204] ProjectLoggingController project-ch5jn/pl-588tw [project-logging-controller] failed with : create configmap : failed: namespaces "cattle-logging" not found```

**More steps (B)**
Set project log target to none, and save.
Reload page.

**Results**
Log target still the same.

```E0424 20:28:27.941120       1 generic_controller.go:204] ProjectLoggingController project-ch5jn/pl-588tw [project-logging-controller] failed with : failed to remove finalizer on project-ch5jn:pl-588tw```

**Steps (c)**
Enable cluster logging to syslog target (program name: rancherbuffer)
Enable project logging to syslog target (program name: projectbuffer)
Deploy workload to project w/ custom log path
Write lines to log file

**Results**
Log entries come twice from cluster level program name, none from project level program name

`log line 7` && `log line 8` only written once:
```
Apr 24 20:26:42 fluentd-p7fcm rancherbuffer: log:2018-04-24 20:26:37 +0000 [warn]: #0 pattern not match: "log line 7"
Apr 24 20:26:42 fluentd-p7fcm rancherbuffer: log:2018-04-24 20:26:37 +0000 [warn]: #0 pattern not match: "log line 7"
Apr 24 20:27:10 fluentd-p7fcm rancherbuffer: log:2018-04-24 20:27:05 +0000 [warn]: #0 pattern not match: "log line 8"
Apr 24 20:27:10 fluentd-p7fcm rancherbuffer: log:2018-04-24 20:27:05 +0000 [warn]: #0 pattern not match: "log line 8"
```

**Comment by aiwantaozi** [comment]
Hi @bmdepesa 
Re B) caused by a change in norman repo, Darren has updated, use the latest version could be resolved.
Re A) may be the same root cause, when to disable the logging, the component like namespace, configmap actually deleted, but the framework not delete the crd, so you could see it in the UI. I try the latest version, it works.

**Comment by zionwu** [comment]
The related framework issue is ttps://github.com/rancher/rancher/issues/13021

**Comment by deniseschannon** [comment]
@zionwu since that issue is fixed, would this issue be ready to be tested?

**Comment by aiwantaozi** [comment]
@deniseschannon Yes

**Comment by aiwantaozi** [comment]
Need more improvement, because the crd obj could not be deleted quickly, we need to improve both UI side and backend side, make it more easy to use.

**Comment by bmdepesa** [comment]
Validated against v2.0.0-rc1

Use case B is working

Use case A is not working. I am still not seeing logging from the project level. 

Regarding case C .. I get "pattern not match" with any format I use. Do we have any examples that work for the non-regex options?
