### ISSUE TITLE
[API] Should not be allowed to edit any field other than "locked" for built-in roles .

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#13595]
Ranche Version - Build from master

Currently we are allowed to edit any field other than "locked" for built-in rules.

**Comment by dramich** [comment]
Available in master

**Comment by sangeethah** [comment]
@dramich , Tested with latest build from master (Jun 26):

From UI, trying to lock an existing 	built-in roles fails with:
 
```Validation failed in API: Only field 'locked' can be updated on builtin roleTemplate```

Expected Behavior:
Admin should be allowed to edit the "locked" field from built-in roles .

**Comment by sangeethah** [comment]
Tested with latest build from master

From UI, trying to lock an existing built-in roles fails with:

```Validation failed in API: Only field 'locked' can be updated on builtin roleTemplate```

I tested with "cluster Member" and few other roles.

**Comment by dramich** [comment]
Fixed in master

**Comment by sangeethah** [comment]
Tested with latest build from master

From UI, trying to lock an existing built-in roles fails it succeeds for most of the custom built-in roles .

But it fails with the same error when trying to lock "cluster owner" - "Validation failed in API: Only field 'locked' can be updated on builtin roleTemplate"

**Comment by dramich** [comment]
Available in master

**Comment by sangeethah** [comment]
Tested with v2.0.5-rc1
We are not be allowed to edit any field other than "locked" for built-in roles. 
API does not error out but ignore all the changes made to any other field.

From UI, trying to lock an existing built-in roles fails it succeeds for most of the custom built-in roles still fails which is tracked in https://github.com/rancher/rancher/issues/14351
