### ISSUE TITLE
Site Access Info not getting populated until manual refresh. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#14353]
**Rancher versions: v2.0.5-rc2

**Steps to Reproduce:**

Have Github/Azure AD auth enabled setup with "Allow members of Clusters, Projects, plus Authorized Users and Organizations"/"Restrict access to only Authorized Users and Organizations".

Log out.
Log in back as  Github/Azure AD admin user.
Go to Settings->Authentication to launch the auth page.

Notice that the Site Access Info is empty.

<img width="1311" alt="screen shot 2018-07-02 at 9 59 40 pm" src="https://user-images.githubusercontent.com/4266958/42199423-4588cec6-7e43-11e8-9d32-0ec2190d268c.png">

On Manual refresh ,  Site Access info shows up as expected.

**Comment by westlywright** [comment]
@tfiduccia I think I fixed this yesterday stemming from something we talked about. Can you retest?

**Comment by sangeethah** [comment]
I am still able to reproduce this issue:

github enabled set in 2.0.4  with access site set to - "Allow members of Clusters, Projects, plus Authorized Users" with few users added.
Upgrade to 2.0.5-rc3 .

After upgrade, Log in as github enabled user.
Go to Settings->Authentication to launch the auth page.
Notice that the Site Access Info is empty.
on Manual refresh , I see the Site Access Info show up as expected.

Log out.
Log in back as Github  admin user.
Notice that the Site Access Info is empty.
on Manual refresh , I see the Site Access Info show up as expected.

**Comment by sangeethah** [comment]
This issue does not happen amymore .
But want to verify this issue again once this issue gets fixed - https://github.com/rancher/rancher/issues/14430

**Comment by sangeethah** [comment]
@westlywright  I see this issue still happen in Azure AD setup.
Reopening this issue to fix  Azure AD setup.
