### ISSUE TITLE
Preferences show other user's name and username instead of the logged in user

### ISSUE THREAD

**Issue by divyangjp** [rancher/rancher#14420]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.4
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): 1.10.3

**Docker version: 17.03.2

**Operating system and kernel: Ubuntu 16.04

**Type/provider of hosts: Openstack

**Setup details: Rancher HA with 3 nodes and internal DB

**Environment Template: Kubernetes

**Steps to Reproduce:**
Create new Admin user say `xyz@abc.com`. 
Using any admin user create standard user say `stuser@abc.com`. 
Now login with standard user.
Go to `Preferences`. 
**Results:**
Check that `My Account` contains name and username of Admin user `xyz@abc.com`

**Expected Result**
Name and username should be of logged in user and not the admin user.

**Comment by loganhz** [comment]
Hi @divyangjp , I can not reproduce this issue.

Can you provide the screenshot like this, please?

![image](https://user-images.githubusercontent.com/21168270/42438311-47b4add8-8392-11e8-9548-3a76e2fbe158.png)

**Comment by loganhz** [comment]
Steps to reproduce:
1. Create an admin user `user1`.
2. Login as `user1` and create a `standard` user `user2`.
3. Change the role of `user1` to standard user.
4. Logout `user1` and Login as `user2`

API `/v3/users?me=true` returns `user1`.

I think we need to fix this issue in server side.

**Comment by cjellick** [comment]
Thanks for the steps @loganhz

**Comment by almoore** [comment]
I am still seeing this issue in the v2.0.6 release. I am using the OpenLDAP setup and have only the admin user locally. All the users see the Preferences user info as the admin user.

**Comment by erikwilson** [comment]
It appears this was fixed in v2.0.8

**Comment by loganhz** [comment]
API `/v3/users?me=true` returns the multiple users in `v2.0.4`
![image](https://user-images.githubusercontent.com/21168270/50672616-543a2d80-1014-11e9-86f0-2f55a082f45b.png)


API `/v3/users?me=true` returns the current user in `v2.1.4`
![image](https://user-images.githubusercontent.com/21168270/50672593-1f2ddb00-1014-11e9-9b8e-fc5a4de46f1b.png)

This issue has been fixed in current rancher/rancher:stable version

**Comment by sangeethah** [comment]
@loganhz Thank you for the detail steps to reproduce the issue.


Create an admin user user1.
Login as user1 and create a standard user user2.
Change the role of user1 to standard user.
Logout user1 and Login as user2

When testing the above steps in 2.0.4, API -  /v3/users?me=true returns user1 and user2

When testing the above steps in latest master builds  API -  /v3/users?me=true returns user2  as expected.

**Comment by loganhz** [comment]
It still happens in Rancher 2.3.5.

Steps:

1. Login as Admin user
2. Create a new admin user `user1`
3. DO NOT close the current tab. Open a new tab in browser and login as `user1`
4. Switch back to previous tab. 
5. Edit admin user without any change.

Results:

`/v3/users?me=true` will always return 2 users.

Expected:

Maybe we should  change `me` to readonly field

**Comment by aaronRancher** [comment]
The bug is reproduced with Rancher server `rancher\rancher:v2.0.4` and `rancher\rancher:v2.3.5`
Steps:
Login as Admin user
Create a new admin user user1
DO NOT close the current tab. Open a new tab in browser and login as user1
Switch back to previous tab.
Edit default admin user without any change.
![Screen Shot 2020-04-06 at 4 42 15 PM](https://user-images.githubusercontent.com/57409052/78616608-86df6100-7829-11ea-8b22-869c399f1fd3.png)
![Screen Shot 2020-04-06 at 4 42 33 PM](https://user-images.githubusercontent.com/57409052/78616610-88108e00-7829-11ea-8c29-ac43ae83a548.png)


The bug fix is verified with Rancher server `rancher\rancher:master-head` `version ea9700b41` and `rancher\rancher:v2.4-head` `version 481cb64b3`
Only 1 user is shown
![Screen Shot 2020-04-06 at 5 08 09 PM](https://user-images.githubusercontent.com/57409052/78616552-631c1b00-7829-11ea-92b7-c4fad1a62798.png)
![Screen Shot 2020-04-06 at 5 06 41 PM](https://user-images.githubusercontent.com/57409052/78616597-81821680-7829-11ea-9d39-12ce9afdc715.png)
