### ISSUE TITLE
node-controller error with the exoscale driver

### ISSUE THREAD

**Issue by greut** [rancher/rancher#14906]
**Rancher versions:**
rancher/rancher:

**Infrastructure Stack versions:**
node drivers

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Exoscale

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

single `docker run rancher/rancher` deploying a cluster via node driver plugin.

**Steps to Reproduce:**

Add cluster, Exoscale, create a template, then Create.

**Results:**

> [ERROR] NodeController c-j5k29/m-vmqfk [node-controller] failed with : Error creating machine: Error in driver during machine creation: Panic in the driver: interface conversion: interface {} is nil, not *egoscale.DeployVirtualMachineResponse

As the primary maintainer of egoscale, I'm keen to help you with this issue. Sadly I didn't manage to find where this code come from. Let me know if I/we can be of any help here.

Best!

**Comment by greut** [comment]
there? https://github.com/machine-drivers/machine

**Comment by loganhz** [comment]
Hi @greut , the code is here https://github.com/rancher/machine/blob/master/drivers/exoscale/exoscale.go

**Comment by vhf** [comment]
I'm getting a similar error when trying to create a new host with the exoscale driver: `Error in driver during machine creation: json: cannot unmarshal string into Go struct field VirtualMachine.ostypeid of type int64`.

I [upgraded](https://rancher.com/docs/rancher/v1.6/en/upgrading/) to the latest rancher 1.x (not my first upgrade, works smoothly) and I'm now running 1.6.25. All rancher services are up-to-date.

We have several hosts at exoscale already, it's the first time creating a new one fails. I re-read the [docs](https://rancher.com/docs/rancher/v1.6/en/hosts/exoscale/) and our firewalling group `rancher-machine` is ok.

If this has been fixed, how can I upgrade the machine drivers in Rancher 1.6? I noticed our Rancher still uses `https://github.com/rancher/machine-package/releases/download/v0.14.0/docker-machine.tar.gz` and I couldn't find out how to use the latest: `https://github.com/rancher/machine-package/releases/download/v0.15.0-rancher1/docker-machine.tar.gz`

<img width="267" alt="screenshot 2018-12-06 at 10 52 21" src="https://user-images.githubusercontent.com/2022803/49576633-ef70b200-f945-11e8-9012-f28af19bd928.png">
<img width="478" alt="screenshot 2018-12-06 at 10 52 38" src="https://user-images.githubusercontent.com/2022803/49576635-f0094880-f945-11e8-8944-c4250ca1a0f5.png">

Sorry if this is the wrong issue/channel. @greut if that would help I'd be happy to reach out to `support@exoscale.ch`?

**Comment by greut** [comment]
@vhf thanks. We made changes to the docker-machine that weren't picked up by rancher's fork as of yet (either mainstream or that pull request https://github.com/rancher/machine/pull/14)

As docker-machine has reached a maintenance mode, we strongly advise how customers to go for the custom cluster solution. Manage the infrastructure using ansible/terraform/... and let Rancher/RKE do the Kubernetes layer.

Cheers,

**Comment by cjellick** [comment]
merged the machine PR. I need to build machine binaries and update rancher accordingly

**Comment by cjellick** [comment]
@vhf @greut can you confirm that the issue is resolved?

**Comment by cjellick** [comment]
My plan is to not validate this in-house. If @greut can confirm the fix, I will close

**Comment by vhf** [comment]
@cjellick Thanks for the heads up and for the fix! I just tested it and it works 👍

**Comment by cjellick** [comment]
Thanks for the feedback

**Comment by vhf** [comment]
I'm having the same error again unfortunately.

> I [upgraded](https://rancher.com/docs/rancher/v1.6/en/upgrading/) to the latest rancher 1.x (not my first upgrade, works smoothly) and I'm now running 1.6.25. All rancher services are up-to-date.

Now running `1.6.27`.

> I noticed our Rancher still uses `https://github.com/rancher/machine-package/releases/download/v0.14.0/docker-machine.tar.gz` and I couldn't find out how to use the latest: `https://github.com/rancher/machine-package/releases/download/v0.15.0-rancher1/docker-machine.tar.gz`.

Still the same: v0.14.0. I don't know how I can upgrade this, I noticed there are many more recent versions: https://github.com/rancher/machine-package/releases

**Comment by vhf** [comment]
@cjellick Should have there been upgrades to https://github.com/rancher/rancher/blob/v1.6/server/Dockerfile in #17435 as well?
