### ISSUE TITLE
Node provision fail and many key pairs are created 

### ISSUE THREAD

**Issue by thiagosantosleite** [rancher/rancher#16798]
**What kind of request is this (question/bug/enhancement/feature request):**
When I create a aws ec2 cluster and if It the keep failing to be provisioned one node, many key pairs are created. I ended with more hundreds key pairs after time.

Rancher | v2.1.1
-- | --
User Interface | v2.1.4
Helm | v2.10.0-rancher5
Machine | v0.15.0-rancher1-1

**Comment by ntkach** [comment]
At least in our case it's specifically when trying to provision new aws ec2 nodes.  There seems to be a point where the provision gets to the point of trying to create a keypair to use, does that, but then fails to actually finish the provision.  The next one comes along, tries to make another keypair (always uses a unique id suffix), fails, etc.

If there was some way to specify a particular pre-existing ec2 ssh keypair to use, that would be ideal I would say.  We ran into the same thing.  Left a cluster provision running overnight (failing) and wound up with 5000 junk ssh keys in aws ec2.

**Comment by ntkach** [comment]
I would say, the feature I expect would be to somehow pass in (whether pasting a key into the node template or uploading it or whatever) the private half of an existing aws ec2 ssh keypair and then setting the name on the template and have a node template use that when creating a pool.  I'm *guessing* that mostly be a matter of somehow pulling in those two pieces and then just passing them to the docker-machine call, but then I'm not familiar with that.

**Comment by vincent99** [comment]
Machine drivers either don't have an option to specify using an existing SSH key or assume that the private key is available in ~/.ssh and have no good way to manage that in a multi-tenant environment.  So using an existing key is not really practical.

They also tend to not be very good at cleaning up after themselves, especially when errors occur.

**Comment by juliovalcarcel** [comment]
For anyone else who has this problem (It was failing over a long weekend and it maxed out the keypairs with 5000) here is a little hacked together script to clean up your keys

I ran `aws ec2 describe-key-pairs  > keypairs.json` and then used the below script to delete the keypairs. You will need to change the regex in the match statement to match your prefix

```node
const keypairs = require('./keypairs.json');
const {exec}  = require('child_process');

function deleteKeypair(keypair) {
  exec(`aws ec2 delete-key-pair --key-name ${keypair.KeyName}`, (err, stdout, stderr) => {
    console.log(`stdout ${stdout} stderr ${stderr}`)
    console.log(`deleted ${keypair.KeyName}`)
  }) 
}
keypairs.KeyPairs.map((keypair, idx) => {
  if (keypair.KeyName.match(/rancher\-.*/)) {
    setTimeout(() => {deleteKeypair(keypair)}, 200 * idx)
  }
});
```

If you start getting request limits just kill the node script and rerun the first command so you get the new list of keypairs to delete (So you aren't running through the old ones)

**Comment by cjellick** [comment]
Can this be addressed by allowing the user to specify an existing key pair in AWS?

**Comment by cjellick** [comment]
before implementing, check with @deniseschannon on whether the above solutoin would be acceptable

**Comment by vincent99** [comment]
To do this the user needs to provide the private key and corresponding public key that will be put on the nodes, so that machine can use them to SSH to the node.  In some providers there's a specific API resource to define and reference a particular public key (AWS).  In others you just provide the public key string directly.

So if you want to implement this, I think we should add a new top-level secret type for SSH Keypair and then pick from those in node templates, then change the machine plumbing to support that.

  - Add a new top-level secret type for SSH Key Pair.  It should handle encrypted keys, prompting for a password and decrypting them for you on the server-side, because the private key on your laptop is encrypted (right?) and you don't have or want an unencrypted copy sitting on your disk.

  - Add a field referencing a keypair to nodetemplate to request using that one instead of creating new.

  - Write the key at a well-known path into the jail that machine runs in.

  - Change machine drivers as needed to support using the specified key path instead of creating a new one.  For some (AWS) this will mean searching for an existing key with the given fingerprint and creating it if it doesn't already exist so that it can be referenced.

  - If you're not going to change ALL the builtin drivers to support this, add a flag somewhere so that the UI can tell if it should ask or not for a given driver.

  - Provide a mechanism for 3rd-party drivers to use this (e.g. an annotation on the driver which specifies what flag the key path should be passed as)

  - Download machine config should not include the plaintext private key if you used an existing one instead of generating.

**Comment by v1k0d3n** [comment]
just ran into this. was surprise to still see this issue open.

**Comment by milindchawre** [comment]
+1

Can you guys take this issue on priority.
This feature is very generic and essential one.
Quite surprise to see it getting pushed in backlog since few years.
Also rancher internally uses RKE to bringup k8s and RKE do have an option to specify pem file, so was quite surprise to see this issue lying around.

Because of this issue, we have to compromise on few things like:
- Need to use custom nodes option rather than ec2-nodes option.
- Have to figure out how to implement cluster autoscaling in rancher using custom option. The ec2-node option might have made this quite easy.

**Comment by vincent99** [comment]
Provisioning the node in a provider and installing k8s on it are two separate and unrelated steps.

docker/rancher-machine does the first part from creating a VM and then configuring it by installing docker and starting the node agent.  That configuration is done using SSH, with a key generated for each node. 

RKE does the second part, and its SSH-related options are not involved; When used in Rancher (vs standalone), the tunnel already established by the node agent is used by the RKE library to communicate with the nodes.  There is no SSH.

As I've already explained above, supporting providing your own keys uniformly is an involved project.  There's limited demand for it, compared to other things people want and their benefits, and that's why it's never been prioritized.

Fixing bugs in individual drivers where keys are not cleaned up in certain situations and you end up with tons of orphaned keys is a much more tractable problem, given specific reproducible issues.

**Comment by mhermosi** [comment]
I am just starting a new aws account running rancher from my laptop and provisioning a cluster of EC2 nodes. I was as well surprised that once connected to AWS rancher did not allow on the node template to choose (as EC2 instance creation does) if you want to use an existing key pair, create a new one or provide your own private key. this is indeed a problem having to go to the keys section and clean up all the garbage left by failed nodes

**Comment by HoustonDad** [comment]
This is becoming a major issue due to provisioning failures, and KeyPairs in AWS accounts in the *thousands*

Can we get a priority bump on this please?

**Comment by jiaqiluo** [comment]
closing this one as a duplication of https://github.com/rancher/rancher/issues/34729
