### ISSUE TITLE
Rancher CLI: Numbers with integer part of greater than 6 digits converted to scientific notation, when provided in yaml to app deploy via `--values`

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#20704]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Spin up a Rancher v2.2.4 cluster
2. Attempt to deploy an application via the Rancher v2.2.0 CLI `rancher app install redis --values values.yaml` where values.yaml contains a integer value, greater than 6 digits long, i.e. `number: 1234567`
3. Attempt to deploy the same application, specifying `number: 1234567` in the answers yaml text entry, via the UI
4. Check the definition for both the UI and CLI deployed applications via the API

**Result:**

Observe that where the application was deployed via the CLI, the `number: 1234567` has been converted into scientific notation: `number: 1.234567e+06` in the `answers` map. For the application deployed via the UI `number: 1234567` is preserved as expected in `valuesYaml` field.

I believe the issue lies somewhere in the CLI code for conversion of the Yaml to JSON (and back):
https://github.com/rancher/cli/blob/v2.2.0/cmd/common.go#L514
https://github.com/rancher/cli/blob/v2.2.0/cmd/app.go#L1059

If you pass a 7 digit or more number integer in yaml through yaml.Unmarshal only, as the test code does, you do not see this behaviour:
https://github.com/rancher/cli/blob/v2.2.0/cmd/app_test.go#L64

**Other details that may be helpful:**

Whilst the number is still technically the same, this is inconsistent UI vs CLI and I would not expect the representation to change.

**Environment information**

Rancher v2.2.4
Rancher CLI v2.2.0

**Comment by axeal** [comment]
Conducted further testing to demonstrate difference in handling of numbers when deploying catalog apps via Rancher CLI vs UI:

1. Create a simple helm chart with a templated deployment with the following templated environment variables:

```
            - name: TEST_NUMBER_UNQUOTED
              value: "{{ .Values.test.myNumericValue.num1 }}"
            - name: TEST_NUMBER_QUOTED
              value: "{{ .Values.test.myNumericValue.num2 }}"
```
2. Deploy the catalog app via the Rancher UI specifying the following values as answers under 'Edit as Yaml':
```
test:
  myNumericValue:
    num1: 20190411
    num2: "20190411"
```
3. Observe the following representation of these under valuesYaml numbers when viewing the app in the Rancher API: `num1: 20190411\n    num2: \"20190411\"`

4. Observe the following representation of these numbers in the generated deployment specification yaml:
```
- name: TEST_NUMBER_UNQUOTED
  value: "2.0190411e+07"
- name: TEST_NUMBER_QUOTED
  value: "20190411"
```

5. Deploy the application via the Rancher CLI providing the following values in a yaml file via the `--values` parameter:
```
test:
  myNumericValue:
    num1: 20190411
    num2: "20190411"
```

6. Observe the following representation of these numbers in the `answers` field when inspecting the CLI deployed app via the Rancher API:
```
"test.myNumericValue.num1": "2.0190411e+07",
"test.myNumericValue.num2": "20190411",
```

7. Observe the following representation of these numbers in the generated deployment specification yaml for the CLI deployed app:
```
- name: TEST_NUMBER_UNQUOTED
  value: "2.0190411e+07"
- name: TEST_NUMBER_QUOTED
  value: "2.0190411e+07"
```

8. Behaviour when rendering the helm (`v2.14.1`) chart via `helm template` with the same values in yaml file via `--values` parameter:
```
- name: TEST_NUMBER_UNQUOTED
  value: "2.0190411e+07"
- name: TEST_NUMBER_QUOTED
  value: "20190411"
```

**Appears behaviour via the UI is correct/same as helm CLI, but deployment via Rancher CLI is altering quoted numbers to scientific representation**

**Comment by marcusianlevine** [comment]
We are also experiencing this issue, although it also appears to manifest when using `--answers` from the CLI

Upon redeployment of the app from the UI, all integer answers are rendered properly without being converted to scientific notation

**Comment by sangeethah** [comment]
Reopening to get the fix merged in release branch

**Comment by dramich** [comment]
Available in v2.3.3-rc1

**Comment by soumyalj** [comment]
Reproduced the issue using CLI version v2.3.2
Deployed grafana with values.yml as below:
```
---
  defaultImage: true
  image: 
    repository: "ranchercharts/grafana-grafana"
    tag: "6.3.4"
  sidecar: 
    image: "ranchercharts/kiwigrid-k8s-sidecar:0.1.20"
  downloadDashboardsImage: 
    repository: "ranchercharts/appropriate-curl"
    tag: "latest"
  admin: 
    existingSecret: ""
  adminUser: "admin"
  adminPassword: ""
  rbac: 
    namespaced: true
  persistence: 
    enabled: false
    size: "8Gi"
    storageClass: ""
    existingClaim: ""
  ingress: 
    enabled: true
    hosts: 
      - "xip.io"
  service: 
    type: "NodePort"
    nodePort: ""
  num:
    num1: 12345678
    num2: "12345678"

```
In the API the app displays scientific notation for num1 as below:
```
"answers": {
"admin.existingSecret": "",
"adminPassword": "",
"adminUser": "admin",
"defaultImage": "true",
"downloadDashboardsImage.repository": "ranchercharts/appropriate-curl",
"downloadDashboardsImage.tag": "latest",
"image.repository": "ranchercharts/grafana-grafana",
"image.tag": "6.3.4",
"ingress.enabled": "true",
"ingress.hosts[0]": "xip.io",
"num.num1": "1.2345678e+07",
"num.num2": "12345678",
"persistence.enabled": "false",
"persistence.existingClaim": "",
"persistence.size": "8Gi",
"persistence.storageClass": "",
"rbac.namespaced": "true",
"service.nodePort": "",
"service.type": "NodePort",
"sidecar.image": "ranchercharts/kiwigrid-k8s-sidecar:0.1.20"
}
```

**Comment by tjanson** [comment]
This issue still appears to be present in v2.6.9 when using the Rancher web UI to change Helm Chart values.
