### ISSUE TITLE
Bug: kubectl hangs on 'rollout status' when using Rancher API

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#21324]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1) Point kubectl to your Rancher kubeconfig for a cluster running Kubernetes 1.13.5
2) Use kubectl client 1.14 or 1.15 and check a rollout status like the following command.
```
 kubectl -n cattle-system rollout status deployment rancher 
```

**Result:**
Rollout status will hang for 8 to 15 minutes before completing.

**Other details that may be helpful:**
1) If you use kubectl 1.13 against Rancher API on a  1.13.5 cluster then it will not hang
2) If you use kubectl 1.13/1.14/1.15 against the kube-apiserver directly, it will not hang
3) Bypassing load balancer with a 1.14/1.15 kubectl but still using the Rancher API will still result in the rollout status to hang.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):2.1.8
- Installation option (single install/HA):HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): local rancher cluster and downstream cluster of unknown provider type.
- Machine type (cloud/VM/metal) and specifications (CPU/memory):16GB of RAM, CPU unknown
- Kubernetes version (use `kubectl version`):1.13.5

- Docker version (use `docker version`):

```
Containers: 40
 Running: 37
 Paused: 0
 Stopped: 3
Images: 41
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-46-generic
Operating System: Ubuntu 16.04.6 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67GiB
Name: drekar-rancher-na-np-a
ID: SH6R:CDOC:LJ6N:W25N:F36U:B2ZH:X7LB:WFSX:WJLG:MWRH:N23E:EP2G
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

SURE-4958

**Comment by patrick0057** [comment]
This issue actually happens even when the kubectl version matches when deleting a pod.  We've tested with the proxied config directly on the Rancher node so that it didn't have to go through a load balancer or any other hops except for Rancher.

**Comment by PCatinean** [comment]
I experience the exact same symptoms, I just did not zone in on the information regarding kubectl versions

**Comment by alena1108** [comment]
The symptoms look similar to https://github.com/rancher/rancher/issues/17027 @aiwantaozi @loganhz can you investigate

**Comment by ajchiarello** [comment]
This problem has just started occurring for me, with rancher 2.5.2. Changing context to address the kubernetes control plane directly does not experience the hang.

**Comment by Kampfmoehre** [comment]
Is there any solution or at least a work around for this?

**Comment by jbilliau-rcd** [comment]
We are having this exact same problem on Rancher 2.5.5 running on EKS. Our 2.5.3 RKE cluster works just fine, but anytime we use `kubectl rollout status` on any deployment on any cluster behind Rancher 2.5.5/EKS, it hangs.

We our 2.5.5/EKS and our 2.5.3/RKE are running behind AWS NLB's going to 80/443 on target groups, which is then routing to nginx to terminate TLS. So it's odd becuase both setups are identical as far as I can tell. Only difference is the patch version?

**Comment by tnamoradze** [comment]
I have same problem with Rancher 2.5.5 running on K3S v1.19.8+k3s1

**Comment by jimbo8098** [comment]
I'm having the same issue. For context, I've setup a release pipeline which runs on a Ubuntu 18.04 machine (changing that to 20.04.2 soon). The output of the command is as follows:
```
2021-06-10T15:12:51.0784504Z ##[section]Starting: Wait for the service to become available
2021-06-10T15:12:51.0795114Z ==============================================================================
2021-06-10T15:12:51.0795444Z Task         : Kubectl
2021-06-10T15:12:51.0795834Z Description  : Deploy, configure, update a Kubernetes cluster in Azure Container Service by running kubectl commands
2021-06-10T15:12:51.0796195Z Version      : 1.181.0
2021-06-10T15:12:51.0796467Z Author       : Microsoft Corporation
2021-06-10T15:12:51.0796761Z Help         : https://aka.ms/azpipes-kubectl-tsg
2021-06-10T15:12:51.0797373Z ==============================================================================
2021-06-10T15:12:52.4123588Z ==============================================================================
2021-06-10T15:12:52.4138563Z 			Kubectl Client Version: v1.21.1
2021-06-10T15:12:52.4139226Z 			Kubectl Server Version: v1.19.9
2021-06-10T15:12:52.4140965Z ==============================================================================
2021-06-10T15:12:52.4383769Z [command]/home/<redacted>/azure-agents/<redacted>/_work/_tool/kubectl/1.21.1/x64/kubectl rollout -n openroute status deployment/openroute-api
2021-06-10T15:12:52.6992306Z Waiting for deployment "openroute-api" rollout to finish: 1 old replicas are pending termination...
2021-06-10T15:21:51.8349409Z Waiting for deployment "openroute-api" rollout to finish: 1 old replicas are pending termination...
2021-06-10T15:21:51.8350396Z Waiting for deployment spec update to be observed...
2021-06-10T15:21:51.8360419Z deployment "openroute-api" successfully rolled out
2021-06-10T15:29:04.8768441Z commandOutputWaiting for deployment "openroute-api" rollout to finish: 1 old replicas are pending termination...
2021-06-10T15:29:04.8770773Z ,Waiting for deployment "openroute-api" rollout to finish: 1 old replicas are pending termination...
2021-06-10T15:29:04.8771953Z ,Waiting for deployment spec update to be observed...
2021-06-10T15:29:04.8774173Z ,deployment "openroute-api" successfully rolled out
2021-06-10T15:29:04.8774741Z 
2021-06-10T15:29:04.8829509Z ##[section]Finishing: Wait for the service to become available
```

Note the large timestamp difference. I also had the same issue occur on the same machine using a matching kubectl version:

```
2021-06-10T15:48:52.1161534Z ##[section]Starting: Wait for the service to become available
2021-06-10T15:48:52.1172226Z ==============================================================================
2021-06-10T15:48:52.1172562Z Task         : Kubectl
2021-06-10T15:48:52.1173462Z Description  : Deploy, configure, update a Kubernetes cluster in Azure Container Service by running kubectl commands
2021-06-10T15:48:52.1173872Z Version      : 1.181.0
2021-06-10T15:48:52.1174148Z Author       : Microsoft Corporation
2021-06-10T15:48:52.1174443Z Help         : https://aka.ms/azpipes-kubectl-tsg
2021-06-10T15:48:52.1174800Z ==============================================================================
2021-06-10T15:48:52.4202816Z Found tool in cache: kubectl 1.19.9 x64
2021-06-10T15:48:52.5875158Z ==============================================================================
2021-06-10T15:48:52.5877118Z 			Kubectl Client Version: v1.19.9
2021-06-10T15:48:52.5878454Z 			Kubectl Server Version: v1.19.9
2021-06-10T15:48:52.5879186Z ==============================================================================
2021-06-10T15:48:52.6090543Z [command]/home/<redacted>/azure-agents/<redacted>/_work/_tool/kubectl/1.19.9/x64/kubectl rollout -n openroute status deployment/openroute-api
2021-06-10T15:48:52.8788034Z Waiting for deployment "openroute-api" rollout to finish: 1 old replicas are pending termination...
2021-06-10T15:55:33.9329909Z Waiting for deployment "openroute-api" rollout to finish: 1 old replicas are pending termination...
2021-06-10T15:55:33.9343584Z Waiting for deployment spec update to be observed...
2021-06-10T15:55:33.9358950Z Waiting for deployment spec update to be observed...
2021-06-10T15:55:33.9375047Z deployment "openroute-api" successfully rolled out
2021-06-10T16:01:58.9720078Z commandOutputWaiting for deployment "openroute-api" rollout to finish: 1 old replicas are pending termination...
2021-06-10T16:01:58.9723128Z ,Waiting for deployment "openroute-api" rollout to finish: 1 old replicas are pending termination...
2021-06-10T16:01:58.9725057Z ,Waiting for deployment spec update to be observed...
2021-06-10T16:01:58.9725764Z ,Waiting for deployment spec update to be observed...
2021-06-10T16:01:58.9726884Z ,deployment "openroute-api" successfully rolled out
2021-06-10T16:01:58.9727228Z 
2021-06-10T16:01:58.9794688Z ##[section]Finishing: Wait for the service to become available
```
I tried the same with `--v=10` and could see the curl responses coming back but the process would hand after saying `deployment "openroute-api" successfully rolled out` with nothing appearing in even the verbose logs for it. I'm not sure exactly what the holdup is since the only thing I really have to go on is:

https://github.com/kubernetes/client-go/blob/master/tools/watch/informerwatcher.go#L146

which is the last thing hit before we start seeing curl responses. A curl response to the machine returns a 401 with no bearer token very quickly and most `kubectl` commands work in a timely fashion.

**Comment by jimbo8098** [comment]
Updated the server last night and re-ran, same status unfortunately.

**Comment by clarkezone** [comment]
I'm having the same issue

**Comment by jarett-cyxtera** [comment]
I'm experiencing the same. Using the last curl command from the `-v10` output, you can see that a 200 response is immediately returned when connecting to the downstream cluster even though the connection remains open, but when passing through the Rancher endpoint nothing is returned until the timeout value passed in the URL expires.

Rancher v2.5.9 + downstream K8s v1.18.12

**Comment by Kampfmoehre** [comment]
So should I disable HTTP/2 for the whole cluster only for kubectl rollout status to not hang anymore?

**Comment by RalphDriessen** [comment]
I am having the same problem using rancher v2.6.4 and kubernetes v1.22.7. When connecting via an authorized cluster endpoint instead of via the rancher authentication proxy this issue does not occur. Also on our clusters running rancher v2.5.1 and kubernetes v1.19.7 using the same configurations/pipelines we're not experiencing this issue. The difference with the clusters using the newer rancher version is that for those rancher is hosted on an Azure cluster instead of on our own vps using docker.

**Comment by KokoBello** [comment]
We're experiencing the same issue, running rancher 2.6.4, rke kubernetes v1.22.6 with nginx ingress, behind external reverse proxy and kubectl 1.23.5

Everything works fine when using the authorized cluster endpoint.

I just want to share a few observations I have made when running 'kubectl rollout status <some-resource> --timeout=5s --watch=false -v=10'

When looking at the logs it looks like kubectl ignores the **--timeout** and **--watch** flags, and will hang until it hits the timeout (in this case 370 seconds).

```
...
I0408 13:50:00.710973   12030 round_trippers.go:466] curl -v -XGET  -H "Accept: application/json" -H "User-Agent: kubectl/v1.23.5 (darwin/amd64) kubernetes/c285e78" -H "Authorization: Bearer <masked>" 'https://<reverse-proxy-dn>/k8s/clusters/local/apis/apps/v1/namespaces/delivery/statefulsets?allowWatchBookmarks=true&fieldSelector=metadata.name%3Ddeploy-assistant&resourceVersion=9739553&**timeoutSeconds=370&watch=true**'
**partitioned roll out complete: 3 new pods have been updated...**
I0408 13:56:09.699723   12030 round_trippers.go:570] HTTP Statistics: GetConnection 0 ms **ServerProcessing 368984 ms Duration 368984 ms**
I0408 13:56:09.699758   12030 round_trippers.go:577] Response Headers:
I0408 13:56:09.699776   12030 round_trippers.go:580]     Connection: keep-alive
I0408 13:56:09.699793   12030 round_trippers.go:580]     X-Content-Type-Options: nosniff
I0408 13:56:09.699805   12030 round_trippers.go:580]     X-Kubernetes-Pf-Flowschema-Uid: 8d6342e8-ed57-49ef-b90c-e38089ca7b07
I0408 13:56:09.699814   12030 round_trippers.go:580]     Date: Fri, 08 Apr 2022 11:50:00 GMT
I0408 13:56:09.699821   12030 round_trippers.go:580]     Content-Type: application/json
I0408 13:56:09.699833   12030 round_trippers.go:580]     Audit-Id: 493c27d8-ae6f-44a4-933b-7a07aa113c85
I0408 13:56:09.699847   12030 round_trippers.go:580]     Cache-Control: no-cache, private
I0408 13:56:09.699860   12030 round_trippers.go:580]     X-Api-Cattle-Auth: true
I0408 13:56:09.699872   12030 round_trippers.go:580]     X-Kubernetes-Pf-Prioritylevel-Uid: d46ade84-83ca-4452-8171-714bdbf645e0
I0408 13:56:09.701660   12030 reflector.go:225] Stopping reflector *unstructured.Unstructured (0s) from k8s.io/client-go/tools/watch/informerwatcher.go:146
```

 If I modify the curl request and set watch=false, I get a response immediatly
```
{"kind":"StatefulSetList","apiVersion":"apps/v1","metadata":{"resourceVersion":"9745715"},"items":[{"metadata":{"name":"deploy-assistant","namespace":"delivery","uid":"5bd95d4b-1dd4-4fff-ad1e-fe8eae247056","resourceVersion":"8901655","generation":11,"creationTimestamp":"2022-03-17T12:54:33Z","labels":{"app":"deploy-assistant","group":"se.tre.sales.deployassistant"},"annotations":{"field.cattle.io/publicEndpoints":"[{\"addresses\":[\"\",\"\",\"\"],\"port\":80,\"protocol\":\"HTTP\",\"serviceName\":\"delivery:deploy-assistant
...
```
 
 If watch is set to true, the curl request will hang silently for as long as timeoutSeconds is set, and finally reply with an "empty" body
````
{"type":"BOOKMARK","object":{"kind":"StatefulSet","apiVersion":"apps/v1","metadata":{"resourceVersion":"9745715","creationTimestamp":null},"spec":{"replicas":0,"selector":null,"template":{"metadata":{"creationTimestamp":null},"spec":{"containers":null}},"serviceName":"","updateStrategy":{}},"status":{"replicas":0}}}
```

**Comment by martinounap** [comment]
Hi

We are sadly having same issue with Rancher 2.6.4

**Comment by DominikKol** [comment]
Hello, 

we also have the same problem on Rancher 2.6.4. Are there any resolution plans?

**Comment by tbernacchi** [comment]
SURE-4958

**Comment by cloudlady911** [comment]
I am having this issue as well.  Could it be because of a kubectl version mismatch between local host and rancher kubernetes cluster?  Has anyone checked that?

**Comment by cloudlady911** [comment]
Well, I tested that theory and it still hangs.

**Comment by cloudlady911** [comment]
if I bypass the rancher cli and just use the cluster config, (i.e. kubectl rollout status -w deployment app -n app) it works just fine.  But I am using a deployment tool.  It does not have the kubectl config available.

My stack:
Rancher version: 2.6.1
EKS with k8s version 1.20

On my deployment server I have the following:
rancher cli version v2.6.0

Result of rancher kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.15-eks-84b4fe6", GitCommit:"c813d094d1e9fa409079753049cfaa9a67524ed2", GitTreeState:"clean", BuildDate:"2022-06-09T18:20:31Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by cloudlady911** [comment]
I tried downgrading the rancher cli to 2.4 and the kubectl to 1.22.2, because that is what I am running on my mac.  Same issue.

**Comment by catherineluse** [comment]
A bug with proxied kubectl commands hanging was fixed in 2.6.6 https://github.com/rancher/rancher/issues/37707, so I would be interested to know if this bug is also reproducible in 2.6.6.

**Comment by sotona-** [comment]
Looks like I faced similar bug on 2.6.6:
`kubectl rollout status` hangs for 1 minute after output if I use Rancher proxy. The same command directly to K8S API works well.

K8S version v1.21.14-eks-18ef993

Rancher:
Component | Version
-- | --
Rancher | v2.6.6
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher85

**Comment by Horus-K** [comment]
I add annotations on ingress
nginx.ingress.kubernetes.io/http2-push-preload: 'false'
kubectl no longer hanging

**Comment by lemniskett** [comment]
> rancher version:2.6.9 kubectl version:1.20.11 I add annotations on ingress nginx.ingress.kubernetes.io/http2-push-preload: 'false' kubectl no longer hanging full annotations:
> 
> ```
> apiVersion: networking.k8s.io/v1
> kind: Ingress
> metadata:
>   annotations:
>     meta.helm.sh/release-name: rancher
>     meta.helm.sh/release-namespace: cattle-system
>     nginx.ingress.kubernetes.io/http2-push-preload: 'false'
>     nginx.ingress.kubernetes.io/proxy-connect-timeout: '200'
>     nginx.ingress.kubernetes.io/proxy-read-timeout: '1800'
>     nginx.ingress.kubernetes.io/proxy-send-timeout: '1800'
> ```

I can confirm that this fixed the issue, I'm running Rancher v2.7.7-rc3 with kubectl v1.27.4

**Comment by samjustus** [comment]
@snasovich randomly looking through bugs - it seems this is resolved?

**Comment by KokoBello** [comment]
Still didn't work for us... tried with http2-push-preload header, but no luck

**Comment by snasovich** [comment]
@samjustus , we have not received the confirmation from the customer who reported the same issue yet, however the internal testing was successful for fix suggested in https://github.com/rancher/rancher/issues/21324#issuecomment-1696991174

@KokoBello , are you sure you're running into the same exact issue? Could you share more information about your setup?

**Comment by edwin-bruurs** [comment]
Also tried the setting the http2-push-preload annotation but still didn't resolve the issue. 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rancher
  namespace: cattle-system
  labels:
    app: rancher
    app.kubernetes.io/managed-by: Helm
    chart: rancher-2.7.6
    heritage: Helm
    release: rancher
  annotations:
    cert-manager.io/issuer: rancher
    cert-manager.io/issuer-kind: Issuer
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["w.x.y.z"],"port":443,"protocol":"HTTPS","serviceName":"cattle-system:rancher","ingressName":"cattle-system:rancher","hostname":"rancher.redacted","path":"/","allNodes":false}]
    meta.helm.sh/release-name: rancher
    meta.helm.sh/release-namespace: cattle-system
    nginx.ingress.kubernetes.io/http2-push-preload: 'false'
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '200'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '1800'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '1800'
```

When setting `use-http2: false` in the config I don't have any timeouts any more (as mentioned in https://github.com/rancher/rancher/issues/21324#issuecomment-952457417).
I am using Rancher 2.7.6 and Kubernetes v1.26.8+rke2r1 for both the cluster running Rancher and the downstream cluster.

**Comment by Kamaradeivanov** [comment]
Same issue here with version describe bellow 

| Application| Version|
| -------- | ------- |
| rancher  | 2.7.9    |
| cluster | 1.26.8+rke2r1 |
|kubectl | 1.26.10|
|bitnami nginx-ingress controller | chart 9.9.2 ; app 1.9.3 |

The annotation `nginx.ingress.kubernetes.io/http2-push-preload: 'false'` does not fix the issue, but `use-http2: false` in the configmap fix the issue.

**Comment by KokoBello** [comment]
> @samjustus , we have not received the confirmation from the customer who reported the same issue yet, however the internal testing was successful for fix suggested in [#21324 (comment)](https://github.com/rancher/rancher/issues/21324#issuecomment-1696991174)
> 
> @KokoBello , are you sure you're running into the same exact issue? Could you share more information about your setup?

Yes, sounds like exactly the same issue.
Rancher 2.7.6 (RKE1)
Kubernetes Version: v1.24.10

I don't really know what 'http2-push-preload' does, but we are accessing our cluster thru an upstream (nginx) reverse proxy which I don't have any knowledge about, or control over. Maybe all upstream reverse proxies needs http2-push-preload disabled.

Our setup did work though, until some year ago, and broke when Rancher was upgraded.
