### ISSUE TITLE
[UI] Cluster went down because of wrong k8s version in cluster edit page

### ISSUE THREAD

**Issue by nickngch** [rancher/rancher#25335]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a rke template with the Kubernetes version set to 1.16.x
2. Create a cluster using that RKE template but set the Kubernetes version from drop down to 1.17.2
3. Edit the cluster, the Kubernetes version displayed as "1.16" instead of "1.17.2" in the page
4. Click Save

**Result:**
The cluster will be stuck in the "Updating" state

**Other details that may be helpful:**
Error on UI:
[etcd] Failed to bring up Etcd Plane: etcd cluster is unhealthy: hosts [172.31.0.27] failed to report healthy.  Check etcd container logs on each host for more information

Error on etcd container:
etcdserver/membership: cluster cannot be downgraded (current version: 3.3.15 is lower than determined cluster version: 3.4).

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.4
- Installation option (single install/HA):  HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 4core/16GB
- Kubernetes version (use `kubectl version`): 1.17

- Docker version (use `docker version`):
19.03.5

**Comment by westlywright** [comment]
@nickngch do you have any additional info? The data from your rke template (sensitive info redacted please) would be ideal. I am unable to reproduce this using `v2.3.4` or later. I suspect there may be some deeper issue here as you shouldn't have been able to downgrade, at least the versions I tested against wouldn't let me. Was this truly a custom cluster? Meaning that when you launched the cluster you selected `From Existing Nodes (custom)` or did you use one the RKE providers? If at all possible can you get the values for the following settings? `k8s-version`, `ui-k8s-supported-versions-range`, `ui-k8s-default-version-range`

**Comment by nickngch** [comment]
@westlywright sure here are the requested information:

```
# 
# Cluster Config
# 
docker_root_dir: /var/lib/docker
enable_cluster_alerting: false
enable_cluster_monitoring: false
enable_network_policy: false
local_cluster_auth_endpoint:
  enabled: true
# 
# Rancher Config
# 
rancher_kubernetes_engine_config:
  addon_job_timeout: 30
  authentication:
    strategy: x509
  ignore_docker_version: true
# 
# # Currently only nginx ingress provider is supported.
# # To disable ingress controller, set `provider: none`
# # To enable ingress on specific nodes, use the node_selector, eg:
#    provider: nginx
#    node_selector:
#      app: ingress
# 
  ingress:
    provider: nginx
  kubernetes_version: v1.16.6-rancher1-2
  monitoring:
    provider: metrics-server
# 
#   If you are using calico on AWS
# 
#    network:
#      plugin: calico
#      calico_network_provider:
#        cloud_provider: aws
# 
# # To specify flannel interface
# 
#    network:
#      plugin: flannel
#      flannel_network_provider:
#      iface: eth1
# 
# # To specify flannel interface for canal plugin
# 
#    network:
#      plugin: canal
#      canal_network_provider:
#        iface: eth1
# 
  network:
    mtu: 0
    options:
      flannel_backend_type: vxlan
    plugin: canal
# 
#    services:
#      kube-api:
#        service_cluster_ip_range: 10.43.0.0/16
#      kube-controller:
#        cluster_cidr: 10.42.0.0/16
#        service_cluster_ip_range: 10.43.0.0/16
#      kubelet:
#        cluster_domain: cluster.local
#        cluster_dns_server: 10.43.0.10
# 
  services:
    etcd:
      backup_config:
        enabled: true
        interval_hours: 12
        retention: 6
        safe_timestamp: false
      creation: 12h
      extra_args:
        election-timeout: '5000'
        heartbeat-interval: '500'
      gid: 0
      retention: 72h
      snapshot: false
      uid: 0
    kube_api:
      always_pull_images: false
      pod_security_policy: false
      service_node_port_range: 30000-32767
  ssh_agent_auth: false
windows_prefered_cluster: false
```

Yes it is custom cluster, I created an EC2 instance and ran the `docker run` manually to create the cluster.

I would love to share those information, do you mind to share where can I get those information?

**Comment by westlywright** [comment]
@nickngch Sorry I should have been more clear. If you open the vertical ellipsis menu for that particular template and click `view in api`, that's the info I would like to see. Honestly this sounds like it may have been a bug that has been resolved. If you selected the `1.16.x` version and did not select the allow override toggle then you should have never been able to select 1.17 in the drop down which is how it is currently behaving. We did have some issues in this area a while back though.

**Comment by nickngch** [comment]
@westlywright Got it, here is the information from `view in api of` that RKE template

```
{

    "actions": {
        "disable": "…/v3/clusterTemplateRevisions/cattle-global-data:ctr-p796d?action=disable"
    },
    "annotations": { },
    "baseType": "clusterTemplateRevision",
    "clusterConfig": {
        "defaultClusterRoleForProjectMembers": null,
        "defaultPodSecurityPolicyTemplateId": null,
        "dockerRootDir": "/var/lib/docker",
        "enableClusterAlerting": false,
        "enableClusterMonitoring": false,
        "enableNetworkPolicy": false,
        "localClusterAuthEndpoint": {
            "enabled": true,
            "type": "/v3/schemas/localClusterAuthEndpoint"
        },
        "rancherKubernetesEngineConfig": {
            "addonJobTimeout": 30,
            "authentication": {
                "strategy": "x509",
                "type": "/v3/schemas/authnConfig"
            },
            "ignoreDockerVersion": true,
            "ingress": {
                "provider": "nginx",
                "type": "/v3/schemas/ingressConfig"
            },
            "kubernetesVersion": "v1.16.7-rancher1-1",
            "monitoring": {
                "provider": "metrics-server",
                "type": "/v3/schemas/monitoringConfig"
            },
            "network": {
                "mtu": 0,
                "options": {
                    "flannel_backend_type": "vxlan"
                },
                "plugin": "canal",
                "type": "/v3/schemas/networkConfig"
            },
            "services": {
                "etcd": {
                    "backupConfig": {
                        "enabled": true,
                        "intervalHours": 12,
                        "retention": 6,
                        "safeTimestamp": false,
                        "type": "/v3/schemas/backupConfig"
                    },
                    "creation": "12h",
                    "extraArgs": {
                        "election-timeout": "5000",
                        "heartbeat-interval": "500"
                    },
                    "gid": 0,
                    "retention": "72h",
                    "snapshot": false,
                    "type": "/v3/schemas/etcdService",
                    "uid": 0
                },
                "kubeApi": {
                    "alwaysPullImages": false,
                    "podSecurityPolicy": false,
                    "serviceNodePortRange": "30000-32767",
                    "type": "/v3/schemas/kubeAPIService"
                },
                "type": "/v3/schemas/rkeConfigServices"
            },
            "sshAgentAuth": false,
            "type": "/v3/schemas/rancherKubernetesEngineConfig"
        },
        "type": "/v3/schemas/clusterSpecBase",
        "windowsPreferedCluster": false
    },
    "clusterTemplateId": "cattle-global-data:ct-kqdcn",
    "created": "2020-03-06T16:32:34Z",
    "createdTS": 1583512354000,
    "creatorId": "user-ghjrp",
    "enabled": true,
    "id": "cattle-global-data:ctr-p796d",
    "labels": {
        "io.cattle.field/clusterTemplateId": "ct-kqdcn"
    },
    "links": {
        "clusterTemplates": "…/v3/clusterTemplates?defaultRevisionId=cattle-global-data%3Actr-p796d",
        "clusters": "…/v3/clusters?clusterTemplateRevisionId=cattle-global-data%3Actr-p796d",
        "remove": "…/v3/clusterTemplateRevisions/cattle-global-data:ctr-p796d",
        "self": "…/v3/clusterTemplateRevisions/cattle-global-data:ctr-p796d",
        "update": "…/v3/clusterTemplateRevisions/cattle-global-data:ctr-p796d"
    },
    "name": "v1",
    "ownerReferences": [
        {
            "apiVersion": "management.cattle.io/v3",
            "kind": "ClusterTemplate",
            "name": "ct-kqdcn",
            "type": "/v3/schemas/ownerReference",
            "uid": "1509dc34-5fc8-11ea-93af-0242ac110002"
        }
    ],
    "questions": [
        {
            "default": "v1.16.7-rancher1-1",
            "max": 0,
            "maxLength": 0,
            "min": 0,
            "minLength": 0,
            "required": false,
            "type": "string",
            "variable": "rancherKubernetesEngineConfig.kubernetesVersion"
        }
    ],
    "type": "clusterTemplateRevision",
    "uuid": "1532abf2-5fc8-11ea-93af-0242ac110002"

}
```
Sorry I think I didn't mention that in my orignal comment, I did allow override toggle for Kubernetes version in the RKE template. But I can reproduce the issue by press F5 to refresh the page in `Edit Cluster` page

Steps to reproduce *updated:
1. Create a rke template with the Kubernetes version set to 1.16.x and allow override toggle for Kubernetes version
2. Create a cluster using that RKE template but set the Kubernetes version to 1.17.x
3. Edit the cluster, the Kubernetes version is 1.17.x, press F5 to refresh the page and the Kubernetes version will become 1.16
4. Dont save and quit from Edit cluster page (e.g. close the page or go to the home page)
5.  Go back to Edit cluster page again, the Kubernetes version still displayed as "1.16" instead of "1.17.x" in the UI
6. The cluster will stuck in the Updating stage if user didn't notice the Kubernetes version and click Save.

**Comment by westlywright** [comment]
@nickngch thanks for the info! I was able to track this down and as I suspected it was fixed in Rancher v2.3.5. If you can upgrade to that the problem should be cleared for you. If you can't upgrade your entire rancher release there is a global setting for `ui-index`. If you change just the tag number in that setting to `2.3.37` you will get the updated UI with the fix for that but this is a temporary solution and really the install should be upgraded.

**Comment by soumyalj** [comment]
Reproduced the issue in Rancher v2.3.4 with the below steps:
1. Create a RKE template with the Kubernetes version set to 1.16.x and allow override toggle for Kubernetes version
2. Create a cluster using that RKE template but set the Kubernetes version to 1.17.x
Edit the cluster, the Kubernetes version is 1.17.x, press F5 to refresh the page and the Kubernetes version will become 1.16
3. Dont save and quit from Edit cluster page (e.g. close the page or go to the home page)
Go back to Edit cluster page again, the Kubernetes version still displayed as "1.16" instead of "1.17.x" in the UI
4. Click on save and the cluster will be stuck in the "Updating"  state as below:
![Screen Shot 2020-03-06 at 5 45 29 PM](https://user-images.githubusercontent.com/18536626/76134342-4d20fd80-5fd2-11ea-9350-276786f48d81.png)

**Comment by westlywright** [comment]
@nickngch Strike that, I missed something about the issue so I'll need to investigate more. Sorry about that.

**Comment by soumyalj** [comment]
Tested with master-head (version 0519da989) using the steps above.
The issue is not fixed. Also, when we edit the cluster in step 2, the K8s version is showing as v1.16.7. This needs to be fixed too.

**Comment by soumyalj** [comment]
Validated with master-head (version 8ede17d10)
Steps:

1. Create a RKE template with the Kubernetes version set to 1.16.x/v1.16.7 and allow override toggle for Kubernetes version
2. Create a cluster using that RKE template but set the Kubernetes version to 1.17.3-rancher1-2
Edit the cluster, the Kubernetes version is 1.17.3-rancher1-2 , press F5 to refresh the page and the Kubernetes version will  continue to be v1.17.3-rancher1-2 as expected **[Fixed]**

![Screen Shot 2020-03-10 at 3 42 41 PM](https://user-images.githubusercontent.com/18536626/76366335-f1fb4d80-62e6-11ea-80a2-2a5acb230fd6.png)

3. Don't save and quit from Edit cluster page. Go back to Edit cluster page again, the Kubernetes version still displayed as v1.17.3-rancher1-2 **[Fixed]**
4. Click on save and the cluster does not go to "Updating" state . The cluster remains in "Active" state as expected.
