### ISSUE TITLE
Failure to deploy Helm3 App: apiVersion v2 invalid, must be v1

### ISSUE THREAD

**Issue by allout58** [rancher/rancher#26407]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1) Click Cluster > Apps > Launch
2) Choose an app from a Helm3 repository and launch

**Result:**
Fails to deploy app, saying `wait helm template failed. Error: apiVersion 'v2' is not valid. The value must be "v1"`

**Other details that may be helpful:**
The log when deleting the app looks like the following, which looks like it's trying to use Helm2/Tiller to control the app
```
2020/03/31 21:06:39 [ERROR] AppController p-p6c5p/ocm [helm-controller] failed with : wait helm template failed. Error: apiVersion 'v2' is not valid. The value must be "v1": exit status 1
---- repeats about once a second until I delete the app -----
2020/03/31 21:06:40 [INFO] Deleting chart using helm version: rancher-helm
[main] 2020/03/31 21:06:40 Starting Tiller v2.16.3-rancher1 (tls=false)
[main] 2020/03/31 21:06:40 GRPC listening on :47294
[main] 2020/03/31 21:06:40 Probes listening on :39590
[main] 2020/03/31 21:06:40 Storage driver is ConfigMap
[main] 2020/03/31 21:06:40 Max history per release is 10
[storage] 2020/03/31 21:06:41 getting release history for "ocm"
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.0
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM 4core 4GB ram
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Comp
iler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Comp
iler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:27:04 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:25:42 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by hwaastad** [comment]
https://rancher.com/docs/rancher/v2.x/en/catalog/#catalog-helm-deployment-versions

"When you create a custom catalog, you will have to configure the catalog to use either Helm 2 or Helm 3. This version cannot be changed later. If the catalog is added with the wrong Helm version, it will need to be deleted and re-added."

**Comment by allout58** [comment]
Yeah, I deleted my old custom catalog and re-added it as Helm3, then deployed the app. After filing this, I tried nuking the catalog (which was labeled Helm3) and recreating it, and it seemed to work. I'll try to investigate a little more, having some other issues with my test cluster right now so it might be a little slow

**Comment by Oats87** [comment]
I encountered this on an upgrade from 2.3.6 -> 2.4.2, where my helm catalog repo was migrated to a helm 2 repo (as expected) but I could no longer install new revisions of my app.

**Comment by cbron** [comment]
@Oats87 isn't that the opposite problem of the original issue ? OP was trying to install helm3 chart and got helm2 error. Sounds like you have helm2 chart and got helm2 error, was it same error ?

**Comment by cbron** [comment]
We figured it out. Real issue is that rancher's 2.3.6 helm version (2.14) didn't have the api validation, it was introduced in helm 2.15. And then Rancher 2.4's helm2 version is 2.16, so the validation is there. So the effect is that you can add a helm3 (api-v2) chart in rancher 2.3.6 and deploy with helm2, but you can't do the same in 2.4.

The current fix is to either: 
a) downgrade your chart to helm2 (apiv1)
b) upgrade the catalog and its charts to helm3 (apiv2)

We don't want to remove the check, as it is the standard (upstream) helm behavior. In an ideal world it should have always been there and the 2.3.x deploy should have failed.

**Comment by cbron** [comment]
Will add note about this to 2.4 release and docs.

**Comment by dasMulli** [comment]
> After filing this, I tried nuking the catalog (which was labeled Helm3) and recreating it, and it seemed to work.

I did that a couple of times, it seemed to work some of the time, but around half the instances of my apps i try to create in different projects fail with the v1/v2 error again because rancher apparently tries to use helm 2 instead of helm 3.

Are there known cache issues? Can it have to do with re-using names for namespaces / projects / app combinateions where previously a helm 2 app existed?
I also made sure that the v3 catalog has a different name than the v2 catalog that existed before, still Rancher tries to deploy apps with helm2 and then fails with the invalid apiVersion v2 error..

What is a good way to help diagnose this issue?

**Comment by cbron** [comment]
@dasMulli the apps will continue to use the helm version they were deployed with. If you delete the app and catalog then recreate both (ensuring you select helm3 from dropdown when creating catalog) it should work. If you're still seeing it at that point, check the rancher pod logs for `[Installing/Deleting] chart using helm version [X]`. After the install you can do `kubectl get apps myApp  -n namespace` and `check status.helmVersion` to see what it's set to.

If you're still seeing issues can you create a minimal sample repo/chart that you can reproduce with ? Then we can take a look.

**Comment by dasMulli** [comment]
Thanks, i'll try that next week.

**Comment by theAkito** [comment]
The catalog I have was always Helm 3 based, never Helm 2. Created a fresh Helm v3 App with a Helm v3 binary and yet Rancher complains about the Chart not being `v1`.

Is this confirmed to be fixed in Rancher 2.4.6?

**Comment by brendarearden** [comment]
@theAkito It should be resolved in 2.4.6, but let me go ahead and test it out to see if I am seeing the same issues. 

Was it a fresh install of Rancher 2.4.6 or did you upgrade from a previous rancher version?

**Comment by theAkito** [comment]
@brendarearden 

Sorry for the misunderstanding. I cannot update my cluster just for fun, so I want to only update, if it really works. I am on Rancher 2.4.5.

**Comment by dasMulli** [comment]
@theAkito the workaround is to create an app with an old version of the chart that was present in the catalog when you created it initially, then update the app to a recent version.

**Comment by theAkito** [comment]
@dasMulli 

So now I understand why it worked, when I upgraded the main app from Helm v2 to Helm v3. I basically issued the workaround without knowing it. So I'm kind of lost here with the brand new chart, that was never v2 to begin with... 🐕 💨

**Comment by theAkito** [comment]
Due to this and other issues, I was forced to upgrade to a newer version, so I chose `v2.5.0-alpha2` to be safe.
Yet, the version information says, that it is still using the exact same Helm version, as before. The error coming from this issue still persists and nothing changed...

**Comment by cyboman32** [comment]
Guys actually this issue still exists. Rancher 2.5.2 and 2.5.3
Tried to upgrade rook-ceph:
from
v1.4.7: (uses v1) https://charts.rook.io/release/rook-ceph-v1.4.7.tgz
to 
v.1.5.0-1: (uses v2) https://charts.rook.io/release/rook-ceph-v1.5.1.tgz
with the same error
handler helm-controller: wait helm template failed. Error: apiVersion 'v2' is not valid. The value must be "v1"
: exit status 1, requeuing

Everywhere is Helm 3 defined but still - Tiller
```
2020/12/03 08:12:35 [INFO] Installing chart using helm version: rancher-helm
[main] 2020/12/03 08:12:38 Starting Tiller v2.16.8-rancher1 (tls=false)
[main] 2020/12/03 08:12:38 GRPC listening on :56147
[main] 2020/12/03 08:12:38 Probes listening on :49897
[main] 2020/12/03 08:12:38 Storage driver is ConfigMap
[main] 2020/12/03 08:12:38 Max history per release is 10
[tiller] 2020/12/03 08:12:40 getting history for release rook-ceph
[storage] 2020/12/03 08:12:40 getting release history for "rook-ceph"
[tiller] 2020/12/03 08:12:41 preparing update for rook-ceph
[storage] 2020/12/03 08:12:41 getting deployed releases from "rook-ceph" history
[storage] 2020/12/03 08:12:41 getting last revision of "rook-ceph"
[storage] 2020/12/03 08:12:41 getting release history for "rook-ceph"
[tiller] 2020/12/03 08:12:42 rendering rook-ceph chart using values
[tiller] 2020/12/03 08:12:47 creating updated release for rook-ceph
[storage] 2020/12/03 08:12:47 creating release "rook-ceph.v14"
[storage] 2020/12/03 08:12:47 getting release history for "rook-ceph"
[storage] 2020/12/03 08:12:48 getting deployed releases from "rook-ceph" history
[storage] 2020/12/03 08:12:48 deleting release "rook-ceph.v4"
[storage] 2020/12/03 08:12:48 Pruned 1 record(s) from rook-ceph with 0 error(s)
...
```

```
apiVersion: management.cattle.io/v3
kind: CatalogTemplateVersion
metadata:
  creationTimestamp: "2020-11-28T21:30:58Z"
  generation: 1
  labels:
    catalog.cattle.io/template_name: rook-release-rook-ceph
    cattle.io/creator: norman
  managedFields:
  - apiVersion: management.cattle.io/v3
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:catalog.cattle.io/template_name: {}
          f:cattle.io/creator: {}
        f:ownerReferences: {}
      f:spec:
        .: {}
        f:digest: {}
        f:externalId: {}
        f:version: {}
        f:versionName: {}
        f:versionUrls: {}
      f:status:
        .: {}
        f:helmVersion: {}
    manager: Go-http-client
    operation: Update
    time: "2020-11-28T21:30:58Z"
  name: rook-release-rook-ceph-v1.4.7
  namespace: cattle-global-data
  ownerReferences:
  - apiVersion: management.cattle.io/v3
    kind: CatalogTemplate
    name: rook-release-rook-ceph
    uid: bbdecfdc-0492-44a0-81aa-86e8bc81013b
  resourceVersion: "82758340"
  selfLink: /apis/management.cattle.io/v3/namespaces/cattle-global-data/catalogtemplateversions/rook-release-rook-ceph-v1.4.7
  uid: 97686d7e-9f20-4117-bd9a-af1bcede7656
spec:
  digest: 108f3648608ed1407d5c8d3ed13c72b8c8f4bdae2b7708be067e3fd3bbf740cd
  externalId: catalog://?catalog=rook-release&template=rook-ceph&version=v1.4.7
  version: v1.4.7
  versionName: rook-ceph
  versionUrls:
  - https://charts.rook.io/release/rook-ceph-v1.4.7.tgz
status:
  helmVersion: helm_v3
```

```
apiVersion: management.cattle.io/v3
kind: CatalogTemplate
metadata:
  creationTimestamp: "2020-11-28T21:30:58Z"
  generation: 1
  labels:
    catalog.cattle.io/name: rook-release
    cattle.io/creator: norman
  managedFields:
  - apiVersion: management.cattle.io/v3
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:catalog.cattle.io/name: {}
          f:cattle.io/creator: {}
      f:spec:
        .: {}
        f:catalogId: {}
        f:defaultVersion: {}
        f:description: {}
        f:displayName: {}
        f:folderName: {}
        f:icon: {}
        f:projectURL: {}
        f:versions: {}
      f:status:
        .: {}
        f:helmVersion: {}
    manager: Go-http-client
    operation: Update
    time: "2020-11-28T21:30:58Z"
  name: rook-release-rook-ceph
  namespace: cattle-global-data
  resourceVersion: "82758331"
  selfLink: /apis/management.cattle.io/v3/namespaces/cattle-global-data/catalogtemplates/rook-release-rook-ceph
  uid: bbdecfdc-0492-44a0-81aa-86e8bc81013b
spec:
  catalogId: rook-release
  defaultVersion: v1.5.1
  description: File, Block, and Object Storage Services for your Cloud-Native Environment
  displayName: rook-ceph
  folderName: rook-ceph
  icon: https://rook.io/images/rook-logo.svg
  projectURL: https://github.com/rook/rook
  versions:
  - digest: 993846d3fa7d1e25fb0e120627ec3b85b20db80a1c10d6cec30a10840760230f
    externalId: catalog://?catalog=rook-release&template=rook-ceph&version=v1.5.1
    version: v1.5.1
    versionName: rook-ceph
    versionUrls:
    - https://charts.rook.io/release/rook-ceph-v1.5.1.tgz
  - digest: 7c06929d8e5d8776fabd321c10f9aa6a7498b672c3dc8c7f34245fc1b981d548
    externalId: catalog://?catalog=rook-release&template=rook-ceph&version=v1.5.0
    version: v1.5.0
    versionName: rook-ceph
    versionUrls:
    - https://charts.rook.io/release/rook-ceph-v1.5.0.tgz
  - digest: 108f3648608ed1407d5c8d3ed13c72b8c8f4bdae2b7708be067e3fd3bbf740cd
    externalId: catalog://?catalog=rook-release&template=rook-ceph&version=v1.4.7
    version: v1.4.7
    versionName: rook-ceph
    versionUrls:
    - https://charts.rook.io/release/rook-ceph-v1.4.7.tgz
...SKIPPED a lot of old versions
status:
  helmVersion: helm_v3
```

Seems rancher wrongly detect what helm binary to use, still tries to use rancher-helm, which is, I beleive, Helm2.

**Comment by cyboman32** [comment]
Tried removing and re-adding rook.io catalog - no effect

**Comment by rex** [comment]
@cbron This issue should be reopened, as this problem persists. I am dead in the water right now trying to spin up a new cluster because a critical infrastructure service (`bitnami/rabbitmq`) refuses to deploy. Tried deploying both Helm 2 and Helm 3 versions, the error is the same. There are other instances of this service running just fine in other clusters, but it refuses to deploy in the new one. 

I will not remove and re-add the catalog because so many things deployed to production rely on the catalog and I can't afford any downtime if removing the catalog causes rancher to freak out. What else is there that we can do? Since apparently upgrading to the most recent version is not even enough to resolve the issue.

**Comment by jnfinitym** [comment]
@rex yes, same issue trying to deploy the Ghost Blogging platform on a test cluster via the Bitnami helm chart. I can confim the issue still persists. I am using Rancher v2.5.7 with K3S (Kubernetes 1.20.5)

**Comment by krumware** [comment]
Also exiting here when trying to deploy extrenal-dns from Bitnami helm v3
Rancher 2.5.7

**Comment by swadeshp** [comment]
Issue still persists on v2.5.9 stable.
Is it fixed in v2.6.0?

**Comment by HcgRandon** [comment]
Also facing this still

**Comment by swadeshp** [comment]
1 month, no response. So much for an enterprise kubernetes management that can't even deploy an app without breaking.

**Comment by vincent99** [comment]
You're commenting on an issue closed 18 months ago that nobody is regularly monitoring.

2.6 (and the explorer UI in 2.5, which is now the only option) has a new "Apps & Marketplace" system that is much more directly Helm 3.  The Rancher "App" abstraction as its own type is no longer needed to provide reasonable RBAC, which native Helm 2 was totally missing.  You should be using that at this point, there is no reason to use the old apps other than maintaining existing installs.
