### ISSUE TITLE
Fix URL Parsing Logic in Norman to allow login requests to work with ports

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#26434]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Using `master-head` if you install following this issue (https://github.com/rancher/rancher/issues/26422), login fails
 2. We reverted the original PR in release/v2.4 (https://github.com/rancher/rancher/pull/26426)
3. We need a proper fix in `master`.

**Comment by sangeethah** [comment]
Reopening to get the fix merged in master

**Comment by khushboo-rancher** [comment]
Currently, in 2.4-head cf5ab1dcb Rancher login requests is getting redirected with correct ports.
UI is getting launched properly in rancher pointing to 8443 port and user is able to set password and login properly.

**With port 8443**
<img width="805" alt="Screen Shot 2020-04-17 at 11 23 33 AM" src="https://user-images.githubusercontent.com/60111667/79601785-3de7a200-809e-11ea-9dec-c948c1a69b51.png">

**with default port 443**
<img width="775" alt="Screen Shot 2020-04-17 at 11 27 47 AM" src="https://user-images.githubusercontent.com/60111667/79602101-bcdcda80-809e-11ea-96ce-36145f91f3ab.png">

**Comment by khushboo-rancher** [comment]
Verified in master-2777-head c49a121fc, login requests is getting redirected to correct port.
Tested with 443 and 8443 ports.

**Comment by carylewis** [comment]
I know this has been closed, but I am still experiencing this issue with rancher v2.7.10, dashboard v2.7.7
