### ISSUE TITLE
Can't provision clusters in Rancher single node docker install with bring your own valid certs 

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#28605]
**What kind of request is this:**
bug

**Steps to reproduce:**

- Perform a byo-valid certs Rancher docker install ([Option C](https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/single-node-docker/#option-c-bring-your-own-certificate-signed-by-a-recognized-ca))
- After installation provision a single node DO RKE cluster.
- Or any other cluster even importing clusters fail

**Result:**

Node gets created but the kubernetes cluster won't get active
`Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [x.x.x.x]`

**Other details that may be helpful:**

```
2020/08/27 21:43:38 [INFO] Provisioning node izaac-do-error1 done
2020/08/27 21:43:38 [INFO] Generating and uploading node config izaac-do-error1
2020/08/27 21:43:38 [INFO] Creating jail for c-xb447
2020/08/27 21:43:38 [INFO] Provisioning cluster [c-xb447]
2020/08/27 21:43:38 [INFO] Creating cluster [c-xb447]
2020/08/27 21:43:38 [INFO] Generating and uploading node config
2020/08/27 21:43:43 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:36113
2020/08/27 21:43:43 [INFO] cluster [c-xb447] provisioning: Initiating Kubernetes cluster
2020/08/27 21:43:43 [INFO] cluster [c-xb447] provisioning: [dialer] Setup tunnel for host [x.x.x.x]
2020/08/27 21:43:43 [INFO] [certificates] Generating CA kubernetes certificates
2020/08/27 21:43:43 [ERROR] cluster [c-xb447] provisioning: Failed to set up SSH tunneling for host [x.x.x.x]: Can't retrieve Docker Info: error during connect: Get "http://%!F(MISSING)var%!F(MISSING)run%!F(MISSING)docker.sock/v1.24/info": can not build dialer to [c-xb447:m-b79jq]
2020/08/27 21:43:43 [ERROR] cluster [c-xb447] provisioning: Removing host [x.x.x.x] from node lists
2020/08/27 21:43:43 [ERROR] cluster [c-xb447] provisioning: [state] can't fetch legacy cluster state from Kubernetes: Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [x.x.x.x]
2020/08/27 21:43:44 [INFO] [certificates] Generating Kubernetes API server aggregation layer requestheader client CA certificates
2020/08/27 21:43:44 [INFO] [certificates] GenerateServingCertificate is disabled, checking if there are unused kubelet certificates
2020/08/27 21:43:44 [INFO] [certificates] Generating Kubernetes API server certificates
2020/08/27 21:43:44 [INFO] [certificates] Generating Service account token key
2020/08/27 21:43:44 [INFO] [certificates] Generating Kube Controller certificates
2020/08/27 21:43:45 [INFO] [certificates] Generating Kube Scheduler certificates
2020/08/27 21:43:45 [INFO] [certificates] Generating Kube Proxy certificates
2020/08/27 21:43:45 [INFO] [certificates] Generating Node certificate
2020/08/27 21:43:45 [INFO] [certificates] Generating admin certificates and kubeconfig
2020/08/27 21:43:46 [INFO] [certificates] Generating Kubernetes API server proxy client certificates
2020/08/27 21:43:46 [INFO] cluster [c-xb447] provisioning: Successfully Deployed state file at [management-state/rke/rke-224419388/cluster.rkestate]
2020/08/27 21:43:46 [INFO] cluster [c-xb447] provisioning: Building Kubernetes cluster
2020/08/27 21:43:46 [ERROR] cluster [c-xb447] provisioning: Cluster must have at least one etcd plane host: please specify one or more etcd in cluster config
2020/08/27 21:43:46 [INFO] kontainerdriver rancherkubernetesengine stopped
2020/08/27 21:43:46 [ERROR] error syncing 'c-xb447': handler cluster-provisioner-controller: Cluster must have at least one etcd plane host: please specify one or more etcd in cluster config, requeuing
2020/08/27 21:44:16 [INFO] Provisioning cluster [c-xb447]
2020/08/27 21:44:16 [INFO] Creating cluster [c-xb447]
2020/08/27 21:44:21 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:36629
2020/08/27 21:44:21 [ERROR] Cluster c-xb447 previously failed to create
2020/08/27 21:44:21 [INFO] [certificates] GenerateServingCertificate is disabled, checking if there are unused kubelet certificates
2020/08/27 21:44:21 [INFO] [certificates] Generating Kubernetes API server certificates
2020/08/27 21:44:21 [INFO] cluster [c-xb447] provisioning: Initiating Kubernetes cluster
2020/08/27 21:44:21 [INFO] [certificates] Generating admin certificates and kubeconfig
2020/08/27 21:44:21 [INFO] [certificates] Generating kube-etcd-164-90-151-38 certificate and key
2020/08/27 21:44:22 [INFO] cluster [c-xb447] provisioning: Successfully Deployed state file at [management-state/rke/rke-584146539/cluster.rkestate]
2020/08/27 21:44:22 [INFO] cluster [c-xb447] provisioning: Building Kubernetes cluster
2020/08/27 21:44:22 [INFO] cluster [c-xb447] provisioning: [dialer] Setup tunnel for host [x.x.x.x]
2020/08/27 21:44:22 [ERROR] cluster [c-xb447] provisioning: Failed to set up SSH tunneling for host [x.x.x.x]: Can't retrieve Docker Info: error during connect: Get "http://%!F(MISSING)var%!F(MISSING)run%!F(MISSING)docker.sock/v1.24/info": can not build dialer to [c-xb447:m-b79jq]
2020/08/27 21:44:22 [INFO] kontainerdriver rancherkubernetesengine stopped
2020/08/27 21:44:22 [ERROR] cluster [c-xb447] provisioning: Removing host [x.x.x.x] from node lists
2020/08/27 21:44:22 [ERROR] cluster [c-xb447] provisioning: Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [x.x.x.x]
2020/08/27 21:44:22 [ERROR] error syncing 'c-xb447': handler cluster-provisioner-controller: Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [x.x.x.x], requeuing
2020/08/27 21:45:22 [INFO] Provisioning cluster [c-xb447]
2020/08/27 21:45:22 [INFO] Creating cluster [c-xb447]
2020/08/27 21:45:27 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:41501
2020/08/27 21:45:27 [ERROR] Cluster c-xb447 previously failed to create
2020/08/27 21:45:27 [INFO] cluster [c-xb447] provisioning: Initiating Kubernetes cluster
2020/08/27 21:45:27 [INFO] [certificates] GenerateServingCertificate is disabled, checking if there are unused kubelet certificates
2020/08/27 21:45:27 [INFO] [certificates] Generating admin certificates and kubeconfig
2020/08/27 21:45:27 [INFO] cluster [c-xb447] provisioning: Successfully Deployed state file at [management-state/rke/rke-310026958/cluster.rkestate]
2020/08/27 21:45:27 [INFO] cluster [c-xb447] provisioning: Building Kubernetes cluster
2020/08/27 21:45:27 [INFO] kontainerdriver rancherkubernetesengine stopped
2020/08/27 21:45:27 [INFO] cluster [c-xb447] provisioning: [dialer] Setup tunnel for host [x.x.x.x]
2020/08/27 21:45:27 [ERROR] cluster [c-xb447] provisioning: Failed to set up SSH tunneling for host [x.x.x.x]: Can't retrieve Docker Info: error during connect: Get "http://%!F(MISSING)var%!F(MISSING)run%!F(MISSING)docker.sock/v1.24/info": can not build dialer to [c-xb447:m-b79jq]
2020/08/27 21:45:27 [ERROR] cluster [c-xb447] provisioning: Removing host [x.x.x.x] from node lists
2020/08/27 21:45:27 [ERROR] cluster [c-xb447] provisioning: Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [x.x.x.x]
2020/08/27 21:45:27 [ERROR] error syncing 'c-xb447': handler cluster-provisioner-controller: Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [x.x.x.x], requeuing
2020-08-27 21:45:54.187620 I | mvcc: store.index: compact 2842
2020-08-27 21:45:54.220104 I | mvcc: finished scheduled compaction at 2842 (took 31.26481ms)
E0827 21:46:00.195739      25 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
From https://git.rancher.io/charts
 * branch            dev-v2.5   -> FETCH_HEAD
From https://git.rancher.io/partner-charts
 * branch            dev-v2.5   -> FETCH_HEAD
E0827 21:46:34.958150      25 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
2020/08/27 21:47:27 [INFO] Provisioning cluster [c-xb447]
2020/08/27 21:47:27 [INFO] Creating cluster [c-xb447]
2020/08/27 21:47:32 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:43619
2020/08/27 21:47:32 [ERROR] Cluster c-xb447 previously failed to create
2020/08/27 21:47:32 [INFO] cluster [c-xb447] provisioning: Initiating Kubernetes cluster
2020/08/27 21:47:32 [INFO] [certificates] GenerateServingCertificate is disabled, checking if there are unused kubelet certificates
2020/08/27 21:47:32 [INFO] [certificates] Generating admin certificates and kubeconfig
2020/08/27 21:47:32 [INFO] cluster [c-xb447] provisioning: Successfully Deployed state file at [management-state/rke/rke-020587477/cluster.rkestate]
2020/08/27 21:47:32 [INFO] cluster [c-xb447] provisioning: Building Kubernetes cluster
2020/08/27 21:47:32 [INFO] kontainerdriver rancherkubernetesengine stopped
2020/08/27 21:47:32 [INFO] cluster [c-xb447] provisioning: [dialer] Setup tunnel for host [x.x.x.x]
2020/08/27 21:47:32 [ERROR] cluster [c-xb447] provisioning: Failed to set up SSH tunneling for host [x.x.x.x]: Can't retrieve Docker Info: error during connect: Get "http://%!F(MISSING)var%!F(MISSING)run%!F(MISSING)docker.sock/v1.24/info": can not build dialer to [c-xb447:m-b79jq]
2020/08/27 21:47:32 [ERROR] cluster [c-xb447] provisioning: Removing host [x.x.x.x] from node lists
2020/08/27 21:47:32 [ERROR] cluster [c-xb447] provisioning: Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [x.x.x.x]
2020/08/27 21:47:32 [ERROR] error syncing 'c-xb447': handler cluster-provisioner-controller: Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [x.x.x.x], requeuing
2020-08-27 21:47:57.128777 I | http: TLS handshake error from 127.0.0.1:59720: EOF
2020-08-27 21:48:56.449297 I | http: TLS handshake error from 127.0.0.1:59732: EOF
2020-08-27 21:50:54.193837 I | mvcc: store.index: compact 4115
2020-08-27 21:50:54.219823 I | mvcc: finished scheduled compaction at 4115 (took 24.773859ms)
E0827 21:51:08.061851      25 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
From https://git.rancher.io/charts
 * branch            dev-v2.5   -> FETCH_HEAD
From https://git.rancher.io/partner-charts
 * branch            dev-v2.5   -> FETCH_HEAD
2020/08/27 21:51:32 [INFO] Provisioning cluster [c-xb447]
2020/08/27 21:51:32 [INFO] Creating cluster [c-xb447]
2020/08/27 21:51:37 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:39023
2020/08/27 21:51:37 [ERROR] Cluster c-xb447 previously failed to create
2020/08/27 21:51:37 [INFO] [certificates] GenerateServingCertificate is disabled, checking if there are unused kubelet certificates
2020/08/27 21:51:37 [INFO] [certificates] Generating admin certificates and kubeconfig
2020/08/27 21:51:37 [INFO] cluster [c-xb447] provisioning: Initiating Kubernetes cluster
2020/08/27 21:51:37 [INFO] cluster [c-xb447] provisioning: Successfully Deployed state file at [management-state/rke/rke-883038000/cluster.rkestate]
2020/08/27 21:51:37 [INFO] cluster [c-xb447] provisioning: Building Kubernetes cluster
2020/08/27 21:51:37 [INFO] kontainerdriver rancherkubernetesengine stopped
2020/08/27 21:51:37 [INFO] cluster [c-xb447] provisioning: [dialer] Setup tunnel for host [x.x.x.x]
2020/08/27 21:51:37 [ERROR] cluster [c-xb447] provisioning: Failed to set up SSH tunneling for host [x.x.x.x]: Can't retrieve Docker Info: error during connect: Get "http://%!F(MISSING)var%!F(MISSING)run%!F(MISSING)docker.sock/v1.24/info": can not build dialer to [c-xb447:m-b79jq]
2020/08/27 21:51:37 [ERROR] cluster [c-xb447] provisioning: Removing host [x.x.x.x] from node lists
2020/08/27 21:51:37 [ERROR] cluster [c-xb447] provisioning: Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [x.x.x.x]
2020/08/27 21:51:37 [ERROR] error syncing 'c-xb447': handler cluster-provisioner-controller: Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [x.x.x.x], requeuing
2020-08-27 21:55:54.197389 I | mvcc: store.index: compact 5352
2020-08-27 21:55:54.222819 I | mvcc: finished scheduled compaction at 5352 (took 24.453425ms)
E0827 21:55:56.389234      25 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
2020-08-27 21:56:05.166952 I | http: TLS handshake error from 127.0.0.1:59880: EOF
From https://git.rancher.io/charts
 * branch            dev-v2.5   -> FETCH_HEAD
From https://git.rancher.io/partner-charts
 * branch            dev-v2.5   -> FETCH_HEAD
2020-08-27 21:56:33.134532 W | etcdserver: read-only range request "key:\"/registry/leases/kube-system/kube-scheduler\" " with result "range_response_count:1 size:286" took too long (442.0573ms) to execute
2020-08-27 21:56:33.134926 W | etcdserver: read-only range request "key:\"/registry/services/endpoints/kube-system/kube-controller-manager\" " with result "range_response_count:1 size:453" took too long (348.318345ms) to execute
E0827 21:58:43.598711      25 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
2020/08/27 21:59:37 [INFO] Provisioning cluster [c-xb447]
2020/08/27 21:59:37 [INFO] Creating cluster [c-xb447]
2020/08/27 21:59:42 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:41783
2020/08/27 21:59:42 [ERROR] Cluster c-xb447 previously failed to create
2020/08/27 21:59:42 [INFO] cluster [c-xb447] provisioning: Initiating Kubernetes cluster
2020/08/27 21:59:42 [INFO] [certificates] GenerateServingCertificate is disabled, checking if there are unused kubelet certificates
2020/08/27 21:59:42 [INFO] [certificates] Generating admin certificates and kubeconfig
2020/08/27 21:59:42 [INFO] cluster [c-xb447] provisioning: Successfully Deployed state file at [management-state/rke/rke-621949135/cluster.rkestate]
2020/08/27 21:59:42 [INFO] cluster [c-xb447] provisioning: Building Kubernetes cluster
2020/08/27 21:59:42 [INFO] kontainerdriver rancherkubernetesengine stopped
2020/08/27 21:59:42 [INFO] cluster [c-xb447] provisioning: [dialer] Setup tunnel for host [x.x.x.x]
2020/08/27 21:59:42 [ERROR] cluster [c-xb447] provisioning: Failed to set up SSH tunneling for host [x.x.x.x]: Can't retrieve Docker Info: error during connect: Get "http://%!F(MISSING)var%!F(MISSING)run%!F(MISSING)docker.sock/v1.24/info": can not build dialer to [c-xb447:m-b79jq]
2020/08/27 21:59:42 [ERROR] cluster [c-xb447] provisioning: Removing host [x.x.x.x] from node lists
2020/08/27 21:59:42 [ERROR] cluster [c-xb447] provisioning: Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [x.x.x.x]
2020/08/27 21:59:43 [ERROR] error syncing 'c-xb447': handler cluster-provisioner-controller: Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [x.x.x.x], requeuing
2020-08-27 22:00:54.200806 I | mvcc: store.index: compact 6589
2020-08-27 22:00:54.228681 I | mvcc: finished scheduled compaction at 6589 (took 26.207635ms)
E0827 22:00:55.124402      25 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
From https://git.rancher.io/charts
 * branch            dev-v2.5   -> FETCH_HEAD
From https://git.rancher.io/partner-charts
 * branch            dev-v2.5   -> FETCH_HEAD
2020-08-27 22:05:54.205136 I | mvcc: store.index: compact 7826
2020-08-27 22:05:54.232815 I | mvcc: finished scheduled compaction at 7826 (took 23.74734ms)
From https://git.rancher.io/charts
 * branch            dev-v2.5   -> FETCH_HEAD
From https://git.rancher.io/partner-charts
 * branch            dev-v2.5   -> FETCH_HEAD
E0827 22:07:35.829778      25 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
2020-08-27 22:07:45.037780 I | http: TLS handshake error from 127.0.0.1:60242: EOF
2020/08/27 22:09:43 [INFO] Provisioning cluster [c-xb447]
2020/08/27 22:09:43 [INFO] Creating cluster [c-xb447]
2020/08/27 22:09:48 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:44715
2020/08/27 22:09:48 [ERROR] Cluster c-xb447 previously failed to create
2020/08/27 22:09:48 [INFO] [certificates] GenerateServingCertificate is disabled, checking if there are unused kubelet certificates
2020/08/27 22:09:48 [INFO] [certificates] Generating admin certificates and kubeconfig
2020/08/27 22:09:48 [INFO] cluster [c-xb447] provisioning: Initiating Kubernetes cluster
2020/08/27 22:09:48 [INFO] cluster [c-xb447] provisioning: Successfully Deployed state file at [management-state/rke/rke-239748066/cluster.rkestate]
2020/08/27 22:09:48 [INFO] kontainerdriver rancherkubernetesengine stopped
2020/08/27 22:09:48 [INFO] cluster [c-xb447] provisioning: Building Kubernetes cluster
2020/08/27 22:09:48 [INFO] cluster [c-xb447] provisioning: [dialer] Setup tunnel for host [x.x.x.x]
2020/08/27 22:09:48 [ERROR] cluster [c-xb447] provisioning: Failed to set up SSH tunneling for host [x.x.x.x]: Can't retrieve Docker Info: error during connect: Get "http://%!F(MISSING)var%!F(MISSING)run%!F(MISSING)docker.sock/v1.24/info": can not build dialer to [c-xb447:m-b79jq]
2020/08/27 22:09:48 [ERROR] cluster [c-xb447] provisioning: Removing host [x.x.x.x] from node lists
2020/08/27 22:09:48 [ERROR] cluster [c-xb447] provisioning: Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [x.x.x.x]
2020/08/27 22:09:48 [ERROR] error syncing 'c-xb447': handler cluster-provisioner-controller: Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [x.x.x.x], requeuing
2020-08-27 22:10:54.212085 I | mvcc: store.index: compact 9053
2020-08-27 22:10:54.237335 I | mvcc: finished scheduled compaction at 9053 (took 24.111214ms)
From https://git.rancher.io/charts
 * branch            dev-v2.5   -> FETCH_HEAD
From https://git.rancher.io/partner-charts
 * branch            dev-v2.5   -> FETCH_HEAD
2020-08-27 22:12:19.560694 I | http: TLS handshake error from 127.0.0.1:60334: EOF
E0827 22:12:37.531916      25 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
2020-08-27 22:15:54.215923 I | mvcc: store.index: compact 10289
2020-08-27 22:15:54.247905 I | mvcc: finished scheduled compaction at 10289 (took 23.667538ms)
From https://git.rancher.io/charts
 * branch            dev-v2.5   -> FETCH_HEAD
From https://git.rancher.io/partner-charts
 * branch            dev-v2.5   -> FETCH_HEAD
E0827 22:19:34.208910      25 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
2020/08/27 22:19:48 [INFO] Provisioning cluster [c-xb447]
2020/08/27 22:19:48 [INFO] Creating cluster [c-xb447]
2020/08/27 22:19:53 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:36495
2020/08/27 22:19:53 [ERROR] Cluster c-xb447 previously failed to create
2020/08/27 22:19:53 [INFO] [certificates] GenerateServingCertificate is disabled, checking if there are unused kubelet certificates
2020/08/27 22:19:53 [INFO] [certificates] Generating admin certificates and kubeconfig
2020/08/27 22:19:53 [INFO] cluster [c-xb447] provisioning: Initiating Kubernetes cluster
2020/08/27 22:19:53 [INFO] cluster [c-xb447] provisioning: Successfully Deployed state file at [management-state/rke/rke-820190169/cluster.rkestate]
2020/08/27 22:19:53 [INFO] cluster [c-xb447] provisioning: Building Kubernetes cluster
2020/08/27 22:19:53 [INFO] kontainerdriver rancherkubernetesengine stopped
2020/08/27 22:19:53 [INFO] cluster [c-xb447] provisioning: [dialer] Setup tunnel for host [x.x.x.x]
2020/08/27 22:19:53 [ERROR] cluster [c-xb447] provisioning: Failed to set up SSH tunneling for host [x.x.x.x]: Can't retrieve Docker Info: error during connect: Get "http://%!F(MISSING)var%!F(MISSING)run%!F(MISSING)docker.sock/v1.24/info": can not build dialer to [c-xb447:m-b79jq]
2020/08/27 22:19:53 [ERROR] cluster [c-xb447] provisioning: Removing host [x.x.x.x] from node lists
2020/08/27 22:19:53 [ERROR] cluster [c-xb447] provisioning: Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [x.x.x.x]
2020/08/27 22:19:53 [ERROR] error syncing 'c-xb447': handler cluster-provisioner-controller: Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [x.x.x.x], requeuing
2020-08-27 22:20:54.227505 I | mvcc: store.index: compact 11516
2020-08-27 22:20:54.252853 I | mvcc: finished scheduled compaction at 11516 (took 24.044065ms)
From https://git.rancher.io/charts
 * branch            dev-v2.5   -> FETCH_HEAD
From https://git.rancher.io/partner-charts
 * branch            dev-v2.5   -> FETCH_HEAD
E0827 22:21:36.202796      25 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
2020-08-27 22:22:31.305741 I | http: TLS handshake error from 127.0.0.1:60578: EOF
2020-08-27 22:22:31.305813 I | http: TLS handshake error from 127.0.0.1:60576: EOF
2020-08-27 22:25:54.231449 I | mvcc: store.index: compact 12754
```

**Environment information**
- Rancher version: `master-head (08/27/2020)` _5e1b21b93_
- Installation option: single

gzrancher/rancher#12756

**Comment by cbron** [comment]
Main issue: https://github.com/rancher/rancher/issues/28279

**Comment by izaac** [comment]
Rancher version: `master-head (09/08/2020)` _76c26fb0f_

I'm still experiencing this error even using `--privileged` 

`docker run -d --privileged --name=master --restart=unless-stopped -p 80:80 -p 443:443 -v ./cert.pem:/etc/rancher/ssl/cert.pem -v ./privkey.pem:/etc/rancher/ssl/key.pem  rancher/rancher:master-head --no-cacerts`


```
2020/09/08 17:02:02 [INFO] Provisioning cluster [c-hlr5j]
2020/09/08 17:02:02 [INFO] Creating cluster [c-hlr5j]
2020/09/08 17:02:07 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:33147
2020/09/08 17:02:07 [ERROR] Cluster c-hlr5j previously failed to create
2020/09/08 17:02:07 [INFO] [certificates] GenerateServingCertificate is disabled, checking if there are unused kubelet certificates
2020/09/08 17:02:07 [INFO] [certificates] Generating admin certificates and kubeconfig
2020/09/08 17:02:07 [INFO] cluster [c-hlr5j] provisioning: Initiating Kubernetes cluster
2020/09/08 17:02:07 [INFO] kontainerdriver rancherkubernetesengine stopped
2020/09/08 17:02:07 [INFO] cluster [c-hlr5j] provisioning: Successfully Deployed state file at [management-state/rke/rke-088564443/cluster.rkestate]
2020/09/08 17:02:08 [INFO] cluster [c-hlr5j] provisioning: Building Kubernetes cluster
2020/09/08 17:02:08 [INFO] cluster [c-hlr5j] provisioning: [dialer] Setup tunnel for host [x.x.x.x]
2020/09/08 17:02:08 [ERROR] cluster [c-hlr5j] provisioning: Failed to set up SSH tunneling for host [x.x.x.x]: Can't retrieve Docker Info: error during connect: Get "http://%!F(MISSING)var%!F(MISSING)run%!F(MISSING)docker.sock/v1.24/info": can not build dialer to [c-hlr5j:m-5szzd]
2020/09/08 17:02:08 [ERROR] cluster [c-hlr5j] provisioning: Removing host [x.x.x.x] from node lists
2020/09/08 17:02:08 [ERROR] cluster [c-hlr5j] provisioning: Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [x.x.x.x]
2020/09/08 17:02:08 [ERROR] error syncing 'c-hlr5j': handler cluster-provisioner-controller: Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [x.x.x.x], requeuing
```

![Screen Shot 2020-09-08 at 10 09 30 AM](https://user-images.githubusercontent.com/27659/92507226-7dcd3400-f1bb-11ea-98b9-2914c8184c7c.png)

**Comment by cbron** [comment]
There is a new fix going out for main issue that should resolve the above issue also. DNS wasn't working so that would explain why ssh tunnel failed.

**Comment by cbron** [comment]
Back in test, but may want to wait for main issue to resolve first.

**Comment by izaac** [comment]
Rancher version (master-head (09/08/2020) _343b8e19c_

I see core-dns in the `local` cluster in the docker Rancher install

`docker run -d --privileged --name=master --restart=unless-stopped -p 80:80 -p 443:443 -v ./cert.pem:/etc/rancher/ssl/cert.pem -v ./privkey.pem:/etc/rancher/ssl/key.pem rancher/rancher:master-head --no-cacerts`


But I'm still experiencing the issue mentioned here https://github.com/rancher/rancher/issues/28605#issuecomment-689017366

**Comment by izaac** [comment]
This is also reproducible on `v2.5.0-alpha3`

**Comment by rene-demonsters** [comment]
I tried upgrading an existing setup-up running Rancher v2.4.8 (single node docker install) which uses Let's Encrypt certificates (--acme-domain for Rancher). After which I run into a similar issue. It runs into: 

`2020/10/06 12:46:39 [ERROR] error syncing 'c-r5h93': handler cluster-deploy: Error while applying agent YAML, it will be retried automatically: exit status 1, Unable to connect to the server: net/http: TLS handshake timeout , requeuing`

Any suggestions on how to recover from this as my cluster is stuck on provisioning?

**Comment by dwene** [comment]
Bummer. Is there any way to work around this issue for those of us who are running a single docker container and want to upgrade to 2.5?

**Comment by shinebayar-g** [comment]
Does it also affects rancher container started with `--no-cacerts` flag and doesn't use any external certificates? Our rancher is deployed by option B as documented [here](https://rancher.com/docs/rancher/v2.x/en/installation/resources/advanced/single-node-install-external-lb/#2-choose-an-ssl-option-and-install-rancher).

![image](https://user-images.githubusercontent.com/3091558/95289959-ab94af80-0831-11eb-94de-15526baf2d21.png)

**Comment by rene-demonsters** [comment]
So with my cluster stuck in provisioning and the rollback not completely removing all traces, I decided I best reinstall Rancher and the cluster entirely but on K3s instead of Single Node Docker.

I removed all traces of the cluster, removed Rancher from the Rancher node. After that I did the following things:
1. Install k3s server on docker using `curl -sfL https://get.k3s.io | sh -s - --docker`
2. Install Rancher v2.5.0 on that K3s cluster using helm3 and the instructions from https://rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-k8s/
3. This seems to have launch 3 Rancher v2.5.0 containers
4. Added a new cluster to Rancher, telling it to use K8s 1.19.2
5. Registered 3 nodes with the roles etcd, control plane and worker roles
5. The new cluster is stuck at provisioning. When I check the logs of the agent I see the following:

```
INFO: Arguments: --server https://example.com --token REDACTED --etcd --controlplane --worker
INFO: Environment: CATTLE_ADDRESS=83.x.x.x CATTLE_INTERNAL_ADDRESS= CATTLE_NODE_NAME=ncwt-production-1 CATTLE_ROLE=,etcd,worker,controlplane CATTLE_SERVER=https://example.com CATTLE_TOKEN=REDACTED
INFO: Using resolv.conf: nameserver 79.x.x.x nameserver 194.x.x.x nameserver 194.x.x.x nameserver 8.8.8.8 search ams.resource.cloud
INFO: https://example.com/ping is accessible
INFO: example.com resolves to 173.x.x.x
time="2020-10-08T11:29:13Z" level=info msg="Listening on /tmp/log.sock"
time="2020-10-08T11:29:13Z" level=info msg="Rancher agent version v2.5.0 is starting"
time="2020-10-08T11:29:13Z" level=info msg="Option customConfig=map[address:83.x.x.x internalAddress: label:map[] roles:[etcd worker controlplane] taints:[]]"
time="2020-10-08T11:29:13Z" level=info msg="Option etcd=true"
time="2020-10-08T11:29:13Z" level=info msg="Option controlPlane=true"
time="2020-10-08T11:29:13Z" level=info msg="Option worker=true"
time="2020-10-08T11:29:13Z" level=info msg="Option requestedHostname=ncwt-production-1"
time="2020-10-08T11:29:13Z" level=info msg="Connecting to wss://example.com/v3/connect/register with token REDACTED
time="2020-10-08T11:29:13Z" level=info msg="Connecting to proxy" url="wss://example.com/v3/connect/register"
time="2020-10-08T11:29:13Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering or etcd and controlplane node have to be registered first"
time="2020-10-08T11:29:15Z" level=info msg="Starting plan monitor, checking every 15 seconds"
```

So as @izaac said, it looks like Rancher fails to start etcd and controlplane first

**Comment by rene-demonsters** [comment]
Ok, I've uninstalled v2.5.0, downgraded to v2.4.8 and tried again with K8s 1.18.9 for the cluster. It gets stuck at the same step, etcd keeps restarting itself. I've grabbed the logs and it's an endless loop of:

```
[WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
2020-10-08 16:21:00.895496 I | etcdmain: etcd Version: 3.4.3
2020-10-08 16:21:00.895501 I | etcdmain: Git SHA: 3cf2f69b5
2020-10-08 16:21:00.895504 I | etcdmain: Go Version: go1.12.12
2020-10-08 16:21:00.895506 I | etcdmain: Go OS/Arch: linux/amd64
2020-10-08 16:21:00.895510 I | etcdmain: setting maximum number of CPUs to 8, total number of available CPUs is 8
2020-10-08 16:21:00.895562 N | etcdmain: the server is already initialized as member before, starting as etcd member...
[WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
2020-10-08 16:21:00.895601 I | embed: peerTLS: cert = /etc/kubernetes/ssl/kube-etcd-83-x-x-x6.pem, key = /etc/kubernetes/ssl/kube-etcd-83-x-x-x6-key.pem, trusted-ca = /etc/kubernetes/ssl/kube-ca.pem, client-cert-auth = true, crl-file =
2020-10-08 16:21:00.896395 I | embed: name = etcd-ncwt-production-3
2020-10-08 16:21:00.896412 I | embed: data dir = /var/lib/rancher/etcd/
2020-10-08 16:21:00.896417 I | embed: member dir = /var/lib/rancher/etcd/member
2020-10-08 16:21:00.896420 I | embed: heartbeat = 500ms
2020-10-08 16:21:00.896422 I | embed: election = 5000ms
2020-10-08 16:21:00.896425 I | embed: snapshot count = 100000
2020-10-08 16:21:00.896432 I | embed: advertise client URLs = https://8x.x.x6:2379,https://8x.x.x6:4001
2020-10-08 16:21:00.896436 I | embed: initial advertise peer URLs = https://8x.x.x6:2380
2020-10-08 16:21:00.896440 I | embed: initial cluster =
2020-10-08 16:21:00.906700 I | etcdserver: recovered store from snapshot at index 9900104
2020-10-08 16:21:01.128069 I | mvcc: restore compact to 8785060
2020-10-08 16:21:01.218305 I | etcdserver: restarting member 63702b1f9fd35046 in cluster 5d9c12bf9d684399 at commit index 9909364
raft2020/10/08 16:21:01 INFO: 63702b1f9fd35046 switched to configuration voters=(5452969647235042514 7165274421971865670 9323449840846847951)
raft2020/10/08 16:21:01 INFO: 63702b1f9fd35046 became follower at term 8
raft2020/10/08 16:21:01 INFO: newRaft 63702b1f9fd35046 [peers: [4bacd700ca6e8cd2,63702b1f9fd35046,81638c3b84d93fcf], term: 8, commit: 9909364, applied: 9900104, lastindex: 9909364, lastterm: 8]
2020-10-08 16:21:01.219045 I | etcdserver/api: enabled capabilities for version 3.4
2020-10-08 16:21:01.219063 I | etcdserver/membership: added member 63702b1f9fd35046 [https://8x.x.x6:2380] to cluster 5d9c12bf9d684399 from store
2020-10-08 16:21:01.219068 I | etcdserver/membership: added member 81638c3b84d93fcf [https://8x.x.x5:2380] to cluster 5d9c12bf9d684399 from store
2020-10-08 16:21:01.219072 I | etcdserver/membership: added member 4bacd700ca6e8cd2 [https://8x.x.x7:2380] to cluster 5d9c12bf9d684399 from store
2020-10-08 16:21:01.219077 I | etcdserver/membership: set the cluster version to 3.4 from store
2020-10-08 16:21:01.224421 I | mvcc: restore compact to 8785060
2020-10-08 16:21:01.234913 W | auth: simple token is not cryptographically signed
2020-10-08 16:21:01.242883 I | rafthttp: starting peer 4bacd700ca6e8cd2...
2020-10-08 16:21:01.242941 I | rafthttp: started HTTP pipelining with peer 4bacd700ca6e8cd2
2020-10-08 16:21:01.244310 I | rafthttp: started streaming with peer 4bacd700ca6e8cd2 (writer)
2020-10-08 16:21:01.245983 I | rafthttp: started streaming with peer 4bacd700ca6e8cd2 (writer)
2020-10-08 16:21:01.247526 I | rafthttp: started peer 4bacd700ca6e8cd2
2020-10-08 16:21:01.247564 I | rafthttp: added peer 4bacd700ca6e8cd2
2020-10-08 16:21:01.247578 I | rafthttp: starting peer 81638c3b84d93fcf...
2020-10-08 16:21:01.247585 I | rafthttp: started streaming with peer 4bacd700ca6e8cd2 (stream MsgApp v2 reader)
2020-10-08 16:21:01.247596 I | rafthttp: started streaming with peer 4bacd700ca6e8cd2 (stream Message reader)
2020-10-08 16:21:01.247610 I | rafthttp: started HTTP pipelining with peer 81638c3b84d93fcf
2020-10-08 16:21:01.248710 I | rafthttp: started streaming with peer 81638c3b84d93fcf (writer)
2020-10-08 16:21:01.249608 I | rafthttp: started streaming with peer 81638c3b84d93fcf (writer)
2020-10-08 16:21:01.251349 I | rafthttp: started peer 81638c3b84d93fcf
2020-10-08 16:21:01.251372 I | rafthttp: added peer 81638c3b84d93fcf
2020-10-08 16:21:01.251391 I | etcdserver: starting server... [version: 3.4.3, cluster version: 3.4]
2020-10-08 16:21:01.251417 I | rafthttp: started streaming with peer 81638c3b84d93fcf (stream Message reader)
2020-10-08 16:21:01.251591 I | rafthttp: started streaming with peer 81638c3b84d93fcf (stream MsgApp v2 reader)
2020-10-08 16:21:01.253422 I | embed: ClientTLS: cert = /etc/kubernetes/ssl/kube-etcd-83-x-x-x6.pem, key = /etc/kubernetes/ssl/kube-etcd-83-x-x-x6-key.pem, trusted-ca = /etc/kubernetes/ssl/kube-ca.pem, client-cert-auth = true, crl-file =
2020-10-08 16:21:01.253471 I | embed: listening for peers on [::]:2380
2020-10-08 16:21:01.255558 E | etcdserver: the member has been permanently removed from the cluster
2020-10-08 16:21:01.255573 I | etcdserver: the data-dir used by this member must be removed.
2020-10-08 16:21:01.255585 I | etcdserver: aborting publish because server is stopped
raft2020/10/08 16:21:01 INFO: 63702b1f9fd35046 switched to configuration voters=(5452969647235042514 9323449840846847951)
2020-10-08 16:21:01.280927 I | etcdserver/membership: removed member 63702b1f9fd35046 from cluster 5d9c12bf9d684399
2020-10-08 16:21:01.280972 I | rafthttp: stopping peer 4bacd700ca6e8cd2...
2020-10-08 16:21:01.280990 I | rafthttp: stopped streaming with peer 4bacd700ca6e8cd2 (writer)
2020-10-08 16:21:01.280998 I | rafthttp: stopped streaming with peer 4bacd700ca6e8cd2 (writer)
2020-10-08 16:21:01.281018 I | rafthttp: stopped HTTP pipelining with peer 4bacd700ca6e8cd2
2020-10-08 16:21:01.281032 I | rafthttp: stopped streaming with peer 4bacd700ca6e8cd2 (stream MsgApp v2 reader)
2020-10-08 16:21:01.281044 I | rafthttp: stopped streaming with peer 4bacd700ca6e8cd2 (stream Message reader)
2020-10-08 16:21:01.281053 I | rafthttp: stopped peer 4bacd700ca6e8cd2
2020-10-08 16:21:01.281057 I | rafthttp: stopping peer 81638c3b84d93fcf...
2020-10-08 16:21:01.281063 I | rafthttp: stopped streaming with peer 81638c3b84d93fcf (writer)
2020-10-08 16:21:01.281073 I | rafthttp: stopped streaming with peer 81638c3b84d93fcf (writer)
2020-10-08 16:21:01.281084 I | rafthttp: stopped HTTP pipelining with peer 81638c3b84d93fcf
2020-10-08 16:21:01.281099 I | rafthttp: stopped streaming with peer 81638c3b84d93fcf (stream MsgApp v2 reader)
2020-10-08 16:21:01.281115 I | rafthttp: stopped streaming with peer 81638c3b84d93fcf (stream Message reader)
2020-10-08 16:21:01.281126 I | rafthttp: stopped peer 81638c3b84d93fcf
2020-10-08 16:22:01.535559 W | pkg/flags: unrecognized environment variable ETCD_UNSUPPORTED_ARCH=x86_64
```

If this is supposed to go in a new issue, please let me know. But I figure it's related to why etcd isn't starting properly and the subsequent failing of provisioning.

**Comment by slash1387** [comment]
No chance to provision any combination of api and authorized cluster endpoint on/off via docker run commands. Always stuck on API not being ready. Kubeapi server logs always brings this log: 
_authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, square/go-jose: error in cryptographic primitive]_
We are using single docker installation with self signed cert. Please fix this asap as it is not usable in smaller setups with docker installlation :(

**Comment by izaac** [comment]
Re-tested on Rancher version `v2.5.1`

Coverage: Rancher single node install then RKE DO provisioned cluster. 

The only certificate install option that failed for me was **Build Your Own with Valid Certs**
With **Letsencrypt** and **Build Your Own Self-Signed** I am able to provision the RKE DO downstream Cluster.

Symptoms in the BYO-Valid:

```
[ERROR] error syncing 'c-drn8q': handler cluster-provisioner-controller: Cluster must have at least one etcd plane host: please specify one or more etcd in cluster config, requeuing
Failed to set up SSH tunneling for host [x.x.x.x]: Can't retrieve Docker Info: error during connect: Get "http://%!F(MISSING)var%!F(MISSING)run%!F(MISSING)docker.sock/v1.24/info": can not build dialer to [c-drn8q:m-q28d7]
```


Kubernetes version used in Downstream cluster: `1.19.2`

**Comment by izaac** [comment]
Rancher version upgrade `from v2.4.8 to v2.5.1` single install. With Letsencrpyt option.

I was not able to reproduce the issue reported here: https://github.com/rancher/rancher/issues/28605#issuecomment-704252705  
@rene-demonsters could you provide the following info of `c-r5h93` ?

- Cluster type (DO, Linode, GKE, etc)
- Or was it the local cluster after upgrading to `v2.5.x` ?

But that upgrade issue looks pre-existing #29131

**Comment by izaac** [comment]
@superseb dug into this and and I was using the `cert.pem` certificate file instead of the `fullchain.pem` for the `byo-valid` installation option.

After a fresh Rancher `v2.5.1` install using the `fullchain.pem` I was able to provision an RKE DO cluster.

**Comment by izaac** [comment]
Closing, all four certificates installation methods worked in Rancher `v2.5.1`

**Comment by slash1387** [comment]
@izaac whats so hard to reproduce?
1. fresh install
```
docker run -d --restart=unless-stopped --name=rancher2.5.1 -p 80:80 -p 443:443 --privileged rancher/rancher:v2.5.1

2. Global -> Add Cluster -> Existing Nodes -> Choose all 3 roles (etcd, worker, control-plane)
3. wait...it will stop with ERROR: Cluster health check failed: cluster agent is not ready

not working!

**Comment by izaac** [comment]
@slash1387 this is a different error related to custom clusters https://github.com/rancher/rancher/issues/28836 If the cluster doesn't recover after some time, could you please open an issue and provide the logs ? Thanks for reporting this issue.

**Comment by hrvatskibogmars** [comment]
I tried v2.5.1 what I get is when trying to import cluster is this. (Importedv1.14.9-eks)

`Error while applying agent YAML, it will be retried automatically: exit status 1, Unable to connect to the server: remote error: tls: internal error`

I can inspect the cluster but the message is still present there.

--

**Comment by a14stoner** [comment]
For me it helped when upgrading rancher from v2.4.5 to v2.5.9. Then add a new node to the cluster and remove it afterwards. 
Now everything works fine and the cluster is up again.

**Comment by Kritika2206** [comment]
> I tried v2.5.1 what I get is when trying to import cluster is this. (Importedv1.14.9-eks)
> 
> `Error while applying agent YAML, it will be retried automatically: exit status 1, Unable to connect to the server: remote error: tls: internal error`
> 
> I can inspect the cluster but the message is still present there.
> 
> --

Hi [hrvatskibogmars],

Did you got any solution for this TLS issue while importing cluster.

**Comment by Kritika2206** [comment]
> > > ## I tried v2.5.1 what I get is when trying to import cluster is this. (Importedv1.14.9-eks)
> > > `Error while applying agent YAML, it will be retried automatically: exit status 1, Unable to connect to the server: remote error: tls: internal error`
> > > I can inspect the cluster but the message is still present there.
> > 
> > 
> > Hi [hrvatskibogmars],
> > Did you got any solution for this TLS issue while importing cluster.
> 
> No. had to provision a new Rancher cluster from scratch.

If i will provision new rancher also then to my rancher is running on secure domain which is using AWS ACM certificate, not passing certificate as a secret in ingress part (This is the scenario ) , then to getting same error.

Thanks for your response.
