### ISSUE TITLE
When nodepools with no roles is created, nodes get stuck in "registering" state forever.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#28758]
Rancher Server version - `v2.4.6`

Steps to reproduce the problem:
Create a DO cluster.
Add a node pool to this cluster with no roles.
Node gets created and gets stuck in "Registering" state forever.
Once we edit the node pool and set roles , node will be able to register successfully.

Expected Behavior:
We should prevent node pools from getting created with no roles. Or defaulted it to have  “worker” nodes when no roles are provided.

**Comment by sangeethah** [comment]
Tested with `master-198ec5bdf52d3ed2b4865cfcf6ac1d61150bf55f-head`

Steps to reproduce the problem:
Create a DO cluster.
Add a node pool to this cluster with no roles.
Node gets created successfully with worker role.
But the nodePool still has `worker: false`.


@ibuildthecloud We expect the  `node pool` to have  `worker: true` to indicate that the nodes from these nodepools have worker roles .

In the edit cluster page , it is still shown as no roles
<img width="1095" alt="Screen Shot 2020-09-10 at 11 17 54 AM" src="https://user-images.githubusercontent.com/4266958/92779977-5f9c3b00-f357-11ea-99be-9f2cc5e5ee5e.png">

**Comment by sangeethah** [comment]
This test case also is not working as expected.

Steps to reproduce the problem:
Create a DO cluster.
Add a node pool - NP1 to this cluster with no roles.
Node gets created successfully with worker role.
Edit cluster and set "etcd" role to this node pool - NP1 ( Note "worker" role is still not selected at this time).
We see the existing node in the node pool get both worker and etcd node.
I created another nodepool with "etcd" role.
Sometime after this , I see the existing node in node pool - NP1 actually loose the "worker" role and have only "etcd" role.

**Comment by deniseschannon** [comment]
The other use cases should be fixed with the UI validation being added here: https://github.com/rancher/rancher/issues/28817

**Comment by westlywright** [comment]
The UI will default new node pools to a worker role. If a node pool is saved without any roles (eg unselect worker, don't select any) it will receive the worker role before saving.

**Comment by sangeethah** [comment]
Tested with latest build from master - `27000be`

Steps to reproduce the problem:
Create a DO cluster.
Add a node pool to this cluster with no roles.
Node gets added as worker successfully.
Edit cluster , notice the the nodepool still does not show "worker" role enabled.
Nodepool has - `"worker": false`

<img width="1172" alt="Screen Shot 2020-09-26 at 12 43 46 PM" src="https://user-images.githubusercontent.com/4266958/94349072-09392880-fff6-11ea-8c57-4d1ee5634cb8.png">

Expected behavior:
worker roles should be set for the nodepools.

**Comment by sangeethah** [comment]
Tested with latest build from master:
Steps to reproduce the problem:
Create a DO cluster.
Add a node pool to this cluster with no roles.
```
{controlPlane: false, deleteNotReadyAfterSecs: 0, etcd: false, quantity: 1, worker: true,…}
clusterId: "c-ftcrw"
controlPlane: false
deleteNotReadyAfterSecs: 0
etcd: false
hostnamePrefix: "sanf"
nodeTemplateId: "cattle-global-nt:nt-9nv5k"
quantity: 1
type: "nodePool"
worker: true
```
Nodepool gets created with "worker" role set.
Node gets added as worker successfully.
On cluster edit , we see the "worker" role  selected for the nodepool as expected.
