### ISSUE TITLE
Error "secrets c-f64cl already exists" while creating a hosted EKS v2 cluster when the cluster already exists in EKS

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#29549]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Create a cluster named cluster1 in EKS console.  Wait for it to come up active.
- Create/Deploy a hosted EKS cluster with name cluster1  in rancher.
- Cluster fails to come up with error secrets \"c-f64cl\" already exists . It is stuck in Provisioning state
- Error in operator logs:
```
time="2020-10-15T19:28:57Z" level=error msg="error syncing 'cattle-global-data/c-f64cl': handler eks-controller: secrets \"c-f64cl\" already exists, requeuing"
time="2020-10-15T19:29:38Z" level=error msg="error syncing 'cattle-global-data/c-f64cl': handler eks-controller: secrets \"c-f64cl\" already exists, requeuing"
time="2020-10-15T19:31:01Z" level=error msg="error syncing 'cattle-global-data/c-f64cl': handler eks-controller: secrets \"c-f64cl\" already exists, requeuing"
```

**Expected Result:**
User should not be allowed to deploy a hosted cluster with the same name as an existing one in EKS

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head - latest - commit id: `ffbdcb993`
- Installation option (single install/HA): Single node

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): hosted EKS v2
- Kubernetes version (use `kubectl version`):

```
1.17 (any)
```

**Comment by sadiapoddar** [comment]
Reproduced with 2.5.1 version
Steps to repro
1. created an EKS cluster, sadia-cluster1 from EKS console 
2. Waited till the sadia-cluster1 is active and running
3. created EKS hosted cluster from 2.5.1 Rancher UI 
Cluster creation eventually with the error already exists. 
<img width="374" alt="Screen Shot 2020-11-09 at 4 01 05 PM" src="https://user-images.githubusercontent.com/72409237/98611114-2116f400-22a6-11eb-9eab-b078df79b047.png">

secrel already exists error in Rancher UI.

<img width="1373" alt="Screen Shot 2020-11-09 at 3 55 37 PM" src="https://user-images.githubusercontent.com/72409237/98611208-502d6580-22a6-11eb-9e34-ca3fa2235ca1.png">

**Comment by rmweir** [comment]
Resolved by https://github.com/rancher/eks-operator/pull/18, moving to test

**Comment by sadiapoddar** [comment]
Verified the fix with 2.5-head, f671292, 

1. created an EKS cluster, sadia-cluster1 from EKS console
2. Waited till the sadia-cluster1 is active and running
3. Created EKS hosted cluster "sadia-cluster1" and got the proper error message and cluster didn't get created

<img width="1212" alt="Screen Shot 2020-11-20 at 12 41 14 PM" src="https://user-images.githubusercontent.com/72409237/99850611-82ef1d80-2b32-11eb-8745-5efe0b375dc1.png">

Verified with master-head, c845a29.
1. created an EKS cluster, sadia-cluster1 from EKS console
2. Waited till the sadia-cluster1 is active and running
3. Created EKS hosted cluster "sadia-cluster1" and but it's not working on master-head, 
<img width="408" alt="Screen Shot 2020-11-20 at 12 27 11 PM" src="https://user-images.githubusercontent.com/72409237/99850550-67841280-2b32-11eb-8dea-62d171e05fa8.png">

From the master branch we found that master-head is pointing at a release version of system-charts
<img width="1376" alt="Screen Shot 2020-11-20 at 12 31 28 PM" src="https://user-images.githubusercontent.com/72409237/99850803-e2e5c400-2b32-11eb-8819-27b427e66a5c.png">

Then edited the catalog and made the following changes manually. 
<img width="1367" alt="Screen Shot 2020-11-20 at 12 37 39 PM" src="https://user-images.githubusercontent.com/72409237/99850910-10cb0880-2b33-11eb-8fcf-64d690d303b9.png">

Then repeat these steps
. created an EKS cluster, sadia-cluster1 from EKS console
2. Waited till the sadia-cluster1 is active and running
3. Created EKS hosted cluster "sadia-cluster1" 

The expectation was an exist error message but instead,  it deleted the original cluster from eks and recreated a new cluster in eks. 
<img width="1203" alt="Screen Shot 2020-11-20 at 12 55 50 PM" src="https://user-images.githubusercontent.com/72409237/99851115-74553600-2b33-11eb-82af-21cc45f409bb.png">

**Comment by sadiapoddar** [comment]
Reopening to fix the issues found in the master branch.

**Comment by sowmyav27** [comment]
@sadiapoddar Can you please retry the steps to validate this issue by making sure the catalog charts are pointing to `dev-v2.5` branch on master. I am guessing the [issue](https://github.com/rancher/rancher/issues/29549#issuecomment-731414682) mentioned here seems to have been caused by this issue [here](https://github.com/rancher/rancher/issues/29103#issuecomment-728916805) (which was NOT fixed on master branch)

**Comment by rmweir** [comment]
Also discussed behavior outside of github concerning cluster being created after upstream cluster is removed and I believe we have concluded that is expected behavior.

**Comment by sadiapoddar** [comment]
verified on master-head, a549b47and 2.5-head, 9ee39b9
1. created an EKS cluster, sadia-cluster1 from EKS console
2. Waited till the sadia-cluster1 is active and running
3. Created EKS hosted cluster "sadia-cluster1" and got the proper error message and cluster didn't get created. 

<img width="510" alt="Screen Shot 2020-12-01 at 10 38 50 AM" src="https://user-images.githubusercontent.com/72409237/100782965-04ac3a00-33c2-11eb-8f42-600d9f1c3966.png">
