### ISSUE TITLE
Allocator should be able to place containers with networkmode:host on hosts where there is no port conflicts.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3016]
Server version - V0.50.0-rc2

Containers of service with networkmode:host  can end up being placed in hosts where the exposed port of the containers area currently in use.

This results in containers getting to "stopped" state and constantly being restarted.
It would be good for allocators to be aware of the exposed ports in this case and be able to place the containers in host where the ports are available.

With support for health check being enabled for container with networkmode:host (#2432) , it becomes important that when we removed containers that are detected as being unhealthy to be able to start new containers  in hosts where they can come up successfully (with out any port conflicts).

**Comment by cjellick** [comment]
I _think_ this is fixed. Need to check with @sangeethah  to make sure I'm trying to repro properly.

**Comment by cjellick** [comment]
Scheduling now fails if a container with host networking tries to use a port that is already in use.

Here's the step I used to test. Let me know if I missed something:

1. Have one active host
1. Deploy a container on the rancher network that binds to host port 80
1. Deploy a service that uses host networking and attempts to use port 80 on the hsot

Result: container continually fails to schedule.

**Comment by cjellick** [comment]
Note: I didn't make any code change for this fix at this time. Not sure when it got fixed, but it might have been fixed as a side-effect of the bind-to-ip feature that I implemented for GA.

**Comment by soumyalj** [comment]
@cjellick : I still see this issue. Followed the below steps:
1. Create a service with image nginx and exposed port 80 using managed network
2. Create another service with nginx image which uses host networking. Containers of service with networkmode:host end up being placed in hosts where the exposed port of the containers area currently in use. The container is in stopped state and is constantly restarted.
