### ISSUE TITLE
Monitoring v2 k8s-prometheus-adapter log spam "apiserver was unable to write a JSON response: http2: stream closed"

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#30697]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Deploy a Rancher v2.5.3 instance and a custom cluster with 3 all role nodes
2. Deploy the `monitoring` chart from `Apps & Marketplace` in the Cluster Explorer UI

**Result:**

When the monitoring chart has finished installing, observe repeating messages of the following format in the `rancher-monitoring-prometheus-adapter` Deployment logs in the `cattle-monitoring-system` namespace.

```
E0106 15:15:10.658751       1 writers.go:163] apiserver was unable to write a JSON response: http2: stream closed
E0106 15:15:10.658799       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}
```

**Other details that may be helpful:**

The upstream k8s-prometheus-adapter issue for these log messages is at https://github.com/DirectXMan12/k8s-prometheus-adapter/issues/292.

When the following is set in the values YAML on installing the monitoring chart (per https://github.com/DirectXMan12/k8s-prometheus-adapter/issues/292#issuecomment-671786467) the log spam does not occur:

```
prometheus-adapter:
  rules:
    default: false
```

The upstream issue identifies a potential Kubernetes fix in v1.20 (https://github.com/kubernetes/kubernetes/pull/94589), per https://github.com/DirectXMan12/k8s-prometheus-adapter/issues/292#issuecomment-741777382, and expects the issue resolved once the API machinery dependencies in prometheus-adapter are bumped to v1.20 (https://github.com/DirectXMan12/k8s-prometheus-adapter/issues/292#issuecomment-741870086).

**Environment information**
- Rancher v2.5.3

**Comment by MKlimuszka** [comment]
QA, please test this in the newest version of 2.6.x

**Comment by ronhorton** [comment]
Tested in `2.6-head Commit ID 8a31d3c`

Error is still present in logs. 

1. install monitoring v2
2. workload > pods > rancher-monitoring-prometheus-adapter-xxxx
3. right click 3 dots
4. view logs

`E0518 18:41:29.145364 1 writers.go:130] apiserver was unable to write a fallback JSON response: http2: stream closed`
`E0518 18:41:29.147069 1 writers.go:117] apiserver was unable to write a JSON response: http: Handler timeout`

**Comment by MKlimuszka** [comment]
This needs to be reproduced in 2023-Q1-2.6x and 2023-Q1-2.7x

**Comment by PennyScissors** [comment]
Reproduced in 2.7-head 9376ad2 in an RKE2 v1.25.6 +rke2r1 downstream cluster (non custom, cluster created through Rancher) with monitoring 102.0.0+up40.1.2 installed.
```
E0216 23:54:57.688602       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"}: http: Handler timeout
E0216 23:54:57.689789       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}: http2: stream closed
E0216 23:54:57.692041       1 writers.go:131] apiserver was unable to write a fallback JSON response: http: Handler timeout
E0216 23:54:57.693205       1 writers.go:131] apiserver was unable to write a fallback JSON response: http: Handler timeout
E0216 23:54:57.694298       1 writers.go:131] apiserver was unable to write a fallback JSON response: http: Handler timeout
E0216 23:54:57.695515       1 writers.go:131] apiserver was unable to write a fallback JSON response: http2: stream closed
```

Also reproduced in 2.6-head 6d1bd94 in an RKE  v1.24.9 downstream cluster (non custom, cluster created through Rancher) with monitoring 100.2.0+up40.1.2 installed.
```
E0217 00:26:10.139403       1 writers.go:131] apiserver was unable to write a fallback JSON response: http: Handler timeout
E0217 00:26:10.140917       1 writers.go:131] apiserver was unable to write a fallback JSON response: http: Handler timeout
E0217 00:26:10.143083       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}: http2: stream closed
E0217 00:26:10.144196       1 writers.go:131] apiserver was unable to write a fallback JSON response: http: Handler timeout
E0217 00:26:10.145433       1 timeout.go:141] post-timeout activity - time-elapsed: 20.250622ms, GET "/apis/custom.metrics.k8s.io/v1beta1" result: <nil>
E0217 00:26:10.147089       1 timeout.go:141] post-timeout activity - time-elapsed: 23.421925ms, GET "/apis/custom.metrics.k8s.io/v1beta1" result: <nil>
E0217 00:26:10.148219       1 writers.go:131] apiserver was unable to write a fallback JSON response: http2: stream closed
```

**Comment by joshmeranda** [comment]
Replaced image `rancher/mirrored-prometheus-adapter-prometheus-adapter:v0.10.0` with most recent upstream image `gcr.io/k8s-staging-prometheus-adapter/prometheus-adapter:master`. Issue still persists. I'm thinking this is because they are using an older version of golang (1.18).

@sanjay920 @MKlimuszka @prachidamle

**Comment by cornfeedhobo** [comment]
I have confirmed that this was fixed in `v0.11.x`.

Unfortunately `v0.11.x` also deprecated the `logtostderr` flag, and the chart does not expose the container args as a value, so the only way to run `v0.11.x` is using kustomize to override the args.

**Comment by elektro-wolle** [comment]
On https://github.com/kubernetes-sigs/prometheus-adapter/issues/292 there are some discussions about this.

**Comment by MKlimuszka** [comment]
Upstream ticket was closed, and we've rebased. Let's test this again after we make our new mirrored images.

**Comment by jbiers** [comment]
Testing shows the behavior still persists after the rebase. The upstream ticket was closed since the originally reported panic has been resolved, but several comments report still having those logs in the prometheus-adapter deployment.

**Comment by thsnielsen** [comment]
Just added ASML as a customer having this issue on 2.9.2

**Comment by shaunbugler** [comment]
Still see this in 2.10.1

**Comment by thzuccoli** [comment]
I am have a equal problem in 2.11.1 rancher and helm chart rancher-monitoring (106.1.0+up69.8.2-rancher.4)

**Comment by jbiers** [comment]
The issue comes from the upstream project prometheus-adapter and still hasn't been fixed as they apparently lack the bandwidth to do a deeper investigation. The upstream issue is closed as the panic that was present in older versions was fixed, but the spammy error logs persist.

@Jono-SUSE-Rancher removing the v2.12 tag as we don't have a fix for this one implemented upstream

**Comment by Jono-SUSE-Rancher** [comment]
OK good catch @jbiers -- I went ahead and moved it to **blocked** on our end (upstream) until we have a fix upstream.

**Comment by prachidamle** [comment]
Moving to QA to check if the latest monitoring rebase for 2.14.0 fixes this issue.

**Comment by pankajsqe** [comment]
I am still able to reproduce this issue on our latest rancher-monitoring chart


details
rancher : v2.14.0-alpha9
rancher-monitoring:109.0.0-rc.2+up80.9.1-rancher.4
Cluster : RKE2


```
E0106 15:15:10.658751       1 writers.go:163] apiserver was unable to write a JSON response: http2: stream closed
E0106 15:15:10.658799       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}
```


<img width="1728" height="961" alt="Image" src="https://github.com/user-attachments/assets/e7f9c564-9a65-4d78-8e9d-a225135aaf4e" />
<img width="1727" height="956" alt="Image" src="https://github.com/user-attachments/assets/d09c7e15-c10c-4a44-b8d9-b6b610ea1206" />

**Comment by alemorcuq** [comment]
I've been looking into this. As @pankajsqe noted above, this is still an issue.

## Background

The goal of the Prometheus Adapter is to register certain metrics as Custom Metrics in the Kubernetes API so that Horizontal Pod Autoscalers can query them to scale applications. By default, HPAs use resource usage to trigger scaling, but that is usually not enough. An API application may want to scale depending on the number of requests per second it is serving and that is made possible by Prometheus and the Prometheus Adapter.

Prometheus would scrape the metrics from the API application and the user would tell the Prometheus Adapter to register the number of requests per second metric in the Custom Metrics API. Once there, the HPA can use that to scale the application.

## What is happening

After installing `rancher-monitoring` with the default values, the `prometheus-adapter` pod continuously logs errors like:

```console
I0428 09:23:56.586011       1 panic.go:770] "HTTP" verb="GET" URI="/apis/custom.metrics.k8s.io/v1beta1" latency="6.567184ms" userAgent="Go-http-client/2.0" audit-ID="56db5b8a-1e7b-4d99-b805-f76108a59ffb" srcIP="10.42.0.1:59150" resp=200
E0428 09:23:56.586052       1 timeout.go:142] post-timeout activity - time-elapsed: 1.511564ms, GET "/apis/custom.metrics.k8s.io/v1beta1" result: <nil>
E0428 09:23:56.586061       1 wrap.go:54] timeout or abort while handling: method=GET URI="/apis/custom.metrics.k8s.io/v1beta1" audit-ID="56db5b8a-1e7b-4d99-b805-f76108a59ffb"
E0428 09:23:56.586069       1 writers.go:122] apiserver was unable to write a JSON response: http: Handler timeout
E0428 09:23:56.587261       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}: http2: stream closed
```

## Why is this happening

The `prometheus-adapter` Helm chart includes 6 default catch-all rules matching every Prometheus metric. For example, the following query matches every non-container metric:

```yaml
seriesQuery: '{namespace!="",__name__!~"^container_.*"}'
```

A quick call to Prometheus reveals this query matches more than 130k series:

```console
$ kubectl exec -n cattle-monitoring-system -it prometheus-rancher-monitoring-prometheus-0 -- wget -qO- 'http://localhost:9090/api/v1/series?match[]=%7Bnamespace%21%3D%22%22%2C__name__%21~%22%5Econtainer_.*%22%7D' | jq '.data | length'
131141
```

The adapter then registers every Prometheus metric as a custom metric against every Kubernetes resource. This produces more than 8k API resources and a JSON response of over 1MB:

```console
$ kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1" | jq '.resources | length'
8531

$ kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1" | wc -c
1167729
```

This is causing the `kube-apiserver` to timeout or abort the discovery requests.

## Impact on users

- **Functionality**: None for default installations. The adapter still serves metrics when queried, and the APIService remains available because the health checks succeed. Grafana dashboards are also unaffected as Grafana queries Prometheus directly.
- **Log noise**: In my testing, it generated over 3k error lines per hour in the adapter logs. This can make it hard to spot real problems.
- **Resource waste**: The adapter is using over 700MB of memory and ~0.4 cpus after a clean installation. This is a lot for a small binary like this.

<img width="2239" height="483" alt="Image" src="https://github.com/user-attachments/assets/24f63822-8474-43df-83dc-5323a85e680b" />

## Known upstream issue

This problem has been reported and acknowledged multiple times in the upstream repositories:

  - [kubernetes-sigs/prometheus-adapter#221](https://github.com/kubernetes-sigs/prometheus-adapter/issues/221): July 2019. User reports high memory usage. A maintainer confirms they are aware of the issue and suggests reducing the amount of discovered metrics.
  - [kubernetes-sigs/prometheus-adapter#292](https://github.com/kubernetes-sigs/prometheus-adapter/issues/292): May 2020. The issue linked in this thread. A maintainer confirms: "Yeah we're aware of problems with the scalability of the current approach, because of the discovery mechanism.". The panic reported by the author was fixed, but the rest of the errors persist. A user in June 2025 suggests reducing the number of rules to remove the errors.
  - [kubernetes-sigs/prometheus-adapter#625](https://github.com/kubernetes-sigs/prometheus-adapter/issues/625): November 2023. Reports the same issue.
  - [prometheus-community/helm-charts#5747](https://github.com/prometheus-community/helm-charts/issues/5747): June 2025. Reports huge CPU spikes specifically from the `prometheus-adapter` in `rancher-monitoring` with default values.

Moreover, there are talks to deprecate the Prometheus Adapter:

  - [kubernetes-sigs/prometheus-adapter#701](https://github.com/kubernetes-sigs/prometheus-adapter/issues/701): May 2025. "We want to deprecate the project in the near-future, post-triage, and suggest users to fulfill their use-cases using KEDA."

In short, and as previously identified, this is not a Rancher issue. Any installation of `kube-prometheus-stack` with the `prometheus-adapter` enabled and default rules would experience the same problem at similar cluster scale. Given this has been known for almost 7 years and the intention to deprecate the adapter, I don't think we are going to see an upstream fix.

## Potential fix

Change the default configuration of `prometheus-adapter` to disable the default rules by setting `rules.default: false`. Users that are using metrics exposed by the default rules in their HPAs should either create custom rules for their specific metrics (which would be the recommended approach, configurable via `rules.custom`) or set `rules.default: true` and keep facing this issue.

Alternatively, we could reduce the number of default rules.

Note that this does not fix the underlying issue but prevents it from happening in default installations.

## Summary

This is an upstream issue known for 7+ years that probably won't be fixed given the talks to deprecate the Prometheus Adapter. Other than the log pollution and the resource usage, there's no real downside for users. At most, we could change our default configuration to workaround it and prevent it from happening.
