### ISSUE TITLE
[Monitoring v2] root_url issues for non-local clusters

### ISSUE THREAD

**Issue by codyrancher** [rancher/rancher#31891]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a NON-local cluster
2. On the non-local cluster install monitoring with this addition to the configuration
```
grafana:
   grafana.ini:
      server:
         root_url: https://floof.com/floofy
```

**Result:**
The base url of the grafana dashboard isn't changing which prevents me from loading grafana dashboards within the rancher dashboard because I either load the iframe with the original url and can't inject our assets or I load the iframe with localhost and subsequent resources and scripts fail to load due to cors.
![image](https://user-images.githubusercontent.com/55104481/113362538-79a56700-9303-11eb-9c1b-a8257a2220fb.png)
![image](https://user-images.githubusercontent.com/55104481/113362832-2849a780-9304-11eb-9ae7-464fecaa36d1.png)

**Other details that may be helpful:**
This is only happening for non-local clusters. When defining root_url for local we can see the base url change.
![image](https://user-images.githubusercontent.com/55104481/113363167-08ff4a00-9305-11eb-9d74-d81dc7faa7bd.png)

I've also attempted to use the domain and subpath properties without luck.
```
grafana:
   grafana.ini:
      server:
         root_url: https://floof.com/floofy
         domain: floof.com
         serve_from_sub_path: true
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):  v2.5-b2a34d7cef440e3ed1de7d506233aa3a332649ae-head
- Installation option (single install/HA): single install

**Comment by aiyengar2** [comment]
@sowmyav27 Can we test if this was a regression from 2.5.6 or 2.5.7 with the monitoring chart today? The fact that this is only affecting local clusters makes me think that this is related to the changes we made to rancher/rancher for the downstream cluster proxies

**Comment by slickwarren** [comment]
I tested this on 2.5.5 (monitoring version 9.4.202 and 9.4.200) and the issue reproduces using the downstream (non-local) cluster.  I added the following to the monitoring yaml
<img width="617" alt="Screen Shot 2021-04-01 at 5 31 09 PM" src="https://user-images.githubusercontent.com/16691014/113368357-626e7580-9313-11eb-92ad-4b76ed1cfe4a.png">

**Comment by aiyengar2** [comment]
Blocks https://github.com/rancher/dashboard/issues/812 in a non-local cluster

**Comment by SheilaghM** [comment]
@aiyengar2 - is this related to https://zube.io/rancher/rancher/c/37339

**Comment by aiyengar2** [comment]
Hmm I'm not sure @SheilaghM . @codyrancher do you remember if the Zube issue (https://github.com/rancher/rancher/issues/31732) was in a downstream cluster as well?

It would make sense to me that both might be related.

**Comment by codyrancher** [comment]
It wasn't a downstream cluster. If it were downstream I wouldn't be able to set the root_url to resolve it.

However, I did just test this in both a local and downstream cluster. It looks like I'm able to sign in even though the root_url isn't set. So this appears to be resolved unless @aiyengar2 expects the the root_url to be set.

**Comment by aiyengar2** [comment]
I don't think root_url needs to be set, afaik.

Also, @codyrancher you mean https://github.com/rancher/rancher/issues/31732 is resolved, not this issue right?

**Comment by aiyengar2** [comment]
@codyrancher and I hopped on a call about this offline and decided that it was okay to push this back to 2.6 instead of 2.5.8.

cc: @SheilaghM @gaktive @Jono-SUSE-Rancher @sowmyav27 

### Scope of Issue

The scope of this issue is something that should only impact the UI development process. Normal users of Rancher will not experience this issue since this is something that arises from the fact that the UI developer is using a local development URL (e.g. http://localhost:8085 that is rendering the rancher/dashboard code pointing to the Rancher deployment) that differs from the Rancher URL.

Note: this is not really a root_url problem but rather an inconsistency that happens when root_url is not set. We do not expect root_url to be set.

### Summary of Technical Issue

For the current UI developer working on rancher/dashboard, the overall workflow for local clusters looks something like this (when the root_url is not set):
1. UI Developer makes a request from the origin http://localhost:8085 to the rancher/rancher backend at `RANCHER_URL/k8s/clusters/local/{k8s-api-server-proxy-stuff}/proxy/{actual-grafana-path}`
2. Rancher sees the request coming to `/k8s/clusters/local/{k8s-api-server-proxy-stuff}/proxy/{actual-grafana-path}` and forwards it to `{k8s-api-server-proxy-stuff}/proxy/{actual-grafana-path}`
3. The api-server sees `{k8s-api-server-proxy-stuff}/proxy/{actual-grafana-path}` and queries the Grafana pod at port 8080 for `/{actual-grafana-path}`
4. On return, the base href that is encoded is a relative URL which is just `/{actual-grafana-path}`

However, in downstream clusters, there is an additional step between 2 and 3 where the `/k8s/cluster/{clusterId}` part goes through our rancher pod (I believe cluster-agent?) on the management cluster to the corresponding pod on the downstream cluster and for some reason this is causing Grafana to return a base href that is `RANCHER_URL/k8s/cluster/{clusterId}/{k8s-api-server-proxy-stuff}/{actual-grafana-path}`, even when the root_url is not set.

We tried to do a number of things to debug this issue, including adding a sidecar to the Grafana deployment and tcpdump-ing the incoming requests and looking through the Grafana UI code, but we weren't able to catch anything that was fairly intuitive that was causing this difference to occur.

@ibuildthecloud do you have any idea what issue we might be running into here? I'm not 100% familiar with the Rancher Steve proxying mechanism in rancher/rancher, so perhaps I'm misunderstanding something here on why this workflow is failing.

**Comment by aiyengar2** [comment]
Also, @SheilaghM @Jono-SUSE-Rancher @gaktive we should prioritize this fairly soon since this does block the ability for UI developers to be able to test things like etcd embedding of cluster overview graphs without spinning up a local RKE cluster for testing, since the normal local k3s cluster does not have etcd monitoring.

**Comment by deniseschannon** [comment]
Note: There were some issues talking about potentially updating k3s to use etcd which may solve this issue for UI developers, but not positive. Check with broader team when this issue comes up to be picked up.

**Comment by SamuZad** [comment]
This is extremely annoying, we ran into this limitation as well  😅 

We needed to set the root URL of the non-local clusters, so that we can enable OIDC authentication to Grafana.

```
server:
  root_url: "https:/mycompany.com/k8s/clusters/${ .ClusterName }/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy"
  serve_from_sub_path: false
```
As a result, Grafana failed to load, with the following hint in the network tab:
```
Request URL:
https://mycompany.com/k8s/clusters/CLUSTER_ID/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/k8s/clusters/CLUSTER_ID/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/public/fonts/roboto/xxxxxxxxxxxxx
Request Method:
GET
Status Code:
404 Not Found
```

For some reason the `k8s/clusters/CLUSTER_ID.....` part is double-added to the call.

Note, this issue persists whether we set `serve_from_sub_path` to `true` or `false`.
