### ISSUE TITLE
login command doesn't create cli2.json file

### ISSUE THREAD

**Issue by pradeepiyerust** [rancher/rancher#31967]
Hi,

I downloaded v2.4.10 CLI zip file for Windows 64bit, extracted the zip and added the path to the environment variables. Now I can execute "rancher" commands from Command Prompt, but "rancher login <URL> --token <token>" command is not creating the cli2.json file. The command is pulling the projects from my Rancher server, but once I select the project I need to use, it comes back with the following error:

```
time="2021-04-07T16:08:53+05:30" level=info msg="Saving config to \\.rancher\\cli2.json"
time="2021-04-07T16:08:53+05:30" level=fatal msg="open \\.rancher\\cli2.json: The system cannot find the path specified."
```

Am I doing anything wrong?

Thanks,
Pradeep.

sure-7018

**Comment by pradeepiyerust** [comment]
This worked from Git Bash, but from Command prompt it is failing to save. Closing as it is resolved.

**Comment by philomory** [comment]
this works in powershell/cmd as well if you explicitly set the `RANCHER_CONFIG_DIR` environment variable.

**Comment by ST-DDT** [comment]
IMO it is really strange that you have to use the git bash or a cmd with a modified env to use the cli.
IIRC I still had to create the `.rancher` dir in the git bash, but that's way easier that trying to setup any envs.

**Comment by fenchu** [comment]
You can fix this so it writes correctly in powershell
```
mkdir \\.rancher 
mkdir : The path is not of a legal form.
```

it should be:
```
mkdir c:\\.rancher
```
But I like to have it under:
```
mkdir ~\\.rancher
```

**Comment by trandersen-ufst** [comment]
Problem is that the default value for the configuration file is calculated in main.go line 87 as

```
			Value:  os.ExpandEnv("${HOME}/.rancher"),
```

which does not resolve correctly under Windows in CMD.exe.

**Comment by eecavanna** [comment]
I hit this issue today, using:
- Rancher CLI version: `rancher-windows-386-v2.6.11`
- Rancher version: `v2.6.13`
- Windows 10 Enterprise 2019 LTSC

In Git bash, it looks for the file under my home directory. Creating the `.rancher` folder there fixed things for me (thanks for the tip, @ST-DDT):

```bash
# Before the folder exists -> error.
rancher.exe login "https://...redacted_url..." --token "...redacted_access_key...:...redacted_secret_key..."
NUMBER    CLUSTER NAME   PROJECT ID        PROJECT NAME   PROJECT DESCRIPTION
1         development    some_id           some_name
2         production     other_id          other_name
Select a Project:1
time="2023-06-22T19:04:04-07:00" level=info msg="Saving config to C:\\Users\\MyName\\.rancher\\cli2.json"
time="2023-06-22T19:04:04-07:00" level=fatal msg="open C:\\Users\\MyName\\.rancher\\cli2.json: The system cannot find the path specified."

# Create the folder.
mkdir ~/.rancher

# When the folder exists -> success.
rancher.exe login "https://...redacted_url..." --token "...redacted_access_key...:...redacted_secret_key..."
NUMBER    CLUSTER NAME   PROJECT ID        PROJECT NAME   PROJECT DESCRIPTION
1         development    some_id           some_name
2         production     other_id          other_name
Select a Project:1
time="2023-06-22T19:06:54-07:00" level=info msg="Saving config to C:\\Users\\MyName\\.rancher\\cli2.json"
```

**Comment by markusewalker** [comment]
**QA TEST PLAN**

|#|Scenario|Test Case|
|---|---|---|
|1|`cli2.json` created after logging in with CMD|Run `rancher login` command, validate login is successful and `cli2.json` file exists|
|2|`cli2.json` created after logging in with Powershell|Run `rancher login` command, validate login is successful and `cli2.json` file exists|

**Comment by markusewalker** [comment]
Reproduced this issue using the Rancher CLI v2.8.0. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.8-head` https://github.com/rancher/rancher/commit/673290980ca6def732d61fcb46720b5deb5ea8f9.
- Rancher CLI version: `v2.8.0`

**TEST RESULT**
|#|Scenario|Test Case|Result
|---|---|---|---|
|1|`cli2.json` created after logging in with CMD|Run `rancher login` command, validate login is successful and `cli2.json` file exists|:x:|

```
>rancher.exe login --token <removed> <Rancher server URL>
...
Do you want to continue connecting (yes/no)? yes
NUMBER    CLUSTER NAME     PROJECT ID        PROJECT NAME   PROJECT DESCRIPTION
1         auto-ec2-mgxkr   <removed>   System         System project created for the cluster
2         auto-ec2-mgxkr  <removed>  Default        Default project created for the cluster
3         mew-test         <removed>  Default        Default project created for the cluster
4         mew-test         <removed> System         System project created for the cluster
5         local            <removed>    Default        Default project created for the cluster
6         local            <removed>    System         System project created for the cluster
Select a Project:5
time="2024-03-28T18:46:30Z" level=info msg="Saving config to \\.rancher\\cli2.json"
time="2024-03-28T18:46:30Z" level=fatal msg="open \\.rancher\\cli2.json: The system cannot find the path specified."
```

Now that this is reproduced, I will use Rancher CLI 2.8.3 and see if this has been addressed.

**Comment by HarrisonWAffel** [comment]
RC `v2.9.0-rc1` has been created so this issue is now ready to be tested

**Comment by markusewalker** [comment]
Validated this issue using the Rancher CLI `v2.9.0-rc1`. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.9-head` https://github.com/rancher/rancher/commit/7911791120d423a9b90c1fafbbdf642dd8d54a50.
- Rancher CLI version: `v2.9.0-rc1`

**TEST RESULT**
|#|Scenario|Test Case|Result
|---|---|---|---|
|1|`cli2.json` created after logging in with CMD|Run `rancher login` command, validate login is successful and `cli2.json` file exists|:white_check_mark:|
|2|`cli2.json` created after logging in with Powershell|Run `rancher login` command, validate login is successful and `cli2.json` file exists|:white_check_mark:|

**REPRO STEPS**
1. Downloaded Rancher CLI.
2. In CMD, ran the following command: 
```
>rancher.exe login --token <removed> <Rancher server URL>
...
time="2024-04-05T20:00:37Z" level=info msg="Saving config to C:\\Users\\Administrator\\.rancher\\cli2.json"
>dir C:\Users\Administrator\.rancher
 Volume in drive C has no label.
 Volume Serial Number is A6F0-A5C4

 Directory of C:\Users\Administrator\.rancher

04/05/2024  08:01 PM    <DIR>          .
04/05/2024  08:01 PM    <DIR>          ..
04/05/2024  08:01 PM             1,062 cli2.json
               1 File(s)          1,062 bytes
               2 Dir(s)  90,222,632,960 bytes free
```

_______

**Scenario 2**
1. Repeated scenario 1, but used Powershell instead of CMD - same successful results.
