### ISSUE TITLE
Adding Bitnami chart causes 2-3 minute CPU spikes every 15 minutes and 30-40 minute CPU spike when rancher restarted

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#32175]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Install Rancher
2. Enable v1 monitoring on local cluster (so you can get see CPU graphs)
3. Add the Bitnami catalog - Tools -> Catalogs, add URL=https://charts.bitnami.com/bitnami as a global catalog. Version =Helm v3
4. Wait a few hours (may not see spikes for a while)

**Result:**
After waiting a few hours, will see 100% CPU spikes that last 2-3 minutes. These happen every 15 minutes:
![image](https://user-images.githubusercontent.com/468462/114947281-b2643680-9e01-11eb-957c-caac818b1295.png)

Go to System -> workloads and delete the rancher pods, they'll respawn and CPU will be maxed out for 30-40 minutes:
![image](https://user-images.githubusercontent.com/468462/114947323-cdcf4180-9e01-11eb-8b72-9e1a8df564b2.png)

In both cases, it's the k3s-server process that is maxing out the CPU. Observed this in the k3s logs:
```
Apr 15 03:24:26 ip-10-10-101-200 k3s[937]: I0415 03:24:26.178016     937 trace.go:205] Trace[71675938]: "Update" url:/apis/management.cattle.io/v3/catalogs/bitnami,user-agent:rancher/v0.0.0 (linux/amd64) kubernetes/$Format,client:10.10.100.143 (15-Apr-2021 03:23:52.126) (total time: 34050ms):
Apr 15 03:42:18 ip-10-10-101-200 k3s[937]: I0415 03:42:18.555397     937 trace.go:205] Trace[1026252523]: "Update" url:/apis/management.cattle.io/v3/catalogs/bitnami,user-agent:rancher/v0.0.0 (linux/amd64) kubernetes/$Format,client:10.10.100.143 (15-Apr-2021 03:41:44.505) (total time: 34049ms):
Apr 15 03:42:54 ip-10-10-101-200 k3s[937]: I0415 03:42:54.299409     937 trace.go:205] Trace[1920579102]: "Update" url:/apis/management.cattle.io/v3/catalogs/bitnami,user-agent:rancher/v0.0.0 (linux/amd64) kubernetes/$Format,client:10.10.100.143 (15-Apr-2021 03:42:20.224) (total time: 34075ms):
Apr 15 04:00:11 ip-10-10-101-200 k3s[937]: I0415 04:00:11.110604     937 trace.go:205] Trace[167055759]: "Update" url:/apis/management.cattle.io/v3/catalogs/bitnami,user-agent:rancher/v0.0.0 (linux/amd64) kubernetes/$Format,client:10.10.100.143 (15-Apr-2021 03:59:37.057) (total time: 34052ms):
Apr 15 04:00:47 ip-10-10-101-200 k3s[937]: I0415 04:00:47.430394     937 trace.go:205] Trace[1689552688]: "Update" url:/apis/management.cattle.io/v3/catalogs/bitnami,user-agent:rancher/v0.0.0 (linux/amd64) kubernetes/$Format,client:10.10.100.143 (15-Apr-2021 04:00:13.277) (total time: 34152ms):
Apr 15 04:18:04 ip-10-10-101-200 k3s[937]: I0415 04:18:04.187835     937 trace.go:205] Trace[1508257776]: "Update" url:/apis/management.cattle.io/v3/catalogs/bitnami,user-agent:rancher/v0.0.0 (linux/amd64) kubernetes/$Format,client:10.10.100.143 (15-Apr-2021 04:17:30.132) (total time: 34055ms):
Apr 15 04:18:39 ip-10-10-101-200 k3s[937]: I0415 04:18:39.811915     937 trace.go:205] Trace[878091697]: "Update" url:/apis/management.cattle.io/v3/catalogs/bitnami,user-agent:rancher/v0.0.0 (linux/amd64) kubernetes/$Format,client:10.10.100.143 (15-Apr-2021 04:18:05.722) (total time: 34089ms):
Apr 15 04:36:32 ip-10-10-101-200 k3s[937]: I0415 04:36:32.342801     937 trace.go:205] Trace[502588042]: "Update" url:/apis/management.cattle.io/v3/catalogs/bitnami,user-agent:rancher/v0.0.0 (linux/amd64) kubernetes/$Format,client:10.10.100.143 (15-Apr-2021 04:35:58.230) (total time: 34112ms):
Apr 15 04:53:49 ip-10-10-101-200 k3s[937]: I0415 04:53:49.019193     937 trace.go:205] Trace[408489179]: "Update" url:/apis/management.cattle.io/v3/catalogs/bitnami,user-agent:rancher/v0.0.0 (linux/amd64) kubernetes/$Format,client:10.10.100.143 (15-Apr-2021 04:53:14.969) (total time: 34049ms):
Apr 15 04:54:24 ip-10-10-101-200 k3s[937]: I0415 04:54:24.656113     937 trace.go:205] Trace[1988414344]: "Update" url:/apis/management.cattle.io/v3/catalogs/bitnami,user-agent:rancher/v0.0.0 (linux/amd64) kubernetes/$Format,client:10.10.100.143 (15-Apr-2021 04:53:50.564) (total time: 34091ms):
```

**Other details that may be helpful:**
If you delete the bitnami catalog, everything returns to normal - no CPU spikes.

Possible related issue - https://github.com/rancher/rancher/issues/31940

Catalog also displayed in "Refreshed" state and never changes to "Active":
![image](https://user-images.githubusercontent.com/468462/114953180-af227800-9e0c-11eb-959b-8f7281653206.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.5.7
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
k3s
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
2 m5a.large AWS instances (2vCPU, 8GB RAM) w/ RDS Aurora MySQL DB

- Kubernetes version (use `kubectl version`):

```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5+k3s1", GitCommit:"355fff3017b06cde44dbd879408a3a6826fa7125", GitTreeState:"clean", BuildDate:"2021-03-31T06:21:52Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):
containerd

gz#16028

**Comment by dramich** [comment]
I think this is related as well: https://github.com/rancher/rancher/issues/32295

**Comment by dnoland1** [comment]
From further testing found this only happens on Kubernetes 1.20 clusters (both RKE and K3s). Could not reproduce the issue on 1.19.

**Comment by dnoland1** [comment]
Was also able to reproduce this issue on k3s 1.21.

**Comment by cbron** [comment]
This should be fixed now that the upstream k8s patches have fixed, anything past 1.21.3 cc @dnoland1

**Comment by dnoland1** [comment]
Tested this on Rancher v2.6.3 with k3s 1.21.7. The CPU seems to stay at a reasonable level after adding the Bitnami catalog. However, if I add ten copies of the catalog, the environment locks up and becomes completely unresponsive. So there still appears to be a scaling issue if you add ten substantially large catalogs.

**Comment by cbron** [comment]
Thats not too surprising. The fix we made was to compress/minimize the catalogs, so if you add 10x catalogs then you will have gone beyond the space saved by the compression. The upstream k8s fix was included in 1.21.3, so your test includes those fixes too. I think for now we should close until someone hits this again with fixes.

**Comment by slickwarren** [comment]
I've also tested this on 2.6.4-rc3 and do not see any sort of spikes 8 hours after adding the bitnami chart.
