### ISSUE TITLE
Cannot delete volume via docker if it has been deleted via convoy

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#3232]
If you have a convoy volume and do a `convoy delete`, the volume will still show up in `docker volume ls`. So, to clean the volume up, you should be to do a `docker volume delete`. But you can't because convoy fails with an error message like `Failed to execute:...cannot find volume.` ...I'm paraphrasing this error message as I don't have it handy at the moment.

~~I think you get the same error if you did `convoy volume delete` twice in a row, which means convoy volume delete isn't idempotent, but it needs to be.~~ EDIT: I no longer think this is technically an idempotency issue. But nonetheless, we are in a situation where docker thinks the volume exists and we cannot delete it.

**Comment by cjellick** [comment]
This is actually a bug in docker as well. See my patch:
https://github.com/cjellick/docker/commit/07b7ddb11697d8570923e6e2bbc48bd7c3dcd4a6

**Comment by cjellick** [comment]
This is fixed by implementing the docker 1.10 volume plugin Get and List methods.
As soon as you do a `convoy delete`, the volume is gone from `docker volume ls`.

This bug manifested itself as a rancher volume purge sometimes hanging forever. Testing this explicilty requires a contrived scenario. Here it is:

1. Deploy a container in rancher with a convoy-nfs volume (we'll call it foo).
1. Delete and purge the container
1. SSH into the host where the container was running.
1. Run `docker volume ls` and verify volume foo is in the list.
1. Run `cat /etc/docker/plugins/convoy-nfs.spec` and note the value. It should be `unix:///var/run/convoy-convoy-nfs.sock`
On the host where the container was deployed, find the convoy-nfs container that is running the `/launch volume-agent` command and `exec` into it.
1. Assuming that the value from that cat command matched what I said it should be, run `convoy -s /host/var/run/convoy-convoy-nfs.sock list`. Should return json with the volume you created.
1. Delete the volume with `convoy -s /host/var/run/convoy-convoy-nfs.sock delete foo`. Should succeed with an empty response.
1. exit the container and on the host run `docker volume ls`. Volume `foo` should be gone.

**Comment by sangeethah** [comment]
Tested with latest build from master and convoy agent - rancher/convoy-agent:v0.6.0

When volumes from convoy-nfs storage pool is deleted and purged from  rancher-server UI , it is still being listed in host (docker volume ls) and is still present in the nfs server.

@cjellick , Will retest this scenario once deletion of volumes gets fixes.

**Comment by cjellick** [comment]
OK, lets try again @sangeethah.
Use my catalog again. New image is rancher/convoy-agent:v0.7.0

**Comment by sangeethah** [comment]
Tested with latest build from master and using rancher/convoy-agent:v0.7.0.

Tested the following scenario:
Create nfs-convoy (v0.3.0) stack from catalog url - https://github.com/cjellick/rancher-catalog/

Deploy a container in rancher with a convoy-nfs volume (we'll call it foo).
Delete and purge the container
SSH into the host where the container was running.
Run docker volume ls and verify volume foo is in the list.
Run cat /etc/docker/plugins/convoy-nfs.spec and note the value. It should be unix:///var/run/convoy-convoy-nfs.sock On the host where the container was deployed, find the convoy-nfs container that is running the /launch volume-agent command and exec into it.
Assuming that the value from that cat command matched what I said it should be, run convoy -s /host/var/run/convoy-convoy-nfs.sock list. Should return json with the volume you created.
Delete the volume with convoy -s /host/var/run/convoy-convoy-nfs.sock delete foo. 
Succeeds with an empty response.
Exit the container and on the host run docker volume ls.
Volume foo is not listed anymore.
It is also removed from the nfs server.

This volume continues to listed in "inactive" state in "Storage pool" view.

Tried to start a new container using the same volume name in "convoy-nfs" volume driver.
Once the container starts , a new volume gets created in nfs server for with the same volume name and the volume state gets to "active" state in rancher-server.
