### ISSUE TITLE
RKE2 Provisioning: Rancher Proxy Support

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#32602]
RKE2 provisioned clusters that are installed behind a proxy need special install instructions. 

This ticket should cover the scenario for when Rancher Server is behind a proxy.
- Support Rancher Server behind a proxy;

**Comment by slickwarren** [comment]
on master-head (479795f):
* custom cluster (ec2, k3s node), proxy-gapped node with http_proxy, https_proxy, and no_proxy set in rancher and on the external node:
  * cluster appears to connect and begin to provision, but never gets out of `provisioning` state.  CAPI cluster is unavailable. Here is a screenshot + relevant logs from rke2-server:
<img width="553" alt="Screen Shot 2021-06-16 at 2 01 00 PM" src="https://user-images.githubusercontent.com/16691014/122292953-625e2a80-ceab-11eb-8414-24532cf6a8b1.png">

```
 time="2021-06-16T21:02:20Z" level=error msg="Failed to check local etcd status for learner management: context deadline exceeded"
Jun 16 21:02:20 ip-10-0-1-200 rke2[3597]: {"level":"warn","ts":"2021-06-16T21:02:20.127Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"p
Jun 16 21:02:20 ip-10-0-1-200 rke2[3597]: time="2021-06-16T21:02:20Z" level=info msg="Failed to test data store connection: context deadline exceeded"
Jun 16 21:02:20 ip-10-0-1-200 rke2[3597]: time="2021-06-16T21:02:20Z" level=info msg="Waiting for cloudcontroller rbac role to be created"
Jun 16 21:02:25 ip-10-0-1-200 rke2[3597]: time="2021-06-16T21:02:25Z" level=info msg="Waiting for cloudcontroller rbac role to be created"
Jun 16 21:02:30 ip-10-0-1-200 rke2[3597]: time="2021-06-16T21:02:30Z" level=info msg="Waiting for cloudcontroller rbac role to be created"
Jun 16 21:02:35 ip-10-0-1-200 rke2[3597]: {"level":"warn","ts":"2021-06-16T21:02:35.121Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"p
Jun 16 21:02:35 ip-10-0-1-200 rke2[3597]: time="2021-06-16T21:02:35Z" level=error msg="Failed to check local etcd status for learner management: context deadline exceeded"
Jun 16 21:02:35 ip-10-0-1-200 rke2[3597]: {"level":"warn","ts":"2021-06-16T21:02:35.128Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"p
Jun 16 21:02:35 ip-10-0-1-200 rke2[3597]: time="2021-06-16T21:02:35Z" level=info msg="Failed to test data store connection: context deadline exceeded"
Jun 16 21:02:35 ip-10-0-1-200 rke2[3597]: time="2021-06-16T21:02:35Z" level=info msg="Waiting for cloudcontroller rbac role to be created"
Jun 16 21:02:40 ip-10-0-1-200 rke2[3597]: time="2021-06-16T21:02:40Z" level=info msg="Waiting for etcd server to become available"
Jun 16 21:02:40 ip-10-0-1-200 rke2[3597]: time="2021-06-16T21:02:40Z" level=info msg="Waiting for cloudcontroller rbac role to be created"
Jun 16 21:02:45 ip-10-0-1-200 rke2[3597]: time="2021-06-16T21:02:45Z" level=info msg="Waiting for cloudcontroller rbac role to be created"
Jun 16 21:02:50 ip-10-0-1-200 rke2[3597]: {"level":"warn","ts":"2021-06-16T21:02:50.121Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"p
Jun 16 21:02:50 ip-10-0-1-200 rke2[3597]: time="2021-06-16T21:02:50Z" level=error msg="Failed to check local etcd status for learner management: context deadline exceeded"
Jun 16 21:02:50 ip-10-0-1-200 rke2[3597]: {"level":"warn","ts":"2021-06-16T21:02:50.130Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"p
Jun 16 21:02:50 ip-10-0-1-200 rke2[3597]: time="2021-06-16T21:02:50Z" level=info msg="Failed to test data store connection: context deadline exceeded"
Jun 16 21:02:50 ip-10-0-1-200 rke2[3597]: time="2021-06-16T21:02:50Z" level=info msg="Waiting for cloudcontroller rbac role to be created"
```

* node provisioner (Digital Ocean) cluster with public proxy settings (ec2 proxy) http_proxy, https_proxy, and no_proxy set in rancher:
  * node does provision/create and is listed on the provider, however is not getting to `active` state on rancher
  * no related resources are showing up as they did for custom cluster above (i.e. there is no `CAPI cluster` or any other resource listed)
  * rke2-server logs stopped after this line (no observed errors in the logs)
```
time="2021-06-16T20:59:00Z" level=info msg="Saving current etcd snapshot set to rke2-etcd-snapshots ConfigMap"
```

**Comment by deniseschannon** [comment]
From @bashofmann in this issue: https://github.com/rancher/rancher/issues/32363

For me the rancher-system-agent fails to even pull the `system-agent-installer-rke2`

```
Aug 05 12:21:15 ip-10-0-1-230 rancher-system-agent[2757]: time="2021-08-05T12:21:15Z" level=info msg="Pulling image index.docker.io/rancher/system-agent-installer-rke2:v1.21.3-rc3-rke2r2"
Aug 05 12:22:15 ip-10-0-1-230 rancher-system-agent[2757]: time="2021-08-05T12:22:15Z" level=error msg="error while staging: Get \"https://index.docker.io/v2/\": context deadline exceeded: failed to get image index.docker.io/rancher/system-agent-installer-rke2:v1.21.3-rc3-rke2r2"
Aug 05 12:22:15 ip-10-0-1-230 rancher-system-agent[2757]: time="2021-08-05T12:22:15Z" level=error msg="error syncing 'fleet-default/custom-61ef3f741d5c-machine-plan': handler secret-watch: error applying plan: error executing instruction 0: Get \"https://index.docker.io/v2/\": context deadline exceeded: failed to get image index.docker.io/rancher/system-agent-installer-rke2:v1.21.3-rc3-rke2r2, requeuing"
```

The setup:

Rancher and downstream cluster are in the same private network and only have internet connectivity through a http proxy

I set the necessary HTTP_PROXY, HTTPS_PROXY and NO_PROXY environment variables under "Agent Environment Variables". These are also present in `/etc/systemd/system/rancher-system-agent.env`:

```
sudo cat /etc/systemd/system/rancher-system-agent.env
HTTPS_PROXY=http://10.0.0.125:8888
NO_PROXY=127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local,rancher.10.0.0.125.nip.io
HTTP_PROXY=http://10.0.0.125:8888
```

The same proxy settings work fine in a K3s cluster and images can be pulled there through the proxy.

**Comment by Oats87** [comment]
@bashofmann Are you able to see the logs on your proxy to see if the requests from the `rancher-system-agent` are even landing at your proxy? The implemented `RoundTripper` should be properly utilizing proxies from environment variable i.e. https://github.com/rancher/wharfie/blob/v0.3.2/pkg/registries/registries.go#L152

**Comment by bashofmann** [comment]
@Oats87 You're completely right. I seem to have messed up my environment yesterday with all the tests. `rancher-system-agent` gets the proxy environment variables configured and can pull the image successfully through the proxy.

But, the `rke2-server` is missing the proxy environment variables. `/usr/local/lib/systemd/system/rke2-server.env` only contains:

```
HOME=/root
````

And because of this RKE2 containerd can not pull the images. When I manually add the proxy variables:

```
HOME=/root
HTTPS_PROXY=http://10.0.0.125:8888
NO_PROXY=127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local
HTTP_PROXY=http://10.0.0.125:8888
````

and restart RKE2, it successfully comes up and works.

**Comment by ibuildthecloud** [comment]
@Oats87 The idea is if the http_proxy args are in /etc/systemd/system/rancher-system-agent.env then all instructions ran by the system-agent will see the proxy arguments so when we install rke2 the install script should have the proxy env variables set and then use them.  k3s will take the current env vars and put them in the systemd unit env file but rke2 does not seem to do this.

**Comment by deniseschannon** [comment]
This was updated in the system-agent-installer-rke2 and it was re-tagged so we should be able to test with RKE2 v1.21.3-rc6+rke2r2

https://github.com/rancher/system-agent-installer-rke2/releases/tag/v1.21.3-rc6%2Brke2r2

**Comment by deniseschannon** [comment]
@bashofmann It looks like all issues have been resolved. If you could test, that'd be great!

**Comment by bashofmann** [comment]
When I create a cluster, the proxy environment variables are now correctly configured in the rke2 service as well.

But when I try to edit the environment variables, /var/lib/rancher/rke2/system-agent-installer/rke2-sa.env is not updated to the new values, instead each time I edit the values in the UI, the old values are appended to the file an additional time.
Also the rke2 service does not seem to be restarted. So even if the values were changed correctly, the change would not have any effect.

**Comment by deniseschannon** [comment]
Available to test with k8s v1.21.3+rke2r2, which leverages the updated system-agent-installer that has these changes. 

@bashofmann Can you please retest?

**Comment by bashofmann** [comment]
Tested with v2.6-head b7c440b and v1.21.3+rke2r2: I still see the same behaviour described above. Could it be that these changes are not included there yet?

**Comment by deniseschannon** [comment]
No, it should work. @Oats87 had updated the image for that version so it should work. I will reopen the issue for him.

**Comment by bashofmann** [comment]
In my setup I have both: Rancher can only connect to the internet through a proxy and the downstream cluster can only connect to Rancher and the internet (to pull images) through a proxy.

**Comment by Oats87** [comment]
@bashofmann You’re seeing that the environment file is still being appended to instead of recreated, and RKE2 is not restarting? Is there any way you can upload the logs from the rancher-system-agent here?
