### ISSUE TITLE
Cluster explorer and websocket connection broken after upgrading to rancher 2.5.8 (fine with 2.5.7)

### ISSUE THREAD

**Issue by cortopy** [rancher/rancher#32934]
SURE-3499
SURE-3469 

**What kind of request is this (question/bug/enhancement/feature request):**
Bug/Regression

**Steps to reproduce (least amount of steps as possible):**

1. Upgrade from 2.5.7 to 2.5.8
2. Go to cluster explorer of Rancher local cluster. It's all fine
3. Go to cluster explorer of downstream cluster: There's a second when in a flash I can see the dashboard, and then I get logged out and redirected to the login page

It seems that the websocket connection is not established and that's when the redirect happens.

**RANCHER 2.5.8**
Right after upgrading, the rancher pod in the rancher upstream cluster logs each time I try to access the cluster explorer:

```
[ERROR] Error during subscribe websocket: close sent
```

In the downstream cluster, cattle node agents report:

```
time="2021-05-28T09:10:12Z" level=info msg="Starting plan monitor, checking every 120 seconds"
time="2021-05-28T09:45:25Z" level=error msg="Remotedialer proxy error" error="websocket: close 1006 (abnormal closure): unexpected EOF"
time="2021-05-28T09:45:35Z" level=info msg="Connecting to wss://my.rancher.host/v3/connect with token xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
time="2021-05-28T09:45:35Z" level=info msg="Connecting to proxy" url="wss://my.rancher.host/v3/connect"
```

and the cattle cluster agent:

```
time="2021-05-28T09:40:14Z" level=error msg="Error during subscribe websocket: close sent"
time="2021-05-28T09:42:10Z" level=error msg="Error during subscribe websocket: close sent"
W0528 09:42:48.617883 39 warnings.go:80] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
time="2021-05-28T09:43:58Z" level=error msg="Error during subscribe websocket: close sent"
time="2021-05-28T09:45:25Z" level=error msg="Remotedialer proxy error" error="websocket: close 1006 (abnormal closure): unexpected EOF"
time="2021-05-28T09:45:35Z" level=info msg="Connecting to wss://my.rancher.host/v3/connect with token xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
time="2021-05-28T09:45:35Z" level=info msg="Connecting to proxy" url="wss://my.rancher.host/v3/connect"
W0528 09:47:25.012488 39 warnings.go:80] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
time="2021-05-28T09:50:30Z" level=error msg="Error during subscribe websocket: close sent"
```

**RANCHER 2.5.7**

Upstream and downstream are working fine. Rancher UI working fine too

When the cattle cluster agent starts it logs no errors

```
time="2021-05-28T09:53:52Z" level=info msg="Connecting to wss://my.rancher.host/v3/connect/register with token xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
time="2021-05-28T09:53:52Z" level=info msg="Connecting to proxy" url="wss://my.rancher.host/v3/connect/register"
time="2021-05-28T09:53:52Z" level=info msg="Starting user controllers"`
```

When each cattle node agent pod is started they log something like:

```
time="2021-05-28T09:53:52Z" level=info msg="Connecting to wss://my.rancher.host/v3/connect/register with token xxxxxxxxxxxxxxxxxxxxxxxxxxx"
time="2021-05-28T09:53:52Z" level=info msg="Connecting to proxy" url="wss://my.rancher.host/v3/connect/register"
time="2021-05-28T09:53:52Z" level=info msg="Starting user controllers"
```

Neither of them logs any errors

**Result:**

I have to rollback to 2.5.7 if I want to carry on using rancher

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.8
- Installation option (single install/HA): single install with helm

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Cloud
- Kubernetes version (use `kubectl version`): v1.20.7+rke2r2

- Docker version (use `docker version`):

```
20.10.3
```

**Comment by virtuman** [comment]
+1 
same issue

**Comment by munenari** [comment]
I had a same issue, and I resolved.

In my case, I set wrong hostname.
To accese `https://my-k3s.local`, install command should be `helm install rancher rancher-stable/rancher --namespace cattle-system --set hostname=my-k3s.local` (not hostname=my-wrong-k3s.local)

I hope it helps...

**Comment by decimalator** [comment]
+1 
same issue. I upgraded through the cluster explorer on the upstream Rancher cluster. I verified the hostname value is correct, same value as it had been for 2.5.7 fwiw

**Comment by 852808** [comment]
+1 Same issue

**Comment by superseb** [comment]
Please share what kind of clusters you experience the issue with (created using Rancher yes/no, what type, what version or anything else that is specific to where you are seeing the issue) so we can more easily track down where it is happening, thanks in advance.

**Comment by 852808** [comment]
Yes we have  **2.5.8** version running in our environment. We have created the cluster usign the **terraform rancher provider in OKE**. The cluster explorerr access to local cluster works fine but other cluster it logs out and re-directed to the login page.

**Comment by cortopy** [comment]
In my case:

- My Rancher cluster has been going since 2.5.4. It was deployed with helm on a rke2 cluster (now at v1.20.7+rke2r2). This setup hasn't changed. Upgrades to 2.5.5-2.5.7 went ok. I reported this issue when upgrading to 2.5.8 as that's when it broke. This failed upgrade was also done with helm
- Downstream cluster was created with the above Rancher cluster using custom provider (Hetzner) with a mix of dedicated servers and VM

**Comment by decimalator** [comment]
For us:

- cluster that runs Rancher was provisioned with RKE running 1.18.16 on CentOS 7
  - previously running 2.5.7, installed via `helm`
  - upgraded to 2.5.8 through the `Apps & Marketplace` section of the cluster explorer with `helm`
  - upgrade appeared to be successful
- downstream cluster with broken cluster explorer was also provisioned with RKE running 1.18.16 on CentOS 7

**Comment by Martin-Weiss** [comment]
FYI - just hit this issue (or a very similar one), too 
- but in my case after the upgrade from 2.5.8 to 2.5.9.. 
https://github.com/rancher/rancher/issues/33667

**Comment by decimalator** [comment]
I upgraded our 2.5.8 instance to 2.5.9 which didn't resolve the issue. I'm going to test an upgrade of our upstream rancher cluster from 1.18.16 to the latest 1.20 that we are already planning. We'll see if that has any effect. If not, we'll be doing the same upgrade to the downstream clusters. 

if nothing resolves it, I'll revert back to 2.5.7 until this gets fixed. Not having the cluster explorer UI is starting to become a problem

**Comment by Martin-Weiss** [comment]
> I upgraded our 2.5.8 instance to 2.5.9 which didn't resolve the issue. I'm going to test an upgrade of our upstream rancher cluster from 1.18.16 to the latest 1.20 that we are already planning. We'll see if that has any effect. If not, we'll be doing the same upgrade to the downstream clusters.
> 
> if nothing resolves it, I'll revert back to 2.5.7 until this gets fixed. Not having the cluster explorer UI is starting to become a problem

@decimalator JFYI - in my case deleting and re-importing the downstream cluster solved the problem - not sure if that is possible in your case..

**Comment by decimalator** [comment]
> > I upgraded our 2.5.8 instance to 2.5.9 which didn't resolve the issue. I'm going to test an upgrade of our upstream rancher cluster from 1.18.16 to the latest 1.20 that we are already planning. We'll see if that has any effect. If not, we'll be doing the same upgrade to the downstream clusters.
> > if nothing resolves it, I'll revert back to 2.5.7 until this gets fixed. Not having the cluster explorer UI is starting to become a problem
> 
> @decimalator JFYI - in my case deleting and re-importing the downstream cluster solved the problem - not sure if that is possible in your case..

@Martin-Weiss ooh, yeah we can definitely give that a shot if my k8s upgrades don't solve it. thanks!

**Comment by cortopy** [comment]
@Martin-Weiss so glad to know there's a solution. But wouldn't I lose all the benefits of [provisioned clusters](https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/)?

**Comment by Martin-Weiss** [comment]
> 
> 
> @Martin-Weiss so glad to know there's a solution. But wouldn't I lose all the benefits of [provisioned clusters](https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/)?

Yeah - I agree this is not a good solution - but until we have a real fix....

**Comment by StrongMonkey** [comment]
For all of you that are using v1.20.7+rke2r2 as your local cluster, Did you install rancher through [rancherd](https://rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-linux/rancherd-configuration/) or other installation method?

**Comment by cortopy** [comment]
I installed with the bash command `curl -sfL https://get.rke2.io | sh -`. However, I upgraded it using the Rancher cluster edit tool

**Comment by StrongMonkey** [comment]
Also for anyone who is experiencing this issue, can you share `cattle-cluster-agent` pod logs in cattle-system on downstream clusters before and after upgrade? If the cattle-cluster-agent is not working then dashboard is not likely to work.

**Comment by decimalator** [comment]
Interestingly, a complete reboot of all of the nodes of the downstream cluster ended up solving the issue, unintentionally, temporarily. I didn't delete the cluster from Rancher. I didn't close the Chrome tab I had had open to the Cluster Manager interface for cordoning nodes during the reboots. After all of the reboots I was browsing the System project of the downstream cluster to watch logs. I don't remember how, but I somehow ended up in the Cluster Explorer interface for the downstream cluster and it was working.

After awhile, with no changes to either the upstream Rancher cluster or the downstream cluster, it stopped working again. Same log entries for the cattle-cluster-agent as have been shared before. 

The ONLY change to the cluster was rolling reboots of the worker nodes. We had done rolling reboots of the control plane nodes on a Friday with no effect to the Cluster Explorer UI.

**Comment by flostru** [comment]
we are seeing this on 1.19.x downstream clusters
all 1.20.x are fine here
As soon as i switch to a 1.19.x cluster in explorer it kicks me to the login prompt

**Comment by flostru** [comment]
i think i found it

did you guys perhaps disable anonymous auth in grafana?

```yaml
  grafana.ini:
    auth:
      disable_login_form: false
    auth.anonymous:
      enabled: false
      org_role: Viewer
```
obviously rancher explorer gets the metrics from rancher-monitoring grafana, so it will get a 401 from grafana when loading the dashboard and that ripps the websocket

**Comment by cortopy** [comment]
@flostru thank you for posting that but it's not related to this issue. This is about the rancher cluster agent and the cluster explorer dashboard. Grafana would be an entirely different thing

**Comment by flostru** [comment]
> @flostru thank you for posting that but it's not related to this issue. This is about the rancher cluster agent and the cluster explorer dashboard. Grafana would be an entirely different thing

maybe more than one issue but since rancher 2.5.8 the explorer dashboard integrates grafana metrics via iframe, if grafana needs authentication it will return an 401 (unauthorised) and your websocket in cluster explorer will break, leading to

```
level=error msg="Error during subscribe websocket: close sent"
```
in cluster agent

so leading to the symptoms described, and it will send you back to log-in.

Still its possible that its a different issue, do you have grafana "anonymous.auth" disabled? It is enabled by default and rancher explorer needs it enabled.

Can you reach a submenu of the explorer without getting loged out?
like: https://rancher.yourdomain.com/dashboard/c/c-xxxxx/explorer/namespace

**Comment by decimalator** [comment]
@flostru that helped me! Thanks!!

In my case, I had renamed the name of the only Org. I created a blank Org called "Main Org." to match the default in grafana.ini and :tada: I can get to the Cluster Explorer again.

**Comment by cortopy** [comment]
It was working for me for about 3 weeks and today it all broke again. I downgraded to 2.5.7 and then upgraded again to 2.5.9 and I can access the explorer again.

@flostru I didn't think grafana was related because I can't access any area in the explorer, not even the dashboard, let alone trying any link to the monitoring app

My grafana config is exactly like your except I didn't have a `org_name`. I've added it just in case. Fingers crossed

**Comment by cortopy** [comment]
arrrgg spoke too soon. It's broke again, even with the grafana config

**Comment by ikogan** [comment]
We had this start suddenly with no changes to our cluster, today. Grafana configuration hasn't changed, anonymous auth is still enabled. We didn't do any org renaming. We have other downstream clusters that are virtually identical where this doesn't happen.

Production Cluster (Broken): K8s v1.19.10, docker 20.10.8.
DevTest Cluster (Working): K8s v1.19.12, docker 20.10.8.

We have another cluster identical to devtest which is also working. Symptoms in our prod cluster are identical to what's described here, including being able to use the explorer if we follow a deep link. The momen we click on "Cluster Overview" we get logged out. Our `grafana.ini` sections looks like this:

```yaml
grafana.ini:
    auth:
        disable_login_form: false
    auth.anonymous:
        enabled: true
        org_role: Viewer
    auth.basic:
        enabled: false
    dashboards:
        default_home_dashboard_bath: /tmp/dashboards/rancher-default-home.json
    security:
        allow_embedding: true
    users:
        auto_assign_org_role: Viewer
```

This same configuration has been deployed for 199 days.

**Comment by bentastic27** [comment]
It appears that websockets break when V1 monitoring isn't currently working as well. I worked on a setup just now where prometheus was crashlooping due to the memory limit being too low. I don't recall if Grafana was having issues, but it likely was as well. Navigating to Cluster Explorer on this cluster eventually broke the websocket, therefore broke Cluster Explorer AND Cluster Manager as well until a new connection was made.

**Comment by vincent99** [comment]
https://github.com/rancher/dashboard/issues/3214

**Comment by szthanatos** [comment]
same issue +1 in harvester.

**Comment by wonleing** [comment]
How is this issue resolved? Any way to fix?

**Comment by slickwarren** [comment]
this issue has the same repro steps [as this ticket](https://github.com/rancher/rancher/issues/34819#issuecomment-1013354661), linking the two for tracking. There was a reopen for the last fix so we are waiting for this to come back to test.

**Comment by sowmyav27** [comment]
Based on offline discussion with @davidnuzik @ibuildthecloud @deniseschannon closing this issue for 2.5.12 release. 
Note: We have not be able to full repro/validate this issue. We will have user test it using 2.5.12 and 2.6.3-patch1 and if there are any further fixes needed, they will be addressed separately.

**Comment by wang-xiaowu** [comment]
> 基于与@davidnuzik @ibuildthecloud @deniseschannon的离线讨论，为 2.5.12 版本关闭此问题。 注意：我们无法完全重现/验证此问题。我们将让用户使用 2.5.12 和 2.6.3-patch1 对其进行测试，如果需要任何进一步的修复，它们将单独解决。

the version of 2.6.3 is in the same situatiuon
it's a problem

**Comment by maradwan** [comment]
the issue still on v2.6.4

**Comment by uje-m** [comment]
@maradwan Same with me

**Comment by Terry-Basin** [comment]
same here on v2.6.5

**Comment by rjbaat** [comment]
I also have wss connection issue notifications popping up on 2.6.7.

The message is: 

```
The connection to wss://my.rancher.host/v1/subscribe closed unexpectedly Thu, Aug 25 2022 11:17:06 am. Retrying...
Websocket Disconnected
The connection to wss://my.rancher.host/v1/subscribe closed unexpectedly 
```

And in the logs it tels me: 

```
Error during subscribe websocket: close sent
Error during subscribe write tcp 172.17.0.3:443->xxx.xxx.xxx.xxx:52499: write: broken pipe
```
Is there a solution?

**Comment by wonleing** [comment]
can anyone open this issue, or any other issue track this problem?

**Comment by BryceTech122** [comment]
> I also have wss connection issue notifications popping up on 2.6.7.
> 
> The message is:
> 
> ```
> The connection to wss://my.rancher.host/v1/subscribe closed unexpectedly Thu, Aug 25 2022 11:17:06 am. Retrying...
> Websocket Disconnected
> The connection to wss://my.rancher.host/v1/subscribe closed unexpectedly 
> ```
> 
> And in the logs it tels me:
> 
> ```
> Error during subscribe websocket: close sent
> Error during subscribe write tcp 172.17.0.3:443->xxx.xxx.xxx.xxx:52499: write: broken pipe
> ```
> 
> Is there a solution?

I am also having this issue in 2.6.7

**Comment by franznemeth** [comment]
We are also facing this issue on 2.6.8

**Comment by rjbaat** [comment]
Please reopen this issue, so it can be tracked and fixed.

**Comment by gabrielcandrade** [comment]
Having problems on stable version: 2.6.8

**Comment by eumel8** [comment]
Not sure what do you expect from me-too comments on a closed Rancher 2.5 issue. Indeed, there was a similar problem in Rancher 2.6 which was solved in 2.6.6 with this [PR](https://github.com/rancher/remotedialer/pull/46)
Root cause was in our case a high traffic use case on downstream cluster API which burned the cluster agent connection from time to time originated by this back pressure thing.
If you have still problems with broken websocket connections my recommendation would be to open a new issue with description of your exact use case, e.g. bandwith on your cluster agents, load on the Rancher server, count of downstream clusters/nodes. It seems Rancher needs more and more resources from version to version. So it's a good opportunity "to solve" some issues with increase cpu/mem resources on the Rancher server.  Also ordinary network issues can cause broken websocket connections, so check your network and look for similar network issues at the same time.  My last advice would be to set 
```
        - name: CATTLE_DEBUG
          value: "true"
```  
in cluster agent deployment and node agent daemonset, to get more informatiion whats going on. Also helpful, but a little bit of dangerous due the high flood of data:  Increase loglevel of Rancher instance on the fly: 
```
kubectl -n cattle-system exec -it rancher-yyyy loglevel --set debug
or
kubectl -n cattle-system exec -it rancher-yyyy loglevel --set trace
```

**Comment by konstantin-921** [comment]
We are also facing this issue on 2.6.8.
We are using 4 installations of rancher + downstream cluster. We got this problem in all of our clusters. That is, there were different conditions everywhere: resources, network, etc.

**Comment by rjbaat** [comment]
I have made a new issue to raise awareness for this, since this issue is closed en we still deal with the problem. https://github.com/rancher/rancher/issues/38931

Please feel free to add comments to the new issue if you have the same or similar problems with the websockets, so it hopefully gets more priority. Thnx!

**Comment by shou55** [comment]
I also encountered an error similar to this websocket, but the reason for the problem is that I used nginx-Ingress-controller in K8S. After I changed it to Kubernetes /ingress-nginx, everything was fine

**Comment by uje-m** [comment]
> I also encountered an error similar to this websocket, but the reason for the problem is that I used nginx-Ingress-controller in K8S. After I changed it to Kubernetes /ingress-nginx, everything was fine

what do you mean by that?

**Comment by franznemeth** [comment]
For us the situation was caused because of unusually high load on rancher which was resolved through #38804. This is probably only relevant if you're using ActiveDirectory as authentication provider.

**Comment by eumel8** [comment]
@franznemeth nice catch, thx for sharing!
We had some few Keycloak users with `ExtraByProvider: nil` and after manually fixing userattributes no websocket error occurred anymore. But Rancher nodes have still high load.

**Comment by mfbrj** [comment]
Same issue on Rancher 2.5.11

Dashboard works fine for local (rancher) cluster.
On the downstream cluster, "there's a second when in a flash I can see the dashboard, and then I get logged out and redirected to the login page". (as exactly said by the issue owner)

In my case, there was no Rancher upgrade, neither downstream cluster upgrade. The dashboard just stopped working for no apparent reason.

**Comment by zhang8473** [comment]
I have the same issue when upgrading from Rancher 2.5 to 2.7.5. I delete all cattle namespaces on EKS and apply the yaml again., still encountered this problem.

**Comment by alen-z** [comment]
Rancher 2.8.0 `Error during subscribe websocket` provisioning `v1.27.8+rke2r1`.

**Comment by tariksimsek** [comment]
So no help here?

**Comment by eumel8** [comment]
@tariksimsek What do you expect from a closed issue? As I already mentioned I'm not fine with this "me-too" comments. Best way is to open a new issue and provide the most information as you can with environment description, logs, Rancher and Cluster Agent in debug mode, any observations what can help to find the root cause. 
From my experiences it's still a load problem. Rancher needs more and more resources because they don't cleanup old stuff. Because of that you need bigger machines for a relative small workload. Not sure how long this will work out.
