### ISSUE TITLE
Rancher 2.5.9 uninstall via helm on RKE2 cluster with CIS profile active does not honor podSecurityPolicies for uninstall job

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rancher#33724]
SURE-3193

**Rancher Server Setup**
- Rancher version: 2.5.9
- Installation option (Docker install/Helm Chart): helm chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke2 with cis 1.6 profile active

**Information about the Cluster**
- Kubernetes version: 1.20
- Cluster Type (Local/Downstream): Local

**Describe the bug**
helm uninstall rancher -n cattle-system -> gets stuck
kubectl get jobs -A shows rancher-post-delete job that is in FailedCreate

`Warning  FailedCreate  17s (x5 over 2m47s)  job-controller  Error creating: pods "rancher-post-delete-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.containers[0].securityContext.runAsUser: Invalid value: 0: running with the root UID is forbidden`

-> seems that the container runs as root and that is not allowed due to security reasons and blocked by the PSP due to that

**To Reproduce**
Install rancher 2.5.9 via helm in to rke2 cluster with PSP enabled (cis profile 1.6)
Uninstall rancher via helm

**Result**
Uninstall job does not run

**Expected Result**
Uninstall job runs

**Comment by Martin-Weiss** [comment]
Seems that in the cluster role rancher-post-delete this is missing for secured RKE2 clusters:

```
- apiGroups:
  - policy
  resourceNames:
  - system-unrestricted-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use
```

**Comment by cjellick** [comment]
Thanks for digging in and IDing the fix @Martin-Weiss

**Comment by cjellick** [comment]
Looks like this is being addressed in 2.6.0. perhaps we need a backport.
PR: https://github.com/rancher/rancher/pull/33023
issue: https://github.com/rancher/rancher/issues/32878

**Comment by Martin-Weiss** [comment]
When do we get 2.6 and which release will be production ready? Or is that already planned for 2.6.0?

**Comment by SheilaghM** [comment]
Backport PR#33023 to 2.5.10.

**Comment by SheilaghM** [comment]
https://github.com/rancher/rancher/pull/33069 - backport of PR #33023 to 2.5.x
 jiaqiluo merged commit 253edc5 into rancher:release/v2.5 on Jun 7

https://github.com/rancher/rancher/pull/33349 - backport of PR #33023 to 2.5.9
jiaqiluo merged commit c8ad7f3 into rancher:release/v2.5.9 on Jun 25

@Martin-Weiss can we verify that this is still an issue in 2.5.9?

**Comment by Martin-Weiss** [comment]
> @Martin-Weiss can we verify that this is still an issue in 2.5.9?

Not sure what you are asking - we found this issue in 2.5.9...

**Comment by MKlimuszka** [comment]
Assigning Seb because Jack isn't on the team anymore.

**Comment by superseb** [comment]
This was validated in v2.5.10-rc1, see https://github.com/rancher/rancher/issues/33068#issuecomment-920260659

It was pulled from v2.5.9 in https://github.com/rancher/rancher/pull/33405

**Comment by jmcsagdc** [comment]
With Rancher 2.5.12-rc2, the helm uninstall seems to not complete fully:

`kubectl get pods -n cattle-system                                                                                             
NAME                               READY   STATUS    RESTARTS   AGE
rancher-post-delete-sf8qd          1/1     Running   2          6m9s
rancher-webhook-84bfb69844-gl4k6   1/1     Running   0          12m`

`Uninstalling Rancher resources in the following namespaces: fleet-system cattle-system rancher-operator-system
--- Skip the app [fleet-crd] in the namespace [fleet-system]
--- Deleting the app [rancher-webhook] in the namespace [cattle-system]
Error: warning: Hook pre-delete rancher-webhook/templates/pre-delete-hook-psp.yaml failed: podsecuritypolicies.policy is forbidden: User "system:serviceaccount:cattle-system:rancher-post-delete" cannot create resource "podsecuritypolicies" in API group "policy" at the cluster scope
waiting 5 seconds for pods of [rancher-webhook] to be terminated ...
waiting 5 seconds for pods of [rancher-webhook] to be terminated ...
waiting 5 seconds for pods of [rancher-webhook] to be terminated ...
waiting 5 seconds for pods of [rancher-webhook] to be terminated ...
waiting 5 seconds for pods of [rancher-webhook] to be terminated ...
waiting 5 seconds for pods of [rancher-webhook] to be terminated ...
waiting 5 seconds for pods of [rancher-webhook] to be terminated ...
waiting 5 seconds for pods of [rancher-webhook] to be terminated ...
waiting 5 seconds for pods of [rancher-webhook] to be terminated ...
waiting 5 seconds for pods of [rancher-webhook] to be terminated ...
waiting 5 seconds for pods of [rancher-webhook] to be terminated ...
waiting 5 seconds for pods of [rancher-webhook] to be terminated ...
waiting 5 seconds for pods of [rancher-webhook] to be terminated ...
waiting 5 seconds for pods of [rancher-webhook] to be terminated ...
waiting 5 seconds for pods of [rancher-webhook] to be terminated ...
waiting 5 seconds for pods of [rancher-webhook] to be terminated ...
waiting 5 seconds for pods of [rancher-webhook] to be terminated ...
waiting 5 seconds for pods of [rancher-webhook] to be terminated ...
waiting 5 seconds for pods of [rancher-webhook] to be terminated ...
waiting 5 seconds for pods of [rancher-webhook] to be terminated ...
waiting 5 seconds for pods of [rancher-webhook] to be terminated ...
waiting 5 seconds for pods of [rancher-webhook] to be terminated ...
waiting 5 seconds for pods of [rancher-webhook] to be terminated ...
waiting 5 seconds for pods of [rancher-webhook] to be terminated ...
timeout uninstalling [rancher-webhook] in the namespace [cattle-system]
--- Skip the app [rancher-operator-crd] in the namespace [rancher-operator-system]
------ Summary ------
Failed to uninstall the following apps: rancher-webhook`

The rancher-post-delete pod first went to an error state, then running and hung for a while on the webhook (which did fail) then error then crashloopbackooff then running again.

![image (1)](https://user-images.githubusercontent.com/15971368/149594874-1979b597-adda-49cf-8d23-5c0ad7feaf29.png)

The rancher-post-delete job/pod seems to infintiely re-run and attempt to delete the webhook, but it never will due to this PSP issue

**Comment by jmcsagdc** [comment]
Verified in 2.5.12-rc5

Setup: rke2 local cluster, v1.20.14+rke2r2, cert-manager jetstack version v1.0.1
Cluster is EC2, 3 server nodes, one worker node, t3xlarge/60GB

The uninstall completes cleanly, helm does not error and the cattle-system namespace has no lingering pods.
