### ISSUE TITLE
Azure Cloud Credential - Fail

### ISSUE THREAD

**Issue by claudioser** [rancher/rancher#34112]
**If this is a UI issue, please file an issue at https://github.com/rancher/dashboard/**

**Rancher Server Setup**
- Rancher version:  Rancher 2.6 rc1
- Installation option (Docker install/Helm Chart): Helm - RKE1 

**Describe the bug**
trying to create an Azure cloud credential and it fails with "authentication Failed" . This credential works fine with Rancher 2.5.x

Please see screen shot .
The developer console screenshot, shows that the response is returning an invalid tenantId from azure, even though this is not even asked for. 

**Screenshots**
![image](https://user-images.githubusercontent.com/53047113/128834953-d82083e0-400d-4628-bad5-fe72703f63cd.png)

**Additional context**
a)  when I try to create an aks cluster, and fill in the appropriate credentials as per screenshot  :
![image](https://user-images.githubusercontent.com/53047113/128838951-335ef63e-9f99-4e75-86a2-6cef38acb12d.png)

The credentials are fine and cluster does provision correctly

**Comment by cbron** [comment]
This should be fixed on rc2. We've switched the credential check to properly handle tenant ID.

**Comment by kinarashah** [comment]
Available to test with `v2.6.0-rc2`

**Comment by prabalsharma** [comment]
was able to create Azure CC on rc2

**Comment by davidnuzik** [comment]
I thought this was related it's not? I get "invalid tenantId" when try to create a cluster.
v2.6.0-rc2

![image](https://user-images.githubusercontent.com/45179589/128947105-af7a2166-db84-4693-999e-48d80f707cab.png)

Thus I can't specify machine types, etc.

**Comment by cmurphy** [comment]
@davidnuzik that looks like this issue https://github.com/rancher/dashboard/issues/3758 which is not fixed yet

**Comment by davidnuzik** [comment]
Copy thanks
