### ISSUE TITLE
After upgrade to 0.56, existing load balancers break

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#3415]
After upgrading to 0.56, some (but not all) of the load balancers get stuck in "initializing" mode, and do not work.  Logs end with:
````
26/01/2016 3:38:57 pmINFO: Sending agent-instance-startup applied 2-d015189ec911e5368c15141a1d1ab7d015a2cd0f1fab8452da3c3480e4e9adae
26/01/2016 3:38:57 pmStarting monit daemon with http interface at [localhost:2812]
````
However, some other load balancers work correctly.  Re-creating the load balancer, or even defining a new stack, does not solve the issue.

All hosts are running Docker 1.9.1, all load balancer containers are agent-instance:0.6.0

**Comment by sshipway** [comment]
May be related to #3413

**Comment by sshipway** [comment]
Problem seems to only affect HTTP load balancers; TCP balancers keep working.  Container is running and active, and can be attached to, but Rancher says LB is "Initialising" and port on container times out (no connect)

**Comment by sshipway** [comment]
The `/etc/haproxy/haproxy.cfg` file created in the Load Balancer containers appears to have the correct IP addresses and ports for the backing service, but on the LoadBalancers that are not working, the IP address is not pingable from within the LB container.
````
frontend c292fcc1-bc1f-4c1d-8fa2-2bf3b2e9ec48_48080_frontend                    
        bind 10.42.223.230:48080                                                
        mode http                                                               
                                                                                
        default_backend c292fcc1-bc1f-4c1d-8fa2-2bf3b2e9ec48_48080_0_backend    
                                                                                
backend c292fcc1-bc1f-4c1d-8fa2-2bf3b2e9ec48_48080_0_backend                    
        mode http                                                               
        server f93b584d-cc03-48ea-a39a-0c640e0f477d 10.42.12.230:80             
                                                                                
                                                                                
listen default 0.0.0.0:42                                                       
                                                                                
root@9ae70557ce45:/# ping 10.42.12.230                                          
PING 10.42.12.230 (10.42.12.230) 56(84) bytes of data.                          
^C                                                                              
--- 10.42.12.230 ping statistics ---                                            
3 packets transmitted, 0 received, 100% packet loss, time 1999ms                
                                                                                
root@9ae70557ce45:/#                                                          
````
On the LB that is still working, I can ping the IP successfully.

**Comment by sangeethah** [comment]
@sshipway , after upgrade some of your hosts seems to have lost connectivity with other hosts on managed network. You can try to restart network agent on the hosts that have connectivity issue , which should restore the connectivity with other hosts .
Restarting Network Agent may result in network agent stuck in "Starting" state due to #1406 . 
If you hit this issue , rebooting hosts should fix the problem.

**Comment by sshipway** [comment]
I agree it does look like the host-host Rancher network is broken; the LB seems to work if the target is on the same Host.  I'm rebooting the cluster hosts now to see if this solves the issue.  However, I has thought a Rancher upgrade should be independent of the individual Hosts?  Having to reboot every host in the Environment after a Rancher upgrade could be very problematic.

**Comment by sshipway** [comment]
@sangeethah - Have rebooted all hosts in the Environment, which also cleans out the saved container images so that all have to be re-downloaded, ensuring we get the correct versions.  
The problem is not fixed.

**Comment by sangeethah** [comment]
@sshipway , what is the OS of your hosts ? If it is coreOS hosts , connectivity between hosts are broken when we switched to charon in rancher-server version-V0.56.0  tracked in #3416

**Comment by sshipway** [comment]
Yes, this is CoreOS (CoreOS 899.0 Docker 1.9.1, Kernel 4.4)

**Comment by deniseschannon** [comment]
@sshipway Since you are on CoreOS, I'm going to close this in favor of #3416. We are releasing v0.56.1 shortly.
