### ISSUE TITLE
Change events and deleting provisioning clusters is causing clusters to re-appear in the UI 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#34306]
There's a problem with change events and deleting provisioning clusters, if you delete some clusters, they send resource.removes and go away.  Then you create a new one, or maybe do nothing at all sometimes?, and those recently deleted ones resurrect themselves from change events.  Then they maybe go away later.

**Comment by deniseschannon** [comment]
create and delete clusters to see if you see any of the deleted clusters appear. 

This was only observed by someone else, so no concrete reproduction steps. 

Try creating and deleteing 10 clusters (do a mix of node provisioned and custom)

**Comment by vincent99** [comment]
More specifically, the problem we fixed would be when you're a basic non-admin user and gain/lose a cluster.  That triggers a bunch of changes in the schemas you are authorized to see see, which temporarily stops and then re-establishes all the watches for change events, and the watch was being resumed "in the past" so a bunch of change events for things that have already happened came in and "resurrected" resources that have since been deleted.

**Comment by jiaqiluo** [comment]
The fix is validated in rancher v2.6.0-rc6, docker install 

Steps:
- run rancher v2.6.0-rc6, docker install 
- create a local user `user1` 
- open 2 sessions in the browser, one logging as admin, another logging as user1 
- as `admin`, provision multiple clusters, a mix of node provisioned and custom
- as `admin`, assign `user1` as cluster owner/member of those clusters 
- as `user1`, provision multiple clusters, a mix of node provisioned and custom
- as `admin`, delete all clusters at the same; meanwhile, checking the user1's page 

Results:
- on the `user1`'s page, all clusters go to the deleting state, then disappear
- no cluster came back after it is deleted 

There are about 12 clusters assigned to `user1` and changing their states at the same time, and the issue does not happen anymore.

**Comment by jiaqiluo** [comment]
@sowmyav27 Could you review the validation and close the issue?

**Comment by deniseschannon** [comment]
There have been additional changes made in another issue, so I'd like to move this to test to see if we are still seeing these phantom clusters and if we don't see it in the next couple of weeks, we close this issue.

**Comment by anupama2501** [comment]
Verified on v2.6-head 6a0a991

Enabled openLDAP auth, created a local user -user1

- As an admin - created an rke1 and rke2 node driver clusters
- As a local user, create an rke1 and rke2 custom clusters
- As an auth user, created an rke1 k8s v1.20.10-rancher1-2 and an rke1 k8s v1.19.14-rancher1-2
- deleted the clusters as by local user1, admin and auth user and see that there were no phantom clusters showing up in cluster management, fleet [default clusters] and home page. 


As per @deniseschannon's comment, will keep this issue open for a week for any similar issues seen.

**Comment by anupama2501** [comment]
Closing this ticket as no issues reported. Will open the issue if seen again in future.
