### ISSUE TITLE
rancher 2.5.9 - EKS - rancher downstream cluster does not add security group to launch template

### ISSUE THREAD

**Issue by ifelsefi** [rancher/rancher#34749]
SURE-3369

Hi,

I am running Rancher 2.5.9.   Previously deploying downstream EKS clusters would add security groups we to the instances which we already have defined in our VPC.   Though after upgrading from 2.5.5 to 2.5.9 that isn't the case anymore.

```me@laptop[~]$ aws ec2 get-launch-template-data --instance-id i-0b43dd1010d7f3279
LaunchTemplateData:
  BlockDeviceMappings:
  - DeviceName: /dev/xvda
    Ebs:
      DeleteOnTermination: true
      Encrypted: true
      KmsKeyId: our-kms
      SnapshotId: snap-0639f1b0f4e646866
      VolumeSize: 600
      VolumeType: gp2
  CapacityReservationSpecification:
    CapacityReservationPreference: open
  CpuOptions:
    CoreCount: 2
    ThreadsPerCore: 2
  DisableApiTermination: false
  EbsOptimized: false
  EnclaveOptions:
    Enabled: false
  HibernationOptions:
    Configured: false
  IamInstanceProfile:
    Arn: our-arn
  ImageId: ami-0f047c3819e0145ea
  InstanceInitiatedShutdownBehavior: stop
  InstanceType: p2.xlarge
  KeyName: eks
  MetadataOptions:
    HttpEndpoint: enabled
    HttpPutResponseHopLimit: 1
    HttpTokens: optional
  Monitoring:
    Enabled: false
  NetworkInterfaces:
  - DeleteOnTermination: true
    Description: ''
    DeviceIndex: 0
    Groups:
    - sg-0931602ccbd6be811
    -  SECURITY GROUP MISSING HERE 
    InterfaceType: interface
    Ipv6Addresses: []
    NetworkCardIndex: 0
    PrivateIpAddresses:
  
  ```
  
It should contain "sg-0fdfd2958bc1602f5" but it only contains  "sg-0931602ccbd6be811" which was created by Rancher.

I tried this using the Rancher GUI and Terraform.   Both fail. 

Interestingly the Rancher API does show the security group.

```
{
"actions": {
"enableMonitoring": "…/v3/clusters/c-wm7tz?action=enableMonitoring",
"generateKubeconfig": "…/v3/clusters/c-wm7tz?action=generateKubeconfig",
"importYaml": "…/v3/clusters/c-wm7tz?action=importYaml"
},
"agentImage": "registry/rancher/rancher-agent:v2.5.9",
"agentImageOverride": "",
"allocatable": {
"cpu": "39620m",
"memory": "247599672Ki",
"pods": "584"
},
"annotations": {
"authz.management.cattle.io/creator-role-bindings": "{\"created\":[\"cluster-owner\"],\"required\":[\"cluster-owner\"]}",
"clusters.management.cattle.io/ke-last-refresh": "1631729034",
"lifecycle.cattle.io/create.cluster-agent-controller-cleanup": "true",
"lifecycle.cattle.io/create.cluster-provisioner-controller": "true",
"lifecycle.cattle.io/create.cluster-scoped-gc": "true",
"lifecycle.cattle.io/create.mgmt-cluster-rbac-remove": "true"
},
"answers": {
"clusterId": null,
"projectId": null,
"type": "/v3/schemas/answer"
},
"apiEndpoint": "https://foobar.us-east-2.eks.amazonaws.com",
"appliedEnableNetworkPolicy": false,
"appliedPodSecurityPolicyTemplateId": "",
"appliedSpec": {
"agentImageOverride": "",
"answers": {
"clusterId": null,
"projectId": null,
"type": "/v3/schemas/answer"
},
"clusterTemplateId": null,
"clusterTemplateRevisionId": null,
"defaultClusterRoleForProjectMembers": null,
"defaultPodSecurityPolicyTemplateId": null,
"description": "",
"desiredAgentImage": "",
"desiredAuthImage": "",
"displayName": "",
"dockerRootDir": "/var/lib/docker",
"eksConfig": {
"amazonCredentialSecret": "cattle-global-data:cc-rvkr5",
"displayName": "eksgpu",
"imported": false,
"kmsKey": "",
"kubernetesVersion": "1.20",
"loggingTypes": [ 5 items
"api",
"audit",
"authenticator",
"controllerManager",
"scheduler"
],
"nodeGroups": [ 2 items
{
"desiredSize": 2,
"diskSize": 20,
"ec2SshKey": "eks",
"gpu": false,
"imageId": null,
"instanceType": "m5d.4xlarge",
"labels": {
"size": "m5d.4xlarge"
},
"launchTemplate": null,
"maxSize": 10,
"minSize": 2,
"nodegroupName": "md5-4xlarge",
"requestSpotInstances": false,
"resourceTags": { },
"spotInstanceTypes": null,
"subnets": [ 2 items
"subnet-0369125b57d0db817",
"subnet-0ee419315dbccbed3"
],
"tags": {
"MaintenanceOwner": "FOOBAR",
},
"type": "/v3/schemas/nodeGroup",
"version": "1.20"
},
{
"desiredSize": 2,
"diskSize": 600,
"ec2SshKey": "eks",
"gpu": true,
"imageId": null,
"instanceType": "p2.xlarge",
"labels": {
"gpu": "true",
"size": "p2.xlarge"
},
"launchTemplate": null,
"maxSize": 10,
"minSize": 2,
"nodegroupName": "p2-xlarge",
"requestSpotInstances": false,
"resourceTags": { },
"spotInstanceTypes": null,
"subnets": [ 2 items
"subnet-0369125b57d0db817",
"subnet-0ee419315dbccbed3"
],
"tags": {
"MaintenanceOwner": "foobar",
},
"type": "/v3/schemas/nodeGroup",
"version": "1.20"
}
],
"privateAccess": true,
"publicAccess": false,
"publicAccessSources": [
"0.0.0.0/0"
],
"region": "us-east-2",
"secretsEncryption": false,
"securityGroups": [ 2 items
"sg-017e712e8a7950e53",
"sg-0fdfd2958bc1602f5"
],
"serviceRole": "rancher-service-role",
"subnets": [ 2 items
"subnet-0369125b57d0db817",
"subnet-0ee419315dbccbed3"
],
"tags": {
"MaintenanceOwner": "FOOBAR",
},
"type": "/v3/schemas/eksClusterConfigSpec"
},
"enableClusterAlerting": false,
"enableClusterMonitoring": false,
"enableNetworkPolicy": null,
"internal": false,
"localClusterAuthEndpoint": {
"enabled": false,
"type": "/v3/schemas/localClusterAuthEndpoint"
},
"type": "/v3/schemas/clusterSpec",
"windowsPreferedCluster": false
},
"authImage": "",
"baseType": "cluster",
"caCert": "certdata",
"capabilities": {
"loadBalancerCapabilities": {
"healthCheckSupported": false,
"type": "/v3/schemas/loadBalancerCapabilities"
},
"nodePoolScalingSupported": false,
"pspEnabled": false,
"type": "/v3/schemas/capabilities"
},
"capacity": {
"cpu": "40",
"memory": "255631928Ki",
"pods": "584"
},
"clusterTemplateId": null,
"clusterTemplateRevisionId": null,
"componentStatuses": [ 3 items
{
"conditions": [
{
"message": "ok",
"status": "True",
"type": "Healthy"
}
],
"name": "controller-manager",
"type": "/v3/schemas/clusterComponentStatus"
},
{
"conditions": [
{
"message": "{\"health\":\"true\"}",
"status": "True",
"type": "Healthy"
}
],
"name": "etcd-0",
"type": "/v3/schemas/clusterComponentStatus"
},
{
"conditions": [
{
"message": "ok",
"status": "True",
"type": "Healthy"
}
],
"name": "scheduler",
"type": "/v3/schemas/clusterComponentStatus"
}
],
"conditions": [ 17 items
{
"status": "True",
"type": "Pending"
},
{
"lastUpdateTime": "2021-09-15T15:20:22Z",
"status": "True",
"type": "Provisioned"
},
{
"lastUpdateTime": "2021-09-15T15:20:38Z",
"status": "True",
"type": "Waiting"
},
{
"lastUpdateTime": "2021-09-15T15:08:16Z",
"status": "True",
"type": "BackingNamespaceCreated"
},
{
"lastUpdateTime": "2021-09-15T15:08:16Z",
"status": "True",
"type": "DefaultProjectCreated"
},
{
"lastUpdateTime": "2021-09-15T15:08:16Z",
"status": "True",
"type": "SystemProjectCreated"
},
{
"lastUpdateTime": "2021-09-15T15:08:16Z",
"status": "True",
"type": "InitialRolesPopulated"
},
{
"lastUpdateTime": "2021-09-15T15:08:16Z",
"status": "True",
"type": "CreatorMadeOwner"
},
{
"lastUpdateTime": "2021-09-15T15:08:16Z",
"status": "True",
"type": "NoDiskPressure"
},
{
"lastUpdateTime": "2021-09-15T15:08:16Z",
"status": "True",
"type": "NoMemoryPressure"
},
{
"lastUpdateTime": "2021-09-15T15:27:32Z",
"status": "True",
"type": "Updated"
},
{
"lastUpdateTime": "2021-09-15T15:20:24Z",
"status": "False",
"type": "AlertingEnabled"
},
{
"lastUpdateTime": "2021-09-15T15:20:24Z",
"status": "True",
"type": "GlobalAdminsSynced"
},
{
"lastUpdateTime": "2021-09-15T15:20:38Z",
"status": "True",
"type": "Ready"
},
{
"lastUpdateTime": "2021-09-15T15:24:05Z",
"status": "True",
"type": "SystemAccountCreated"
},
{
"lastUpdateTime": "2021-09-15T15:24:07Z",
"status": "True",
"type": "AgentDeployed"
},
{
"lastUpdateTime": "2021-09-15T15:24:08Z",
"status": "False",
"type": "PrometheusOperatorDeployed"
}
],
"created": "2021-09-15T15:08:16Z",
"createdTS": 1631718496000,
"creatorId": "u-2q4ldi7vqs",
"defaultClusterRoleForProjectMembers": null,
"defaultPodSecurityPolicyTemplateId": null,
"description": "Terraform EKS cluster",
"desiredAgentImage": "",
"desiredAuthImage": "",
"dockerRootDir": "/var/lib/docker",
"driver": "EKS",
"eksConfig": {
"amazonCredentialSecret": "cattle-global-data:cc-rvkr5",
"displayName": "eksgpu",
"imported": false,
"kmsKey": "",
"kubernetesVersion": "1.20",
"loggingTypes": [ 5 items
"api",
"audit",
"authenticator",
"controllerManager",
"scheduler"
],
"nodeGroups": [ 2 items
{
"desiredSize": 2,
"diskSize": 20,
"ec2SshKey": "eks",
"gpu": false,
"imageId": null,
"instanceType": "m5d.4xlarge",
"labels": {
"size": "m5d.4xlarge"
},
"launchTemplate": null,
"maxSize": 10,
"minSize": 2,
"nodegroupName": "md5-4xlarge",
"requestSpotInstances": false,
"resourceTags": { },
"spotInstanceTypes": null,
"subnets": [ 2 items
"subnet-0369125b57d0db817",
"subnet-0ee419315dbccbed3"
],
"tags": {
"MaintenanceOwner": "FOOBAR",
},
"type": "/v3/schemas/nodeGroup",
"version": "1.20"
},
{
"desiredSize": 2,
"diskSize": 600,
"ec2SshKey": "eks",
"gpu": true,
"imageId": null,
"instanceType": "p2.xlarge",
"labels": {
"gpu": "true",
"size": "p2.xlarge"
},
"launchTemplate": null,
"maxSize": 10,
"minSize": 2,
"nodegroupName": "p2-xlarge",
"requestSpotInstances": false,
"resourceTags": { },
"spotInstanceTypes": null,
"subnets": [ 2 items
"subnet-0369125b57d0db817",
"subnet-0ee419315dbccbed3"
],
"tags": {
"AllocatedOwner": "FOOBAR",
},
"type": "/v3/schemas/nodeGroup",
"version": "1.20"
}
],
"privateAccess": true,
"publicAccess": false,
"publicAccessSources": [
"0.0.0.0/0"
],
"region": "us-east-2",
"secretsEncryption": false,
"securityGroups": [ 2 items
"sg-017e712e8a7950e53",
"sg-0fdfd2958bc1602f5"
],
"serviceRole": "rancher-service-role",
"subnets": [ 2 items
"subnet-0369125b57d0db817",
"subnet-0ee419315dbccbed3"
],
"tags": {
"MaintenanceOwner": "FOOBAR",
},
"type": "/v3/schemas/eksClusterConfigSpec"
},
"eksStatus": {
"managedLaunchTemplateID": "lt-0e4d0180c1a9abbe8",
"managedLaunchTemplateVersions": {
"md5-4xlarge": "2",
"p2-xlarge": "3"
},
"privateRequiresTunnel": false,
"securityGroups": [ 2 items
"sg-017e712e8a7950e53",
"sg-0fdfd2958bc1602f5"
],
"subnets": [ 2 items
"subnet-0369125b57d0db817",
"subnet-0ee419315dbccbed3"
],
"type": "/v3/schemas/eksStatus",
"upstreamSpec": {
"amazonCredentialSecret": "cattle-global-data:cc-rvkr5",
"displayName": "eksgpu",
"imported": false,
"kmsKey": "",
"kubernetesVersion": "1.20",
"loggingTypes": [ 5 items
"api",
"audit",
"authenticator",
"controllerManager",
"scheduler"
],
"nodeGroups": [ 2 items
{
"desiredSize": 2,
"diskSize": 20,
"ec2SshKey": "eks",
"gpu": false,
"imageId": null,
"instanceType": "m5d.4xlarge",
"labels": {
"size": "m5d.4xlarge"
},
"launchTemplate": null,
"maxSize": 10,
"minSize": 2,
"nodegroupName": "md5-4xlarge",
"requestSpotInstances": false,
"resourceTags": { },
"spotInstanceTypes": null,
"subnets": [ 2 items
"subnet-0369125b57d0db817",
"subnet-0ee419315dbccbed3"
],
"tags": {
"MaintenanceOwner": "FOOBAR",
},
"type": "/v3/schemas/nodeGroup",
"version": "1.20"
},
{
"desiredSize": 2,
"diskSize": 600,
"ec2SshKey": "eks",
"gpu": true,
"imageId": null,
"instanceType": "p2.xlarge",
"labels": {
"gpu": "true",
"size": "p2.xlarge"
},
"launchTemplate": null,
"maxSize": 10,
"minSize": 2,
"nodegroupName": "p2-xlarge",
"requestSpotInstances": false,
"resourceTags": { },
"spotInstanceTypes": null,
"subnets": [ 2 items
"subnet-0369125b57d0db817",
"subnet-0ee419315dbccbed3"
],
"tags": {
"MaintenanceOwner": "FOOBAR",
},
"type": "/v3/schemas/nodeGroup",
"version": "1.20"
}
],
"privateAccess": true,
"publicAccess": false,
"publicAccessSources": [
"0.0.0.0/0"
],
"region": "us-east-2",
"secretsEncryption": false,
"securityGroups": [ 2 items
"sg-017e712e8a7950e53",
"sg-0fdfd2958bc1602f5"
],
"serviceRole": "rancher-service-role",
"subnets": [ 2 items
"subnet-0369125b57d0db817",
"subnet-0ee419315dbccbed3"
],
"tags": {
"MaintenanceOwner": "FOOBAR",
},
"type": "/v3/schemas/eksClusterConfigSpec"
},
"virtualNetwork": ""
},
"enableClusterAlerting": false,
"enableClusterMonitoring": false,
"enableNetworkPolicy": false,
"fleetWorkspaceName": "fleet-default",
"gkeStatus": {
"privateRequiresTunnel": null,
"type": "/v3/schemas/gkeStatus",
"upstreamSpec": null
},
"id": "c-wm7tz",
"internal": false,
"istioEnabled": false,
"labels": {
"cattle.io/creator": "norman",
"fleet.cattle.io/cluster-name": "c-wm7tz",
"rancher.cattle.io/claimed-by-name": "c-wm7tz",
"rancher.cattle.io/claimed-by-namespace": "fleet-default"
},
"limits": {
"cpu": "200m",
"memory": "1540Mi",
"pods": "0"
},
"links": {
"apiServices": "…/v3/clusters/c-wm7tz/apiservices",
"clusterAlertGroups": "…/v3/clusters/c-wm7tz/clusteralertgroups",
"clusterAlertRules": "…/v3/clusters/c-wm7tz/clusteralertrules",
"clusterAlerts": "…/v3/clusters/c-wm7tz/clusteralerts",
"clusterCatalogs": "…/v3/clusters/c-wm7tz/clustercatalogs",
"clusterLoggings": "…/v3/clusters/c-wm7tz/clusterloggings",
"clusterMonitorGraphs": "…/v3/clusters/c-wm7tz/clustermonitorgraphs",
"clusterRegistrationTokens": "…/v3/clusters/c-wm7tz/clusterregistrationtokens",
"clusterRoleTemplateBindings": "…/v3/clusters/c-wm7tz/clusterroletemplatebindings",
"clusterScans": "…/v3/clusters/c-wm7tz/clusterscans",
"etcdBackups": "…/v3/clusters/c-wm7tz/etcdbackups",
"namespaces": "…/v3/clusters/c-wm7tz/namespaces",
"nodePools": "…/v3/clusters/c-wm7tz/nodepools",
"nodes": "…/v3/clusters/c-wm7tz/nodes",
"notifiers": "…/v3/clusters/c-wm7tz/notifiers",
"persistentVolumes": "…/v3/clusters/c-wm7tz/persistentvolumes",
"projects": "…/v3/clusters/c-wm7tz/projects",
"remove": "…/v3/clusters/c-wm7tz",
"self": "…/v3/clusters/c-wm7tz",
"shell": "wss://rancher.foo.domain.bar.com/v3/clusters/c-wm7tz?shell=true",
"storageClasses": "…/v3/clusters/c-wm7tz/storageclasses",
"subscribe": "…/v3/clusters/c-wm7tz/subscribe",
"templates": "…/v3/clusters/c-wm7tz/templates",
"tokens": "…/v3/clusters/c-wm7tz/tokens",
"update": "…/v3/clusters/c-wm7tz"
},
"localClusterAuthEndpoint": {
"enabled": false,
"type": "/v3/schemas/localClusterAuthEndpoint"
},
"name": "eksgpu",
"nodeCount": 4,
"nodeVersion": 0,
"provider": "eks",
"requested": {
"cpu": "840m",
"memory": "1340Mi",
"pods": "14"
},
"state": "active",
"transitioning": "no",
"transitioningMessage": "",
"type": "cluster",
"uuid": "4080e2c0-ffe8-4eb6-ba96-e6e8d3af6baf",
"version": {
"buildDate": "2021-07-31T00:29:12Z",
"compiler": "gc",
"gitCommit": "d886092805d5cc3a47ed5cf0c43de38ce442dfcb",
"gitTreeState": "clean",
"gitVersion": "v1.20.7-eks-d88609",
"goVersion": "go1.15.12",
"major": "1",
"minor": "20+",
"platform": "linux/amd64",
"type": "/v3/schemas/info"
},
"windowsPreferedCluster": false
}
```

**Comment by deniseschannon** [comment]
Note: This needs to be backported to 2.5.13 as well and needs a backport issue to track as part of it

**Comment by bentastic27** [comment]
A customer is hitting this. However, the issue ends up being a bit different. This user doesn't have access to the VPCs default security group, so when (what I'm assuming is the launch template) sees that the user doesn't have access to it, it bombs out with this:

> You do not have access to a default security group in VPC vpc-xxxx. Specify a security group, and try again

For most folks the clusters will finish building, but it appears that the VPCs default security group is used.

**Comment by annablender** [comment]
An EKS cluster will always create a default cluster security group https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html.

If when creating an EKS cluster in Rancher, you specify an additional security group(s), those security group(s) should show up in the AWS cluster configuration. 

I was unable to reproduce this issue on Rancher 2.6-head.

Steps
1. Run Rancher 2.6-head in goland
2. Create EKS cluster
3. Specify a custom VPC and two subnets within the same network
4. Select the all-open security group
5. Select Cluster configuration -> Networking in AWS and view the added security groups

![image](https://user-images.githubusercontent.com/12955547/153954598-43af79b3-e6e7-4df3-ad37-478581d981e1.png)

Additional security group is added.

This also means that the additional group was present on the EKS launch template.

**Comment by annablender** [comment]
My repro steps
1. Spin up an EKS single node downstream cluster with Kubernetes 1.20-21
2. On the Create page, select custom VPC and select two subnets. Security groups are only added to clusters in a VPC.
3. Add the *all-open* security group

![32df355d5e4b398b91e8a58f6568a229.png](:/62ffc9ec73e24dc4a7a738c1a89d770d)

4. After cluster becomes active, check 1) EKS Cluster configuration - Networking 2) node instance and 3) launch template for the security group you specified in Rancher. If not there, repro is successful.

I reproduced the issue on Rancher 2.6-head. Oddly enough, my additional security group showed up in the EKS cluster configuration, but not in the launch template or was added to the node instance.

Cluster config
![db2f04871b1562e54b193fe275296082.png](:/d68230f976a14e2d930ba50256d0467d)

Node instance (only has the default cluster security group `08187b740aa5fbd4f`)
![cc0f7b9bd902af3638883f235c45a020.png](:/c7780f1c7fba4001902af02cae53f8f2)

Launch template v2
![d9f3c17949833174f8a262b2a6aff583.png](:/b630623d7cfa411cbef28b0e5c9ee7f6)

That means the `eks-operator` is appending the security group when creating the cluster, but not when creating the launch template. Will submit a PR to fix this issue.

**Comment by annablender** [comment]
## Testing template

#### Root cause

Users were not seeing additional [security groups](https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html) that they added in Rancher show up in the EKS launch template or node instances on their cluster. This is because the eks-operator was adding security groups when creating a cluster, but not when creating a launch template.
 
#### What was fixed, or what changes have occurred

I added security groups to the launch template request in `eks-operator` https://github.com/rancher/eks-operator/blob/b7f0241ff8a6fd1dc6077bf1b88c74bc2633759c/controller/nodegroup.go#L125

#### Areas or cases that should be tested

Use security groups
* Create EKS single-node downstream cluster; specify custom VPC, subnets, and default security group. Tested on both * * * Kubernetes 1.20 and 1.21
* Check EKS cluster launch template v2 for security group
* Check EKS node instance for security group

No security group
* Create EKS single-node downstream cluster; specify standard VPC
* Check that provisioning was successful
 
#### What areas could experience regressions ?

Launch template config if the data fields passed to EKS are modified.
 
#### Are the repro steps accurate/minimal ?

Yes.

**Comment by sowmyav27** [comment]
**On 2.6.3 reproduced the issue:**

- Deployed an EKS cluster through UI.
**Launch Template:**
<img width="950" alt="Screen Shot 2022-02-23 at 8 26 18 AM" src="https://user-images.githubusercontent.com/26032343/155423805-326a631d-ca57-491c-9426-ea858ff25053.png">

**Instance:**
<img width="1073" alt="Screen Shot 2022-02-23 at 8 29 06 AM" src="https://user-images.githubusercontent.com/26032343/155423810-12e390ef-44f6-49e5-844a-e9dc67806b62.png">

**Cluster detail in EKS**
<img width="940" alt="Screen Shot 2022-02-23 at 8 28 15 AM" src="https://user-images.githubusercontent.com/26032343/155423811-982ac784-62b4-4641-af6d-30d2e39ec135.png">

**On 2.6-head commit id: `d4089da`**

**Comment by annablender** [comment]
@sowmyav27 Thank you for testing! I now know selecting a custom VPC, but not selecting a security group is a valid use case.

`@annablender Why is there a change in status of status of cluster here ?
`

This happened I believe because the invalid security group error caused the `eks-operator` to crash. The eks-operator is the operator that sends requests to the EKS API to provision nodes. Since it crashed, Rancher failed to completely provision the node group resulting in the 'must have at least one node group' error.

I've put in a PR with a fix.

**Comment by annablender** [comment]
## Testing template

#### Root cause

Missed an edge case where when you create a custom EKS cluster, you can select a custom VPC and not choose any security groups.
 
#### What was fixed, or what changes have occurred

Fixed case here https://github.com/rancher/eks-operator/blob/63884cd7cddaf45625ff7d192ba342ec07d3fa0d/controller/nodegroup.go#L108.

#### Areas or cases that should be tested

Use security groups
* Create EKS single-node downstream cluster; specify custom VPC, subnets, and default security group. Test on both Kubernetes 1.20 and 1.21
* Check EKS cluster launch template v2 for security group
* Check EKS node instance for security group

Standard VPC
* Create EKS single-node downstream cluster; specify standard VPC
* Check that provisioning is successful

Custom VPC, no security group
 * Create EKS single-node downstream cluster; specify custom VPC but don't select a security group
 * Check that provisioning is successful

#### What areas could experience regressions ?

Launch template config if the data fields passed to EKS are modified.

#### Are the repro steps accurate/minimal ?

Yes.

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `4df2214`**

**Scenario 1**
- Deploy an EKS cluster.
- Select custom VPC
- Do not select additional SG
- Create cluster. Cluster comes up Active
- There is no additional SG in cluster level/Cluster template

**Scenario 2**
- Deploy an EKS cluster.
- Select custom VPC
- Select an additional SG - `default`
- Add one node goup and select a Launch template from the dropdown
- Create cluster. Cluster comes up Active
- Cluster level shows the additional SG.
- But there is no SG in the cluster template.

@annablender is this expected? ^^^

**Comment by annablender** [comment]
Yes, that behavior is expected. If a user specifies a launch template in Rancher, we don't add anything/set values on it. It's the user's responsibility to add the configuration so if they just selected a launch template and didn't add the default SG then it won't show up on the template in EKS.

**Comment by empeekdev** [comment]
We still have this issue. We are not using custom launch templates, but Rancher still continue adding default EKS SG group and none from list of additional SGs. We are on Rancher 2.6.4

**Comment by empeekdev** [comment]
During creating of downstream cluster it shows that node groups will have only automatically generated SG, but after creation - it shows custom provided SGs. And as a result - all versions of launch templates have only instance types specified, and security group field is empty.

**Comment by annablender** [comment]
@empeekdev It sounds like you are seeing issue https://github.com/rancher/rancher/issues/38014. Our team decided that Rancher must have parity with vanilla EKS, and when adding custom security groups without a specified launch template, EKS adds all security groups at cluster level but only the auto-generated one to the nodes. Rancher works the same way. This is expected and has been fixed in rancher 2.6.5, so if you upgrade you will see the fix for this. Does this resolve your issue?

**Comment by ivankalyt-sb** [comment]
Hi @a-blender I am using Rancher 2.7(v2.7-ccf3425c44daca60b095d29e4174b92d023d9eda-head) and running into the same issue, where only Rancher created default security group is added to EC2(nodes) but not the extra SGs selected within Rancher
