### ISSUE TITLE
Istio airgap volume mount support

### ISSUE THREAD

**Issue by brendarearden** [rancher/rancher#34858]
**Issue**
To support Istio upgrades in an airgapped environment, the istio manifests are bundled into the https://github.com/rancher/istio-installer and served from nginx. Because the manifests are bundled into the Docker image, any Istio releases that are made out of band would not be supported for upgrades due to the image not existing in the Docker image. 

For example:
- we release `istio-1.10.4` and bundle all of the existing rancher supported istio releases into the `istio-1.10.4` istio installer image. This means the supported upgrade paths would include upgrades from `istio-1.7.3`, `istio-1.8.6`, and `istio-1.9.6`
- Then a security patch is release for the 1.9.x line and we make an OOB release for istio-1.9.8`
- If you are currently on 1.9.6, you would want to upgrade to 1.9.8. But once you are upgraded to 1.9.8, you would not be able to upgrade to 1.10.4 in an airgapped environment. 

**Potential Solutions**
1. Add a commented out volume mount in the rancher-istio chart so that a user can easily uncomment it and point to their existing volume mount that would contain the manifest file needed to complete the upgrade. We can't include the manifest in the chart directly because hostPaths are insecure and the file is too large for a configMap.
2. When we do OOB releases, re-release any versions that are part of the upgrade path to ensure the new istio-installer image has the required manifests 
3. Have a docs page that shows all of the possible airgap upgrade paths based on what images are bundled in with which istio versions - looking at the example above that would look like: if you are on 1.9.6, upgrade to 1.10.4 directly - do not upgrade to 1.9.8. 

**Related Issue**
https://github.com/rancher/rancher/issues/30842

**Comment by cbron** [comment]
Tentatively pushing this back into 2.6.1. If it's not ready in time then it will get pushed back again.

**Comment by brendarearden** [comment]
### Root cause 
When support was added for install / upgrading in air-gapped environment, [a list of specifically supported istio version](https://github.com/rancher/istio-installer/blob/04f05d569dc5b69fdd1d29fa2f799516c37eb0db/scripts/fetch_istio_releases.sh#L9) was added to the istio-installer docker image. This limits what versions a user can upgrade to, because the version of istio that is currently installed in their cluster has to be in the list. More flexibility is needed to improve upgrade scenarios for our users.

### What was fixed, or what changes have occurred 
A volume and volume mount was added to the istio-install-job - this is disabled by default, but it allows users to edit the volume mount and volume in the values.yaml. This will provide a way for users to mount an [ istio version tar (https://github.com/istio/istio/releases/download/1.11.4/istio-1.11.4-linux-amd64.tar.gz) to the file path that is used by the istio-installer to ensure a user can upgrade from any istio version. 

### Areas or cases that should be tested 
In an air-gapped environment, install a version of istio that is not listed in the [istio versions array ](https://github.com/rancher/istio-installer/blob/04f05d569dc5b69fdd1d29fa2f799516c37eb0db/scripts/fetch_istio_releases.sh#L9 ), setup a volume and volume mount with the tar for the version of istio that you have installed and upgrade to the latest version of istio. 

### What areas could experience regressions ? 
Install & upgrade

### Are the repro steps accurate/minimal ?
Yes: 

1. In an airgapped environment, install a version of istio that is not listed in the istio-installer image
2. Upgrade istio to the latest release that support air-gapped upgrade
3. See upgrade error

**Comment by brendarearden** [comment]
Available to test on v2.6.3-rc1

**Comment by anupama2501** [comment]
Re-opening as I'm still seeing the issue in air-gapped setup rancher v2.6.3-rc3

Steps:
- Install rancher in an air-gapped setup
- Create a custom cluster on v1.21.6 with 3 worker, 1 etcd, 1 cp
- Install istio 1.10.2 by adding the following images in the private registry:
```
istio/install-cni:1.10.2,
istio/pilot:1.10.2,istio/proxyv2:1.10.2,
ranchertest/mytestcontainer
```
- Update the values.yaml while installing istio to reflect the above values.
- Create a pod in the istio-system as follows:
```
apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image:ranchertest/mytestcontainer
    name: test-container
    volumeMounts:
    - mountPath: /opt/istio-releases/1.10.2/istio-1.10.2-linux-amd64.tar.gz
      name: rancher-istio-additional-image
  volumes:
  - name: rancher-istio-additional-image
    emptyDir: {}
```
- Copy the tar istio-1.10.2-linux-amd64.tar.gz to the mounted volume path
- Upgrade the istio app by adding the following details in values.yaml 
```
installer:
  debug:
    secondsSleep: 60
  releaseMirror:
    additionalIstioImage:
      enabled: false
      tag: 1.10.4
      volumeMountName: rancher-istio-additional-image
      volumes:
        - name: rancher-istio-additional-image
          emptyDir: {}
    enabled: false
```
- Upgrade the istio to the version 1.11.4 and see the error :
```
Upgrade version check passed: 1.10.2 -> 1.11.4.

info    Error: failed to generate Istio configs from file [/app/istio-base.yaml] for the current version: 1.11.4, error: Get "https://github.com/istio/istio/releases/download/1.11.4/istio-1.11.4-osx.tar.gz":

```

- Executed into the installer shell and do not see the mounted volume.

**Comment by brendarearden** [comment]
The changes have been reverted from the v2.6.3 release and will now be moved to v2.6.4

**Comment by vardhaman22** [comment]
I was able to reproduce the issue on rancher 2.6.3. The volume mount support is reverted so now this issue is also same as the related issue. https://github.com/rancher/rancher/issues/30842
The related issue was fixed by adding the required tars in istio-installer image.
Here the issue is with the versions which are not present in the our charts repo. so the root cause of the related issue and this issue is same just that our workaround works for the istio versions we have in our charts repo and not for others.

There was an upstream  issue related to this problem which was closed without any solution. but recently i confirmed that the issue with which we are concerned is fixed. https://github.com/istio/istio/issues/28995#issuecomment-1327121142
the fixed issue milestone was istio 1.13 so this problem does not occur with istio 1.13 and higher.

I confirmed it with rancher 2.6.9  and istio 1.14.1

**Steps**

1. Install rancher in an air-gapped setup
2. Install istio **1.13.5** in local cluster  by adding the following images in the private registry:
```
istio/install-cni:1.13.5, istio/pilot:1.13.5, istio/proxyv2:1.13.5
```
3. Update the values.yaml while installing istio to reflect the above values.
4. Upgrade the istio app by updating the values.yaml and changing the istio images back to 
```
....
....
  repository: rancher/mirrored-istio-install-cni
  tag: 1.14.1-distroless
...
proxy:
    repository: rancher/mirrored-istio-proxyv2
    tag: 1.14.1-distroless
  proxy_init:
    repository: rancher/mirrored-istio-proxyv2
    tag: 1.14.1-distroless
....
pilot:
  enabled: true
  repository: rancher/mirrored-istio-pilot
  tag: 1.14.1-distroless
```
 **Result** : Istio upgrade from 1.13.5 to 1.14.1 successful.
 
 @anupama2501  please verify.

**Comment by vivek-infracloud** [comment]
As per comment by @vardhaman22 [here](https://github.com/rancher/rancher/issues/34858#issuecomment-1333250257)
the issue was fixed upstream in istio v1.13. Hence validated if the upgrade is working or not in following way.

**Steps**

1. Install rancher 2.6.9  in an air-gapped setup
2. Install istio **1.13.5** in local cluster  by adding the following images in the private registry:
```
istio/install-cni:1.13.5, istio/pilot:1.13.5, istio/proxyv2:1.13.5
```
3. Update the values.yaml while installing istio to reflect the above values.
4. Upgrade the istio app by updating the values.yaml and changing the istio images back to 
```
....
....
  repository: rancher/mirrored-istio-install-cni
  tag: 1.14.1-distroless
...
proxy:
    repository: rancher/mirrored-istio-proxyv2
    tag: 1.14.1-distroless
  proxy_init:
    repository: rancher/mirrored-istio-proxyv2
    tag: 1.14.1-distroless
....
pilot:
  enabled: true
  repository: rancher/mirrored-istio-pilot
  tag: 1.14.1-distroless
```
 **Result** : Istio upgrade from 1.13.5 to 1.14.1 successful.

@ronhorton Istio upgrade was successful. Hence, if the above test steps are enough for validation, we can close this issue. Let me know.

**Comment by ronhorton** [comment]
@vivek-infracloud reviewed your steps - you're good to close this ticket
