### ISSUE TITLE
Rancher cannnot deploy k3s cluster on ARM because of incorrect binary

### ISSUE THREAD

**Issue by rkgupta76** [rancher/rancher#34966]
**Rancher Server Setup**
- Rancher version: v2.6.1-rc5
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: Self-signed certificate

**Information about the Cluster**
- Kubernetes version: v1.21.4+k3s1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

**Describe the bug**

When deploying K3s on Raspberry Pi (running SLE Micro 5.1) using Rancher v2.6.1-rc5 UI, k3s service does not start since the k3s binary is an x86-64 version rather than ARM aarch64 version

**To Reproduce**
 
- Have SLE Micro 5.1 deployed on Raspberry Pi
- Create a Custom Cluster from Rancher UI by selecting RKE2/K3s option
- Select Kubernetes version as v1.21.4+k3s1
- Copy and run the registration command on Raspberry Pi

**Result**
k3s cluster does not start because of the incorrect binary

**Expected Result**

K3s cluster should have been deployed successfully

**Screenshots**

**Additional context**
<!--Add any other context about the problem here.—>
k3s-slemicro-pi3b:~ # file /usr/local/bin/k3s
/usr/local/bin/k3s: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
[R261_K3s_Pi_deployment_issue.txt](https://github.com/rancher/rancher/files/7250222/R261_K3s_Pi_deployment_issue.txt)

**Comment by lgraziosi** [comment]
I have the same issue when I try to import a manually created k3s arm cluster on Rancher 2.6.2, since the agent doesn't even start with this log:  
`standard_init_linux.go:228: exec user process caused: exec format error`

**Comment by mmontecchi** [comment]
I have the same issue when I try to import a manually created k3s arm cluster (Raspberry Pi4 with openSUSE 15.3) on Rancher 2.6.2, since the agent doesn't even start with this log:
standard_init_linux.go:228: exec user process caused: exec format error

**Comment by dougmeek** [comment]
@rkgupta76 I'd recommend changing the title to say ARM instead of RPi. This issue affects more than just Pi, since anything else running ARM would also have this issue. I'm here to chime in and say I have the issue as well.

**Comment by rkgupta76** [comment]
> @rkgupta76 I'd recommend changing the title to say ARM instead of RPi. This issue affects more than just Pi, since anything else running ARM would also have this issue. I'm here to chime in and say I have the issue as well.

Done. Thanks for your input

**Comment by dougmeek** [comment]
@rkgupta76 did you intend to close this? It doesn't look like there was a PR associated and no workaround posted in here.

**Comment by rkgupta76** [comment]
> @rkgupta76 did you intend to close this? It doesn't look like there was a PR associated and no workaround posted in here.

No. I did not intend to close it. I am re-opening it.

**Comment by ncareau** [comment]
I believe this issue is still actual and should be left open. Thanks.

**Comment by rotecodefraktion** [comment]
Same problem here. 
error while staging: no child with platform linux/arm64 in index rancher/system-agent-installer-rke2:v1.21.10-rke2r2: failed to get image index.docker.io/rancher/system-agent-installer-rke2:v1.21.10-rke2r2"

**Comment by rajha-korithrien** [comment]
As of a week ago, we retried to do aarch64 based deployment of k3s via Rancher UI and it still fails in the same place. Sad times.

**Comment by rajha-korithrien** [comment]
This issue is still relevant.

**Comment by rajha-korithrien** [comment]
This is (I think) tracked in https://github.com/rancher/rancher/issues/34658
