### ISSUE TITLE
Unable to mount volumes on custom hardened and node driver vSphere cluster using CSI charts.

### ISSUE THREAD

**Issue by vivek-shilimkar** [rancher/rancher#35173]
**Rancher Server Setup**
- Rancher version: v2.6.1
- Installation option (Helm Chart):

**Information about the Cluster**
- Kubernetes version: v1.18.20
- Cluster Type (Local/Downstream): Downstream 
   - Custom hardened cluster. Used [this RKE template](https://rancher.com/docs/rancher/v2.6/en/security/rancher-2.5/1.6-hardening-2.5/#reference-hardened-rke-template-configuration) for provisioning, with **cloud_provider set to external**.

**Describe the bug**

- Redis/Cockroachdb pods fails to become active/running.
- CSI is able to provision the PVs according to PVC specs, but the PVs fail to mount to vSphere cluster nodes
- Recent Events of Pods shows following error.
```Unable to attach or mount volumes: unmounted volumes=[vol0], unattached volumes=[vol0 default-token-87m75]: timed out waiting for the condition```
- Log of `vsphere-csi-node` in `kube-system` namespace also shows an error. Log is attached in a file. 
[vsphere-csi-node.log](https://github.com/rancher/rancher/files/7370413/vsphere-csi-node.log)

**Steps To Reproduce**
 
- Provision a vSphere hardened cluster v1.18.20 with RKE v1.3.1 on ESXi7+ env.
- Install Rancher v2.6.1 on it using helm.
- Follow hardening guide to provision a downstream vSphere hardened custom cluster v1.18.20 with [this RKE template](https://rancher.com/docs/rancher/v2.6/en/security/rancher-2.5/1.6-hardening-2.5/#reference-hardened-rke-template-configuration) with **cloud_provider set to external**.
- Install vSphere CPI and CSI charts.
- Install a cocroachdb and/or Redis pod with storage set to 'Create Persistent Volume Claim'.

**Expected Result**

Redis/Cockroachdb pods become active in Rancher UI with persistent volume attached to it.

**Comment by deniseschannon** [comment]
With the recent changes of the team, I'd like this re-triaged for prioritization of when and who should fix it.

**Comment by vivek-infracloud** [comment]
The issue is also active on normal cluster as well.

- Rancher version - v2.6-head (772b2f0)
- CPI Chart version - (100.4.0+up1.2.2)
- CSI Chart version - (100.3.0+up2.5.1-rancher1)
- k8s Cluster version - v1.23.7-rancher1-1

Following error was seen.
`AttachVolume.Attach failed for volume "pvc-1b706249-db97-43fc-908b-f62f5788759d" : rpc error: code = Internal desc = failed to attach disk: "64b2b6c3-2a55-4d1d-aad6-c255f6c520ba" with node: "42081787-4de8-866e-abf1-b4744eebc332" err failed to attach cns volume: "64b2b6c3-2a55-4d1d-aad6-c255f6c520ba" to node vm: "VirtualMachine:vm-1016 [VirtualCenterHost: engqa-7-wrangler.fremont.rancherlabs.com, UUID: 42081787-4de8-866e-abf1-b4744eebc332, Datacenter: Datacenter [Datacenter: Datacenter:datacenter-3, VirtualCenterHost: engqa-7-wrangler.fremont.rancherlabs.com]]". fault: "(*types.LocalizedMethodFault)(0xc00076b340)({\n DynamicData: (types.DynamicData) {\n },\n Fault: (types.CnsFault) {\n BaseMethodFault: (types.BaseMethodFault) <nil>,\n Reason: (string) (len=16) \"VSLM task failed\"\n },\n LocalizedMessage: (string) (len=32) \"CnsFault error: VSLM task failed\"\n})\n". opId: "42c88fe8"`

**Comment by paynejacob** [comment]
We should test this on 2.6.5 with k8s 1.21 or later.  Given the age of the chart and Kubernetes version this issue may have been resolved by upstream or other rancher changes.

**Comment by rishabhmsra** [comment]
Validated on rancher v2.6-head(772b2f0)
- Provisioned a k8s v1.23.7-rancher1-1, vSphere node driver cluster.
- Installed CPI chart version 100.4.0+up1.2.2.
- Installed CSI chart version 100.3.0+up2.5.1-rancher1.
- Deployed workloads with storage and it came up active. PVs, PVCs got created successfully.

**Comment by doflamingo721** [comment]
**Validated this issue on Rancher 2.6-head**

Steps followed:
1. Provisioned a k8s v1.23.8-rancher1-1 vSphere node driver cluster.
2. Installed CPI chart version `100.4.0+up1.2.2`
3. Installed CSI chart version `100.3.0+up2.5.1-rancher1`
4. Created a redis deployment with storage set to 'Create Persistent Volume Claim'. The redis pods became active with persistent volume attached to it. 

**Note**: This issue was not validated on vsphere custom hardened cluster as the nodes were not getting registered to the cluster. The issue for the same has been logged [here](https://github.com/rancher/rancher/issues/38293)

**Comment by vivek-infracloud** [comment]
Validated again on rancher v2.6.7-rc3 and v2.6.6, and singlenode harden cluster. Issue is still active.

**Comment by samkulkarni20** [comment]
@vivek-infracloud & @doflamingo721 Tested this issue on `v2.6.7-rc3` & 2.6-head(https://github.com/rancher/rancher/commit/07ee5962e0da85c999d8ebb5fddc6fd427068682) resp. Here's a summary of where this issue currently stands:

**Node Driver (Non-hardened ofcourse) Single/Multi Node**
- The volumes do get mounted on these downstream clusters. Issue with this combination is resolved.

**Single node Hardened Custom cluster**
- The volumes fail to attach to cluster nodes & same errors as mentioned in the issue descriptions are observed.

**Multi node Hardened Custom cluster**
- Downstream cluster with this combination fails to register its nodes with Rancher. This is logged as a [separate issue](https://github.com/rancher/rancher/issues/38293).

**Comment by J-tt** [comment]
We ran into this issue, but it was caused by the VM running an older hardware compatibility version, and resolved by upgrading the hardware compatibility of the VMs in vSphere, and adjusting the VM template to match.

Worth checking for those experiencing the same

**Comment by vivek-infracloud** [comment]
@J-tt What type of cluster are you referring to?

**Comment by J-tt** [comment]
This was on a normal cluster, not hardened, as you mentioned you were experiencing the issues on both.

**Comment by vivek-infracloud** [comment]
@J-tt Okay. As per the latest analysis. Node driver cluster is working fine. Issue is active only on hardened cluster.

**Comment by snasovich** [comment]
@vivek-shilimkar , any chance you could retest it on 2.7.5 since it's been a while since the last update?
FYI @daviswill2 @Sahota1225

**Comment by vivek-shilimkar** [comment]
Re-tested the volume mount issue on custom hardened cluster, the issue is still active on rancher v2.7.5. I tested two combinations.

- k8s v1.23.16 :
  - CPI version : 102.1.0+up1.5.1
  - CSI version : 102.0.0+up2.6.2

- k8s v1.26.6 :
  - CPI version : 102.1.0+up1.5.1
  - CSI version : 102.0.0+up3.0.1

Issue is still active.

**Comment by jiaqiluo** [comment]
According to [the CSI documentation](https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/3.0/vmware-vsphere-csp-getting-started/GUID-0AB6E692-AA47-4B6A-8CEA-38B754E16567.html),  the `disk.EnableUUID` parameter must be enabled on each node(VM) participating in the Kubernetes cluster with vSphere. 

We can see that the `disk.EnableUUID=true` is set in the node template created via Rancher UI.

<img width="1219" alt="Screenshot 2023-07-18 at 11 41 15 AM" src="https://github.com/rancher/rancher/assets/6218999/64c69768-f9d6-4231-821b-99ba178adbaf">

<details>
<summary>nodeTemplate - Vsphere node </summary>

```
apiVersion: management.cattle.io/v3
kind: NodeTemplate
metadata:
  annotations:
    field.cattle.io/creatorId: u-pxem7w2jtj
    ownerBindingsCreated: "true"
  creationTimestamp: "2023-07-18T18:43:24Z"
  generateName: nt-
  generation: 1
  labels:
    cattle.io/creator: norman
  name: nt-b9h97
  namespace: cattle-global-nt
  resourceVersion: "22882658"
  uid: d64a3c95-95f7-4d96-a519-1bb2ebdbe728
spec:
  cloudCredentialName: cattle-global-data:cc-xrzhm
  displayName: jack-test-vsphere-1
  driver: vmwarevsphere
  engineInstallURL: https://releases.rancher.com/install-docker/24.0.sh
  engineRegistryMirror: []
  useInternalIpAddress: true
vmwarevsphereConfig:
  boot2dockerUrl: ""
  cfgparam:
  - disk.enableUUID=TRUE
  cloneFrom: ""
  cloudConfig: '#cloud-config'
  cloudinit: ""
  contentLibrary: ""
  cpuCount: "2"
  creationType: template
  customAttribute: []
  datacenter: ""
  datastore: ""
  datastoreCluster: ""
  diskSize: "20000"
  folder: ""
  hostsystem: ""
  memorySize: "2048"
  network: []
  os: linux
  pool: ""
  sshPassword: tcuser
  sshPort: "22"
  sshUser: docker
  sshUserGroup: staff
  tag: []
  vappIpallocationpolicy: ""
  vappIpprotocol: ""
  vappProperty: []
  vappTransport: ""
```

</details>


@vivek-shilimkar can you confirm if the `disk.EnableUUID` parameter is set on the VMs when you tested custom node clusters, and if not can you give it a try and share the findings?

**Comment by vivek-shilimkar** [comment]
@jiaqiluo Thanks for pointing out.
if the disk.EnableUUID=TRUE parameter is set on the VMs the volume mounts successfully. Hence closing this issue.

**Comment by snasovich** [comment]
Removing the milestone as there was not a fix applied - just misunderstanding of test setup.
