### ISSUE TITLE
docker-compose.yml mem_limit issue

### ISSUE THREAD

**Issue by DanielDent** [rancher/rancher#3554]
In docker-compose, a mem_limit of "512m" works. In rancher-compose, error messages are received unless the 512m value is expressed as an integer.

**Comment by deniseschannon** [comment]
This is an issue in docker/libcompose and would need to be filed in the docker/libcompose repo. 

https://github.com/docker/libcompose/blob/master/project/types.go#L194

I can keep this open for whenever it gets fixed in docker/libcompose and we sync with libcompose to just verify for sanity sake.

**Comment by joshwget** [comment]
This is now supported in libcompose (https://github.com/docker/libcompose/pull/427).

**Comment by maZahaca** [comment]
Do you have any progress here?

**Comment by Joeasaurus** [comment]
Hi, that milestone has gone but this is still an issue -- any news?

**Comment by carolynhu** [comment]
need to add a type of MemStringorInt like what in https://github.com/docker/libcompose

**Comment by deniseschannon** [comment]
Available in master and CLI v0.6.2-rc1

**Comment by soumyalj** [comment]
Tested on master using UI and CLI v0.6.2-rc2. Creation of services with mem_limit: "512m" or mem_limit: 512m or mem_limit: 536870912 is successful. Example below:
```
version: '2'
services:
  test3:
    cap_drop:
    - BLOCK_SUSPEND
    - CHOWN
    labels:
      io.rancher.container.pull_image: always
    tty: true
    hostname: rancherhost
    pid: host
    image: ubuntu:14.04.3
    cpu_shares: 256
    privileged: true
    stdin_open: true
    mem_limit: '512m' 
    cap_add:
    - AUDIT_CONTROL
    - AUDIT_WRITE
```
