### ISSUE TITLE
Intermittent user auth errors relating to "impersonation" ClusterRoles

### ISSUE THREAD

**Issue by armsnyder** [rancher/rancher#36096]
**Rancher Server Setup**
- Rancher version: v2.6.2
- Installation option (Docker install/Helm Chart): Helm chart on EKS cluster
- Proxy/Cert Details: Using nginx ingress-controller behind AWS NLB, with the nginx ingress handling TLS

**Information about the Cluster**
- Kubernetes version: v1.19.13
- Cluster Type (Local/Downstream): Imported (cluster is an EKS cluster)

**User Information**
- What is the role of the user logged in? Admin.
   
**Describe the bug**

A couple users have noticed intermittent authentication errors using the Kubernetes API. It is especially prevalent when browsing the rancher-monitoring Grafana due to number of API requests but occurs in the terminal as well.

The error message is:

```
Templating
Template variable service failed userextras.authentication.k9s.io "redacted@redacted.com" is forbidden: User "system:serviceaccount:cattle-impersonation-system:cattle-impersonation-u-redacted" cannot impersonate resource "userextras/username" in API group "authentication.k8s.io" at the cluster scope.
```

```json
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "userextras.authentication.k8s.io \"okta_user://redacted@redacted.com\" is forbidden: User \"system:serviceaccount:cattle-impersonation-system:cattle-impersonation-u-redacted\" cannot impersonate resource \"userextras/principalid\" in API group \"authentication.k8s.io\" at the cluster scope",
  "reason": "Forbidden",
  "details": {
    "name": "okta_user://redacted@redacted.com",
    "group": "authentication.k8s.io",
    "kind": "userextras"
  },
  "code": 403
}
```

**To Reproduce**

Set up Rancher using the Okta SAML2 auth provider using Rancher v2.6.2. Some users will experience this issue.

**Additional context**

We spent time investigating and discovered that the `cattle-impersonation-system:cattle-impersonation-u-redacted` ClusterRole mentioned in the error message had some empty `resourceNames` in the rules. The ClusterRole looked like:

```yaml
...
- apiGroups:
  - authentication.k8s.io
  resourceNames:
  - ""
  resources:
  - userextras/principalid
  verbs:
  - impersonate
- apiGroups:
  - authentication.k8s.io
  resourceNames:
  - ""
  resources:
  - userextras/username
  verbs:
  - impersonate
 ```

To mitigate the issue we tried deleting the impacted ClusterRole. When the user made another Kubernetes API call, the ClusterRole was recreated with correct data:

```yaml
...
- apiGroups:
  - authentication.k8s.io
  resourceNames:
  - okta_user://redacted@redacted.com
  resources:
  - userextras/principalid
  verbs:
  - impersonate
- apiGroups:
  - authentication.k8s.io
  resourceNames:
  - redacted@redacted.com
  resources:
  - userextras/username
  verbs:
  - impersonate
```

We then scanned the ClusterRoles for others that presented the same issue. There was one other ClusterRole which is continuously flipping between having the buggy `"resourceNames":[""]` rule value and having the values filled in, for the `userextras/username` and `userextras/principalid` rules. We can see the ClusterRole UID is not changing, but its resourceVersion is incrementing about once every 3 seconds. This suggests that Rancher or some agent is periodically updating the ClusterRole with invalid information.

This may not be relevant, but the affected cluster is running a `cattle-cluster-agent` deployment with two pods, using image `rancher/rancher-agent:v2.6.2`. One pod is 60 days old, and its logs are quiet. The second pod is 5 days old and is downloading Helm indices every 5 minutes. No error logs though.

**Comment by armsnyder** [comment]
Just adding that have tried mitigations such as:
- Redeploying the cattle-cluster-agent
- Redeploying Rancher itself

The issue is still present.

**Comment by andrew-landsverk-win** [comment]
I am experiencing this exact same issue after upgrading from Rancher 2.6.2 to 2.6.3. Rancher is hosted on RKE1, downstream clusters are MicroK8s 1.21.x.

**Comment by andrew-landsverk-win** [comment]
@cmurphy - I'm wondering if this is a regression of #34671 ? So far, the issue stays intermittent and doesn't get better after time.

**Comment by cmurphy** [comment]
@andrew-landsverk-win thanks for flagging me, this does look related to #34671.

@armsnyder are there any logs related to "impersonator" or "impersonation" in the rancher logs that looks related that you could include?

**Comment by cmurphy** [comment]
This should already be fixed by https://github.com/rancher/rancher/pull/35325 in v2.6.3. @armsnyder can you try upgrading to v2.6.3 and see if that resolves the issue?

**Comment by andrew-landsverk-win** [comment]
We are on v2.6.3 and we are getting intermittent auth errors. However, the error is weird:

```Error from server (NotFound): the server could not find the requested resource```

On subsequent attempts, the same call, `helm install --upgrade` works perfectly fine.

What sort of other information or logs would you need? We didn't have these errors on 2.6.2, but they started as soon as we upgraded to 2.6.3.

Rancher itself is running on an RKE1 3 node cluster with CentOS 7. Downstream cluster is Microk8s, also on CentOS 7.

**Comment by cmurphy** [comment]
@andrew-landsverk-win that error doesn't look like an auth error and doesn't appear to be related to impersonation, can you provide any logs or errors that show it to be related to the issue that @armsnyder described? The issue of resource names in the clusterrole being set to `""` should be addressed by the PR above, if you are experiencing something else then could you log a different issue?

**Comment by andrew-landsverk-win** [comment]
I can do that once I gather some more information.

**Comment by anupama2501** [comment]
I'm not able to reproduce the issue on v2.6.2:

- creating an eks v2 cluster version 1.19
- Installed monitoring
- Enabled okta auth provider and added a few users in the cluster as owners and members
- Logged in as the cluster owner and cluster member
- Tried to access the monitoring graphs and don't hit the issue mentioned in the ticket.

**Comment by cmurphy** [comment]
This is hard to reproduce because it is intermittent and probably has to do with the number of users making requests. One way to check the changed behavior could be to check the clusterrole on v2.6.2 vs v2.6.3. On v2.6.2, an impersonation clusterrole might be created with `""` as the resourcename for userextras/principalid and userextras/username, e.g.

```
$ kubectl get clusterrole cattle-impersonation-u-njjlihcxhp -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2022-02-25T19:12:18Z"
  labels:
    authz.cluster.cattle.io/impersonator: "true"
    cattle.io/creator: norman
  name: cattle-impersonation-u-njjlihcxhp
  resourceVersion: "2352"
  uid: b3e96d00-8a4c-46f5-9e05-c6ac5478ec58
rules:
- apiGroups:
  - ""
  resourceNames:
  - u-njjlihcxhp
  resources:
  - users
  verbs:
  - impersonate
- apiGroups:
  - ""
  resourceNames:
  - shibboleth_group://janitor@samltest.id
  - system:authenticated
  - system:cattle:authenticated
  resources:
  - groups
  verbs:
  - impersonate
- apiGroups:
  - authentication.k8s.io
  resourceNames:
  - ""
  resources:
  - userextras/principalid
  verbs:
  - impersonate
- apiGroups:
  - authentication.k8s.io
  resourceNames:
  - ""
  resources:
  - userextras/username
  verbs:
  - impersonate
```

On v2.6.3, either the rules with empty resource name should be omitted from the list, or the resourcename should be populated:

```
$ kubectl get clusterrole cattle-impersonation-u-njjlihcxhp -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2022-02-25T19:12:18Z"
  labels:
    authz.cluster.cattle.io/impersonator: "true"
    cattle.io/creator: norman
  name: cattle-impersonation-u-njjlihcxhp
  resourceVersion: "3260"
  uid: b3e96d00-8a4c-46f5-9e05-c6ac5478ec58
rules:
- apiGroups:
  - ""
  resourceNames:
  - u-njjlihcxhp
  resources:
  - users
  verbs:
  - impersonate
- apiGroups:
  - ""
  resourceNames:
  - shibboleth_group://janitor@samltest.id
  - system:authenticated
  - system:cattle:authenticated
  resources:
  - groups
  verbs:
  - impersonate
- apiGroups:
  - authentication.k8s.io
  resourceNames:
  - local://u-njjlihcxhp
  - shibboleth_user://morty
  resources:
  - userextras/principalid
  verbs:
  - impersonate
- apiGroups:
  - authentication.k8s.io
  resourceNames:
  - morty
  resources:
  - userextras/username
  verbs:
  - impersonate
```

**Comment by anupama2501** [comment]
Reproduced on 2.6.2:

- Enabled github auth in the rancher server
- As an admin created an rke1 cluster and added a user as cluster owner 
- logged in as the user and via the kubectl file :

k get nodes --> added userextras/principalid and userextras/username resources to the cluster role.
k get clusterrole cattle-impersonation-u-laykaihuqa -o yaml
```
rules:
- apiGroups:
  - ""
  resourceNames:
  - u-laykaihuqa
  resources:
  - users
  verbs:
  - impersonate
- apiGroups:
  - ""
  resourceNames:
  - system:authenticated
  - system:cattle:authenticated
  resources:
  - groups
  verbs:
  - impersonate
- apiGroups:
  - authentication.k8s.io
  resourceNames:
  - ""
  resources:
  - userextras/principalid
  verbs:
  - impersonate
- apiGroups:
  - authentication.k8s.io
  resourceNames:
  - ""
  resources:
  - userextras/username
  verbs:
  - impersonate
```
Upgraded the rancher server to v2.6-head e93a53c and verified the resource names are updated:
```rules:
- apiGroups:
  - ""
  resourceNames:
  - u-laykaihuqa
  resources:
  - users
  verbs:
  - impersonate
- apiGroups:
  - ""
  resourceNames:
  - system:authenticated
  - system:cattle:authenticated
  resources:
  - groups
  verbs:
  - impersonate
- apiGroups:
  - authentication.k8s.io
  resourceNames:
  - <redacted>
  resources:
  - userextras/principalid
  verbs:
  - impersonate
- apiGroups:
  - authentication.k8s.io
  resourceNames:
  - <redacted>
  resources:
  - userextras/username
  verbs:
  - impersonate

```


Verified the same on a fresh installed cluster as well on v2.6-head e93a53c

**Comment by WolfspiritM** [comment]
As this has been closed is this problem fixed? Cause with rancher v2.6.3-patch1 we're still having this problem every now and then which is really annoying:

```
Failed to load logs: userextras.authentication.k8s.io "local://user-jnbma" is forbidden: User "system:serviceaccount:cattle-impersonation-system:cattle-impersonation-user-jnbma" cannot impersonate resource "userextras/principalid" in API group "authentication.k8s.io" at the cluster scope
```

**Comment by cbron** [comment]
Can you provide any additional details related to the error, including what version you upgraded from, the underlying and downstream k8s version, and role of the user.

**Comment by WolfspiritM** [comment]
@cbron I think I found the issue just a few minutes ago but I'm not sure if this is considered a bug or not.
After setting up rancher I've created a kubeconfig for the default admin user and used that locally with lens. I've then set up Azure AD login which caused my Azure AD Account to be mapped to the default admin user. I did not created a new kubeconfig afterwards and just kept using the one I had.

When inspecting the clusterrole system:serviceaccount:cattle-impersonation-system:cattle-impersonation-user-jnbma I noticed that the "userextras/principalid" resource kept adding and removing the "local://user-jnbma" and the "azuread_user://..." principalid every few seconds. I guess that depends on which token is used and where. (e.g. when using rancher directly with azuread login it added azuread and when using the local token it removed azuread and added the local user.

It seems like both logins have been fighting over the permissions.

I've now created a new kubeconfig token and the problem is fixed with only the "azuread_user://..." principal in the clusterrole.

The infos you requested: Underlaying and downstream cluster are both v1.21.8+rke2r1. I've made the update about 4 weeks ago from v2.6.3 to v2.6.3-patch1 and I think it was v2.6.2 before that but I'm not sure right now.

**Comment by cmurphy** [comment]
Thanks for the details @WolfspiritM, I was able to reproduce the issue and find a solution.

For QA:

### Root cause

The CRTB and PRTB controllers in Rancher and the request proxy handler both control impersonation but were working from different information, causing the rules in the generated ClusterRole to flap.
 
### What was fixed, or what changes have occurred
 
The impersonation module now only uses UserAttributes to generate the ClusterRole rules.

### Areas or cases that should be tested
 
Use an auth provider with a downstream cluster. The impersonation clusterrole should include rules for `userextras/principalid` and `userextras/username` before the user makes any proxied request, and should not change unless the auth provider is changed.

### What areas could experience regressions?

Using an auth provider
 
### Are the repro steps accurate/minimal?

Reproducing the exact issue causing the login failure will still be difficult without having a high load, but you can see the cause of that issue with these steps:

1. Import a downstream cluster.
2. Add an auth provider (I used github)
3. Check the impersonation ClusterRole for the admin user. Use the original kubeconfig for the original admin user on the cluster, NOT a kubeconfig downloaded from Rancher. There should be two rules, one for users and one for groups.
4. Download the kubeconfig for the admin user from Rancher. Use that downloaded kubeconfig to make any request (e.g. `kubectl get node`)
5. Check the clusterrole again. It will now have four rules, with the last two being for `userextras/principalid` and `userextras/username`.
6. Wait a few minutes. Using the original kubeconfig again, check the clusterrole again. It will have reverted back to only having two rules.

**Comment by danielllek** [comment]
I'm experiencing the same issue 5-10 times a day:

I'm creating user in the beginning of test. This user is later used for running tests - and every time `impersonation` fails, tests also fail, giving false positives.

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

## Reproduction Environment

| Component                 | Version / Type                                      |
| ------------------------- | --------------------------------------------------- |
| Rancher version           | 2.6.3                                               |
| Installation option       | Helm high availability (in AWS)                     |
| RKE binary version used   | v1.3.3                                              |
| If Helm Chart k8s cluster | v1.21.7                                             |
| Cert Details              | ingress.tls.source=secret (certificates from files) |
| Docker version            | 20.10.7, build f0df350                              |
| Helm version              | v2.16.8-rancher1                                    |
| Downstream cluster type   | Imported RKE1                                       |
| Downstream K8s version    | v1.21.7                                             |
| Logged in user role       | OpenLDAP Administrator                              |
| Browser type              | Google Chrome                                       |
| Browser version           | 100.0.4896.127 (Official Build) (x86_64)            |

**ADDITIONAL SETUP**

Helm installation commands:

```shell
kubectl create namespace cattle-system
```

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$REDACTED_ADD_YOUR_OWN \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=secret \
  --version 2.6.3
```

```shell
kubectl -n cattle-system create secret tls tls-rancher-ingress \
  --cert=tls.crt \
  --key=tls.key
```

## Reproduction steps

1. Create a separate RKE cluster to import into Rancher using RKE v1.3.3
2. Import the RKE cluster into Rancher
   - Starting from the **default** homepage `/dashboard/home`
   - Click `hamburger menu` -> `Cluster Management` -> `Import Existing` -> `Generic` -> fill out the `Cluster: Import Generic` form
   - Cluster Name: `my-imported-rke-cluster`
   - Click `Create` 
   - Copy the registration `kubectl` command & run that against your standalone RKE cluster
3. Add an `Auth Provider` to Rancher (OpenLDAP)
4. Check the impersonation ClusterRole for the admin user **on the imported cluster**. **Use the original kubeconfig for the original admin user on the standalone imported RKE cluster**, `NOT` a kubeconfig downloaded from Rancher. There should be two rules, one for users and one for groups.
   - Lookup the Administrator user ID
     - `hamburger menu` -> `Users & Authentication` -> note down the admin user ID
   - **USING THE ORIGINAL KUBECONFIG FILE FROM THE STANDALONE RKE CLUSTER** run the following commands
   - `kubectl get clusterroles | grep impersonation` -> copy the clusterrole with the admin user ID
   - `kubectl get clusterrole $REPLACE_WITH_YOUR_CLUSTER_ROLE_FROM_STEP_ABOVE -o yaml`
   - See the screenshot below labeled `A1`



![001-a1](https://user-images.githubusercontent.com/40877149/164110451-66e1f0ce-a553-4d23-9f27-ae3ee9d631d3.png)

5. You'll get back the ClusterRole yaml with only two rules

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2022-04-19T21:07:50Z"
  labels:
    authz.cluster.cattle.io/impersonator: "true"
    cattle.io/creator: norman
  name: cattle-impersonation-user-gjh2g
  resourceVersion: "3888"
  uid: <REDACTED>
rules:
- apiGroups:
  - ""
  resourceNames:
  - user-gjh2g
  resources:
  - users
  verbs:
  - impersonate
- apiGroups:
  - ""
  resourceNames:
  - system:authenticated
  - system:cattle:authenticated
  resources:
  - groups
  verbs:
  - impersonate
```

6. As admin download the kubeconfig file for the imported RKE1 cluster, `my-imported-rke-cluster` via the Rancher UI 
7. Use that downloaded kubeconfig to make any request (e.g. `kubectl get nodes`)
8. Now run the following command using the kubeconfig just downloaded from step `#7`

```shell
`kubectl get clusterrole $REPLACE_WITH_YOUR_CLUSTER_ROLE_FROM_STEP_ABOVE -o yaml`
```

9. Now you'll see four rules

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2022-04-19T21:07:50Z"
  labels:
    authz.cluster.cattle.io/impersonator: "true"
    cattle.io/creator: norman
  name: cattle-impersonation-user-gjh2g
  resourceVersion: "6287"
  uid: <REDACTED>
rules:
- apiGroups:
  - ""
  resourceNames:
  - user-gjh2g
  resources:
  - users
  verbs:
  - impersonate
- apiGroups:
  - ""
  resourceNames:
  - openldap_group://<REDACTED>
  - openldap_group://<REDACTED>
  - system:authenticated
  - system:cattle:authenticated
  resources:
  - groups
  verbs:
  - impersonate
- apiGroups:
  - authentication.k8s.io
  resourceNames:
  - openldap_user://<REDACTED>
  resources:
  - userextras/principalid
  verbs:
  - impersonate
- apiGroups:
  - authentication.k8s.io
  resourceNames:
  - <REDACTED>
  resources:
  - userextras/username
  verbs:
  - impersonate

```

## Additional Info

## RESULTS

#### :white_check_mark: Expected
Using the original kubeconfig the expected four rules are present

#### :x:Actual
Using the original kubeconfig the expected two rules are present

<hr>
  
## Validation Environment

| Component                 | Version / Type                                                                                |
| ------------------------- | --------------------------------------------------------------------------------------------- |
| Rancher version           | v2.6-c8114a946563c4ca902881de703c6e4b55b72cb5-head                                            |
| Rancher commit link       | [c8114a9](https://github.com/rancher/rancher/commit/c8114a946563c4ca902881de703c6e4b55b72cb5) |
| Installation option       | Helm high availability (in AWS)                                                               |
| RKE binary version used   | v1.3.8                                                                                        |
| If Helm Chart k8s cluster | v1.22.7                                                                                       |
| Cert Details              | ingress.tls.source=secret (certificates from files)                                           |
| Docker version            | 20.10.7, build f0df350                                                                        |
| Helm version              | v2.16.8-rancher1                                                                              |
| Downstream cluster type   | Imported RKE1                                                                                 |
| Downstream K8s version    | v1.22.7                                                                                       |
| Logged in user role       | OpenLDAP Administrator                                                                        |
| Browser type              | Google Chrome                                                                                 |
| Browser version           | 100.0.4896.127 (Official Build) (x86_64)                                                      |

**ADDITIONAL SETUP**

Helm installation commands:

```shell
kubectl create namespace cattle-system
```

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$REDACTED_ADD_YOUR_OWN \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=secret \
  --set rancherImageTag=v2.6-head
```

```shell
kubectl -n cattle-system create secret tls tls-rancher-ingress \
  --cert=tls.crt \
  --key=tls.key
```

## Validation steps

1. Create a separate RKE cluster to import into Rancher using RKE v1.3.8
2. Import the RKE cluster into Rancher
   - Starting from the **default** homepage `/dashboard/home`
   - Click `hamburger menu` -> `Cluster Management` -> `Import Existing` -> `Generic` -> fill out the `Cluster: Import Generic` form
   - Cluster Name: `my-imported-rke-cluster`
   - Click `Create` 
   - Copy the registration `kubectl` command & run that against your standalone RKE cluster
3. Add an `Auth Provider` to Rancher (OpenLDAP)
4. Check the impersonation ClusterRole for the admin user **on the imported cluster**. **Use the original kubeconfig for the original admin user on the standalone imported RKE cluster**, `NOT` a kubeconfig downloaded from Rancher. There should be two rules, one for users and one for groups.
   - Lookup the Administrator user ID
     - `hamburger menu` -> `Users & Authentication` -> note down the admin user ID
   - **USING THE ORIGINAL KUBECONFIG FILE FROM THE STANDALONE RKE CLUSTER** run the following commands
   - `kubectl get clusterroles | grep impersonation` -> copy the clusterrole with the admin user ID
   - `kubectl get clusterrole $REPLACE_WITH_YOUR_CLUSTER_ROLE_FROM_STEP_ABOVE -o yaml`

  
## Additional Info

## RESULTS

#### :white_check_mark: Expected
Using the original kubeconfig the expected four rules are present

#### :white_check_mark:Actual
Using the original kubeconfig the expected four rules are present

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

## Reproduction Environment

| Component                 | Version / Type                                      |
| ------------------------- | --------------------------------------------------- |
| Rancher version           | 2.6.3                                               |
| Installation option       | Helm high availability (in AWS)                     |
| RKE binary version used   | v1.3.3                                              |
| If Helm Chart k8s cluster | v1.21.7                                             |
| Cert Details              | ingress.tls.source=secret (certificates from files) |
| Docker version            | 20.10.7, build f0df350                              |
| Helm version              | v2.16.8-rancher1                                    |
| Downstream cluster type   | Imported RKE1                                       |
| Downstream K8s version    | v1.21.7                                             |
| Logged in user role       | OpenLDAP Administrator                              |
| Browser type              | Google Chrome                                       |
| Browser version           | 100.0.4896.127 (Official Build) (x86_64)            |

**ADDITIONAL SETUP**

Helm installation commands:

```shell
kubectl create namespace cattle-system
```

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$REDACTED_ADD_YOUR_OWN \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=secret \
  --version 2.6.3
```

```shell
kubectl -n cattle-system create secret tls tls-rancher-ingress \
  --cert=tls.crt \
  --key=tls.key
```

## Reproduction steps

1. Create a separate RKE cluster to import into Rancher using RKE v1.3.3
2. Import the RKE cluster into Rancher
   - Starting from the **default** homepage `/dashboard/home`
   - Click `hamburger menu` -> `Cluster Management` -> `Import Existing` -> `Generic` -> fill out the `Cluster: Import Generic` form
   - Cluster Name: `my-imported-rke-cluster`
   - Click `Create` 
   - Copy the registration `kubectl` command & run that against your standalone RKE cluster
3. Add an `Auth Provider` to Rancher (OpenLDAP)
4. Check the impersonation ClusterRole for the admin user **on the imported cluster**. **Use the original kubeconfig for the original admin user on the standalone imported RKE cluster**, `NOT` a kubeconfig downloaded from Rancher. There should be two rules, one for users and one for groups.
   - Lookup the Administrator user ID
     - `hamburger menu` -> `Users & Authentication` -> note down the admin user ID
   - **USING THE ORIGINAL KUBECONFIG FILE FROM THE STANDALONE RKE CLUSTER** run the following commands
   - `kubectl get clusterroles | grep impersonation` -> copy the clusterrole with the admin user ID
   - `kubectl get clusterrole $REPLACE_WITH_YOUR_CLUSTER_ROLE_FROM_STEP_ABOVE -o yaml`
   - See the screenshot below labeled `A1`



![001-a1](https://user-images.githubusercontent.com/40877149/164110841-ade4d518-2775-4d74-ab30-47af69420678.png)

5. You'll get back the ClusterRole yaml with only two rules

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2022-04-19T21:07:50Z"
  labels:
    authz.cluster.cattle.io/impersonator: "true"
    cattle.io/creator: norman
  name: cattle-impersonation-user-gjh2g
  resourceVersion: "3888"
  uid: <REDACTED>
rules:
- apiGroups:
  - ""
  resourceNames:
  - user-gjh2g
  resources:
  - users
  verbs:
  - impersonate
- apiGroups:
  - ""
  resourceNames:
  - system:authenticated
  - system:cattle:authenticated
  resources:
  - groups
  verbs:
  - impersonate
```

6. As admin download the kubeconfig file for the imported RKE1 cluster, `my-imported-rke-cluster` via the Rancher UI 
7. Use that downloaded kubeconfig to make any request (e.g. `kubectl get nodes`)
8. Now run the following command using the kubeconfig just downloaded from step `#7`

```shell
`kubectl get clusterrole $REPLACE_WITH_YOUR_CLUSTER_ROLE_FROM_STEP_ABOVE -o yaml`
```

9. Now you'll see four rules

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2022-04-19T21:07:50Z"
  labels:
    authz.cluster.cattle.io/impersonator: "true"
    cattle.io/creator: norman
  name: cattle-impersonation-user-gjh2g
  resourceVersion: "6287"
  uid: <REDACTED>
rules:
- apiGroups:
  - ""
  resourceNames:
  - user-gjh2g
  resources:
  - users
  verbs:
  - impersonate
- apiGroups:
  - ""
  resourceNames:
  - openldap_group://<REDACTED>
  - openldap_group://<REDACTED>
  - system:authenticated
  - system:cattle:authenticated
  resources:
  - groups
  verbs:
  - impersonate
- apiGroups:
  - authentication.k8s.io
  resourceNames:
  - openldap_user://<REDACTED>
  resources:
  - userextras/principalid
  verbs:
  - impersonate
- apiGroups:
  - authentication.k8s.io
  resourceNames:
  - <REDACTED>
  resources:
  - userextras/username
  verbs:
  - impersonate

```

## Additional Info

## RESULTS

#### :white_check_mark: Expected
Using the original kubeconfig the expected four rules are present

#### :x:Actual
Using the original kubeconfig the expected two rules are present

<hr>
  
## Validation Environment

| Component                 | Version / Type                                                                                |
| ------------------------- | --------------------------------------------------------------------------------------------- |
| Rancher version           | v2.6-c8114a946563c4ca902881de703c6e4b55b72cb5-head                                            |
| Rancher commit link       | [c8114a9](https://github.com/rancher/rancher/commit/c8114a946563c4ca902881de703c6e4b55b72cb5) |
| Installation option       | Helm high availability (in AWS)                                                               |
| RKE binary version used   | v1.3.8                                                                                        |
| If Helm Chart k8s cluster | v1.22.7                                                                                       |
| Cert Details              | ingress.tls.source=secret (certificates from files)                                           |
| Docker version            | 20.10.7, build f0df350                                                                        |
| Helm version              | v2.16.8-rancher1                                                                              |
| Downstream cluster type   | Imported RKE1                                                                                 |
| Downstream K8s version    | v1.22.7                                                                                       |
| Logged in user role       | OpenLDAP Administrator                                                                        |
| Browser type              | Google Chrome                                                                                 |
| Browser version           | 100.0.4896.127 (Official Build) (x86_64)                                                      |

**ADDITIONAL SETUP**

Helm installation commands:

```shell
kubectl create namespace cattle-system
```

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$REDACTED_ADD_YOUR_OWN \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=secret \
  --set rancherImageTag=v2.6-head
```

```shell
kubectl -n cattle-system create secret tls tls-rancher-ingress \
  --cert=tls.crt \
  --key=tls.key
```

## Validation steps

1. Create a separate RKE cluster to import into Rancher using RKE v1.3.8
2. Import the RKE cluster into Rancher
   - Starting from the **default** homepage `/dashboard/home`
   - Click `hamburger menu` -> `Cluster Management` -> `Import Existing` -> `Generic` -> fill out the `Cluster: Import Generic` form
   - Cluster Name: `my-imported-rke-cluster`
   - Click `Create` 
   - Copy the registration `kubectl` command & run that against your standalone RKE cluster
3. Add an `Auth Provider` to Rancher (OpenLDAP)
4. Check the impersonation ClusterRole for the admin user **on the imported cluster**. **Use the original kubeconfig for the original admin user on the standalone imported RKE cluster**, `NOT` a kubeconfig downloaded from Rancher
   - Lookup the Administrator user ID
     - `hamburger menu` -> `Users & Authentication` -> note down the admin user ID
   - **USING THE ORIGINAL KUBECONFIG FILE FROM THE STANDALONE RKE CLUSTER** run the following commands
   - `kubectl get clusterroles | grep impersonation` -> copy the clusterrole with the admin user ID
   - `kubectl get clusterrole $REPLACE_WITH_YOUR_CLUSTER_ROLE_FROM_STEP_ABOVE -o yaml`

  
## Additional Info

## RESULTS

#### :white_check_mark: Expected
Using the original kubeconfig the expected four rules are present

#### :white_check_mark:Actual
Using the original kubeconfig the expected four rules are present

**Comment by livenson** [comment]
This issue still happens for me after upgrade to 2.6.6 from 2.5.12. Doesn't feel like this is a solved case.

**Comment by vkruoso** [comment]
@livenson looks like this will be available in v2.6.7.

**Comment by TeroPihlaja** [comment]
I tried updating to v2.6.6 and even to v2.6.7-rc6 and seems that this issue is somewhat present there also.

Our Terraform is getting this error:
```userextras.authentication.k8s.io "local://u-g94lb" is forbidden: User "system:serviceaccount:cattle-impersonation-system:cattle-impersonation-u-g94lb" cannot impersonate resource "userextras/principalid" in API group "authentication.k8s.io" at the cluster scope```

We have a mixed authentication in use with Azure AD and some local (service) accounts. The Terraform account is a Rancher local user.

The rules for ```userextras/principalid``` and ```userextras/username``` are added to the Azure AD account cattle-impersonation cluster roles but not for the local account cluster roles. Getting some Kubernetes resources then fails if the user is logged in using the local accounts.

Local user:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2022-08-03T06:52:38Z"
  labels:
    authz.cluster.cattle.io/impersonator: "true"
    cattle.io/creator: norman
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:authz.cluster.cattle.io/impersonator: {}
          f:cattle.io/creator: {}
      f:rules: {}
    manager: rancher
    operation: Update
    time: "2022-08-03T07:00:38Z"
  name: cattle-impersonation-u-g94lb
  resourceVersion: "128711398"
  uid: 323d4814-6b62-45f3-871a-bdb0f248479e
rules:
- apiGroups:
  - ""
  resourceNames:
  - u-g94lb
  resources:
  - users
  verbs:
  - impersonate
- apiGroups:
  - ""
  resourceNames:
  - system:authenticated
  - system:cattle:authenticated
  resources:
  - groups
  verbs:
  - impersonate
```

And an example of Azure AD user:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2022-01-05T12:38:39Z"
  labels:
    authz.cluster.cattle.io/impersonator: "true"
    cattle.io/creator: norman
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:authz.cluster.cattle.io/impersonator: {}
          f:cattle.io/creator: {}
      f:rules: {}
    manager: rancher
    operation: Update
    time: "2022-01-05T12:38:39Z"
  name: cattle-impersonation-u-nnm6jq6key
  resourceVersion: "128039023"
  uid: 9dd9886d-920d-4592-b8fe-88e5e16528e3
rules:
- apiGroups:
  - ""
  resourceNames:
  - u-nnm6jq6key
  resources:
  - users
  verbs:
  - impersonate
- apiGroups:
  - ""
  resourceNames:
  - azuread_group://<id>
...
  - azuread_group://<id>
  - system:authenticated
  - system:cattle:authenticated
  resources:
  - groups
  verbs:
  - impersonate
- apiGroups:
  - authentication.k8s.io
  resourceNames:
  - azuread_user://<id>
  resources:
  - userextras/principalid
  verbs:
  - impersonate
- apiGroups:
  - authentication.k8s.io
  resourceNames:
  - <username>
  resources:
  - userextras/username
  verbs:
  - impersonate
```

**Comment by cmurphy** [comment]
@TeroPihlaja there was a related issue with upgrades from <=v2.6.2 to <=v2.6.6 that was fixed in v2.6.7 https://github.com/rancher/rancher/issues/37894 - so you would have continued to see it in v2.6.6 but it should have gone away when you tried v2.6.7-rc6.

If you're still seeing this issue on v2.6.7, could you provide the output of the following commands on the local cluster

```
kubectl get userattributes u-g94lb -o yaml
kubectl get userattributes u-nnm6jq6key -o yaml
```

**Comment by jlunaq** [comment]
Is this issue still ongoing on version 2.6.8?

**Comment by suryatejaboorlu** [comment]
Upgraded from 2.6.4 to 2.6.8 and still found this issue. The administrator has to go and do "Refresh Group memberships" , which solves the issue.

**Comment by AlessioCasco** [comment]
We moved as well from `v2.6.4` to `v2.6.8` as @suryatejaboorlu and as result had two local users (used for helm within terraform) that were getting 403 to every call, unfortunately the "Refresh Group memberships" trick didn't work for us.
The fix was to log-in and then log-out into the rancher console with those local users and the issues dissapeared.

**Comment by brudnak** [comment]
# ✅ PASSED

## Reproduction Environment

#### Not required.

<hr>

## Validation Environment

| Component                        | Version / Type                                                                     |
|----------------------------------|------------------------------------------------------------------------------------|
| Rancher version                  | v2.6-2e0026699d7f3498979f9007a17b20668cb076ef-head                                 |
| Rancher commit link              | https://github.com/rancher/rancher/commit/2e0026699d7f3498979f9007a17b20668cb076ef |
| Installation option              | Helm (high availability)                                                           |
| If Helm Chart k8s cluster        | v1.24.4+k3s1                                                                       |
| Cert Details                     | Let's Encrypt / `traefik`                                                          |
| k3s ha external db               | Aurora MySQL 5.7.mysql_aurora.2.10.2                                               |
| Helm version                     | v2.16.8-rancher2                                                                   |
| Downstream cluster type          | RKE1 Linode                                                                        |
| Downstream K8s version           | v1.24.4-rancher1-1                                                                 |
| Authentication providers enabled | local                                                                              |
| Logged in user role              | Administrator setup & standard user as cluster owner                               |
| Browser type                     | Google Chrome                                                                      |
| Browser version                  | 105.0.5195.125 (Official Build) (x86_64)                                           |

### ADDITIONAL VALIDATION SETUP

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$URL_VAR \
  --set bootstrapPassword=$PASSWORD_VAR \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR \
  --set letsEncrypt.ingress.class=traefik \
  --set rancherImageTag=v2.6-head
```

## Validation steps

1. Create a new user
2. Add user as an owner on a non-local cluster
3. Log in as that user and generate a kubeconfig for the cluster
4. On the local cluster, delete the user's userattributes kubectl delete userattributes u-XXXX
5. Log out and log back in as admin
6. Click "refresh group membership" in the user management page for that user
7. User should still be able to authenticate to the downstream cluster with the downloaded kubeconfig
8. ExtraByProvider in userattribute resource should contain principalid and username for enabled providers

## Additional Info

## RESULTS

#### ✅ Expected
The user is still able to authenticate to the downstream cluster with the downloaded kubeconfig.

#### ✅ Actual
The user is still able to authenticate to the downstream cluster with the downloaded kubeconfig.


# Test Plan

<table>
    <tbody>
        <tr>
            <th>Test</th>
            <th>Steps</th>
            <th>Expected</th>
            <th>Actual & Pass/Fail</th>
        </tr>
        <tr>
            <td>Ensure that disabling/removing a user in an auth provider deactivates the user in Rancher as before this change</td>
            <td>
                <ol>
                    <li>Setup GitHub OAuth provider</li>
                    <li>add as cluster owner on a downstream cluster</li>
                    <li>remove the user from auth provider authorized user list</li>
                    <li>refresh group memberships</li>
                    <li>try using kubeconfig file</li>
                </ol>
            </td>
            <td>Expected: error: You must be logged in to the server (the server has asked for the client to provide credentials (get nodes))</td>
            <td>Actual: error: You must be logged in to the server (the server has asked for the client to provide credentials (get nodes))<br><br>Pass/Fail: ✅<code>PASS</code></td>
        </tr>
        <tr>
            <td>Ensure that removing GitHub OAuth user from the downstream cluster as a cluster owner revokes access</td>
            <td>
                <ol>
                    <li>Setup GitHub OAuth provider</li>
                    <li>add as cluster owner on a downstream cluster</li>
                    <li>remove the user as a cluster owner on the downstream</li>
                    <li>refresh group memberships</li>
                    <li>try using kubeconfig file</li>
                </ol>
            </td>
            <td>Expected: Error from server (Forbidden): {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-wrpls\" is forbidden: User \"u-k5s4w353m6\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)</td>
            <td>Actual: Error from server (Forbidden): {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-wrpls\" is forbidden: User \"u-k5s4w353m6\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)<br><br>Pass/Fail: ✅<code>PASS</code></td>
        </tr>
        <tr>
            <td>Test with Shibboleth auth provider</td>
            <td>
                <ol>
                    <li>Setup Shibboleth as an auth provider</li>
                    <li>Follow steps listed above in the main validation template</li>
                </ol>
            </td>
            <td>Expected: When following the main validation steps with Shibboleth as an auth provider. The user is still able to authenticate to the downstream cluster with the downloaded kubeconfig.</td>
            <td>Actual: When following the main validation steps with Shibboleth as an auth provider. The user is still able to authenticate to the downstream cluster with the downloaded kubeconfig.<br><br>Pass/Fail: ✅<code>PASS</code></td>
        </tr>
        <tr>
            <td>Test upgrading from v2.6.2 to v2.6-head</td>
            <td>
                <ol>
                    <li>Start with a 2.6.2 Rancher with auth enabled</li>
                    <li>Upgrade to Rancher v2.6-head</li>
                    <li>Follow the main validation steps listed above</li>
                </ol>
            </td>
            <td>Expected: The user is still able to authenticate to the downstream cluster with the downloaded kubeconfig.</td>
            <td>Actual: The user is still able to authenticate to the downstream cluster with the downloaded kubeconfig.<br><br>Pass/Fail: ✅<code>PASS</code></td>
        </tr>
    </tbody>
</table>

**Comment by cmurphy** [comment]
Release note template

Synopsis of issue: User attributes were not being refreshed correctly and sometimes became empty, which caused impersonation rules to be incorrect.
Resolved (or not): resolved
Versions affected: v2.6.7, v2.6.8

**Comment by andy812** [comment]
We've got the same issue on 2.7.0 :(

**Comment by jbilliau-rcd** [comment]
We are having this issue as well, updated from 2.6.9 to 2.6.11. All of our automated testing broke with the following error when we try to generate a new kubeconfig:

Error from server (InternalError): an error on the server ("unable to create impersonator account: error setting up impersonation for user u-hwltnppexi: failed to get secret for service account: cattle-impersonation-system/cattle-impersonation-u-hwltnppexi, error: resource name may not be empty") has prevented the request from succeeding

A retry of the job then succeeds. This never happened before 2.6.11.

**Comment by scottstout** [comment]
@cmurphy  @brudnak  Seeing the two reports above, should this ticket be reopened or you need a new ticket?

**Comment by jbilliau-rcd** [comment]
@samjustus So when we do platform changes (controller updates, new eks version, etc.), we run a suite of automated tests via a GitHub action. This worked flawlessly on 2.6.9; it basically builds clusters, joins them to Rancher, generates a kubeconfig, then uses that kubeconfig to auth with the cluster and run various tests. Below is the code we use:

```
package rancherconfig

import (
	"fmt"
	"os"

	"github.com/rancher/norman/clientbase"
	rancher3 "github.com/rancher/rancher/pkg/client/generated/management/v3"
)

func CreateKubeConfig() {
	token := os.Getenv("RANCHER_TOKEN")
	clusterId := os.Getenv("RANCHER_CLUSTER_ID")
	if token == "" || clusterId == "" {
		fmt.Print("Missing env variables RANCHER_TOKEN or RANCHER_CLUSTER_ID. Moving on with existing kubeconfig")
		return
	}
	client, err := rancher3.NewClient(&clientbase.ClientOpts{
		URL:      "https://rancher.xxxxx.zone/v3",
		TokenKey: token,
		Insecure: true,
	})
	if err != nil {
		panic(err.Error())
	}
	cluster, err := client.Cluster.ByID(clusterId)
	if err != nil {
		panic(err.Error())
	}
	kubeconfig, err := client.Cluster.ActionGenerateKubeconfig(cluster)
	if err != nil {
		panic(err.Error())
	}

	f, err := os.Create("/users/jbilliau/config-tester")
	if err != nil {
		panic(err.Error())
	}
	defer f.Close()

	_, err2 := f.WriteString(kubeconfig.Config)

	if err2 != nil {
		panic(err.Error())
	}

}
```

I tail the local Rancher logs as this code is run. On 2.6.9, I see this:

`rancher-76b549ffb7-tk2dl rancher 2023/03/14 15:42:14 [INFO] Creating token for user u-bjzkc
`
On 2.6.11, I see this:

`rancher-d4dbfb897-5r4j2 rancher 2023/03/13 17:07:50 [INFO] EnsureSecretForServiceAccount: waiting for secret [cattle-impersonation-u-hwltnppexi-token-hkt2l] to be populated with token`

Oddly enough, a simply retry of the job works, every time....not sure why. The cluster is in Rancher for a good 7-10 minutes before we even try this, so I can't see it as "hitting it too quickly".  We just rolled back to 2.6.9 and the issue is now fixed, so it's def 2.6.10 or 2.6.11 that broke "something". Let me know if this helps.

**Comment by jbilliau-rcd** [comment]
if I had to guess, this commit is what broke it? Is this in 2.6.11?

https://github.com/rancher/rancher/commit/8f4d60c2228de4672a469d07213778ce53df9433#diff-fe913e39db39d26629ffb0d1e83c60678ce415c81af03283120afeec3233f011

**Comment by jbilliau-rcd** [comment]
Actually @samjustus , never mind, it's still a problem. so I took the script, the error handling, all out of it. Went to the very basics....generate a kubeconfig, hit the cluster. It doesnt work the first time, EVER....but immediately rerunning works. Here is the exact thing I ran:

#makes kubeconfig
`➜  ~/git/k8s-tests/clusterFeatures/utils/runrancherconfig git:(main) ✗ go run .
`

#confirms it
```
➜  ~/git/k8s-tests/clusterFeatures/utils/runrancherconfig git:(main) ✗ cat /users/jbilliau/config-tester
apiVersion: v1
kind: Config
clusters:
- name: "tester62"
  cluster:
    server: "https://rancher.yyyyyyyyy/k8s/clusters/c-m-trwd9lfm"

users:
- name: "tester62"
  user:
    token: "kubeconfig-u-bjzkcqkk7h:xxxxxxxxxxxxxxx"


contexts:
- name: "tester62"
  context:
    user: "tester62"
    cluster: "tester62"

current-context: "tester62"
```

#apply some namespaces, fails
```
➜  ~/git/k8s-tests/clusterFeatures/utils/runrancherconfig git:(main) ✗ kubectl apply -f namespaces.yaml
Error from server (InternalError): an error on the server ("unable to create impersonator account: error setting up impersonation for user u-bjzkc: impersonation: error ensuring secret for service account cattle-impersonation-u-bjzkc: error ensuring secret for service account [cattle-impersonation-system:cattle-impersonation-u-bjzkc]: Operation cannot be fulfilled on serviceaccounts \"cattle-impersonation-u-bjzkc\": the object has been modified; please apply your changes to the latest version and try again") has prevented the request from succeeding
```

#apply some namespaces again, works
```
➜  ~/git/k8s-tests/clusterFeatures/utils/runrancherconfig git:(main) ✗ kubectl apply -f namespaces.yaml
namespace/moody-stable unchanged
namespace/moody-canary unchanged
namespace/sleep-stable unchanged
namespace/sleep-canary unchanged
namespace/sleep-stable-dnsproxy unchanged
namespace/sleep-canary-dnsproxy unchanged
namespace/sleep-noistio unchanged
```

If I then run this and try again:

```
#!/bin/bash
kubectl delete sa cattle-impersonation-u-bjzkc -n cattle-impersonation-system
kubectl delete clusterrole cattle-impersonation-u-bjzkc -n cattle-impersonation-system
```

Exact same thing happens. You guys for sure got some bug going on. If I roll back to 2.6.9 all of this works.

**Comment by cmurphy** [comment]
Hi, this looks like a different issue from the one originally reported. It's in the end of the error message - the original ends with "User ... cannot impersonate resource "userextras/username" in API group "authentication.k8s.io" at the cluster scope.", the new message looks like either "error: resource name may not be empty" according to https://github.com/rancher/rancher/issues/36096#issuecomment-1466593049 or "the object has been modified; please apply your changes to the latest version and try again" according to https://github.com/rancher/rancher/issues/36096#issuecomment-1474995166. @jbilliau-rcd could you open a new issue describing the error messages you're seeing and the reproduction steps that lead to each?

**Comment by jbilliau-rcd** [comment]
Ah, good catch, it looks like the error is slightly different. ok, I'll make a new issue
