### ISSUE TITLE
Rancher container is restarting every 15 seconds on Ubuntu 22.04

### ISSUE THREAD

**Issue by fedos3d** [rancher/rancher#36238]
**Rancher Server Setup**
- Rancher version: v2.6.3
- Installation option (Docker install/Helm Chart): Docker install

**Describe the bug**

After I restarted my ubuntu vm, my Rancher UI docker container is restarting every 15 seconds

Here is the log:
```
2022/01/22 11:40:19 [INFO] Rancher version v2.6.3 (3c1d5fac3) is starting
2022/01/22 11:40:19 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features: ClusterRegistry:}
2022/01/22 11:40:19 [INFO] Listening on /tmp/log.sock
2022/01/22 11:40:19 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6443/version?timeout=15m0s": dial tcp 127.0.0.1:6443: connect: connection refused
2022/01/22 11:40:21 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6443/version?timeout=15m0s": dial tcp 127.0.0.1:6443: connect: connection refused
2022/01/22 11:40:23 [INFO] Waiting for server to become available: the server is currently unable to handle the request
2022/01/22 11:40:25 [INFO] Waiting for server to become available: an error on the server ("apiserver not ready") has prevented the request from succeeding
2022/01/22 11:40:27 [INFO] Waiting for server to become available: an error on the server ("apiserver not ready") has prevented the request from succeeding
2022/01/22 11:40:42 [INFO] Running in single server mode, will not peer connections
2022/01/22 11:40:43 [INFO] Applying CRD features.management.cattle.io
2022/01/22 11:41:29 [ERROR] unable to update feature harvester in initialize features: Put "https://127.0.0.1:6443/apis/management.cattle.io/v3/features/harvester": EOF
2022/01/22 11:41:29 [FATAL] k3s exited with: exit status 255
```
Any advice how to make it work again?

**Comment by kha7iq** [comment]
Having same issue running v2.6.3 in a single node docker container.

**Comment by Curtis7015** [comment]
This has been happening to me for about a month and I cannot solve it. I can restore snapshots via Proxmox and it'll be good for about 3 days and randomly back to the reboot loop. Prior to the random event, everything on the node looks healthy.

**Comment by fedos3d** [comment]
> This has been happening to me for about a month and I cannot solve it. I can restore snapshots via Proxmox and it'll be good for about 3 days and randomly back to the reboot loop. Prior to the random event, everything on the node looks healthy.

Sane thing,

**Comment by Acidherr** [comment]
This has also been happenig to me. I installed Version 2.5 and it worked but the latest stable release has the behavior described above.

**Comment by Curtis7015** [comment]
> This has also been happenig to me. I installed Version 2.4 and it worked but the latest stable release has the behavior described above.

I'm going to give this a shot.

**Comment by Acidherr** [comment]
> 

Sorry I wasn't more specific, I installed using the docker container with the tag v2.4.9. It works!

**Comment by kha7iq** [comment]
> > 
> 
> Sorry I wasn't more specific, I installed using the docker container with the tag v2.4.9. It works!

Unfortunately using older versions does not help me, my downstream clusters are k8s 1. 22 so can't import them.

**Comment by themowski** [comment]
Our team is seeing this behavior as well with single-node Rancher v2.6.3-patch1 running on AlmaLinux 8.5 (one of the Enterprise Linux distros).

For the Rancher devs -- this is basically the same behavior reported in #35892 and #36047, which my team is also seeing -- the error messages we get alternate between the ones reported here and the ones in those tickets. The comments on #35892 seem to indicate that this is a problem with updates to various systemd packages in EL 8.5, and that the problems did not occur in EL 8.4.

**Comment by h0jeZvgoxFepBQ2C** [comment]
We have the same problem :(

**Comment by crushing-stegosaur** [comment]
Same problem here on a fresh OpenSUSE server for v2.6. Downgrading to v2.4.9 worked.

**Comment by IanJSaul** [comment]
^ Worked for me as well.

I've briefly tried Rancher so many times in the 1st quarter of this year, and never managed to get one to stay up long enough to USE it.

WHY is this STILL going on?

**Comment by koraykutanoglu** [comment]
hello i have this same problem on ubuntu 22.04 LTS and rancher is not working.

```
2022/04/26 20:33:36 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6443/version?timeout=15m0s": dial tcp 127.0.0.1:6443: connect: connection refused
```

**Comment by kmarji** [comment]
I'm having the same issue ... downgrading to version 2.5 works, however some of my clusters are running 1.22 and I cannot import them.
after SUSE bought rancher it has became the worst product ever ... version 2.6 is very buggy and unstable. I'm willing to rebuild my cluster on version 1.21 and not move to 2.6

**Comment by Indirectelex** [comment]
Waiting for server to become available: an error on the server ("apiserver not ready") has prevented the request from succeeding

**Comment by wbarnard81** [comment]
> hello i have this same problem on ubuntu 22.04 LTS and rancher is not working.
> 
> ```
> 2022/04/26 20:33:36 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6443/version?timeout=15m0s": dial tcp 127.0.0.1:6443: connect: connection refused
> ```

Same here. Will try Ubuntu 20.04 LTS, as the last time that worked.

**Comment by lucserre** [comment]
Fresh Debian 11 images. Same issue.

**Comment by SyriiAdvent** [comment]
VMware - Ubuntu 20.10 to 22.10. same issues.
Even tried rancher v2.5.X. all same issues.

**Comment by IanJSaul** [comment]
Ubuntu 20.04 - no issues with all latest releases of Rancher. This has proven to be the solution for all my issues so far.

**Comment by rsteckler** [comment]
Ubuntu 18.04
Docker 20.10.15
Tried rancher latest, tried 2.6.4, tried 2.5.2.  

Same thing every time.  It runs long enough to get itself setup, then restarts every few minutes.

I can't understand how this has been happening for months with no engagement from the devs?

**Comment by GuilhermeViterboGalvao** [comment]
The solution for me was changing from Ubuntu to CentOS 7 (from AWS Marketplace).

I'm using AWS and I installed the Rancher as a single node (for the main/local cluster).

Here are the steps that I did.

1-) Install the docker on CentOS:
`sudo yum install docker`

2-) Install vim editor:
`sudo yum install vim`

3-) Create the file daemon.json:
`sudo vi /etc/docker/daemon.json`

3.1-) File content:
`
{
   "group": "dockerroot"
}
`

4-) Restart docker:
`sudo systemctl restart docker`

5-) Enable docker:
`sudo systemctl enable docker`

6-) Add centos user to group dockerroot:
`sudo usermod -aG dockerroot centos`

7-) Last but not least, install Rancher:
`sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 -v /rancher:/var/lib/rancher --privileged rancher/rancher`

**Comment by pdavies91** [comment]
Downgraded from Debian11 to 10 works fine

**Comment by FelipeSanchezCalzada** [comment]
Also tried with Debian 10 and it works. With debian 11 it doesn't work.

**Comment by mrsmall** [comment]
Rancher 2.6.5 on ubuntu 22.04 (Hetzner Cloud VM) - same problem.
Reinstalled VM with debian 10 - rancher works fine.

**Comment by ognjen011** [comment]
I had this issue on Ubuntu 22.04 i fixed it by editing /etc/default/grub file. Added these values into GRUB_CMDLINE_LINUX:

GRUB_CMDLINE_LINUX="cgroup_memory=1 cgroup_enable=memory swapaccount=1 systemd.unified_cgroup_hierarchy=0"

then did:

sudo update-grub
sudo reboot 

This resolved my problem but i spent entire day on it. Maybe it helps someone else as well.  I think the same thing works for Debian 11.

**Comment by Kemichal** [comment]
@ognjen011 Thank you, this GRUB config worked for me on Ubuntu 21.10.

**Comment by ragnaros2046** [comment]
> I had this issue on Ubuntu 22.04 i fixed it by editing /etc/default/grub file. Added these values into GRUB_CMDLINE_LINUX:
> 
> GRUB_CMDLINE_LINUX="cgroup_memory=1 cgroup_enable=memory swapaccount=1 systemd.unified_cgroup_hierarchy=0"
> 
> then did:
> 
> sudo update-grub sudo reboot
> 
> This resolved my problem but i spent entire day on it. Maybe it helps someone else as well. I think the same thing works for Debian 11.

It works for Debian 11(debian-11.3.0-amd64-DVD-1.iso) you save my day bro!

**Comment by CplMulder** [comment]
Still having this issue... cannot get rancher to run successfully on any Linux distributions (older versions Ubuntu, Centos and Debian)... I have updated the grub file as suggested above but this seems to disable SSH  for me on Ubuntu?

Really want to try Rancher out but no success... it just keeps restarting every 30 odd seconds

**Comment by brutoid** [comment]
> I had this issue on Ubuntu 22.04 i fixed it by editing /etc/default/grub file. Added these values into GRUB_CMDLINE_LINUX:
> 
> GRUB_CMDLINE_LINUX="cgroup_memory=1 cgroup_enable=memory swapaccount=1 systemd.unified_cgroup_hierarchy=0"
> 
> then did:
> 
> sudo update-grub sudo reboot
> 
> This resolved my problem but i spent entire day on it. Maybe it helps someone else as well. I think the same thing works for Debian 11.

Thank you!

**Comment by ambiguo** [comment]
Same issue on macOS Big Sure M1 with the latest image 2.6. Downgrading to 2.4 worked as well.

**Comment by irenuncio** [comment]
Trying to install Rancher 2.6.x with no luck either. The latest version that seems to have started successfully is the 2.5.15 version.

My servers use fully patched Oracle Linux Server 8.6 with docker-ce 20.10.17

With every 2.6.x version I get the same error: Waiting for server to become available: an error on the server (“apiserver not ready”) has prevented the request from succeeding

What can we do?

**Comment by heavenkiller2018** [comment]
Rancher version v2.6.6  with ubuntu22.04 still has the problem,  how can we do? quick, quick!

**Comment by irenuncio** [comment]
I've personally settled on 2.5.15, now exploring the product and building my first downstream clusters. I recommend you to do the same.

**Comment by CplMulder** [comment]
> I've personally settled on 2.5.15, now exploring the product and building my first downstream clusters. I recommend you to do the same.

Thanks @irenucio... I did get 2.4 running but it lacked the Linode drivers so will try 2.5.15

**Comment by tim-platformbuilders** [comment]
> I had this issue on Ubuntu 22.04 i fixed it by editing /etc/default/grub file. Added these values into GRUB_CMDLINE_LINUX:
> 
> GRUB_CMDLINE_LINUX="cgroup_memory=1 cgroup_enable=memory swapaccount=1 systemd.unified_cgroup_hierarchy=0"
> 
> then did:
> 
> sudo update-grub sudo reboot
> 
> This resolved my problem but i spent entire day on it. Maybe it helps someone else as well. I think the same thing works for Debian 11.

I love you

**Comment by CplMulder** [comment]
I have installed Rancher 2.5.15 on Ubuntu 18.04 and can confirm that this issue is also occurring on 2.5.15 : 

<img width="1287" alt="Rancher 2 5 15" src="https://user-images.githubusercontent.com/29494358/180774189-dccaf882-67e7-4521-9afb-18e0e8aaeb1d.png">

Out of ideas.... is no-one from Rancher bothered about this at all ?

**Comment by BloodyIron** [comment]
How is it that Ubuntu 22.04 (A LONG TERM SUPPORTED RELEASE) is not actually tested against for Rancher? Testing against Alpha/Beta versions of Ubuntu 22.04 were available for MONTHS before its release. And naturally, there's good reasons to move from 20.04 to 22.04.

I have a feeling @ognjen011 's solution is going to fix it for me. But like... this is just straight up unacceptable.

Not only is this an undocumented fix, I don't see ANYONE from the dev team responding in this thread at all!

Literally building a new production environment here and this clearly off to a great start... FFS guys...

**Comment by AkkiaS7** [comment]
> GRUB_CMDLINE_LINUX="cgroup_memory=1 cgroup_enable=memory swapaccount=1 systemd.unified_cgroup_hierarchy=0"

Thank you!
It works perfectly for
Ubuntu 22.04.1 LTS
5.15.0-43-generic
Docker 20.10.12
Rancher v2.6.6

**Comment by BloodyIron** [comment]
Yeah the "GRUB_CMDLINE_LINUX" aspects did the trick for me too.

**Comment by avnes** [comment]
I am able to replicate this issue on macOS using rancher v2.5 and v2.6 started with the command:

`docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher:<tag>`


**Error message (with 2.6.6):**

```
2022/08/03 11:00:07 [INFO] Rancher version v2.6.6 (9b2f2ae0e) is starting
2022/08/03 11:00:07 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features: ClusterRegistry:}
2022/08/03 11:00:07 [INFO] Listening on /tmp/log.sock
2022/08/03 11:00:07 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
2022/08/03 11:00:09 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
2022/08/03 11:00:11 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
2022/08/03 11:00:13 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
2022/08/03 11:00:15 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
2022/08/03 11:00:17 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
2022/08/03 11:00:19 [FATAL] k3s exited with: exit status 1
```

**System details:**

macOS version: 12.5 
CPU: Apple M1 Pro
Docker Server version: 20.10.17

**Workaround:**

For me the workaround was to use version v2.4.9:

`docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher:v2.4.9`

**Comment by rotschyinc** [comment]
Just chiming in to confirm that rancher:v2.4.9 has been the only successful version on Debian 11 for me as well.

**Comment by SubsterNL** [comment]
Not working on debian 11 (cloud image) with the above mentioned grub cmd line change either.

**Comment by dnslin** [comment]
> rancher/rancher:v2.4.9
Yeah, me too. My server is also debian 11 and I can only use tag 2.4.9

**Comment by SubsterNL** [comment]
well I spoke too soon..

Doesn't work a fresh cloud image ubuntu 22.04 with only latest docker / compose installed..

Just keeps on trying to conect forever to k3s (which I can see seems to be running processes via htop)

**Comment by MichelDiz** [comment]
weird, the `rancher/rancher:v2.4.9` works fine in `ubuntu-jammy-22.04-amd64-server`. But latest or the newerst tag doesn't work. Doing `docker logs -f 1f9dfc254c09` we can see the failing loop `Waiting for server to become available`. Which is sad.

**Comment by Oats87** [comment]
@kinarashah on cursory investigation of this issue it looks like we're running into an issue with our embedded K3s running with unified cgroups hierarchy (v2) enabled

@galal-hussein @brandond any ideas on this here?

**Comment by brandond** [comment]
Does anyone have the K3s log file available from the failing startup?

Did Rancher ever pull in the cgroup v2 evacuation script from k3d? The cgroup evacuation needs to be done before the kubelet is started, by the container's init process (pid 1). If k3s is pid 1 it will do this for itself, but if it is being started by an entrypoint script, the entrypoint should do something like https://github.com/k3d-io/k3d/blob/main/pkg/types/fixes/assets/k3d-entrypoint-cgroupv2.sh before starting k3s.

**Comment by Skijolt** [comment]
The GRUB change worked for me on my Proxmox VE V7.1 with a Ubuntu 22.04 VM.
Thank you!

PS.  Be patient after rebooting.  It takes a minute for rancher to restart.

**Comment by huezo** [comment]
`sudo nano /etc/default/grub`

## Rancher
`GRUB_CMDLINE_LINUX="cgroup_memory=1 cgroup_enable=memory swapaccount=1 systemd.unified_cgroup_hierarchy=0"`


`sudo update-grub `


`sudo reboot`

**Comment by lerminou** [comment]
Instead of keeping cgroup V1 with the above fix to grub` systemd.unified_cgroup_hierarchy=0` ,   which may not work for futures releases

Docker 20.10.17 is using the new cgroupv2 kernel  but still using the old iptables and not nftables for the containers

You can do the following  fix.

**Ubuntu / Debian**
```
GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=1"
sudo update-grub
sudo reboot
```

**Fedora/Redhat**
```
sudo grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=1"
sudo reboot
```

And then if you try to connect to your rancher container, you will see these line at the end:
```
I0831 08:24:20.442967      66 network_policy_controller.go:151] Starting network policy controller
F0831 08:24:20.443474      66 network_policy_controller.go:368] failed to check for the existence of chain KUBE-ROUTER-INPUT, error: running [/usr/bin/iptables -t filter -S KUBE-ROUTER-INPUT 1 --wait]: exit status 3: iptables v1.8.6 (legacy): can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
panic: F0831 08:24:20.443474      66 network_policy_controller.go:368] failed to check for the existence of chain KUBE-ROUTER-INPUT, error: running [/usr/bin/iptables -t filter -S KUBE-ROUTER-INPUT 1 --wait]: exit status 3: iptables v1.8.6 (legacy): can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
```

New kernels for Ubuntu 22 or Redhat8 deactivate iptables and activate nftables

So you need to activate the iptables kernel module:
**Ubuntu / Debian**
```
modprobe ip_tables
echo ip_tables | sudo tee -a /etc/modules
```
**Fedora/Redhat**
```
modprobe ip_tables
echo ip_tables > /etc/modules-load.d/ip_tables.conf
```

after that, without reboot, my rancher container is able to start!!

```
INFO: Running k3s server --cluster-init --cluster-reset
Doing /etc/rancher/ssl
WARNING: key.pem does not contain a certificate or CRL: skipping
2022/08/31 09:07:20 [INFO] Rancher version v2.6.5 (c4d59fa88) is starting
2022/08/31 09:07:20 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features: ClusterRegistry:}
2022/08/31 09:07:20 [INFO] Listening on /tmp/log.sock
2022/08/31 09:07:30 [INFO] Running in single server mode, will not peer connections
2022/08/31 09:07:30 [INFO] Applying CRD features.management.cattle.io
2022/08/31 09:08:16 [INFO] Applying CRD navlinks.ui.cattle.io
2022/08/31 09:08:16 [INFO] Applying CRD clusters.management.cattle.io
[...]
2022/08/31 09:08:31 [INFO] Starting rke.cattle.io/v1, Kind=ETCDSnapshot controller
2022/08/31 09:08:31 [INFO] Starting management.cattle.io/v3, Kind=ClusterAlert controller
2022/08/31 09:08:31 [INFO] Starting management.cattle.io/v3, Kind=ClusterLogging controller
2022/08/31 09:08:31 [INFO] Listening on :443
2022/08/31 09:08:31 [INFO] Listening on :80
2022/08/31 09:08:31 [INFO] Listening on :444

```

**Comment by jloisel** [comment]
Same issue with Rancher 2.6.6, 2.6.7 and 2.6.8 on Ubuntu 22.04LTS with docker 20.10.17. Thanks @lerminou for the workaround!

**Comment by DreamCodeY** [comment]
> I am able to replicate this issue on macOS using rancher v2.5 and v2.6 started with the command:
> 
> `docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher:<tag>`
> 
> **Error message (with 2.6.6):**
> 
> ```
> 2022/08/03 11:00:07 [INFO] Rancher version v2.6.6 (9b2f2ae0e) is starting
> 2022/08/03 11:00:07 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features: ClusterRegistry:}
> 2022/08/03 11:00:07 [INFO] Listening on /tmp/log.sock
> 2022/08/03 11:00:07 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
> 2022/08/03 11:00:09 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
> 2022/08/03 11:00:11 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
> 2022/08/03 11:00:13 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
> 2022/08/03 11:00:15 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
> 2022/08/03 11:00:17 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
> 2022/08/03 11:00:19 [FATAL] k3s exited with: exit status 1
> ```
> 
> **System details:**
> 
> macOS version: 12.5 CPU: Apple M1 Pro Docker Server version: 20.10.17
> 
> **Workaround:**
> 
> For me the workaround was to use version v2.4.9:
> 
> `docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher:v2.4.9`

Thanks for your help,this solved my problem.

**Comment by houshym** [comment]
I have the same issue on mac M1 (12.5.1) and podman v4.2.0

``` 
2022/09/12 05:09:56 [INFO] Rancher version v2.6.8 (f650ce839) is starting
2022/09/12 05:09:56 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features: ClusterRegistry:}
2022/09/12 05:09:56 [INFO] Listening on /tmp/log.sock
2022/09/12 05:09:56 [INFO] Waiting for k3s to start
2022/09/12 05:09:57 [FATAL] k3s exited with: exit status 1
INFO: Running k3s server --cluster-init --cluster-reset
2022/09/12 05:10:20 [INFO] Rancher version v2.6.8 (f650ce839) is starting
2022/09/12 05:10:20 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features: ClusterRegistry:}
2022/09/12 05:10:20 [INFO] Listening on /tmp/log.sock
2022/09/12 05:10:20 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
2022/09/12 05:10:22 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
2022/09/12 05:10:24 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
2022/09/12 05:10:26 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
2022/09/12 05:10:28 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
2022/09/12 05:10:29 [FATAL] k3s exited with: exit status 1
INFO: Running k3s server --cluster-init --cluster-reset
```

**Comment by lerminou** [comment]
@houshym podman and docker are using the same kernel capabilities, you can try my workaround

**Comment by houshym** [comment]
@lerminou 
I am on mac, and this workaround did not work for me.  
```
2022/09/12 09:16:46 [INFO] Rancher version v2.6.8 (f650ce839) is starting
2022/09/12 09:16:46 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features: ClusterRegistry:}
2022/09/12 09:16:46 [INFO] Listening on /tmp/log.sock
2022/09/12 09:16:46 [INFO] Waiting for k3s to start
2022/09/12 09:16:46 [FATAL] k3s exited with: exit status 1
INFO: Running k3s server --cluster-init --cluster-reset
```

**Comment by jloisel** [comment]
Any news on a fix for this? It's not sustainable to have a custom entrypoint.sh in the long term.

**Comment by lerminou** [comment]
I can send a PR for the entrypoint but the cgroup prerequisites won't be inside and should be in your side, maybe another documentation PR?

**Comment by kinarashah** [comment]
https://github.com/k3s-io/k3s/pull/3237/files#diff-28ca1392bc87e90a7b14087d1451b94891f76e17def41647545c898fdf94bd20

**Comment by lerminou** [comment]
There is already a documentation ticket, https://github.com/rancher/docs/pull/4251

**Comment by thaneunsoo** [comment]
I have also hit this issue on the latest v2.6-head. There does seem to be a workaround that was found [here](https://github.com/rancher/rancher/issues/36238#issuecomment-1141244691) by another user. After the workaround, Rancher container stopped restarting and worked as expected, being able to provision downstream cluster as well.

**Comment by houshym** [comment]
@thaneunsoo what about mac workaround?

**Comment by lerminou** [comment]
@Sahota1225  not only Ubuntu is impacted, Redhat too.

**Comment by kinarashah** [comment]
Available to test with v2.7-head once https://drone-publish.rancher.io/rancher/rancher/8317/1/1 is green

**Comment by houshym** [comment]
@kinarashah  for me works. Thanks

**Comment by wildcommunist** [comment]
> update-grub

What does this actually do? This solved the problem for me too!
VPS with ovh cloud

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: Custom

----------

### Testing: ###

Tested this issue with the following steps:
1. On Ubuntu 22.04 instance install Rancher using docker
2. Verify install is successful
3. Verify that rancher container does not restart every 15 seconds
4. Reboot the instance
5. Verify that rancher container does not restart every 15 seconds

**Result**
Rancher container is no longer restarting on Ubuntu 22.04

I am now seeing the following error in the docker logs and am unable to reach Rancher
```
[ERROR] available chart version (1.0.5+up0.2.6) for rancher-webhook is less than the min version (1.0.6+up0.2.7-rc4) 
2022/09/21 21:33:09 [ERROR] Failed to find system chart rancher-webhook will try again in 5 seconds: no chart name found

```

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head eab28dd
Rancher cluster type: single-node docker install
Docker version: 20.10

----------

### Testing: ###

Tested this issue with the following steps:
1. On Ubuntu 22.04 instance install Rancher using docker
2. Provision RKE1 cluster
3. Provision RKE2 cluster

**Result** - Pass
Rancher container is running successfully and RKE1 and RKE2 clusters also come up fine as well.
![image.png](https://zube.io/files/rancher/b6f3b2db1ba302cbaa1f559d9b38d9a6-image.png)

![image.png](https://zube.io/files/rancher/9c5d3e5e8e9fa942dea266926c0f3379-image.png)

![image.png](https://zube.io/files/rancher/7a47297f564f3d7e4d18d2e4e691b0b0-image.png)

**Comment by HaigNalbandian** [comment]
Still not working in el9, correct? I can't get `stable` nor `v2.6.9` running on Rocky Linux 9

**Comment by sachaw** [comment]
> Still not working in el9, correct? I can't get `stable` nor `v2.6.9` running on Rocky Linux 9

Same issue, EL9.1 any workarounds?

**Comment by hhruszka** [comment]
I managed to resolve this issue with the following procedure. It turned out that iptables where not installed and appropriate modules loaded into kernel.

Please note that I named rancher container "rancher" (--name=rancher docker run flag) 

create directory on your host:
```
sudo mkdir /rancher
sudo chmod 777 /rancher
```
run rancher with the following command. It is essential to mount volumes for debugging purposes. 
```
sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 -v /rancher:/var/lib/rancher --privileged --net=host --name=rancher rancher/rancher`
```
execute
```
docker logs -f rancher`
```
if rancher fails to start because of https://127.0.0.1:6444/ cannot connect error "[INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused", then you need to investigate /rancher/k3s.log on your host
I found that iptables installtion was missing on the host
After installing iptables I had to manually load two modules - k3s was complaining about missing them in k3s.log:
```
sudo modprobe iptable_nat
sudo modprobe iptable_filter
```

add both modules to the file 
```
sudo cat<<EOF >/etc/modules-load.d/modules.conf
iptable_nat
iptable_filter
EOF
```

then I got an issue with x509 certificate which got resolved by - please note that I named my container "rancher":
```
sudo docker exec -it rancher sh -c "rm /var/lib/rancher/k3s/server/tls/dynamic-cert.json"
sudo docker exec -it rancher k3s kubectl --insecure-skip-tls-verify=true delete secret -n kube-system k3s-serving
sudo docker restart <container id>
```

**Comment by jackyting825** [comment]
> I managed to resolve this issue with the following procedure. It turned out that iptables where not installed and appropriate modules loaded into kernel. I tested it on Rocky 8.7 with rancher 2.7.3.
> 
> **SOLUTION:**
> 
> 1. install iptables
> 2. make sure that missing iptables modules are loaded into kernel:
> 
> Add both modules to the file
> 
> ```
> sudo cat<<EOF >/etc/modules-load.d/modules.conf
> iptable_nat
> iptable_filter
> EOF
> ```
> 
> and reboot your host"
> 
> ```
> sudo reboot
> ```
> 
> 3. execute:
> 
> ```
> sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged --name=rancher rancher/rancher`
> ```
> 
> **TROUBLESHOOTING:**
> 
> Please note that I named rancher container "rancher" (--name=rancher docker run flag)
> 
> Create directory on your host:
> 
> ```
> sudo mkdir /rancher
> sudo chmod 777 /rancher
> ```
> 
> Run rancher container with the following command. It is essential to mount volumes for debugging purposes.
> 
> ```
> sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 -v /rancher:/var/lib/rancher --privileged --net=host --name=rancher rancher/rancher`
> ```
> 
> Execute
> 
> ```
> docker logs -f rancher`
> ```
> 
> If rancher fails to start because of https://127.0.0.1:6444/ cannot connect error "[INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused", then you need to investigate /rancher/k3s.log on your host.
> 
> I found that iptables were missing on the host. After installing iptables I had to manually load two modules - k3s was complaining about missing them in k3s.log:
> 
> ```
> sudo modprobe iptable_nat
> sudo modprobe iptable_filter
> ```
> 
> Add both modules to the file
> 
> ```
> sudo cat<<EOF >/etc/modules-load.d/modules.conf
> iptable_nat
> iptable_filter
> EOF
> ```
> 
> and reboot your host"
> 
> ```
> sudo reboot
> ```
> 
> Then I got an issue with x509 certificate which got resolved by the following commands (please note that I named my container "rancher"):
> 
> ```
> sudo docker exec -it rancher sh -c "rm /var/lib/rancher/k3s/server/tls/dynamic-cert.json"
> sudo docker exec -it rancher k3s kubectl --insecure-skip-tls-verify=true delete secret -n kube-system k3s-serving
> sudo docker restart rancher
> ```
> 
> When you finish troubleshooting and get missing iptables modules loaded into kernel then you can run docker in the way provided in the solution section - without volumes attached and host network. The issue with the invalid x509 certificates could be a side effect of troubleshooting.

on rocky linux 9.3 works fine

**Comment by prbakhsh** [comment]
@hhruszka  your solution works for my oracle linux 9.3
