### ISSUE TITLE
rancher/kubelet-pause container on windows worker node keeps getting removed and new one gets created.

### ISSUE THREAD

**Issue by vivek-infracloud** [rancher/rancher#36898]
**Rancher Server Setup**
- Rancher version: v2.6.4-rc8
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1

**Information about the Cluster**
- Kubernetes version: 1.23
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? : RKE1 - Windows

**User Information**
- What is the role of the user logged in?  : Standard User

**Describe the bug**

`rancher/kubelet-pause` container on windows worker node gets removed and new one gets created. 

**To Reproduce**
 

- Create a ha rancher server v2.6.4-rc8 `rancher-v3_ha_deploy` jenkins job.
- Create a RKE1 downstream k8s v1.23 windows cluster with `rancher-v3_create_windows_cluster`
- Login to any windows node and list all the docker containers with `docker ps -a`

**Result**
- Notice that the `rancher/kubelet-pause` containers are removed and the new container is created.

**Expected Result**

- The `rancher/kubelet-pause` containers should be Up and Running without errors.

**Screenshots**
![remmina_ec2-3-145-177-204 us-east-2 compute amazonaws com_ec2-3-145-177-204 us-east-2 compute amazonaws com_2022315-155656](https://user-images.githubusercontent.com/83208989/158419102-88502c22-5997-41f1-b0d3-75b4e240fed6.png)

**Comment by deniseschannon** [comment]
@vivek-infracloud 

* Does this happen with v1.21 windows clusters in 2.6.4-rcX? 
* Does this happen with v1.21 windows clusters in v2.6.3?

**Comment by deniseschannon** [comment]
For these issues with restarting containers, can you provide the logs inside the containers?

**Comment by deniseschannon** [comment]
Per @rosskirkpat, these are the same root issue that RKE1 1.23 Windows wasn't working that was fixed a part of the review for this issue: https://github.com/rancher/rancher/issues/36849

> RKE1 1.23 Windows was not working due to the k8s service options for windows missing from the initial 1.23 PR in rke1. This has been addressed by the Windows Team and is ready to be tested again with latest 2.6-head once it is published https://drone-publish.rancher.io/rancher/rancher/7495

**Comment by vivek-infracloud** [comment]
@deniseschannon 
> * Does this happen with v1.21 windows clusters in v2.6.3?
No, this does not happen with 1.21 windows clusters in v2.6.3.
However this does happen with v1.21 and v1.22 windows clusters in v.2.6-head.

I will check with v1.21 in 2.6.4-rc8.

**Comment by deniseschannon** [comment]
@vivek-infracloud I believe this may be fixed with the changes regarding 1.23. 

Can you re-do the steps for 1.23 windows RKE1 cluster install and see if it's still an issue?

**Comment by vivek-infracloud** [comment]
Yes, I'm on it.

**Comment by vivek-infracloud** [comment]
@deniseschannon The issue is still active. `rancher/kubelet-pause` container is getting removed and the new container is created.
Could not get log from the `rancher/kubelet-pause` container. The container is getting removed (it is not restarting) within 2 seconds after it is created.

![remmina_ec2-13-59-214-170 us-east-2 compute amazonaws com_ec2-13-59-214-170 us-east-2 compute amazonaws com_2022317-7493](https://user-images.githubusercontent.com/83208989/158761611-e0b7787b-9862-4284-8a01-8cec3397f3a4.png)

**Comment by deniseschannon** [comment]
@vivek-infracloud what happens on a 1.21 cluster? Can you help narrow down when the regression started based on my other questions if this is reproducible in the above scenarios?/

**Comment by vivek-infracloud** [comment]
With k8s v1.21 on rancher 2.6.4-rc9 issue is active. So, in my opinion the regression started in 2.6.4-rcX.

**Comment by rosskirkpat** [comment]
https://github.com/rancher/wins/pull/96
https://github.com/rancher/wins/pull/100
https://github.com/rancher/rke-tools/pull/146
https://github.com/rancher/kontainer-driver-metadata/pull/859
https://github.com/rancher/rke/pull/2878
https://github.com/rancher/rancher/pull/36963

Once the Rancher PR is merged and a run of drone-publish completes, we should be fully unblocked for e2e testing of rke1 windows custom clusters.

**Comment by rosskirkpat** [comment]
Testing template for @deniseschannon @sowmyav27 @slickwarren @vivek-infracloud 

### Root cause

The regression is caused by a urfave cli version bump in wins that occurred in February 2021. The timeline below documents how it took approximately 12 months for the regression to make it's way into Rancher. 

Note: The bug that caused the regression only exists when a specific wins command from sidecar.ps1 is ran inside of the rke-tools:v0.1.79 container on a windows host. The server (host) wins version does not dictate the presence of the bug. This allows for a wins server (host) version of v0.1.1 to not exhibit the bug if the version of the rke-tools container is v0.1.78 or v0.1.80.
 

Timeline for the Regression Being Introduced to Rancher:

Wins changes that caused the regression:

feb 11, 2021 was when urfave 1.22.5 was introduced to wins
https://github.com/rancher/wins/commit/4dfbf501fb9db20667b444573403495e323e78db

the args parsing that broke due to urfave 1.22.5
https://github.com/rancher/wins/commit/309fed6c7aef6e87bba721eb527d3b5aa29c0a7f


Wins versions:

wins v0.0.4 was released on sept 17 2019 with urfave v1.20.0
https://github.com/rancher/wins/releases/tag/v0.0.4


wins v0.1.1 was released on may 4 2021 with urfave 1.22.5
https://github.com/rancher/wins/releases/tag/v0.1.1


rke-tools:

rke-tools v0.1.78 was released on july 21, 2021
https://github.com/rancher/rke-tools/releases/tag/v0.1.78

The version of wins containing the regression was added to rke-tools on Nov 10, 2021. This brought in a version of wins that was released on May 4, 2021 that contained the changes from Feb 2021 that caused the regression.
https://github.com/rancher/rke-tools/commit/d74aaa5202eaaa7c0820487abb7c763488d191b9


rke-tools v0.1.79 was released on Jan 20, 2022 with the regression 
https://github.com/rancher/rke-tools/releases/tag/v0.1.79


KDM:
rke-tools 0.1.79 was bumped in KDM on feb 1 and feb 2 2022
https://github.com/rancher/kontainer-driver-metadata/commit/009970220cf17d53753e38f9abe271d26ea67998
https://github.com/rancher/kontainer-driver-metadata/commit/f03123017a23ca6d42a12b9cbd464760fae50ad9


RKE:
KDM was bumped to include rke-tools v0.1.79 for the four RKE1 versions listed below
https://github.com/rancher/rke/commit/c4ef4ff6a96eb4f5372599a9d97573c64f01a917


Rancher:
The version of RKE that had rke-tools v0.1.79 was pinned in Rancher on Feb 14, 2022
https://github.com/rancher/rancher/commit/d540651a7614b5377f9fe1bb3534b5029c57722e


Result: The regression has been live in Rancher for a month, specifically since v2.6.4-rc3. 

### What was fixed, or what changes have occurred

The version of urfave-cli was pinned to v1.20.0 as that was the last-known working version prior to the bump to v1.22.5 urfave-cli.

RKE1 windows custom clusters were broken on dev/2.6 KDM branch for the following RKE1 versions. There are no regressions in any RKE1 versions listed in the release/v2.6 branch of KDM.

v1.19.16-rancher1-4
v1.21.10-rancher1-1
v1.22.7-rancher1-1
v1.23.4-rancher1-1

These versions are now functional again for rke1 windows provisioning as they use a version of rke-tools for Windows containers (v0.1.80) that has a fix for the regression.
 
### Areas or cases that should be tested

RKE1 custom Windows clusters should be tested for the following versions:

v1.19.16-rancher1-4
v1.21.10-rancher1-1
v1.22.7-rancher1-1
v1.23.4-rancher1-1

Additionally:

Airgap installations of rke1 windows custom clusters of the RKE1 versions that previously contained the regression
Rancher v2.6.3 -> v2.6.4 upgrade with rke1 custom windows workers
Upgrading rke1 windows custom clusters (v1.19, v1.21, v1.22, v1.23) from the RKE1 version prior to the regression to the version that previously contained the regression.


### What areas could experience regressions?

With the impacted versions never hitting a release of Rancher or the release/v2.6 branch of KDM, there are no regressions possible in stable releases of Rancher due to this bug.

### Are the repro steps accurate/minimal?

Yes, the standard process of provisioning of rke1 custom clusters should now function as expected in full e2e testing for all listed RKE1 versions above when using the dev/2.6 branch of KDM.

### Here are the steps we followed when fixing the rke1 Windows regression in 2.6.4

cut a wins v0.1.1-patch1 release after fixing the v0.1.1 branch drone.yml and tests alongside the bug fix of pinning v1.20.0 of urfave cli
validate v0.1.1-patch1  of wins fixes the issue by packaging a dev version of rke-tools,  using a custom KDM and deploying rke1 windows custom clusters
pin the new wins version in rke-tools and bump the version of flannel for windows in rke-tools to 17
release new rke-tools
pin the new rke-tools version in KDM, change the windowsPodInfraContainer image from rancher/kubelet-pause:v0.1.6 to rancher/mirrored-pause:3.6 to address a customer/community issue https://github.com/rancher/windows/issues/97
release new KDM
pin the new KDM in RKE
release new RKE
pin KDM and RKE in the rancher/v2.6 branch
release new rancher 2.6.4 rc for testing -> Waiting for this to occur on Monday morning

### How to validate and perform e2e testing without a Rancher RC

Use the following Rancher image in a single node docker install of Rancher

docker pull rancher/rancher:v2.6-024e6fa23af3678aafa85d4085c02143127bd3a1-head
