### ISSUE TITLE
[BUG] rancher keeps logging errors

### ISSUE THREAD

**Issue by GGGitBoy** [rancher/rancher#41465]
**Rancher Server Setup**
- Rancher version: v2.6.12
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Describe the bug**

**To Reproduce**

1. install rancher 2.6.12

**Result**

rancher keeps logging errors like this
```
2023/05/08 01:32:06 [ERROR] error syncing 'local': handler global-admin-cluster-sync: failed to get GlobalRoleBinding for 'globaladmin-user-8p5d7': %!!(MISSING)w(<nil>), requeuing
```

**Expected Result**

**Screenshots**

**Additional context**

**Comment by cbron** [comment]
Hey @GGGitBoy thanks for issue. We are going to add a release note to the latest 2.6 version with a warning about this. But importantly it shouldn't affect any actual permissions. If it does you can add user as cluster-owner and it will go away. It is fixed on the 2.7.x line, and since 2.6.x is now end-of-maintenance we won't be fixing it there.

**Comment by nheinemans** [comment]
+1, we're seeing the same issue after updating from 2.6.11 to 2.6.12.
However, we need 2.6.12 for k8s 1.24.13 support, so it would be helpful if this can be fixed in 2.6.13.

**Comment by lgraziosi** [comment]
> Hey @GGGitBoy thanks for issue. We are going to add a release note to the latest 2.6 version with a warning about this. But importantly it shouldn't affect any actual permissions. If it does you can add user as cluster-owner and it will go away. It is fixed on the 2.7.x line, and since 2.6.x is now end-of-maintenance we won't be fixing it there.

What do you mean by this? We have the same issue creating a new workload RKE2 cluster from a 2.6.12 rancher installation.  
All the global admins are already cluster owners, but we still have that error.

**Comment by cbron** [comment]
> All the global admins are already cluster owners, but we still have that error.

Global admins have * on * by default, but they are not assigned the cluster-owner role itself. What I meant was they can be assigned directly as a cluster-owner in every cluster and the error logs will go away.

**Comment by Hargeek** [comment]
I am also experiencing the same problem and I want to fix this error in 2.6.12. What should I do or set

**Comment by lgraziosi** [comment]
> > All the global admins are already cluster owners, but we still have that error.
> 
> Global admins have * on * by default, but they are not assigned the cluster-owner role itself. What I meant was they can be assigned directly as a cluster-owner in every cluster and the error logs will go away.

I'm saying that I did that when creating a new RKE2 cluster and I still have the issue.

**Comment by cbron** [comment]
> I'm saying that I did that when creating a new RKE2 cluster and I still have the issue.

Ahh, I had this wrong, adding them as cluster-owner will just fix any permission issues but not fix the log messages. That being said, all this should be working normally on any version of 2.7. The 2.6 line [has been EOM](https://www.suse.com/lifecycle/#rancher) for a while now, so we won't be backporting fixes there.

**Comment by KevinJoiner** [comment]
If you want to fix the log message only and not the permission issue, you can update `cluster.status.Condition[].type=GlobalAdminsSynced` condition to true.
``` yaml
 - lastUpdateTime: "2023-05-30T08:54:49-04:00"
    status: "False"
    type: GlobalAdminsSynced
```
=>
``` yaml
 - lastUpdateTime: "2023-05-30T08:54:49-04:00"
    status: "True"
    type: GlobalAdminsSynced
```

**Comment by svogt** [comment]
I did not find a way to modify conditions manually, can you give a hint on how to do that?

**Comment by murand78** [comment]
Both workarounds did not work for me.

Added local admin user as ClusterOwner of downstream cluster : no effects
Edited the status condition: no effects, returns immediately to error
 
Local Rancher: 2.6.13 on v1.23.17+rke2r1 
Importing a downstream cluster  v1.24.15+rke2r1


> I did not find a way to modify conditions manually, can you give a hint on how to do that?
On Rancher local cluster
$ kubectl -n fleet-default edit cluster <cluster-name>

**Comment by rokoala** [comment]
I had the same problem and resolved it by editing the clusters.management.cattle.io object  using the following command:

`kubectl edit clusters.management.cattle.io <cluster-id>`

I changed the status from:
`status: 'False'`

to:
`status: 'True'`

Additionally, I removed the error message and reason. After making these changes, the error was gone.

**Comment by murand78** [comment]
Thanks @rokoala, editing the clusters.management.cattle.io instead of the Cluster crd the error message disappeared

**Comment by VladimirMesea** [comment]
Any fix for this if GlobalAdminsSynced is already true and the error message still appears? Rancher v2.6.14 + k8s 1.24.15

**Comment by mjeco** [comment]
@VladimirMesea you need to delete the keys `reason` and `message` of the `GlobalAdminsSynced` status.

**Comment by mjeco** [comment]
@VladimirMesea  Oh ok. For me, I had to delete the reason and message keys. After that, the error was fixed. This was with rancher 2.6.13 and downstream k3s 1.20.15

**Comment by fertab** [comment]
> @VladimirMesea you need to delete the keys `reason` and `message` of the `GlobalAdminsSynced` status.

Thanks @VladimirMesea this worked for me

**Comment by ctodea** [comment]
@rokoala 's solution worked for me too
