### ISSUE TITLE
Unable to edit a port to bind using hostIP:Port 

### ISSUE THREAD

**Issue by darkfrog26** [rancher/rancher#4280]
Rancher Version: 1.0.0

Docker Version: 1.10.3

OS: Ubuntu 15.10

Steps to Reproduce: Trying to edit the port configuration on a container in the input's default text it suggests that you can use "eg 1.2.3.4:80", but when I attempt to use that format it ends up saying the port is "1" and the ip address is "None".

Results: No worky

Expected: Worky

Pretty easy to test. If you need additional information let me know.

**Comment by deniseschannon** [comment]
Reproduced with creating a container or service

1. Create a service.
2. Edit the container to add in `104.x.x.x:80` as a port map. 
3. Save the changes.

Results: 

For a service, the port shown in the UI  is `104`, but in the API, the ports field is blank. 

For a container, the port isn't shown in the UI and in the API, the ports field is blank.

Expected Result: The ports to be set in the API and displayed correctly in the UI.

**Comment by darkfrog26** [comment]
I would argue this should be a hotfix update, not a 1.1 release fix since it's a fairly major and glaring bug.  Can you at least offer a work-around for this?

**Comment by vincent99** [comment]
This is already fixed in the UI for 1.0.1

**Comment by darkfrog26** [comment]
@vincent99 any ETA when 1.0.1 will be made available?

**Comment by deniseschannon** [comment]
@darkfrog26 We are aiming for end of this week. In the meantime, you could clone your service and set the ports during creation instead of trying to edit them after they are created.

**Comment by tfiduccia** [comment]
Version - v1.0.1-rc1
Not fixed
UI still say 104 and nothing else.  The API has old value

**Comment by tfiduccia** [comment]
If I start with just a port and edit and try to add the IP, it still doesn't work.  This makes the UI very confusing, cause it looks like I can do this when I edit.

**Comment by vincent99** [comment]
You can only change the port, not the bound IP.

**Comment by darkfrog26** [comment]
Are you saying that going forward you cannot modify the bound IP address?  If you need to you'll have to delete and re-create?

**Comment by tfiduccia** [comment]
@darkfrog26 - Yes, currently you will not be able to modify a bound IP address.

Version - master 2/28
Original Issue - Verified fixed

**Comment by darkfrog26** [comment]
How is that a fix?  Removing the broken feature is a hack, not a fix.

**Comment by deniseschannon** [comment]
The original issue was that the editing the port that had a host IP bound had issues when saving the edits. It wasn't parsing it correctly.

It would be a separate enhancement if you want to support being able to edit the hostIP to another IP of the same container.

**Comment by darkfrog26** [comment]
@deniseschannon, that might be true except the placeholder text gave examples including the IP address proving that it was the original design that IP and port be allowed as input.

**Comment by vincent99** [comment]
It's placeholder text, and I'm the one that put it in there.  The backend doesn't and never has supported editing the bound IP, and that's not what this issue was for.
