### ISSUE TITLE
Logs keep generating with errors on Cluster Deletion

### ISSUE THREAD

**Issue by dasarinaidu** [rancher/rancher#42999]
Logs keep generating with errors on Cluster Deletion 

**Steps:**

1. Provisioned rancher (Docker Linode)
2. Created downstream cluster (Linode)
3. Created a project
4. Delete cluster
5. Check for the error messages in logs

**Actual:**
1. Cluster got deleted successfully
2. PRTBs got deleted 
3. LOGs keep generating errors with 
Did not see any error messages related to crtb or prtb like earlier but seeing errors related to project as below.
--

```
2023/09/28 16:28:56 [ERROR] error syncing 'c-m-47gk986g/p-9q79m': handler mgmt-project-rbac-remove: failed to remove finalizer on controller.cattle.io/mgmt-project-rbac-remove, requeuing
2023/09/28 16:29:10 [ERROR] error syncing 'c-m-jltz97cf/p-sbdrz': handler mgmt-project-rbac-remove: failed to remove finalizer on controller.cattle.io/mgmt-project-rbac-remove, requeuing
2023/09/28 16:29:26 [ERROR] error syncing 'c-m-47gk986g/p-9q79m': handler mgmt-project-rbac-remove: failed to remove finalizer on controller.cattle.io/mgmt-project-rbac-remove, requeuing
W0928 16:29:39.595609      33 warnings.go:80] cluster.x-k8s.io/v1alpha3 Machine is deprecated; use cluster.x-k8s.io/v1beta1 Machine
2023/09/28 16:29:56 [ERROR] error syncing 'c-m-47gk986g/p-9q79m': handler mgmt-project-rbac-remove: failed to remove finalizer on controller.cattle.io/mgmt-project-rbac-remove, requeuing
2023/09/28 16:30:26 [ERROR] error syncing 'c-m-47gk986g/p-9q79m': handler mgmt-project-rbac-remove: failed to remove finalizer on controller.cattle.io/mgmt-project-rbac-remove, requeuing


2023/09/28 16:30:56 [ERROR] error syncing 'c-m-47gk986g/p-9q79m': handler mgmt-project-rbac-remove: failed to remove finalizer on controller.cattle.io/mgmt-project-rbac-remove, requeuing
2023/09/28 16:31:10 [ERROR] error syncing 'c-m-jltz97cf/p-sbdrz': handler mgmt-project-rbac-remove: failed to remove finalizer on controller.cattle.io/mgmt-project-rbac-remove, requeuing
2023/09/28 16:31:26 [ERROR] error syncing 'c-m-47gk986g/p-9q79m': handler mgmt-project-rbac-remove: failed to remove finalizer on controller.cattle.io/mgmt-project-rbac-remove, requeuing
2023/09/28 16:31:56 [ERROR] error syncing 'c-m-47gk986g/p-9q79m': handler mgmt-project-rbac-remove: failed to remove finalizer on controller.cattle.io/mgmt-project-rbac-remove, requeuing
W0928 16:32:24.674168      33 warnings.go:80] cluster.x-k8s.io/v1alpha3 Cluster is deprecated; use cluster.x-k8s.io/v1beta1 Cluster
2023/09/28 16:32:26 [ERROR] error syncing 'c-m-47gk986g/p-9q79m': handler mgmt-project-rbac-remove: failed to remove finalizer on controller.cattle.io/mgmt-project-rbac-remove, requeuing
2023/09/28 16:32:56 [ERROR] error syncing 'c-m-47gk986g/p-9q79m': handler mgmt-project-rbac-remove: failed to remove finalizer on controller.cattle.io/mgmt-project-rbac-remove, requeuing
2023/09/28 16:33:10 [ERROR] error syncing 'c-m-jltz97cf/p-sbdrz': handler mgmt-project-rbac-remove: failed to remove finalizer on controller.cattle.io/mgmt-project-rbac-remove, requeuing
2023/09/28 16:33:26 [ERROR] error syncing 'c-m-47gk986g/p-9q79m': handler mgmt-project-rbac-remove: failed to remove finalizer on controller.cattle.io/mgmt-project-rbac-remove, requeuing
W0928 16:33:36.414612      33 warnings.go:80] cluster.x-k8s.io/v1alpha3 MachineSet is deprecated; use cluster.x-k8s.io/v1beta1 MachineSet
W0928 16:33:47.426984      33 warnings.go:80] cluster.x-k8s.io/v1alpha3 MachineDeployment is deprecated; use cluster.x-k8s.io/v1beta1 MachineDeployment
2023/09/28 16:33:56 [ERROR] error syncing 'c-m-47gk986g/p-9q79m': handler mgmt-project-rbac-remove: failed to remove finalizer on controller.cattle.io/mgmt-project-rbac-remove, requeuing
2023/09/28 16:34:26 [ERROR] error syncing 'c-m-47gk986g/p-9q79m': handler mgmt-project-rbac-remove: failed to remove finalizer on controller.cattle.io/mgmt-project-rbac-remove, requeuing
2023/09/28 16:35:11 [ERROR] error syncing 'c-m-jltz97cf/p-sbdrz': handler mgmt-project-rbac-remove: failed to remove finalizer on controller.cattle.io/mgmt-project-rbac-remove, requeuing
2023/09/28 16:36:26 [ERROR] error syncing 'c-m-47gk986g/p-9q79m': handler mgmt-project-rbac-remove: failed to remove finalizer on controller.cattle.io/mgmt-project-rbac-remove, requeuing
```

**"CATTLE_DEBUG": "true"
POD(Webhook) : Logs**

```
[ERROR] error syncing 'p-pcj48/creator-project-owner': handler mgmt-auth-prtb-controller: clusters.management.cattle.io "c-m-bt572cc6" not found, requeuing
2023/09/28 19:12:03 [ERROR] error syncing 'p-dhb9z/creator-project-owner': handler mgmt-auth-prtb-controller: clusters.management.cattle.io "c-m-bt572cc6" not found, requeuing
```

```
time="2023-09-28T19:19:54Z" level=debug msg="admit result: DELETE management.cattle.io/v3, Kind=Project c-m-tpzhnwxn/ user=system:serviceaccount:kube-system:namespace-controller allowed=true err=<nil>"
time="2023-09-28T19:19:54Z" level=debug msg="admit result: DELETE management.cattle.io/v3, Kind=Project c-m-tpzhnwxn/ user=system:serviceaccount:kube-system:namespace-controller allowed=true err=<nil>"
time="2023-09-28T19:19:56Z" level=debug msg="admit result: UPDATE management.cattle.io/v3, Kind=Project c-m-tpzhnwxn/p-cgvkz user=system:admin allowed=false err=<nil>"
time="2023-09-28T19:19:56Z" level=debug msg="admit result: UPDATE management.cattle.io/v3, Kind=Project c-m-tpzhnwxn/p-cgvkz user=system:admin allowed=false err=<nil>"
time="2023-09-28T19:19:56Z" level=debug msg="admit result: UPDATE management.cattle.io/v3, Kind=Project c-m-tpzhnwxn/p-cgvkz user=system:admin allowed=false err=<nil>"
time="2023-09-28T19:19:57Z" level=debug msg="admit result: UPDATE management.cattle.io/v3, Kind=Project c-m-tpzhnwxn/p-gbvsj user=system:admin allowed=false err=<nil>"
time="2023-09-28T19:19:57Z" level=debug msg="admit result: UPDATE management.cattle.io/v3, Kind=Project c-m-tpzhnwxn/p-gbvsj user=system:admin allowed=false err=<nil>"
time="2023-09-28T19:19:57Z" level=debug msg="admit result: UPDATE management.cattle.io/v3, Kind=Project c-m-tpzhnwxn/p-gbvsj user=system:admin allowed=false err=<nil>"
time="2023-09-28T19:20:03Z" level=debug msg="admit result: DELETE management.cattle.io/v3, Kind=Project c-m-tpzhnwxn/ user=system:serviceaccount:kube-system:namespace-controller allowed=true err=<nil>"
time="2023-09-28T19:20:03Z" level=debug msg="admit result: DELETE management.cattle.io/v3, Kind=Project c-m-tpzhnwxn/ user=system:serviceaccount:kube-system:namespace-controller allowed=true err=<nil>"
time="2023-09-28T19:20:12Z" level=debug msg="admit result: DELETE management.cattle.io/v3, Kind=Project c-m-tpzhnwxn/ user=system:serviceaccount:kube-system:namespace-controller allowed=true err=<nil>"
time="2023-09-28T19:20:12Z" level=debug msg="admit result: DELETE management.cattle.io/v3, Kind=Project c-m-tpzhnwxn/ user=system:serviceaccount:kube-system:namespace-controller allowed=true err=<nil>"
time="2023-09-28T19:20:20Z" level=debug msg="admit result: DELETE management.cattle.io/v3, Kind=Project c-m-tpzhnwxn/ user=system:serviceaccount:kube-system:namespace-controller allowed=true err=<nil>"
time="2023-09-28T19:20:20Z" level=debug msg="admit result: DELETE management.cattle.io/v3, Kind=Project c-m-tpzhnwxn/ user=system:serviceaccount:kube-system:namespace-controller allowed=true err=<nil>"
time="2023-09-28T19:20:29Z" level=debug msg="admit result: DELETE management.cattle.io/v3, Kind=Project c-m-tpzhnwxn/ user=system:serviceaccount:kube-system:namespace-controller allowed=true err=<nil>"
time="2023-09-28T19:20:29Z" level=debug msg="admit result: DELETE management.cattle.io/v3, Kind=Project c-m-tpzhnwxn/ user=system:serviceaccount:kube-system:namespace-controller allowed=true err=<nil>"
time="2023-09-28T19:20:37Z" level=debug msg="admit result: DELETE management.cattle.io/v3, Kind=Project c-m-tpzhnwxn/ user=system:serviceaccount:kube-system:namespace-controller allowed=true err=<nil>"
time="2023-09-28T19:20:37Z" level=debug msg="admit result: DELETE management.cattle.io/v3, Kind=Project c-m-tpzhnwxn/ user=system:serviceaccount:kube-system:namespace-controller allowed=true err=<nil>"
time="2023-09-28T19:20:43Z" level=debug msg="admit result: DELETE management.cattle.io/v3, Kind=Project c-m-bt572cc6/ user=system:serviceaccount:kube-system:namespace-controller allowed=false err=<nil>"
time="2023-09-28T19:20:46Z" level=debug msg="admit result: DELETE management.cattle.io/v3, Kind=Project c-m-tpzhnwxn/ user=system:serviceaccount:kube-system:namespace-controller allowed=true err=<nil>"
time="2023-09-28T19:20:46Z" level=debug msg="admit result: DELETE management.cattle.io/v3, Kind=Project c-m-tpzhnwxn/ user=system:serviceaccount:kube-system:namespace-controller allowed=true err=<nil>"
time="2023-09-28T19:20:56Z" level=debug msg="admit result: DELETE management.cattle.io/v3, Kind=Project c-m-tpzhnwxn/ user=system:serviceaccount:kube-system:namespace-controller allowed=true err=<nil>"
time="2023-09-28T19:20:56Z" level=debug msg="admit result: DELETE management.cattle.io/v3, Kind=Project c-m-tpzhnwxn/ user=system:serviceaccount:kube-system:namespace-controller allowed=true err=<nil>"
time="2023-09-28T19:20:57Z" level=debug msg="admit result: UPDATE management.cattle.io/v3, Kind=Project c-m-bt572cc6/p-2hdzr user=system:admin allowed=false err=<nil>"
time="2023-09-28T19:20:57Z" level=debug msg="admit result: UPDATE management.cattle.io/v3, Kind=Project c-m-bt572cc6/p-2hdzr user=system:admin allowed=false err=<nil>"
```

**"CATTLE_DEBUG": "true"
Rancher Logs:**

```
2023/09/28 19:13:26 [ERROR] error syncing 'c-m-tpzhnwxn/p-cgvkz': handler mgmt-project-rbac-remove: failed to remove finalizer on controller.cattle.io/mgmt-project-rbac-remove, requeuing
2023/09/28 19:13:26 [ERROR] error syncing 'c-m-tpzhnwxn/p-gbvsj': handler mgmt-project-rbac-remove: failed to remove finalizer on controller.cattle.io/mgmt-project-rbac-remove, requeuing
2023/09/28 19:13:33 [ERROR] error syncing 'p-pcj48/creator-project-owner': handler mgmt-auth-prtb-controller: clusters.management.cattle.io "c-m-bt572cc6" not found, requeuing
2023/09/28 19:13:33 [ERROR] error syncing 'p-dhb9z/creator-project-owner': handler mgmt-auth-prtb-controller: clusters.management.cattle.io "c-m-bt572cc6" not found, requeuing
2023/09/28 19:13:34 [ERROR] error syncing 'p-dhb9z/prtb-mrz77': handler mgmt-auth-prtb-controller: clusters.management.cattle.io "c-m-bt572cc6" not found, requeuing
W0928 19:13:39.249334      32 warnings.go:80] Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
2023/09/28 19:13:43 [ERROR] error syncing 'p-pcj48/creator-project-owner': handler mgmt-auth-prtb-controller: clusters.management.cattle.io "c-m-bt572cc6" not found, requeuing
2023/09/28 19:13:43 [ERROR] error syncing 'p-dhb9z/creator-project-owner': handler mgmt-auth-prtb-controller: clusters.management.cattle.io "c-m-bt572cc6" not found, requeuing
2023/09/28 19:13:44 [ERROR] error syncing 'p-dhb9z/prtb-mrz77': handler mgmt-auth-prtb-controller: clusters.management.cattle.io "c-m-bt572cc6" not found, requeuing
2023/09/28 19:13:53 [ERROR] error syncing 'p-dhb9z/creator-project-owner': handler mgmt-auth-prtb-controller: clusters.management.cattle.io "c-m-bt572cc6" not found, requeuing
2023/09/28 19:13:53 [ERROR] error syncing 'p-pcj48/creator-project-owner': handler mgmt-auth-prtb-controller: clusters.management.cattle.io "c-m-bt572cc6" not found, requeuing
2023/09/28 19:13:54 [ERROR] error syncing 'p-dhb9z/prtb-mrz77': handler mgmt-auth-prtb-controller: clusters.management.cattle.io "c-m-bt572cc6" not found, requeuing
W0928 19:13:54.253697      32 warnings.go:80] Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
2023/09/28 19:13:56 [ERROR] error syncing 'c-m-tpzhnwxn/p-cgvkz': handler mgmt-project-rbac-remove: failed to remove finalizer on controller.cattle.io/mgmt-project-rbac-remove, requeuing
2023/09/28 19:13:56 [ERROR] error syncing 'c-m-tpzhnwxn/p-gbvsj': handler mgmt-project-rbac-remove: failed to remove finalizer on controller.cattle.io/mgmt-project-rbac-remove, requeuing
2023/09/28 19:14:03 [ERROR] error syncing 'p-pcj48/creator-project-owner': handler mgmt-auth-prtb-controller: clusters.management.cattle.io "c-m-bt572cc6" not found, requeuing
2023/09/28 19:14:03 [ERROR] error syncing 'p-dhb9z/creator-project-owner': handler mgmt-auth-prtb-controller: clusters.management.cattle.io "c-m-bt572cc6" not found, requeuing
2023/09/28 19:14:04 [ERROR] error syncing 'p-dhb9z/prtb-mrz77': handler mgmt-auth-prtb-controller: clusters.management.cattle.io "c-m-bt572cc6" not found, requeuing
W0928 19:14:09.247961      32 warnings.go:80] Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
```

**Comment by dasarinaidu** [comment]
https://github.com/rancher/rancher/issues/42754

**Comment by KevinJoiner** [comment]
The problem is due to the following sequence of events.

1. Cluster gets marked for deletion by kube-apiserver and the `.deletionTimestamp` field is set on the cluster object.
2. The Project controller sees the cluster is being deleted and [deletes the systemProject](https://github.com/rancher/rancher/blob/63941ee3a6e413ee6355fab1c5f8e4a65e4604dc/pkg/controllers/management/auth/project_cluster_handler.go#L252), which sets the `.deletionTimestamp`  field on the system project.
3. The other [project lifecycle controller](https://github.com/rancher/rancher/blob/63941ee3a6e413ee6355fab1c5f8e4a65e4604dc/pkg/controllers/management/auth/project_cluster_handler.go#L149) see the project is being deleted and attempts to remove the finalizer set on the project.
4. Webhook rejects the request to remove the finalizer because when it attempts to [find a valid clusterName](https://github.com/rancher/webhook/blob/release/v0.4/pkg/resources/management.cattle.io/v3/project/validator.go#L138C3-L138C3) the cluster does not exist. 

Thus, the project lifecycle controller is never able to proceed.
This theory is valid only if objects are removed from the cache when their deletion timestamp is set, which may or may nor be true.

**Comment by MbolotSuse** [comment]
## Validation Template

## Root Cause

The `clusterName` field in the project spec had validation (on create and update) which ensured that it referred to a valid cluster. When a cluster was deleted, this triggered a process to remove all projects for that cluster. By the time that the project was ready to remove, rancher was unable to make changes to the project, since it referred to a non-existent cluster.

## What was fixed, or what change have occurred

- `Project.Spec.ClusterName` now only needs to refer to an existing cluster on create (i.e. we only check for cluster existence on create)
- To prevent people from changing this value to something invalid on update, this field is now immutable. 

## Areas or cases that should be tested

Creating a project with an invalid cluster name. These cases should fail, like before, including:
- Creating a project which is in a different namespace than the cluster that it is for (i.e. `namespace` doesn't match `spec.ClusterName`)
- Creating a project which refers to an invalid cluster (i.e. creating a project in the default namespace).

Updating a project to refer to an invalid cluster. Users should not be able to change the `spec.ClusterName` of a project. 

## What areas could experience regressions

Creating/Updating a project (specifically with regard to the `spec.ProjectName` field and the `spec.ResourceQuota` fields - quota validation should happen just like before).

## Are the repro steps accurate/minimal?
Yes. They are included on the issue.

**Comment by dasarinaidu** [comment]
Validated this issue on` v2.8-fc12e7d779577d10ded1a8e249f51727848b878e-head`. This issue got fixed and all the test cases around clusterName validations are passed.

I am closing this card.

**Test cases:**
1. Cluster Name : Null -- deny
2. Cluster Name : Invalid -- Deny
3. Cluster Name : Valid but No access - Deny
4. Cluster Name : Valid & NameSpace matches-- Accept
5. Cluster Name : Valid but Namespace NULL) -- Deny
6. Cluster Name : Valid but NameSpace Invalid -- Deny

**Comment by MSandro** [comment]
I've noticed this issue in v2.9.1

```
2024/09/04 12:39:48 [ERROR] error syncing 'p-qtqd8/creator-project-owner': handler mgmt-auth-prtb-controller: clusters.management.cattle.io "c-zqkf4" not found, requeuing
2024/09/04 12:39:48 [ERROR] error syncing 'p-b74w9/creator-project-owner': handler mgmt-auth-prtb-controller: clusters.management.cattle.io "c-bmt57" not found, requeuing
2024/09/04 12:39:48 [ERROR] error syncing 'p-xql9s/creator-project-owner': handler mgmt-auth-prtb-controller: clusters.management.cattle.io "c-bmt57" not found, requeuing
2024/09/04 12:39:48 [ERROR] error syncing 'p-db9vm/creator-project-owner': handler mgmt-auth-prtb-controller: clusters.management.cattle.io "c-9k5vn" not found, requeuing
2024/09/04 12:39:48 [ERROR] error syncing 'p-8tv5c/creator-project-owner': handler mgmt-auth-prtb-controller: clusters.management.cattle.io "c-bmt57" not found, requeuing
2024/09/04 12:39:52 [ERROR] error syncing 'c-bmt57/crtb-5kt6s': handler mgmt-auth-crtb-controller: clusters.management.cattle.io "c-bmt57" not found, requeuing
2024/09/04 12:39:52 [ERROR] error syncing 'c-bmt57/creator-cluster-owner': handler mgmt-auth-crtb-controller: clusters.management.cattle.io "c-bmt57" not found, requeuing
2024/09/04 12:39:52 [ERROR] error syncing 'c-9k5vn/creator-cluster-owner': handler mgmt-auth-crtb-controller: clusters.management.cattle.io "c-9k5vn" not found, requeuing
2024/09/04 12:39:52 [ERROR] error syncing 'c-zqkf4/creator-cluster-owner': handler mgmt-auth-crtb-controller: clusters.management.cattle.io "c-zqkf4" not found, requeuing
2024/09/04 12:39:58 [ERROR] error syncing 'p-b74w9/creator-project-owner': handler mgmt-auth-prtb-controller: clusters.management.cattle.io "c-bmt57" not found, requeuing
2024/09/04 12:39:58 [ERROR] error syncing 'p-qtqd8/creator-project-owner': handler mgmt-auth-prtb-controller: clusters.management.cattle.io "c-zqkf4" not found, requeuing
2024/09/04 12:39:58 [ERROR] error syncing 'p-8tv5c/creator-project-owner': handler mgmt-auth-prtb-controller: clusters.management.cattle.io "c-bmt57" not found, requeuing
2024/09/04 12:39:58 [ERROR] error syncing 'p-db9vm/creator-project-owner': handler mgmt-auth-prtb-controller: clusters.management.cattle.io "c-9k5vn" not found, requeuing
2024/09/04 12:39:58 [ERROR] error syncing 'p-zjmqp/creator-project-owner': handler mgmt-auth-prtb-controller: clusters.management.cattle.io "c-zqkf4" not found, requeuing
2024/09/04 12:39:58 [ERROR] error syncing 'p-v5d6f/creator-project-owner': handler mgmt-auth-prtb-controller: clusters.management.cattle.io "c-9k5vn" not found, requeuing
2024/09/04 12:39:58 [ERROR] error syncing 'p-xql9s/creator-project-owner': handler mgmt-auth-prtb-controller: clusters.management.cattle.io "c-bmt57" not found, requeuing
2024/09/04 12:40:02 [ERROR] error syncing 'c-bmt57/crtb-5kt6s': handler mgmt-auth-crtb-controller: clusters.management.cattle.io "c-bmt57" not found, requeuing
2024/09/04 12:40:02 [ERROR] error syncing 'c-bmt57/creator-cluster-owner': handler mgmt-auth-crtb-controller: clusters.management.cattle.io "c-bmt57" not found, requeuing
2024/09/04 12:40:02 [ERROR] error syncing 'c-9k5vn/creator-cluster-owner': handler mgmt-auth-crtb-controller: clusters.management.cattle.io "c-9k5vn" not found, requeuing
2024/09/04 12:40:02 [ERROR] error syncing 'c-zqkf4/creator-cluster-owner': handler mgmt-auth-crtb-controller: clusters.management.cattle.io "c-zqkf4" not found, requeuing
2024/09/04 12:40:08 [ERROR] error syncing 'p-qtqd8/creator-project-owner': handler mgmt-auth-prtb-controller: clusters.management.cattle.io "c-zqkf4" not found, requeuing
2024/09/04 12:40:08 [ERROR] error syncing 'p-8tv5c/creator-project-owner': handler mgmt-auth-prtb-controller: clusters.management.cattle.io "c-bmt57" not found, requeuing
2024/09/04 12:40:08 [ERROR] error syncing 'p-zjmqp/creator-project-owner': handler mgmt-auth-prtb-controller: clusters.management.cattle.io "c-zqkf4" not found, requeuing
2024/09/04 12:40:08 [ERROR] error syncing 'p-b74w9/creator-project-owner': handler mgmt-auth-prtb-controller: clusters.management.cattle.io "c-bmt57" not found, requeuing
2024/09/04 12:40:08 [ERROR] error syncing 'p-xql9s/creator-project-owner': handler mgmt-auth-prtb-controller: clusters.management.cattle.io "c-bmt57" not found, requeuing
2024/09/04 12:40:08 [ERROR] error syncing 'p-v5d6f/creator-project-owner': handler mgmt-auth-prtb-controller: clusters.management.cattle.io "c-9k5vn" not found, requeuing

```

**Comment by BloodyIron** [comment]
Can we get this reopened @dasarinaidu please? This is still happening, even in versions as recent as v2.12.3

Other relevant issues:

#46954

#53128

And I'm not seeing a solution for this at all
