### ISSUE TITLE
Rancher HA does not work with Rancher v1.1.0-dev1 due to rancher-compose issue

### ISSUE THREAD

**Issue by rmops** [rancher/rancher#4733]
**Rancher Version:**
v1.1.0-dev1
**Docker Version:**
Docker version 1.10.3, build 20f81dd
**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu 14.04.2
**Setup Details: (single node vs. single node, internal DB vs. external DB)**
3node ,external DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce: **
1.create database to a external db
2.start a node rancher server with external db
3.enable ha
![image](https://cloud.githubusercontent.com/assets/17241784/15105430/21ee2484-15f4-11e6-990b-cba28f0e3604.png)

4.put rancher-ha.sh to all 3 node
5.docker rm first node rancher server
6.run rancher-ha at all 3 node
bash ./rancher-ha.sh rancher/server:v1.1.0-dev1 

**Results:** 

find error for echo nde 
node A:
time="2016-05-05T16:23:28Z" level=error msg="Could not parse config for project management : Unsupported config option for cattle service: 'health_check'\nUnsupported config option for rancher-compose-executor service: 'health_check'\nUnsupported config option for go-machine-service service: 'health_check'\nUnsupported config option for websocket-proxy service: 'health_check'\nUnsupported config option for websocket-proxy-ssl service: 'health_check'"

node B:

time="2016-05-09T06:48:53Z" level=info msg="Container agent is not running in state &types.ContainerState{Status:\"exited\", Running:false, Paused:false, Restarting:false, OOMKilled:false, Dead:false, Pid:0, ExitCode:0, Error:\"\", StartedAt:\"2016-05-09T06:48:26.550120238Z\", FinishedAt:\"2016-05-09T06:48:37.612325337Z\"}" component=docker
time="2016-05-09T06:48:53Z" level=info msg="Deleting container 8508cc24318bc853033d9712584a5e1b57c28498b8ec8c1307201238bb81e541" component=docker
time="2016-05-09T06:48:53Z" level=info msg="Can not launch agent right now: Error response from daemon: Unable to remove filesystem for 8508cc24318bc853033d9712584a5e1b57c28498b8ec8c1307201238bb81e541: remove /var/lib/docker/containers/8508cc24318bc853033d9712584a5e1b57c28498b8ec8c1307201238bb81e541/shm: device or resource busy" component=service

node c:

time="2016-05-09T06:49:55Z" level=info msg="Can not launch agent right now: Server not available at http://172.17.0.1:18080/ping:" component=service
time="2016-05-09T06:50:01Z" level=info msg="Creating container rancher-ha-agent" component=docker
time="2016-05-09T06:50:01Z" level=info msg="Waiting for 3 host(s) to be active" component=cert
time="2016-05-09T06:50:03Z" level=info msg="Waiting for 3 host(s) to be active" component=cert
time="2016-05-09T06:50:05Z" level=info msg="Waiting for 3 host(s) to be active" component=cert
time="2016-05-09T06:50:07Z" level=info msg="Waiting for 3 host(s) to be active" component=cert
time="2016-05-09T06:50:09Z" level=info msg="Waiting for 3 host(s) to be active" component=cert
time="2016-05-09T06:50:11Z" level=info msg="Waiting for 3 host(s) to be active" component=cert
time="2016-05-09T06:50:13Z" level=info msg="Waiting for 3 host(s) to be active" component=cert
time="2016-05-09T06:50:15Z" level=info msg="Waiting for 3 host(s) to be active" component=cert

**Expected:**

**Comment by rmops** [comment]
I can find this message from echo node 

time="2016-05-09T06:51:04Z" level=info msg="Cluster changed, index=0, members=[10.1.0.53, 10.1.0.100, 10.1.0.101]" component=service

**Comment by Rucknar** [comment]
Step 5 "5.docker rm first node rancher server" Where did you get that from? looks to be the culprit for me.

I've done this prior and left the container for ranchers HA process to mop up, once the upgrade is completed.

**Comment by rmops** [comment]
I also tried let  the container for ranchers HA process to mop up,but still have the same issue
![rancher](https://cloud.githubusercontent.com/assets/17241784/15134676/eec08cf2-16a0-11e6-9c1e-0ba99f4bb5c9.png)

**Comment by HackerWilson** [comment]
@rmops same with you.

I deployed rancher successfully the first time, but when I removed containers and /var/lib/rancher/* then deployed again from the beginning, I got this error! This really confused me.

**Comment by LLParse** [comment]
This looks to be a regression in rancher-compose parsing. I will spend some time this morning testing.

@HackerWilson Do you by chance know if you were running a previous version before restarting? The HA script automatically launches the latest tagged release, which we updated to the new version on May 2nd.

**Comment by deniseschannon** [comment]
@rmops @HackerWilson @Rucknar 

With the changes to rancher-compose, we started having stricter validation on our docker-compose.yml files. Unfortunately, there was a typo for what rancher-compose directives were valid in docker-compose.yml. Due to how HA is set configured, we are hitting an issue. A fix has been made in rancher-compose that will be released with v1.1.0-dev2.

**Comment by rmops** [comment]
tried v1.1.0-dev2-rc3,but still not works well.



time="2016-05-19T07:19:09Z" level=info msg="Container cattle image is different rancher/server != rancher/server:v1.1.0-dev2-rc3" component=docker
time="2016-05-19T07:19:09Z" level=info msg="Container cattle is not running in state &types.ContainerState{Status:\"created\", Running:false, Paused:false, Restarting:false, OOMKilled:false, Dead:false, Pid:0, ExitCode:128, Error:\"nosuchcontainer: No such container: rancher-ha-parent\", StartedAt:\"0001-01-01T00:00:00Z\", FinishedAt:\"0001-01-01T00:00:00Z\"}" component=docker
time="2016-05-19T07:19:09Z" level=info msg="Deleting container 9efb786e8faa4d363c4c77b5e678f917293e5d48d3a7941733e0fe47c8511e0d" component=docker
time="2016-05-19T07:19:09Z" level=info msg="Creating container rancher-ha-cattle" component=docker
time="2016-05-19T07:19:09Z" level=info msg="Waiting for server to be available" component=cert
time="2016-05-19T07:19:09Z" level=info msg="Can not launch agent right now: Server not available at http://172.17.0.1:18080/ping:" component=service
time="2016-05-19T07:19:14Z" level=info msg="Cluster changed, index=2, members=[10.1.0.53, 10.1.0.100, 10.1.0.101]" component=service
time="2016-05-19T07:19:14Z" level=info msg="Creating container rancher-ha-tunnel-redis-2" component=docker
time="2016-05-19T07:19:15Z" level=info msg="Creating container rancher-ha-tunnel-zk-quorum-2" component=docker
time="2016-05-19T07:19:15Z" level=info msg="Creating container rancher-ha-tunnel-zk-leader-2" component=docker
time="2016-05-19T07:19:15Z" level=info msg="Creating container rancher-ha-tunnel-zk-client-2" component=docker
time="2016-05-19T07:19:16Z" level=info msg="Creating container rancher-ha-tunnel-redis-3" component=docker
time="2016-05-19T07:19:16Z" level=info msg="Creating container rancher-ha-tunnel-zk-quorum-3" component=docker
time="2016-05-19T07:19:17Z" level=info msg="Creating container rancher-ha-tunnel-zk-leader-3" component=docker
time="2016-05-19T07:19:17Z" level=info msg="Creating container rancher-ha-tunnel-zk-client-3" component=docker
time="2016-05-19T07:19:17Z" level=info msg="Creating container rancher-ha-zk" component=docker
time="2016-05-19T07:19:18Z" level=info msg="Creating container rancher-ha-redis" component=docker
time="2016-05-19T07:19:18Z" level=info msg="Waiting for server to be available" component=cert
time="2016-05-19T07:19:18Z" level=info msg="Can not launch agent right now: Server not available at http://172.17.0.1:18080/ping:" component=service
time="2016-05-19T07:19:23Z" level=info msg="Waiting for server to be available" component=cert
time="2016-05-19T07:19:23Z" level=info msg="Can not launch agent right now: Server not available at http://172.17.0.1:18080/ping:" component=service
time="2016-05-19T07:19:29Z" level=info msg="Can not launch agent right now: HA environment has not yet been created" component=service
time="2016-05-19T07:19:34Z" level=info msg="Can not launch agent right now: HA environment has not yet been created" component=service
time="2016-05-19T07:19:39Z" level=info msg="Can not launch agent right now: HA environment has not yet been created" component=service
time="2016-05-19T07:19:44Z" level=info msg="Can not launch agent right now: HA environment has not yet been created" component=service
time="2016-05-19T07:19:49Z" level=info msg="Can not launch agent right now: HA environment has not yet been created" component=service
time="2016-05-19T07:19:54Z" level=info msg="Can not launch agent right now: HA environment has not yet been created" component=service
time="2016-05-19T07:19:59Z" level=info msg="Can not launch agent right now: HA environment has not yet been created" component=service
time="2016-05-19T07:20:05Z" level=info msg="Can not launch agent right now: HA environment has not yet been created" component=service
time="2016-05-19T07:20:10Z" level=info msg="Can not launch agent right now: Certificates not yet created" component=service
time="2016-05-19T07:20:15Z" level=info msg="Creating container rancher-ha-agent" component=docker
time="2016-05-19T07:20:26Z" level=info msg="Container agent is not running in state &types.ContainerState{Status:\"exited\", Running:false, Paused:false, Restarting:false, OOMKilled:false, Dead:false, Pid:0, ExitCode:0, Error:\"\", StartedAt:\"2016-05-19T07:20:15.780703092Z\", FinishedAt:\"2016-05-19T07:20:24.787202796Z\"}" component=docker
time="2016-05-19T07:20:26Z" level=info msg="Deleting container 7a096afd4a28e52836c2a9be04104428de077504caa4e20d657ba9e53f006565" component=docker
time="2016-05-19T07:20:26Z" level=info msg="Can not launch agent right now: Error response from daemon: Unable to remove filesystem for 7a096afd4a28e52836c2a9be04104428de077504caa4e20d657ba9e53f006565: remove /var/lib/docker/containers/7a096afd4a28e52836c2a9be04104428de077504caa4e20d657ba9e53f006565/shm: device or resource busy" component=service

**Comment by rmops** [comment]
some logs from rancher-ha-cattle

2016-05-19 07:36:34,654 ERROR [:] [] [] [] [cutorService-35] [i.c.p.e.e.i.ProcessEventListenerImpl] Unknown exception running process [serviceevent.create:2604] on [435] java.lang.IllegalStateException: Attempt to cancel when process is still transitioning
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:191) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:158) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:108) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:105) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:105) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.eventing.impl.ProcessEventListenerImpl.processExecute(ProcessEventListenerImpl.java:74) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.eventing.impl.ProcessEventListenerImpl.processExecute(ProcessEventListenerImpl.java:56) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at sun.reflect.GeneratedMethodAccessor479.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_95]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_95]
	at io.cattle.platform.eventing.annotation.MethodInvokingListener$1.doWithLockNoResult(MethodInvokingListener.java:76) [cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.annotation.MethodInvokingListener.onEvent(MethodInvokingListener.java:72) [cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:135) [cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_95]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_95]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_95]
Caused by: io.cattle.platform.engine.process.impl.ProcessCancelException: State [updating-reinitializing] is not valid
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.preRunStateCheck(DefaultProcessInstanceImpl.java:282) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:183) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:158) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:108) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:105) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:105) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.manager.impl.DefaultProcessManager.scheduleProcessInstance(DefaultProcessManager.java:60) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.scheduleProcessInstance(DefaultObjectProcessManager.java:47) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.scheduleProcessInstance(DefaultObjectProcessManager.java:52) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.iaas.healthcheck.service.impl.HealthcheckServiceImpl.updateInstanceHealthState(HealthcheckServiceImpl.java:191) ~[cattle-iaas-healthcheck-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.iaas.healthcheck.service.impl.HealthcheckServiceImpl.processHealthcheckInstance(HealthcheckServiceImpl.java:113) ~[cattle-iaas-healthcheck-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.iaas.healthcheck.service.impl.HealthcheckServiceImpl$1.doWithLockNoResult(HealthcheckServiceImpl.java:89) ~[cattle-iaas-healthcheck-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.iaas.healthcheck.service.impl.HealthcheckServiceImpl.updateHealthcheck(HealthcheckServiceImpl.java:86) ~[cattle-iaas-healthcheck-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.iaas.healthcheck.process.ServiceEventCreate.handle(ServiceEventCreate.java:41) ~[cattle-iaas-healthcheck-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:446) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:393) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:387) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:387) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:493) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:320) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:260) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:257) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:185) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	... 31 common frames omitted

**Comment by aemneina** [comment]
Just tried out Rancher HA using 1.1.0-dev2-rc4. Was able to deploy successfully and get all the services running. The only issues I was hitting were config issues due to user error. All HA containers/services are operational now. Would you guys mind trying with 1.1.0-dev2-rc4 (or rc5) tags?

**Comment by deniseschannon** [comment]
This was verified with @aemneina in v1.1.0-dev2-rc4. 

It will be available in v1.1.0-dev2.

**Comment by rmops** [comment]
sure,I will try v1.1.0-dev2-rc4 today.

**Comment by rmops** [comment]
![image](https://cloud.githubusercontent.com/assets/17241784/15526069/ac49eea0-2261-11e6-9ebd-b8d5c0d80879.png)

after rancher become ha,some host lost....

**Comment by rmops** [comment]
![image](https://cloud.githubusercontent.com/assets/17241784/15526310/a2dc4622-2263-11e6-88ee-98664404bf24.png)
![image](https://cloud.githubusercontent.com/assets/17241784/15526325/b62ec484-2263-11e6-835d-c8def1e9df4c.png)

**Comment by rmops** [comment]
m:\"-simulated-\", Time:0}"
time="2016-05-25T02:34:33Z" level="info" msg="Connecting to proxy." url="wss://prod-rancher-slb.hzvb.kankanapp.com.cn/v1/connectbackend?token=eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjE0NjQxNDM5NzMsInN1YiI6ImNhdHRsZSIsImlzcyI6Imh0dHA6XC9cL2NhdHRsZS5pbyIsInJlcG9ydGVkVXVpZCI6ImVkMjhlOGNmLWQ5Y2MtNGRjYy05MjQ1LWIzYTUyNzgwMmY1YiIsImlhdCI6MTQ2NDE0MzY3Mywia2lkIjoiZGVmYXVsdCJ9.BEOQIfcAitiYpHQwdTFDT87qbv-LmLYn3FGS4AqutFRiBkSZsUnXk-jsRQaDQK5mXwQAB1kukXnakLnpwoWtBpRA9H1FumQ8V8qQrZQIcqwnHsigspuIyT7YoYjxTxuhoiio99aP4aLpfGCnpQ8LXaTZTjY10ONt4lcJNyoEVe6EFRH02rBxbM4p6Nmo81FYpQsffk6RqXYK4Jg_cSlRLUDbzOu7s01wuvZ1B0ZJ08011h6WHwUEDDHCsfZEeM-yMVwj2CAf1pqHlGZTzQbJ7e-H5mRr_0vtBu8bngb9yjApyeYPaAfQVBW8XT3UJIQpyrxtwQcninXxen5WeoGwjQ"
time="2016-05-25T02:34:33Z" level="fatal" msg="Failed to connect to proxy." error="x509: certificate signed by unknown authority"
time="2016-05-25T02:34:35Z" level="info" msg="Starting event router."
time="2016-05-25T02:34:35Z" level="info" msg="Watching state directory: /var/lib/rancher/state/containers"
time="2016-05-25T02:34:35Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"95aa2a43f0d1cf6c6a0143794d7c4949f176de53fe97a63ee59273ae94fed96c\", From:\"-simulated-\", Time:0}"
time="2016-05-25T02:34:35Z" level="info" msg="Connecting to proxy." url="wss://prod-rancher-slb.hzvb.kankanapp.com.cn/v1/connectbackend?token=eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjE0NjQxNDM5NzUsInN1YiI6ImNhdHRsZSIsImlzcyI6Imh0dHA6XC9cL2NhdHRsZS5pbyIsInJlcG9ydGVkVXVpZCI6ImVkMjhlOGNmLWQ5Y2MtNGRjYy05MjQ1LWIzYTUyNzgwMmY1YiIsImlhdCI6MTQ2NDE0MzY3NSwia2lkIjoiZGVmYXVsdCJ9.d5pMD0FxmXoukl-nXEcXh_bvfIwikAaNSguf-yexqZ5-TCnByJdI1gsCWmgyWJoDyCGd59KfnhzjqghUS8W_u2-gkFN9lP_VjDBz6HbL5oz3qZ2bl477hh-X89u4JKneYYMnfKazu0UfFAUeMw9RZVg_B6wYCrJbz2AMUjJyb7TfwP9F5fMxScOUcw7SQZeakcwP6rnWsAawhhuPzdBl-lw99mxyyxXUWokZcUy232qi8FD52RJrIxKRmGqoo0w-9x5XOqt3Lk19HuPvq_sngmBI0s_kjxgclprmuCorteA0NwU517eKJCmvqpf3OrOXJPwdHaYbvrcERP8kur88mg"
time="2016-05-25T02:34:35Z" level="fatal" msg="Failed to connect to proxy." error="x509: certificate signed by unknown authority"
time="2016-05-25T02:34:37Z" level="info" msg="Starting event router."
time="2016-05-25T02:34:37Z" level="info" msg="Watching state directory: /var/lib/rancher/state/containers"
time="2016-05-25T02:34:37Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"95aa2a43f0d1cf6c6a0143794d7c4949f176de53fe97a63ee59273ae94fed96c\", From:\"-simulated-\", Time:0}"
time="2016-05-25T02:34:37Z" level="info" msg="Connecting to proxy." url="wss://prod-rancher-slb.hzvb.kankanapp.com.cn/v1/connectbackend?token=eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjE0NjQxNDM5NzcsInN1YiI6ImNhdHRsZSIsImlzcyI6Imh0dHA6XC9cL2NhdHRsZS5pbyIsInJlcG9ydGVkVXVpZCI6ImVkMjhlOGNmLWQ5Y2MtNGRjYy05MjQ1LWIzYTUyNzgwMmY1YiIsImlhdCI6MTQ2NDE0MzY3Nywia2lkIjoiZGVmYXVsdCJ9.f-f28cIUGTD5MS1slndAdb1fIWeMktI-nqHFQtMmRwVAcfdHt8Aw805xlT8y8TP-MnqrdcezRBIMWmFyuFgMNsU6vP2RShRxMAfH7IE3zv1Bz7jJAk18U6bOevT_V1n0v1DrOHPpMs2wLv7sZPPYLbBWODDl7XVHZi9WeYwTQPkDv_BJ9NlTzGJk6Y8-wdvxcQAwO4hxSIbHEzvtz7GHlUDbRpMQRp0nEzqo1_K06WUKD4U8tS90PkNMaghoAyXBiNwuRNi44Eqa20TzcXmymlx9MxQakw3lbnsW1BZL_fd-3RZ61OWFKGLm3e0otBny8EdvYErDSpF1peXV0_cqdQ"
time="2016-05-25T02:34:37Z" level="fatal" msg="Failed to connect to proxy." error="x509: certificate signed by unknown authority"

**Comment by rmops** [comment]
ssl create by rancher-ha....

**Comment by aemneina** [comment]
@rmops what load balancer are you using here, what does your protocol/port mapping look like?

**Comment by rmops** [comment]
I use haproxy as load balancer, tcp port map

**Comment by aemneina** [comment]
@rmops if you're terminating SSL at the Rancher servers, your port mapping should map port 443 on the VIP to 444 on the rancher server. Is that the case?

**Comment by rmops** [comment]
Hi aemneina,

Yesterday I map 443 to 443,just now  I map 443 on vip to 444 on rancher server. It show Unknow SSL protocol error.


Here is the detail testing.
VIP:10.1.0.102
RealServer:10.1.0.101,10.1.0.100,10.1.0.99


root@ops01:/var/lib# curl -I -k https://10.1.0.102:443/
curl: (35) Unknown SSL protocol error in connection to 10.1.0.102:443

root@ops01:/var/lib# curl -I -k https://10.1.0.101:444/
curl: (35) Unknown SSL protocol error in connection to 10.1.0.101:444

root@ops01:/var/lib# curl -I -k https://10.1.0.101:443/
HTTP/1.1 200 OK
Date: Wed, 25 May 2016 23:08:45 GMT
Set-Cookie: PL=rancher;Path=/
Expires: Thu, 01 Jan 1970 00:00:00 GMT
X-API-Schemas: https://10.1.0.101/v1/schemas
X-API-ACCOUNT-ID: 1a1
X-API-Client-IP: 10.1.0.40
Content-Type: application/json; charset=utf-8
Content-Length: 324
Server: Jetty(9.2.11.v20150529)


root@ops01:/var/lib# curl -I -k https://10.1.0.100:444/
curl: (35) Unknown SSL protocol error in connection to 10.1.0.100:444
root@ops01:/var/lib# curl -I -k https://10.1.0.100:443/
HTTP/1.1 200 OK
Date: Wed, 25 May 2016 23:13:48 GMT
Set-Cookie: PL=rancher;Path=/
Expires: Thu, 01 Jan 1970 00:00:00 GMT
X-API-Schemas: https://10.1.0.100/v1/schemas
X-API-ACCOUNT-ID: 1a1
X-API-Client-IP: 10.1.0.40
Content-Type: application/json; charset=utf-8
Content-Length: 324
Server: Jetty(9.2.11.v20150529)

**Comment by vincent99** [comment]
81 and 444 are the endpoints which handle [PROXY protocol](http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt), which you need if (and largely only if) using AWS ELB.

**Comment by rmops** [comment]
When single rancher server it use http://Single_ServerIP:8080 as API url
When I upgrade that to a cluster ,the API switch to https://ha_proxy_IP:443
I need new API url works.

**Comment by rmops** [comment]
I just use tcp forward

**Comment by rmops** [comment]
So yesterday I map 80->80 and 443-443 should works?

**Comment by rmops** [comment]
any update？

**Comment by aemneina** [comment]
@rmops sorry for the lag in response. Those mappings should work.
