### ISSUE TITLE
[BUG] Harvester Cloud Credential Expiry not Updated

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#47491]
**Rancher Server Setup**
- Rancher version: v2.10-head
- Installation option (Docker install/Helm Chart): Docker install (affects both)
- Proxy/Cert Details: N/A - self signed.

**Information about the Cluster**
- Kubernetes version: N/A - local cluster issue.
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

Admin

**Describe the bug**

When a Harvester Cloud Credential is regenerated, the annotation containing expiry time is not updated.

**To Reproduce**
1. Create a harvester could credential. Review the `cattle.io/expirationTime` annotation.
2. Update the cloud credential, using a new kubeconfig token (generated after the first one). Review the `cattle.io/expirationTime` annotation.

**Result**

The annotation hasn't changed, despite the fact that there is a new token with a new expiration time.

**Expected Result**

The annotation should change, since the new token has a new expiration time. 

**Screenshots**
N/A.

**Additional context**
This is caused because norman views annotations which contain `cattle.io/` in them as [protected](https://github.com/rancher/norman/blob/78a520c160ab8921ae77392d5f7d4d12d35740b1/types/convert/merge/merge.go#L45), and disallows updating their value (even when Rancher store code is the thing updating the value).

**Comment by MbolotSuse** [comment]
## Validation Template

## Root Cause

Norman prevents updates to annotations which contain "cattle.io/", as seen [here](https://github.com/rancher/norman/blob/78a520c160ab8921ae77392d5f7d4d12d35740b1/types/convert/merge/merge.go#L45). Since the token expiration time was in the "cattle.io/expiration-timestamp" annotation, when the credential was re-generated this annotation was unchanged, which made it appear like the cloud credential was still going to expire. 

## What was fixed, or what change have occurred

The expiration time is now stored in `rancher.io/expiration-timestamp`. This allows it to be updated, since rancher.io annotations are not protected.

## Areas or cases that should be tested

1. Create a new harvester cloud credential. Make sure that `rancher.io/expiration-timestamp` is set to the correct value.
2. Renew the credential through the UI. Make sure that the `rancher.io/expiration-timestamp` is set the the new value - both on the response to the update call, and on future calls to get the cloud credential. The backing secret in `cattle-global-data` should also have this value set to the new value.
3. Create a harvester cloud credential on a previous release of Rancher. Upgrade to a new version. Ensure that the current cloud credentials have `rancher.io/expiration-timestamp` set correctly, both in the secret and in get calls to the cloud credentials endpoint `/v3/cloudcredentials`.

## What areas could experience regressions

1. Automatic addition of the annotation for existing cloud credentials on upgrade.
2. Ability of the UI to rotate/renew cloud credentials.
3. Ability of the UI to read the expiration time of the harvester cloud credentials.

## Are the repro steps accurate/minimal?

Yes, they are included on the issue. A script to help create/update harvester cloud credentials in a minimal way is available on request.

**Comment by irishgordo** [comment]
@MbolotSuse  - with v2.10.0-alpha2, does the setting `ui-dashboard-index` to `https://releases.rancher.com/dashboard/master/index.html` not inteded to work?
I'm having issues getting the UI to display with the information surrounding the ability to renew/refresh the cloud-credentials either through cloud-credentials index or cluster's index.
I additionally tried to change the `ui-index` to the same url/uri as that of the `ui-dashboard-index` but haven't seen any changes propegate.
![Screenshot from 2024-10-14 16-36-44](https://github.com/user-attachments/assets/05c492f5-a1e6-40af-957e-b40141b60d8c)
![Screenshot from 2024-10-14 16-36-22](https://github.com/user-attachments/assets/9f64b188-94e4-4354-99e7-622dd403f7a2)

**Comment by MbolotSuse** [comment]
@irishgordo Try setting `ui-dashboard-index` to `https://releases.rancher.com/dashboard/latest/index.html`, looks like I was wrong about the UI URL for the master branch.

**Comment by irishgordo** [comment]
@MbolotSuse thanks for that suggestion :smile:  :+1: 
I did try to just implement that in modifying:
- at first just the `ui-dashboard-index`
- then after a few hard refreshes / reloads & incognito/private window
    - tried to then modify `ui-index` as well, rinse & repeat ^

But I'm not currently able to see the needed UI changes on v2.10.0-alpha2 w/ the `latest` in `ui-dashboard-index` or `ui-dashboard-index` + `ui-index`.

Is there a v2.10.0-alpha3 that will be released soon that would perhaps already have the UI bundled?

**Comment by irishgordo** [comment]
@MbolotSuse after upgrading to v2.10.0-alpha3 I'm still not able to see the UI changes:

![Screenshot from 2024-10-18 15-07-43](https://github.com/user-attachments/assets/76fd4ac2-63b0-4e06-9f19-b7c87faaa9c8)
![Screenshot from 2024-10-18 15-07-12](https://github.com/user-attachments/assets/393c0044-fd55-41bb-b27d-5bc950b6cf36)

It looks like `latest` is set appropriately too.

**Comment by irishgordo** [comment]
`ui-offline-perferred` set to `"false"` as value does fix things ^ :smile: :+1:

**Comment by irishgordo** [comment]
@MbolotSuse in general this all looks good :smile: :+1:  - thanks for all the help in getting things set up :smile: 

I'll go ahead and close this out, as @m-ildefons looks to cover https://github.com/rancher/rancher/issues/47583 - later.

as a brief mention-> [a small workaround on Harvester side from 6821](https://github.com/harvester/harvester/issues/6821#issuecomment-2420731729) to validate new cloud-credential based v1.31.1+rke2r1 cluster creations

cc: @khushboo-rancher @bk201 

### Physical Bare-Metal Info
- Node 7 HP DL160 Gen9:
	- Hardware:
		- Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
		- 64GB RAM
		- 2 Logical Volumes, P440 4GB RAID Controller:
			- 1 RAID 0 480GB:
				- Kingston SSD
			- 1 RAID 0 480GB
				- Kingston SSD

### Harvester Info:
- Harvester v1.3.2, Single Node
- Harvester v0.6.9 Node Driver in v2.9.2 Rancher
- Harvester v0.7.0 Node Driver in v2.10.0-alpha3 Rancher

### Rancher Info:
- rke2 version v1.30.5+rke2r1 (0c83bc82315cd61664880d0b52a7e070e9fbd623)
	- rancher-cleanup leveraged prior to install
- Harvester v1.3.2 VM w/ 50Gi Disk (virtio), 4C, 8Gi Mem, VLAN 1 Networking over MGMT Interface
- helm install & helm upgrade
- ubuntu-jammy-cloud-img-amd64-kvm.img
- *.sslip.io* based server-url


### Rancher v2.9.2 Cluster
- `Kubernetes Version: v1.30.4+rke2r1`
- 1 Machine Pool, 3 Machines
- 40Gi Disk, 4C, 8Gi Mem, each node



### v2.9.2 

- kubectl get secrets/cc-r99ml -n cattle-global-data -o yaml
```
apiVersion: v1
data:
  harvestercredentialConfig-clusterId: Yy1tLXFqN2hua2Yy
  harvestercredentialConfig-clusterType: aW1wb3J0ZWQ=
  harvestercredentialConfig-kubeconfigContent: YXBpVmVyc2lvbjogdjEKa2luZDogQ29uZmlnCmNsdXN0ZXJzOgotIG5hbWU6ICJ2MTMyaGFydmVzdGVybm9kZSIKICBjbHVzdGVyOgogICAgc2VydmVyOiAiaHR0cHM6Ly9yYW5jaGVyLjE5Mi4xNjguMTA0LjIwNC5zc2xpcC5pby9rOHMvY2x1c3RlcnMvYy1tLXFqN2hua2YyIgogICAgY2VydGlmaWNhdGUtYXV0aG9yaXR5LWRhdGE6ICJMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VKMlJFTkRRXAogICAgICBWZFBaMEYzU1VKQlowbENRVVJCUzBKblozRm9hMnBQVUZGUlJFRnFRa2ROVW5kM1IyZFpSRlpSVVV0RmVFNXJaVmMxYUdKWGJHb0tZXAogICAgICBrZHNlbVJIVm5WYVdFbDBZak5LYmsxVFdYZEtRVmxFVmxGUlJFUkNNV3RsVnpWb1lsZHNhbUpIYkhwa1IxWjFXbGhKZEZreVJrRk5WXAogICAgICBHTjVUMVJKTkFwTmFrVjRUbXBCWlVaM01IbE9SRVYzVFZSbmVVMUVRVFJOZWxwaFJuY3dlazVFUlhkTlZGbDVUVVJCTkUxNldtRk5SXAogICAgICBWbDRTRVJCWVVKblRsWkNRVzlVQ2tVeVVqVmliVVowWVZkT2MyRllUakJhVnpWc1kya3hkbU50WTNoS2FrRnJRbWRPVmtKQlRVMUlWXAogICAgICAxSTFZbTFHZEdGWFRuTmhXRTR3V2xjMWJHTnBNV29LV1ZWQmVFNTZTVFZOYW1kNVRWUkZNazFHYTNkRmQxbElTMjlhU1hwcU1FTkJVXAogICAgICBWbEpTMjlhU1hwcU1FUkJVV05FVVdkQlJVUnJjMVl5V2xkVVNsRkpTZ295WkhKaFprOVZWVkp5ZGtVeVVXTlNSRlEwVUVreVkweFVXXAogICAgICBtVnVOSEJhYUN0dlVuRk1WM1ZKUWtoRlkzRTNWVTlsWlhwUmNuVTVlRkZJU21zNFl6RklDbWxWT0U5cVMyazNPV0ZPUTAxRlFYZEVaXAogICAgICAxbEVWbEl3VUVGUlNDOUNRVkZFUVdkTGEwMUJPRWRCTVZWa1JYZEZRaTkzVVVaTlFVMUNRV1k0ZDBoUldVUUtWbEl3VDBKQ1dVVkdSXAogICAgICAxbDFaRTFVYjNGTU5EQk1lREJQY1VZMVZXdElSR0ZtVkRWQ1RVRnZSME5EY1VkVFRUUTVRa0ZOUTBFd1kwRk5SVkZEU1Vkd2VRcFJaXAogICAgICBtdDBkbm8yUVVsVFNXMU9USGxxUVhKQ2FWaEllbUZVZG1wb1JrODBRMVJOZG5WUldGTmhRV2xCYkZwcWJYZE1hRGxvUm1kSVVGQk5WXAogICAgICAzcHpiMGhYQ201dVNIcEZSMncxVUdoYVRWVlBWRkpwV0ZGRldHYzlQUW90TFMwdExVVk9SQ0JEUlZKVVNVWkpRMEZVUlMwdExTMHQiCgp1c2VyczoKLSBuYW1lOiAidjEzMmhhcnZlc3Rlcm5vZGUiCiAgdXNlcjoKICAgIHRva2VuOiAia3ViZWNvbmZpZy11c2VyLXp6OXprMmxzbjQ6Z2xrMmRicDg5bTI0c3p2azdrNGJyeGx2bHN3dDQ1N2x0Nzg2czU2N213NGQ0NHNndDZ6d2g5IgoKCmNvbnRleHRzOgotIG5hbWU6ICJ2MTMyaGFydmVzdGVybm9kZSIKICBjb250ZXh0OgogICAgdXNlcjogInYxMzJoYXJ2ZXN0ZXJub2RlIgogICAgY2x1c3RlcjogInYxMzJoYXJ2ZXN0ZXJub2RlIgoKY3VycmVudC1jb250ZXh0OiAidjEzMmhhcnZlc3Rlcm5vZGUi
kind: Secret
metadata:
  annotations:
    field.cattle.io/creatorId: user-zz9zk
    field.cattle.io/description: harvester v132 cloud credential start
    field.cattle.io/name: harvester-v132-cc-v292-start
    provisioning.cattle.io/driver: harvester
  creationTimestamp: "2024-10-18T21:34:39Z"
  generateName: cc-
  labels:
    cattle.io/creator: norman
  name: cc-r99ml
  namespace: cattle-global-data
  resourceVersion: "379682"
  uid: fa65910a-e5d9-401b-9bc6-5f526180b6dd
type: Opaque

```


Decoded:
```
harvestercredentialConfig-clusterId: c-m-qj7hnkf2                                                                                                                                           
harvestercredentialConfig-clusterType: imported                                                                                                                                             
harvestercredentialConfig-kubeconfigContent: |-                                                                                                                                             
  apiVersion: v1                                                                                                                                                                            
  kind: Config                                                                                                                                                                              
  clusters:                                                                                                                                                                                 
  - name: "v132harvesternode"                                                                                                                                                               
    cluster:                                                                                                                                                                                
      server: "https://rancher.192.168.104.204.sslip.io/k8s/clusters/c-m-qj7hnkf2"                                                                                                          
      certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2RENDQ\                                                                                                       
        VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\                                                                                                       
        kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\                                                                                                       
        GN5T1RJNApNakV4TmpBZUZ3MHlOREV3TVRneU1EQTRNelphRncwek5ERXdNVFl5TURBNE16WmFNR\                                                                                                       
        Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\                                                                                                       
        1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE56STVNamd5TVRFMk1Ga3dFd1lIS29aSXpqMENBU\                                                                                                       
        VlJS29aSXpqMERBUWNEUWdBRURrc1YyWldUSlFJSgoyZHJhZk9VVVJydkUyUWNSRFQ0UEkyY0xUW\                                                                                                       
        mVuNHBaaCtvUnFMV3VJQkhFY3E3VU9lZXpRcnU5eFFISms4YzFICmlVOE9qS2k3OWFOQ01FQXdEZ\                                                                                                       
        1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGR\                                                                                                       
        1l1ZE1Ub3FMNDBMeDBPcUY1VWtIRGFmVDVCTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUdweQpRZ\                                                                                                       
        mt0dno2QUlTSW1OTHlqQXJCaVhIemFUdmpoRk80Q1RNdnVRWFNhQWlBbFpqbXdMaDloRmdIUFBNV\                                                                                                       
        3pzb0hXCm5uSHpFR2w1UGhaTVVPVFJpWFFFWGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"                                                                                                        
                                                                                                                                                                                            
  users:                                                                                                                                                                                    
  - name: "v132harvesternode"                                                                                                                                                               
    user:                                                                                                                                                                                   
      token: "kubeconfig-user-zz9zk2lsn4:glk2dbp89m24szvk7k4brxlvlswt457lt786s567mw4d44sgt6zwh9"                                                                                            
                                                                                                                                                                                            
                                                                                                                                                                                            
  contexts:                                                                                                                                                                                 
  - name: "v132harvesternode"                                                                                                                                                               
    context:                                                                                                                                                                                
      user: "v132harvesternode"                                                                                                                                                             
      cluster: "v132harvesternode"                                                                                                                                                          
                                                                                                                                                                                            
  current-context: "v132harvesternode"   
```


### v2.10.0-alpha3 cc-r99ml Cloud Credential Before Renewal

```

apiVersion: v1
data:
  harvestercredentialConfig-clusterId: Yy1tLXFqN2hua2Yy
  harvestercredentialConfig-clusterType: aW1wb3J0ZWQ=
  harvestercredentialConfig-kubeconfigContent: YXBpVmVyc2lvbjogdjEKa2luZDogQ29uZmlnCmNsdXN0ZXJzOgotIG5hbWU6ICJ2MTMyaGFydmVzdGVybm9kZSIKICBjbHVzdGVyOgogICAgc2VydmVyOiAiaHR0cHM6Ly9yYW5jaGVyLjE5Mi4xNjguMTA0LjIwNC5zc2xpcC5pby9rOHMvY2x1c3RlcnMvYy1tLXFqN2hua2YyIgogICAgY2VydGlmaWNhdGUtYXV0aG9yaXR5LWRhdGE6ICJMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VKMlJFTkRRXAogICAgICBWZFBaMEYzU1VKQlowbENRVVJCUzBKblozRm9hMnBQVUZGUlJFRnFRa2ROVW5kM1IyZFpSRlpSVVV0RmVFNXJaVmMxYUdKWGJHb0tZXAogICAgICBrZHNlbVJIVm5WYVdFbDBZak5LYmsxVFdYZEtRVmxFVmxGUlJFUkNNV3RsVnpWb1lsZHNhbUpIYkhwa1IxWjFXbGhKZEZreVJrRk5WXAogICAgICBHTjVUMVJKTkFwTmFrVjRUbXBCWlVaM01IbE9SRVYzVFZSbmVVMUVRVFJOZWxwaFJuY3dlazVFUlhkTlZGbDVUVVJCTkUxNldtRk5SXAogICAgICBWbDRTRVJCWVVKblRsWkNRVzlVQ2tVeVVqVmliVVowWVZkT2MyRllUakJhVnpWc1kya3hkbU50WTNoS2FrRnJRbWRPVmtKQlRVMUlWXAogICAgICAxSTFZbTFHZEdGWFRuTmhXRTR3V2xjMWJHTnBNV29LV1ZWQmVFNTZTVFZOYW1kNVRWUkZNazFHYTNkRmQxbElTMjlhU1hwcU1FTkJVXAogICAgICBWbEpTMjlhU1hwcU1FUkJVV05FVVdkQlJVUnJjMVl5V2xkVVNsRkpTZ295WkhKaFprOVZWVkp5ZGtVeVVXTlNSRlEwVUVreVkweFVXXAogICAgICBtVnVOSEJhYUN0dlVuRk1WM1ZKUWtoRlkzRTNWVTlsWlhwUmNuVTVlRkZJU21zNFl6RklDbWxWT0U5cVMyazNPV0ZPUTAxRlFYZEVaXAogICAgICAxbEVWbEl3VUVGUlNDOUNRVkZFUVdkTGEwMUJPRWRCTVZWa1JYZEZRaTkzVVVaTlFVMUNRV1k0ZDBoUldVUUtWbEl3VDBKQ1dVVkdSXAogICAgICAxbDFaRTFVYjNGTU5EQk1lREJQY1VZMVZXdElSR0ZtVkRWQ1RVRnZSME5EY1VkVFRUUTVRa0ZOUTBFd1kwRk5SVkZEU1Vkd2VRcFJaXAogICAgICBtdDBkbm8yUVVsVFNXMU9USGxxUVhKQ2FWaEllbUZVZG1wb1JrODBRMVJOZG5WUldGTmhRV2xCYkZwcWJYZE1hRGxvUm1kSVVGQk5WXAogICAgICAzcHpiMGhYQ201dVNIcEZSMncxVUdoYVRWVlBWRkpwV0ZGRldHYzlQUW90TFMwdExVVk9SQ0JEUlZKVVNVWkpRMEZVUlMwdExTMHQiCgp1c2VyczoKLSBuYW1lOiAidjEzMmhhcnZlc3Rlcm5vZGUiCiAgdXNlcjoKICAgIHRva2VuOiAia3ViZWNvbmZpZy11c2VyLXp6OXprMmxzbjQ6Z2xrMmRicDg5bTI0c3p2azdrNGJyeGx2bHN3dDQ1N2x0Nzg2czU2N213NGQ0NHNndDZ6d2g5IgoKCmNvbnRleHRzOgotIG5hbWU6ICJ2MTMyaGFydmVzdGVybm9kZSIKICBjb250ZXh0OgogICAgdXNlcjogInYxMzJoYXJ2ZXN0ZXJub2RlIgogICAgY2x1c3RlcjogInYxMzJoYXJ2ZXN0ZXJub2RlIgoKY3VycmVudC1jb250ZXh0OiAidjEzMmhhcnZlc3Rlcm5vZGUi
kind: Secret
metadata:
  annotations:
    field.cattle.io/creatorId: user-zz9zk
    field.cattle.io/description: harvester v132 cloud credential start
    field.cattle.io/name: harvester-v132-cc-v292-start
    provisioning.cattle.io/driver: harvester
    rancher.io/expiration-timestamp: "1729289977000"
  creationTimestamp: "2024-10-18T21:34:39Z"
  generateName: cc-
  labels:
    cattle.io/creator: norman
  name: cc-r99ml
  namespace: cattle-global-data
  resourceVersion: "392781"
  uid: fa65910a-e5d9-401b-9bc6-5f526180b6dd
type: Opaque
╭─mike at suse-
```

#### cc-r99ml after renewal
```

apiVersion: v1
data:
  harvestercredentialConfig-clusterId: Yy1tLXFqN2hua2Yy
  harvestercredentialConfig-clusterType: aW1wb3J0ZWQ=
  harvestercredentialConfig-kubeconfigContent: YXBpVmVyc2lvbjogdjEKa2luZDogQ29uZmlnCmNsdXN0ZXJzOgotIG5hbWU6ICJ2MTMyaGFydmVzdGVybm9kZSIKICBjbHVzdGVyOgogICAgc2VydmVyOiAiaHR0cHM6Ly9yYW5jaGVyLjE5Mi4xNjguMTA0LjIwNC5zc2xpcC5pby9rOHMvY2x1c3RlcnMvYy1tLXFqN2hua2YyIgogICAgY2VydGlmaWNhdGUtYXV0aG9yaXR5LWRhdGE6ICJMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VKMlJFTkRRXAogICAgICBWZFBaMEYzU1VKQlowbENRVVJCUzBKblozRm9hMnBQVUZGUlJFRnFRa2ROVW5kM1IyZFpSRlpSVVV0RmVFNXJaVmMxYUdKWGJHb0tZXAogICAgICBrZHNlbVJIVm5WYVdFbDBZak5LYmsxVFdYZEtRVmxFVmxGUlJFUkNNV3RsVnpWb1lsZHNhbUpIYkhwa1IxWjFXbGhKZEZreVJrRk5WXAogICAgICBHTjVUMVJKTkFwTmFrVjRUbXBCWlVaM01IbE9SRVYzVFZSbmVVMUVRVFJOZWxwaFJuY3dlazVFUlhkTlZGbDVUVVJCTkUxNldtRk5SXAogICAgICBWbDRTRVJCWVVKblRsWkNRVzlVQ2tVeVVqVmliVVowWVZkT2MyRllUakJhVnpWc1kya3hkbU50WTNoS2FrRnJRbWRPVmtKQlRVMUlWXAogICAgICAxSTFZbTFHZEdGWFRuTmhXRTR3V2xjMWJHTnBNV29LV1ZWQmVFNTZTVFZOYW1kNVRWUkZNazFHYTNkRmQxbElTMjlhU1hwcU1FTkJVXAogICAgICBWbEpTMjlhU1hwcU1FUkJVV05FVVdkQlJVUnJjMVl5V2xkVVNsRkpTZ295WkhKaFprOVZWVkp5ZGtVeVVXTlNSRlEwVUVreVkweFVXXAogICAgICBtVnVOSEJhYUN0dlVuRk1WM1ZKUWtoRlkzRTNWVTlsWlhwUmNuVTVlRkZJU21zNFl6RklDbWxWT0U5cVMyazNPV0ZPUTAxRlFYZEVaXAogICAgICAxbEVWbEl3VUVGUlNDOUNRVkZFUVdkTGEwMUJPRWRCTVZWa1JYZEZRaTkzVVVaTlFVMUNRV1k0ZDBoUldVUUtWbEl3VDBKQ1dVVkdSXAogICAgICAxbDFaRTFVYjNGTU5EQk1lREJQY1VZMVZXdElSR0ZtVkRWQ1RVRnZSME5EY1VkVFRUUTVRa0ZOUTBFd1kwRk5SVkZEU1Vkd2VRcFJaXAogICAgICBtdDBkbm8yUVVsVFNXMU9USGxxUVhKQ2FWaEllbUZVZG1wb1JrODBRMVJOZG5WUldGTmhRV2xCYkZwcWJYZE1hRGxvUm1kSVVGQk5WXAogICAgICAzcHpiMGhYQ201dVNIcEZSMncxVUdoYVRWVlBWRkpwV0ZGRldHYzlQUW90TFMwdExVVk9SQ0JEUlZKVVNVWkpRMEZVUlMwdExTMHQiCgp1c2VyczoKLSBuYW1lOiAidjEzMmhhcnZlc3Rlcm5vZGUiCiAgdXNlcjoKICAgIHRva2VuOiAia3ViZWNvbmZpZy11c2VyLXp6OXprNXJsamI6dmxwZDQ1ZDd0ODJzanBtaHQ2ajJuenQ5MmJoa243NzlyNzh2dmJqNHBxc2pudDZobDRmejZ3IgoKCmNvbnRleHRzOgotIG5hbWU6ICJ2MTMyaGFydmVzdGVybm9kZSIKICBjb250ZXh0OgogICAgdXNlcjogInYxMzJoYXJ2ZXN0ZXJub2RlIgogICAgY2x1c3RlcjogInYxMzJoYXJ2ZXN0ZXJub2RlIgoKY3VycmVudC1jb250ZXh0OiAidjEzMmhhcnZlc3Rlcm5vZGUi
kind: Secret
metadata:
  annotations:
    field.cattle.io/creatorId: user-zz9zk
    field.cattle.io/description: harvester v132 cloud credential start
    field.cattle.io/name: harvester-v132-cc-v292-start
    provisioning.cattle.io/driver: harvester
    rancher.io/expiration-timestamp: "1729293086000"
  creationTimestamp: "2024-10-18T21:34:39Z"
  generateName: cc-
  labels:
    cattle.io/creator: norman
  name: cc-r99ml
  namespace: cattle-global-data
  resourceVersion: "400768"
  uid: fa65910a-e5d9-401b-9bc6-5f526180b6dd
type: Opaque

```

### v2.10.0-alpha3
- can renew cloud credentials from both index of cloud-credentials & clusters
- can build new cloud credentials that have all the appropriate information
```
╭─mike at suse-workstation-team-harvester in ~/Projects/rancher-feature
╰─○ kubectl get secrets/cc-b2jmx -n cattle-global-data -o yaml | yq
apiVersion: v1
data:
  harvestercredentialConfig-clusterId: Yy1tLXFqN2hua2Yy
  harvestercredentialConfig-clusterType: aW1wb3J0ZWQ=
  harvestercredentialConfig-kubeconfigContent: YXBpVmVyc2lvbjogdjEKa2luZDogQ29uZmlnCmNsdXN0ZXJzOgotIG5hbWU6ICJ2MTMyaGFydmVzdGVybm9kZSIKICBjbHVzdGVyOgogICAgc2VydmVyOiAiaHR0cHM6Ly9yYW5jaGVyLjE5Mi4xNjguMTA0LjIwNC5zc2xpcC5pby9rOHMvY2x1c3RlcnMvYy1tLXFqN2hua2YyIgogICAgY2VydGlmaWNhdGUtYXV0aG9yaXR5LWRhdGE6ICJMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VKMlJFTkRRXAogICAgICBWZFBaMEYzU1VKQlowbENRVVJCUzBKblozRm9hMnBQVUZGUlJFRnFRa2ROVW5kM1IyZFpSRlpSVVV0RmVFNXJaVmMxYUdKWGJHb0tZXAogICAgICBrZHNlbVJIVm5WYVdFbDBZak5LYmsxVFdYZEtRVmxFVmxGUlJFUkNNV3RsVnpWb1lsZHNhbUpIYkhwa1IxWjFXbGhKZEZreVJrRk5WXAogICAgICBHTjVUMVJKTkFwTmFrVjRUbXBCWlVaM01IbE9SRVYzVFZSbmVVMUVRVFJOZWxwaFJuY3dlazVFUlhkTlZGbDVUVVJCTkUxNldtRk5SXAogICAgICBWbDRTRVJCWVVKblRsWkNRVzlVQ2tVeVVqVmliVVowWVZkT2MyRllUakJhVnpWc1kya3hkbU50WTNoS2FrRnJRbWRPVmtKQlRVMUlWXAogICAgICAxSTFZbTFHZEdGWFRuTmhXRTR3V2xjMWJHTnBNV29LV1ZWQmVFNTZTVFZOYW1kNVRWUkZNazFHYTNkRmQxbElTMjlhU1hwcU1FTkJVXAogICAgICBWbEpTMjlhU1hwcU1FUkJVV05FVVdkQlJVUnJjMVl5V2xkVVNsRkpTZ295WkhKaFprOVZWVkp5ZGtVeVVXTlNSRlEwVUVreVkweFVXXAogICAgICBtVnVOSEJhYUN0dlVuRk1WM1ZKUWtoRlkzRTNWVTlsWlhwUmNuVTVlRkZJU21zNFl6RklDbWxWT0U5cVMyazNPV0ZPUTAxRlFYZEVaXAogICAgICAxbEVWbEl3VUVGUlNDOUNRVkZFUVdkTGEwMUJPRWRCTVZWa1JYZEZRaTkzVVVaTlFVMUNRV1k0ZDBoUldVUUtWbEl3VDBKQ1dVVkdSXAogICAgICAxbDFaRTFVYjNGTU5EQk1lREJQY1VZMVZXdElSR0ZtVkRWQ1RVRnZSME5EY1VkVFRUUTVRa0ZOUTBFd1kwRk5SVkZEU1Vkd2VRcFJaXAogICAgICBtdDBkbm8yUVVsVFNXMU9USGxxUVhKQ2FWaEllbUZVZG1wb1JrODBRMVJOZG5WUldGTmhRV2xCYkZwcWJYZE1hRGxvUm1kSVVGQk5WXAogICAgICAzcHpiMGhYQ201dVNIcEZSMncxVUdoYVRWVlBWRkpwV0ZGRldHYzlQUW90TFMwdExVVk9SQ0JEUlZKVVNVWkpRMEZVUlMwdExTMHQiCgp1c2VyczoKLSBuYW1lOiAidjEzMmhhcnZlc3Rlcm5vZGUiCiAgdXNlcjoKICAgIHRva2VuOiAia3ViZWNvbmZpZy11c2VyLXp6OXpranRrYzQ6MmZzZGsybTdtczdrNjdoeHpubHdtZGpoNGd4cWxwdnQ1bGtrbWdkczJremp4cG1zcnZwNzc3IgoKCmNvbnRleHRzOgotIG5hbWU6ICJ2MTMyaGFydmVzdGVybm9kZSIKICBjb250ZXh0OgogICAgdXNlcjogInYxMzJoYXJ2ZXN0ZXJub2RlIgogICAgY2x1c3RlcjogInYxMzJoYXJ2ZXN0ZXJub2RlIgoKY3VycmVudC1jb250ZXh0OiAidjEzMmhhcnZlc3Rlcm5vZGUi
kind: Secret
metadata:
  annotations:
    field.cattle.io/creatorId: user-zz9zk
    field.cattle.io/description: new v2.10.0-alpha3 harvester cc
    field.cattle.io/name: new-harvester-cc
    provisioning.cattle.io/driver: harvester
    rancher.io/expiration-timestamp: "1729294521000"
  creationTimestamp: "2024-10-18T22:23:58Z"
  generateName: cc-
  labels:
    cattle.io/creator: norman
  name: cc-b2jmx
  namespace: cattle-global-data
  resourceVersion: "410181"
  uid: e8d3e111-fad0-4fe1-bac5-d58c562c7b8d
type: Opaque
  
```
- can setup new clusters from new cloud credentials
- can scale clusters (up & down), new-&-old
- v0.7.0 harvester node driver works appropriately
```
╭─mike at suse-workstation-team-harvester in ~/Projects/rancher-feature
╰─○ curl -k https://rancher.192.168.104.204.sslip.io/assets/docker-machine-driver-harvester -o docker-machine-driver-v210-head        
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 51.5M  100 51.5M    0     0  99.7M      0 --:--:-- --:--:-- --:--:-- 99.9M
╭─mike at suse-workstation-team-harvester in ~/Projects/rancher-feature
╰─○ sha256sum docker-machine-driver-v210-head 
ee28240ca31f44f4ee003040da1d92e92a2487dbd96a387c8fe647c605b27d60  docker-machine-driver-v210-head
╭─mike at suse-workstation-team-harvester in ~/Projects/rancher-feature
╰─○ sha256sum ./v070/docker-machine-driver 
sha256sum: ./v070/docker-machine-driver: No such file or directory
╭─mike at suse-workstation-team-harvester in ~/Projects/rancher-feature
╰─○ sha256sum ./v070/docker-machine-driver-harvester
ee28240ca31f44f4ee003040da1d92e92a2487dbd96a387c8fe647c605b27d60  ./v070/docker-machine-driver-harvester

```

- [had to implement workaround for new clusters w/ new cloud-credential but in process of being fixed](https://github.com/harvester/harvester/issues/6821#issuecomment-2423358511)
- epoch time looks appropriate for renewal , changes with renewal
- post/put calls across the wire look appropriate

### Supporting Screen Grabs
![Screenshot from 2024-10-18 16-30-13](https://github.com/user-attachments/assets/1a10af09-7f47-44ba-a1f6-9ff1b9c5c8a3)
![Screenshot from 2024-10-18 16-28-47](https://github.com/user-attachments/assets/3ccdd972-598b-4f9b-b0ce-b14c18bfe192)
![Screenshot from 2024-10-18 16-27-53](https://github.com/user-attachments/assets/5154e8f1-9650-471d-8455-cfd2ae5affef)
![Screenshot from 2024-10-18 16-27-36](https://github.com/user-attachments/assets/9a19cd41-7686-44bb-84b1-de49d2ddbdc6)
![Screenshot from 2024-10-18 16-15-49](https://github.com/user-attachments/assets/000762c5-796c-4605-8698-5ef776e60c88)
![Screenshot from 2024-10-18 16-15-24](https://github.com/user-attachments/assets/6e5d812b-9d03-4765-8f8d-d4bd9d85f6d1)
![Screenshot from 2024-10-18 16-13-40](https://github.com/user-attachments/assets/20757a8c-f330-405b-89d3-4e45572dadd6)
![Screenshot from 2024-10-18 16-11-09](https://github.com/user-attachments/assets/a07a15d1-86e6-474f-80c5-c3c6ea6afcb9)
![Screenshot from 2024-10-18 15-32-06](https://github.com/user-attachments/assets/18216285-b826-4b74-a80e-1496048931fc)
![Screenshot from 2024-10-18 15-27-50](https://github.com/user-attachments/assets/91d3f72c-e565-478e-a207-548eea36a640)
![Screenshot from 2024-10-18 15-24-41](https://github.com/user-attachments/assets/99a50542-5716-40a0-a13b-ec7a32903097)
![Screenshot from 2024-10-18 15-23-50](https://github.com/user-attachments/assets/bb75cb65-5fe8-4dc9-bcc9-ca6075e00ec5)
![Screenshot from 2024-10-18 15-23-10](https://github.com/user-attachments/assets/2684f7d6-5c69-48b2-9834-f4baf587ae0f)
![Screenshot from 2024-10-18 15-18-00](https://github.com/user-attachments/assets/0126e33a-aefe-4f7e-aca1-1a815af416c7)
![Screenshot from 2024-10-18 15-15-11](https://github.com/user-attachments/assets/b746848f-1171-468c-bd68-d50d1a8e0f94)
![Screenshot from 2024-10-18 15-07-43](https://github.com/user-attachments/assets/2d1474eb-e7cf-4a33-8e2d-5d67acf74390)
![Screenshot from 2024-10-18 15-07-12](https://github.com/user-attachments/assets/e34b9b26-7d20-4ac7-9dae-03e5fef57887)
![Screenshot from 2024-10-18 15-04-17](https://github.com/user-attachments/assets/e2eddbc3-aeb7-4189-8daf-017a98d2d00e)
![Screenshot from 2024-10-18 15-01-21](https://github.com/user-attachments/assets/364d2b09-1d01-4eba-926b-0685c1379727)
![Screenshot from 2024-10-18 15-00-35](https://github.com/user-attachments/assets/fe79e3b9-2df0-4c17-932e-70dfbad0e193)
![Screenshot from 2024-10-18 14-48-10](https://github.com/user-attachments/assets/237be12e-105d-4283-80f2-e5f3b9303319)
![Screenshot from 2024-10-18 14-47-29](https://github.com/user-attachments/assets/d4278172-eda9-4cb9-b454-33d91b085d60)
![Screenshot from 2024-10-18 16-53-30](https://github.com/user-attachments/assets/3701456f-711d-4e43-9afb-d816795b4441)
![Screenshot from 2024-10-18 16-40-10](https://github.com/user-attachments/assets/41d7d1a4-3160-4383-93c1-dc2f0d10f52e)
