### ISSUE TITLE
[BUG] Unable to view local cluster in Cluster Explorer or Cluster Management in IPv6 environment

### ISSUE THREAD

**Issue by markusewalker** [rancher/rancher#52255]
**Rancher Server Setup**
- Rancher version: `head` https://github.com/rancher/rancher/commit/0692e5844f6f6a7befa1fdde37a114a219e2fca2
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**

Upon provisioning a Rancher IPv6 environment, I noted the following for the `local` cluster:

<img width="1851" height="365" alt="Image" src="https://github.com/user-attachments/assets/279fe2d8-8d1f-4244-b91a-eccee54fa74a" />

Note that the local cluster icon is missing and that we're unable to see the Version/Architecture.

**To Reproduce**

1. Setup Rancher IPv6 environment.
2. Note that the local cluster does not appear in Cluster Explorer.

**Result**
Unable to see the local cluster in Cluster Explorer and unable to view information in Cluster Management.

**Expected Result**

Should be able to see the local cluster in Cluster Explorer and unable to view information in Cluster Management.

**Comment by anmazzotti** [comment]
@markusewalker May you check if this fixed the issue? https://github.com/rancher/rancher/pull/52269

Also beware that on a fresh installation, it may take longer than usual (a few minutes) for the local cluster to be visualized correctly in the Dashboard. This is due CAPI crds being installed later via Turtles.

**Comment by markusewalker** [comment]
@anmazzotti still seeing this issue on commit https://github.com/rancher/rancher/commit/c67321175fd9bcc18114c20446a1c1a655cca37a. My Rancher has been up for about 20 minutes now, but still no dice, unfortunately.

**Comment by snasovich** [comment]
This is happening due to `rancher-turtles-controller-manager` crashlooping following the merge of https://github.com/rancher/rancher/pull/52067 and Rancher not updating `local` cluster as expected due to waiting on CAPI CRDs to be created.

The root cause of the crashloop seems to be dependency on `api.github.com` which doesn't support IPv6, see below from `rancher-turtles-controller-manager` logs:
```
E1010 17:47:00.068302       1 controller.go:347] "Reconciler error" err="[failed to create config map for provider \"cluster-api\": failed to read metadata.yaml from the repository for provider \"cluster-api\": failed to get GitHub release v1.10.6: failed to read release \"v1.10.6\": Get \"https://api.github.com/repos/kubernetes-sigs/cluster-api/releases/tags/v1.10.6\": dial tcp 140.82.112.5:443: connect: network is unreachable, failed to patch CAPIProvider capi-system/cluster-api: client rate limiter Wait returned an error: context canceled]"
```

This _should_ be addressed with https://github.com/rancher/turtles/pull/1805 and we will want to install Turtles with `airGapped` by default.

**Comment by markusewalker** [comment]
Noting that I am still seeing this behavior on `head` https://github.com/rancher/rancher/commit/32316ab6ab5d2393aca5728939a22cbf6bd641fb.

**Comment by markusewalker** [comment]
Validated that I am no longer seeing this issue on `head` https://github.com/rancher/rancher/commit/abc2ef9403c11d543c048544371ac6ab7eddc52b. I am successfully able to view the local cluster again and navigate to the icon, taking me to the Cluster Explorer.
