### ISSUE TITLE
[BUG] Single-Node Docker Rancher Local Cluster fails to start due to rancher-webhook on each reboot

### ISSUE THREAD

**Issue by JohReit** [rancher/rancher#53053]
**Rancher Server Setup**
- Rancher version: 2.13.0, 2.12.3, 2.11.3, 2.10.3
- Installation option (Docker install/Helm Chart): Docker k3s
- Proxy/Cert Details: HTTP proxy is in use, Rancher generated TLS

**Information about the Cluster**
- Kubernetes version: v1.34.1+k3s1
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
After every update following this update path: 2.9.1 --> 2.9.3 --> 2.10.3 --> 2.11.3 --> 2.12.3 --> 2.13.0 the rancher local cluster fails to start with:
```
2025/12/11 10:31:54 [FATAL] Internal error occurred: failed calling webhook "rancher.cattle.io.namespaces.create-non-kubesystem": failed to call webhook: Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation/namespaces?timeout=10s": no endpoints available for service "rancher-webhook"
```
This has already been described in issue: https://github.com/rancher/rancher/issues/45841 and can be avoided by   uninstalling the rancher-webhook in the local cluster prior to upgrading with:
`helm uninstall rancher-webhook -n cattle-system`
The system then reinstalls the rancher-webhook automatically after a succesfull start of the cluster. It is also stated that this has been fixed with version 2.9.1, which does not appear to be the case.

Additionally, this exact issue currently occurs on every restart of the container, in which case a rollback is either not possible or feasible.
We are working around this issue by uninstalling the rancher-webhook Helm-chart from the container's shell on each restart in the window between cluster start and error occurence with the following commands, starting on the docker host:

1. Wait for container to fail and restart
2. Enter container with `docker exec -ti <CONTAINER_NAME> bash`
3. Find helm executable with `find / -name helm` and navigate to its directory
4. Uninstall webhook with `helm uninstall rancher-webhook -n cattle-system`

**To Reproduce**
Restart container or its host after following the stated upgrade path.

**Result**
Container fails to start with:
```
2025/12/11 10:31:54 [FATAL] Internal error occurred: failed calling webhook "rancher.cattle.io.namespaces.create-non-kubesystem": failed to call webhook: Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation/namespaces?timeout=10s": no endpoints available for service "rancher-webhook"
```

**Expected Result**
Container and cluster starts without an issue.

**Additional context**
Unfortunately I can't exactly pinpoint the exact version where this started happening as the upgrades were executed consecutively.

**Comment by bpedersen2** [comment]
It seems I did see  a similar behaviour  sometimes.
What I also observed: After the restart the rancher service does not refresh it's IP, causing at least  fleet to fail.

my workaround does not require a helm remove, just temporarily disabling the webhook is enough:
```
docker exec -t <rancher container> bash -c "while true; do kubectl delete validatingwebhookconfigurations rancher.cattle.io; 
done"
```

**Comment by JohReit** [comment]
@bpedersen2 Are you running the script at all times? Because this issue has now started happening every other if not every single day without any reboots occuring and I have since scheduled the workaround to just run every 5 minutes.

**Comment by BloodyIron** [comment]
I'm having I think this exact same problem, wherein I did a lot of upgrading Rancher (Docker Install) recently from v2.7.5 -> v2.12.3 and I'm having this problem with some of my backups of the VM. ARGH! I guess this means it is NOT the backups I'm doing then...

What is the permanent solution here? I am not even sure the cause!

**Comment by bpedersen2** [comment]
> [@bpedersen2](https://github.com/bpedersen2) Are you running the script at all times? Because this issue has now started happening every other if not every single day without any reboots occuring and I have since scheduled the workaround to just run every 5 minutes.

No, only after a reboot if  it does not come up.

**Comment by BloodyIron** [comment]
> > [@bpedersen2](https://github.com/bpedersen2) Are you running the script at all times? Because this issue has now started happening every other if not every single day without any reboots occuring and I have since scheduled the workaround to just run every 5 minutes.
> 
> No, only after a reboot if it does not come up.

So you can actually get kubectl to interact with the k3s single-node cluster in the docker container to delete webhook-rancher? I'll have to try that as my attempts have not been successful, I must have been doing it wrong.

**Comment by bpedersen2** [comment]
This is running inside the docker container ( and once you see the successful deltion of the webhook (it normal takes 10-30 sec.)  you can and shoud stop the script again. Otherwise you will be constantly deleting the webhook.

**Comment by BloodyIron** [comment]
> This is running inside the docker container ( and once you see the successful deltion of the webhook (it normal takes 10-30 sec.) you can and shoud stop the script again. Otherwise you will be constantly deleting the webhook.

Yeah I got that, having to stop it. Argh I can't find a permanent fix this, currently having to do this very few days... what's the permanent fix here???

**Comment by JohReit** [comment]
> Yeah I got that, having to stop it. Argh I can't find a permanent fix this, currently having to do this very few days... what's the permanent fix here???

Well just as a temporary workaround until there's an actual fix: You can slightly modify @bpedersen2 command by just adding a wait and letting it run in the background. Not the prettiest workaround but better than doing it manually every few days:

```
docker exec -t <rancher container> bash -c "while true; do kubectl delete validatingwebhookconfigurations rancher.cattle.io; sleep 86400; done" &
```

If, as for me, the command doesn't find the validatingwebhookconfigurations you can use this instead:

```
docker exec -t <rancher container> bash -c "while true; do </path/to>/helm uninstall rancher-webhook -n cattle-system; sleep 86400; done" &
```

**Comment by JohReit** [comment]
As things go... another error that blocks the start of rancher has started to appear without any apparent changes:
```
2026/01/05 09:05:42 [INFO] Skipping handler for clusterrepo rancher-rke2-charts because the next retry time is 2026-01-05 09:10:10 +0000 UTC and now is 2026-01-05 09:05:42.580120058 +0000 UTC
2026/01/05 09:05:42 [ERROR] error syncing 'rancher-rke2-charts': handler helm-clusterrepo-ensure: ensure failure: git -C /var/lib/rancher-data/local-catalogs/v2/rancher-rke2-charts/675f1b63a0a83905972dcab2794479ed599a6f41b86cd6193d69472d0fa889c9 reset --hard FETCH_HEAD error: exit status 128, detail: fatal: Unable to create '/var/lib/rancher-data/local-catalogs/v2/rancher-rke2-charts/675f1b63a0a83905972dcab2794479ed599a6f41b86cd6193d69472d0fa889c9/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
, requeuing
```
This pattern of error has appeared for multiple of these lock files. However, this can be worked around rather easily by deleting the corresponding lock files. I had a similar error when initially upgrading to 2.13.0 which was solved in the same way:
```
Restoring git repositories:
- /var/lib/rancher-data/local-catalogs/v2/rancher-charts/4b40cac650031b74776e87c1a726b0484d0877c3ec137da0872547ff9b73a721/.git
fatal: Unable to create '/var/lib/rancher-data/local-catalogs/v2/rancher-charts/4b40cac650031b74776e87c1a726b0484d0877c3ec137da0872547ff9b73a721/.git/index.lock': File exists.
```
Not sure why or when these appear but perhaps it's related to the original issue?

**Comment by BloodyIron** [comment]
> As things go... another error that blocks the start of rancher has started to appear without any apparent changes:
> 
> ```
> 2026/01/05 09:05:42 [INFO] Skipping handler for clusterrepo rancher-rke2-charts because the next retry time is 2026-01-05 09:10:10 +0000 UTC and now is 2026-01-05 09:05:42.580120058 +0000 UTC
> 2026/01/05 09:05:42 [ERROR] error syncing 'rancher-rke2-charts': handler helm-clusterrepo-ensure: ensure failure: git -C /var/lib/rancher-data/local-catalogs/v2/rancher-rke2-charts/675f1b63a0a83905972dcab2794479ed599a6f41b86cd6193d69472d0fa889c9 reset --hard FETCH_HEAD error: exit status 128, detail: fatal: Unable to create '/var/lib/rancher-data/local-catalogs/v2/rancher-rke2-charts/675f1b63a0a83905972dcab2794479ed599a6f41b86cd6193d69472d0fa889c9/.git/index.lock': File exists.
> 
> Another git process seems to be running in this repository, e.g.
> an editor opened by 'git commit'. Please make sure all processes
> are terminated then try again. If it still fails, a git process
> may have crashed in this repository earlier:
> remove the file manually to continue.
> , requeuing
> ```
> 
> This pattern of error has appeared for multiple of these lock files. However, this can be worked around rather easily by deleting the corresponding lock files. I had a similar error when initially upgrading to 2.13.0 which was solved in the same way:
> 
> ```
> Restoring git repositories:
> - /var/lib/rancher-data/local-catalogs/v2/rancher-charts/4b40cac650031b74776e87c1a726b0484d0877c3ec137da0872547ff9b73a721/.git
> fatal: Unable to create '/var/lib/rancher-data/local-catalogs/v2/rancher-charts/4b40cac650031b74776e87c1a726b0484d0877c3ec137da0872547ff9b73a721/.git/index.lock': File exists.
> ```
> 
> Not sure why or when these appear but perhaps it's related to the original issue?

In my observation, with very limited evidence, I think it is related as I think the container being killed by the rancher-webhook issue doesn't clean up the index.lock files from the git tasks. I have this quite regularly too.

**Comment by qq592304796** [comment]
Even after upgrading to version 2.13.2, the problem persists.

**Comment by BloodyIron** [comment]
Yeah I have to delete the rancher-webhook aspects every few days just to have a workable Rancher instance :/

**Comment by hameno** [comment]
Same here, when is this finally going to be fixed?

**Comment by qq592304796** [comment]
Even after upgrading to version 2.13.3, the problem persists.

**Comment by BloodyIron** [comment]
Is this being looked at at all??? This error is still going on for me every few days! I have to delete the webhook each time and Rancher is completely unusable until then each time... This is causing real infra problems :/ and I don't even know if this is being taken serious at all.

**Comment by montarion** [comment]
> Is this being looked at at all??? This error is still going on for me every few days! I have to delete the webhook each time and Rancher is completely unusable until then each time... This is causing real infra problems :/ and I don't even know if this is being taken serious at all.

But this deployment isn't supported for production, so you shouldn't have infra issues.

**Comment by qq592304796** [comment]
Even after upgrading to version 2.14.0, the problem persists.

**Comment by BloodyIron** [comment]
> > Is this being looked at at all??? This error is still going on for me every few days! I have to delete the webhook each time and Rancher is completely unusable until then each time... This is causing real infra problems :/ and I don't even know if this is being taken serious at all.
> 
> But this deployment isn't supported for production, so you shouldn't have infra issues.

Where did I say it was being used for production? Why does that mean magically this issue _shouldn't_ be fixed? That's not even the least bit helpful, and really more looks to be trolling than anything.

**Comment by daleckystepan** [comment]
Reference: https://github.com/rancher/rancher/issues/42699#issuecomment-4536873057

**Comment by BloodyIron** [comment]
What version-ish could this fix realistically be implemented into Rancher for? Asking as more of a guess than a commitment, I don't know how "fast" fixes like this become publicly available (as in without a SUSE subscription, etc).

**Comment by daleckystepan** [comment]
Absolutely no idea. Let's se if fix will be accepted. And it is also fair to say that it might be fix only for our env not for all and fix needs to be extended somehow to cover them.

**Comment by jloisel** [comment]
Same issue here. The workaround by deleting "ValidatingWebhookConfiguration" works but is only temporary, on v2.13.3.

**Comment by maxsnow651-dev** [comment]
Thanks for the update — sorry you’re still running into this.

**Comment by BloodyIron** [comment]
Yeah I still have to delete the rancher webhook every few days too :/ really frustrating a proper fix still hasn't rolled out.

**Comment by JohReit** [comment]
I've decided to move the installation away from a docker-based deployment and setup an entirely new environment as single node rke2 as the issue has been stale for so long.

**Comment by jloisel** [comment]
I use Rancher precisely because I don't to have to deal with how rke2 internals, rke2 setup / maintenance is working. I just manage clusters via Rancher UI. Having to install Rancher inside an rke2 node / cluster kind of defeats the purpose. In that case, I'd rather entirely switch to manually deployed rke2 clusters without any UI and manage them on my own.

The docker setup is convenient and easy. Just one command line and it's done. It has worked fine for 5+ years for me, without any issue.

**Comment by BloodyIron** [comment]
Why is this taking so long to get fixed? This and multiple other github issues I'm involved in are going nowhere... it seems like the devs are just ignoring issues at this point... :/

**Comment by BloodyIron** [comment]
Okay so do the devs even care at all about this? Honestly this is really highlighting to me that this project ignores issues unless money is attached. WHEN IS THIS GOING TO GET FIXED?

**Comment by jloisel** [comment]
I think the problem lies in the fact that 3000+ issues are open. I hope they will fix this issue too (as well as backup / restore not working at all too), because it plagues the docker setup. I've been unable to upgrade from 2.13.3 to 2.14.3 either, the latest version won't simply start at all and crashes immediately.

**Comment by daleckystepan** [comment]
Based on my experience with this project, I wouldn't expect the maintainers to address this issue, as this deployment scenario is officially unsupported.
However, that doesn't mean we're out of options. We can investigate the root cause ourselves and submit a proposed fix via a PR. I've done this before for a similar issue, and the experience was surprisingly positive—the fix was reviewed and merged without major problems.

**Comment by BloodyIron** [comment]
> Based on my experience with this project, I wouldn't expect the maintainers to address this issue, as this deployment scenario is officially unsupported. However, that doesn't mean we're out of options. We can investigate the root cause ourselves and submit a proposed fix via a PR. I've done this before for a similar issue, and the experience was surprisingly positive—the fix was reviewed and merged without major problems.

What's the point of even having issue tracking for docker installs if the expectation they never get fixed? Wanting something to get fixed... eventually... isn't necessarily the same as typical "support expectations". No SLA or SLO has been declared, and that's reasonable I think. But this issue has been ongoing since at least December 2025, and nobody that I can tell has found a permanent solution, only work-arounds (which I myself rely on). It's commonplace in countless other open source projects, wherein "support is not present" is a thing, and yet the devs still chime in and work to fix things reported by those who don't pay for support services.

For me, it's more that there is _total radio silence_ as a problem, than that it "takes time to fix".

And yes, we certainly can make and submit PRs... for those who actually understand why it's breaking (not me) and know what needs to change to fix it (also not me). And in my case, it seems the devs (who again are radio silent) are best suited for identifying the root cause, and proposing a fix.

Based on the nature of this bug, it _SEEMS_ like a proper fix isn't necessarily going to be hard, but that's speaking from a position of ignorance and speculation, as I still have so much more to learn about kubernetes, and Rancher itself.

Another way to put it... why would I recommend Rancher for my customers (paid support or otherwise) if their devs won't even chime in for community fixes like this at all? Let alone come up with a fix... This is eroding my confidence in the ecosystem, by a lot.

And yes, 3.2k open issues is a very substantial amount of tickets, but how many of them are being ignored by the devs? At least one it seems.

**Comment by JohReit** [comment]
> For me, it's more that there is _total radio silence_ as a problem, than that it "takes time to fix".
> ...
> Another way to put it... why would I recommend Rancher for my customers (paid support or otherwise) if their devs won't even chime in for community fixes like this at all? Let alone come up with a fix... This is eroding my confidence in the ecosystem, by a lot.
> 
> And yes, 3.2k open issues is a very substantial amount of tickets, but how many of them are being ignored by the devs? At least one it seems.

Unfortunately, this is the same experience I've been having thus far. At least this issue has gotten some traction, others become stale as they are created. There's plenty of actual issues several years old without a single comment or acknowledgement, and also things like this:
- https://github.com/rancher/rancher/issues/43531

Even during normal operation it is the norm rather than an exception to encounter bugs or issues - be it minor UI or display bugs (wrong states, wrong numbers for deployments, non-refreshing events, broken ordering of lists, etc.) or more severe issues like duplicate users that loose assigned permissions when using external auth or this issue, all of which I've encountered myself. I'm certain that I as well will not be recommending this for further deployments.

Even while moving the installation away from the docker deployment, which is officially unsupported for production, to the supported RKE2 deployment I've encountered bugs with the then up-to-date version 2.14.2, one amongst which completely prevented the installation of downstream clusters. It seems like some additional personnel on this certainly wouldn't be wrong.

But well - I guess that's besides the point for this issue.

**Comment by BloodyIron** [comment]
> > For me, it's more that there is _total radio silence_ as a problem, than that it "takes time to fix".
> > ...
> > Another way to put it... why would I recommend Rancher for my customers (paid support or otherwise) if their devs won't even chime in for community fixes like this at all? Let alone come up with a fix... This is eroding my confidence in the ecosystem, by a lot.
> > And yes, 3.2k open issues is a very substantial amount of tickets, but how many of them are being ignored by the devs? At least one it seems.
> 
> Unfortunately, this is the same experience I've been having thus far. At least this issue has gotten some traction, others become stale as they are created. There's plenty of actual issues several years old without a single comment or acknowledgement, and also things like this:
> 
> * [test[BUG] #43531](https://github.com/rancher/rancher/issues/43531)
> 
> Even during normal operation it is the norm rather than an exception to encounter bugs or issues - be it minor UI or display bugs (wrong states, wrong numbers for deployments, non-refreshing events, broken ordering of lists, etc.) or more severe issues like duplicate users that loose assigned permissions when using external auth or this issue, all of which I've encountered myself. I'm certain that I as well will not be recommending this for further deployments.
> 
> Even while moving the installation away from the docker deployment, which is officially unsupported for production, to the supported RKE2 deployment I've encountered bugs with the then up-to-date version 2.14.2, one amongst which completely prevented the installation of downstream clusters. It seems like some additional personnel on this certainly wouldn't be wrong.
> 
> But well - I guess that's besides the point for this issue.

I'm just not sure what would be a competent and sufficient alternative to Rancher :/ it's a really great ecosystem and if I'm going to rip it out and replace it (many years worth of work thrown in the bin) it needs to be as capable or preferably better. Do you see any appropriate alternatives?

Alternatively, what would it take to get rancher devs to actually start being participants in these issues and get things fixed? Surely these issues are worth fixing for upstream purposes, as in those who PAY for support, in similar vein to iXsystems ala TrueNAS, Red Hat with CentOS/Fedora, and so many other examples.

**Comment by daleckystepan** [comment]
I have spent hours to fix it. Finally find a solution https://github.com/rancher/rancher/pull/56111 . Can anyone at least verify it works?

**Comment by BloodyIron** [comment]
> I have spent hours to fix it. Finally find a solution [#56111](https://github.com/rancher/rancher/pull/56111) . Can anyone at least verify it works?

Thanks for the contributions! I'm not sure how exactly to apply the changes to my own environment...
