### ISSUE TITLE
Environment variables relating to exposed port and address for linked container is missing.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6544]
Rancher-server version - Build from master

Steps to reproduce the problem:
Create service linked to a container with link name as "WEB1".
Containers of the service is expected to have the following env variables:

```

WEB1_PORT_80_TCP_ADDR=web1
WEB1_PORT_80_TCP_PORT=80

```

These variables are not present in the service containers.

```
=================================== FAILURES ===================================
_____________________ test_services_port_and_link_options ______________________

admin_client = <cattle.Client object at 0x10b833910>
client = <cattle.Client object at 0x10b54e310>, socat_containers = None

    def test_services_port_and_link_options(admin_client, client,
                                            socat_containers):
    
        hosts = client.list_host(kind='docker', removed_null=True, state="active")
    
        host = hosts[0]
        link_host = hosts[1]
    
        link_name = "WEB1"
        link_port = 80
        exposed_port = 9999
    
        link_container = client.create_container(
            imageUuid=LB_IMAGE_UUID,
            environment={'CONTAINER_NAME': link_name},
            name=random_str(),
            requestedHostId=host.id
            )
    
        link_container = client.wait_success(link_container)
    
        launch_config = {"imageUuid": SSH_IMAGE_UUID,
                         "ports": [str(exposed_port)+":22/tcp"],
                         "instanceLinks": {
                             link_name:
                                 link_container.id},
                         "requestedHostId": link_host.id,
                         }
    
        service, env = create_env_and_svc(client, launch_config, 1)
    
        env = env.activateservices()
        service = client.wait_success(service, 300)
    
        container_name = get_container_name(env, service, 1)
        containers = client.list_container(name=container_name, state="running")
        assert len(containers) == 1
        con = containers[0]
    
        validate_exposed_port_and_container_link(admin_client, con, link_name,
>                                                link_port, exposed_port)

/Users/sangeethahariharan1/cattle/validation/validation-tests/tests/v2_validation/cattlevalidationtest/core/test_services.py:358: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

admin_client = <cattle.Client object at 0x10b833910>
con = {'tty': False, 'registryCredentialId': None, 'labels': {'io.rancher.project_service.name': u'test202203/test119793', '...dex': 1, 'dnsSearch': [u'test202203.rancher.internal', u'test119793.test202203.rancher.internal', u'rancher.internal']}
link_name = 'WEB1', link_port = 80, exposed_port = 9999

    def validate_exposed_port_and_container_link(admin_client, con, link_name,
                                                 link_port, exposed_port):
        time.sleep(10)
        # Validate that the environment variables relating to link containers are
        # set
        containers = admin_client.list_container(externalId=con.externalId,
                                                 include="hosts",
                                                 removed_null=True)
        assert len(containers) == 1
        con = containers[0]
        host = admin_client.by_id('host', con.hosts[0].id)
        docker_client = get_docker_client(host)
        inspect = docker_client.inspect_container(con.externalId)
        response = inspect["Config"]["Env"]
        logger.info(response)
        address = None
        port = None
    
        env_name_link_address = link_name + "_PORT_" + str(link_port) + "_TCP_ADDR"
        env_name_link_name = link_name + "_PORT_" + str(link_port) + "_TCP_PORT"
    
        for env_var in response:
            if env_name_link_address in env_var:
                address = env_var[env_var.index("=")+1:]
            if env_name_link_name in env_var:
                port = env_var[env_var.index("=")+1:]
    
        logger.info(address)
        logger.info(port)
>       assert address and port is not None
E       assert (None and None is not None)

/Users/sangeethahariharan1/cattle/validation/validation-tests/tests/v2_validation/cattlevalidationtest/core/common_fixtures.py:906: AssertionError
---------------------------- Captured stderr setup -----------------------------
INFO:tests.v2_validation.cattlevalidationtest.core.test_services:time taken - 30.8764939308
INFO:tests.v2_validation.cattlevalidationtest.core.test_services:total time taken - 30.8764939308
----------------------------- Captured stderr call -----------------------------
INFO:tests.v2_validation.cattlevalidationtest.core.common_fixtures:[u'WEB1_NAME=/cattle/WEB1', u'WEB1_ENV_CONTAINER_NAME=WEB1', u'WEB1_ENV_NGINX_VERSION=1.7.11-1~wheezy', u'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin']
INFO:tests.v2_validation.cattlevalidationtest.core.common_fixtures:None
INFO:tests.v2_validation.cattlevalidationtest.core.common_fixtures:None
======= 60 tests deselected by '-k test_services_port_and_link_options' ========
=================== 1 failed, 60 deselected in 86.69 seconds ===================

Process finished with exit code 0

admin_client = <cattle.Client object at 0x10b833910>
client = <cattle.Client object at 0x10b54e310>, socat_containers = None

    def test_services_port_and_link_options(admin_client, client,
                                            socat_containers):
    
        hosts = client.list_host(kind='docker', removed_null=True, state="active")
    
        host = hosts[0]
        link_host = hosts[1]
    
        link_name = "WEB1"
        link_port = 80
        exposed_port = 9999
    
        link_container = client.create_container(
            imageUuid=LB_IMAGE_UUID,
            environment={'CONTAINER_NAME': link_name},
            name=random_str(),
            requestedHostId=host.id
            )
    
        link_container = client.wait_success(link_container)
    
        launch_config = {"imageUuid": SSH_IMAGE_UUID,
                         "ports": [str(exposed_port)+":22/tcp"],
                         "instanceLinks": {
                             link_name:
                                 link_container.id},
                         "requestedHostId": link_host.id,
                         }
    
        service, env = create_env_and_svc(client, launch_config, 1)
    
        env = env.activateservices()
        service = client.wait_success(service, 300)
    
        container_name = get_container_name(env, service, 1)
        containers = client.list_container(name=container_name, state="running")
        assert len(containers) == 1
        con = containers[0]
    
        validate_exposed_port_and_container_link(admin_client, con, link_name,
>                                                link_port, exposed_port)

/Users/sangeethahariharan1/cattle/validation/validation-tests/tests/v2_validation/cattlevalidationtest/core/test_services.py:358: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

admin_client = <cattle.Client object at 0x10b833910>
con = {'tty': False, 'registryCredentialId': None, 'labels': {'io.rancher.project_service.name': u'test202203/test119793', '...dex': 1, 'dnsSearch': [u'test202203.rancher.internal', u'test119793.test202203.rancher.internal', u'rancher.internal']}
link_name = 'WEB1', link_port = 80, exposed_port = 9999

    def validate_exposed_port_and_container_link(admin_client, con, link_name,
                                                 link_port, exposed_port):
        time.sleep(10)
        # Validate that the environment variables relating to link containers are
        # set
        containers = admin_client.list_container(externalId=con.externalId,
                                                 include="hosts",
                                                 removed_null=True)
        assert len(containers) == 1
        con = containers[0]
        host = admin_client.by_id('host', con.hosts[0].id)
        docker_client = get_docker_client(host)
        inspect = docker_client.inspect_container(con.externalId)
        response = inspect["Config"]["Env"]
        logger.info(response)
        address = None
        port = None
    
        env_name_link_address = link_name + "_PORT_" + str(link_port) + "_TCP_ADDR"
        env_name_link_name = link_name + "_PORT_" + str(link_port) + "_TCP_PORT"
    
        for env_var in response:
            if env_name_link_address in env_var:
                address = env_var[env_var.index("=")+1:]
            if env_name_link_name in env_var:
                port = env_var[env_var.index("=")+1:]
    
        logger.info(address)
        logger.info(port)
>       assert address and port is not None
E       assert (None and None is not None)

```

**Comment by deniseschannon** [comment]
Can we retest as the latest automation run doesn't have this failure? Due to all the networking/metadata fixes, this may have been addressed due to those fixes.

**Comment by sangeethah** [comment]
Tested with master build with commit 0c9c663a6e67c8c14be0bf067807db8ebb621169
rancher/dns:v0.10.2
rancher/healthcheck:v0.1.0
rancher/net:v0.6.2
rancher/metadata:v0.6.3
rancher/plugin-manager:v0.1.4
rancher/scheduler:v0.1.2

This issue is still reproducible.

**Comment by alena1108** [comment]
@StrongMonkey could you look at it? might be an agent bug. We used to propagate env vars based on links

**Comment by StrongMonkey** [comment]
looked at the agent's code, not sure if that is a agent bug. In our agent we have several test cases that already covered `links`. If the instanceLinks come at this format: ```"instanceLinks" : [
                    {
                        "type" : "instanceLink",
                        "linkName" : "mysql",
                        "data" : {
                            "fields" : {
                                "ports" : [
                                    {
                                        "publicPort" : "12345",
                                        "ipAddress" : "127.0.0.1",
                                        "privatePort" : "3306",
                                        "protocol" : "tcp"
                                    },
                                    {
                                        "publicPort" : "12346",
                                        "ipAddress" : "127.0.0.2",
                                        "privatePort" : "3307",
                                        "protocol" : "udp"
                                    }
                                ]
                            }
                        },
                        "targetInstanceId" : null
                    },
                    {
                        "type" : "instanceLink",
                        "linkName" : "redis",
                        "data" : {
                            "fields" : {
                                "ports" : [
                                    {
                                        "publicPort" : "23456",
                                        "ipAddress" : "127.0.0.1",
                                        "privatePort" : "26",
                                        "protocol" : "udp"
                                    }
                                ],
                                "instanceNames" : [
                                    "env_redis_1",
                                    "env_redis_2"
                                ]
                            }
                        },
                        "targetInstanceId" : 42,
                        "targetInstance" : {
                            "uuid" : "anothercontainer",
                            "data" : {
                                "dockerInspect": {
                                    "Config": {
                                        "Env": [
                                            "JUSTKEY",
                                            "PATH=x",
                                            "HOME=x",
                                            "ONE=TWO",
                                            "THREE=FOUR"
                                        ]
                                    }
                                }
                            }
                        }
                    }
                ],```, agent should populate env variables correctly. I ll keep debugging in agent but also want to make sure api in cattle hasn't change too much.

**Comment by StrongMonkey** [comment]
Build from cattle master(4693dac328d6944c74c743efe99af70f58e15a99).
Tested with local host and server, i got the following error: 
```
=================================== FAILURES ===================================
_____________________ test_services_port_and_link_options ______________________

admin_client = <cattle.Client object at 0x109243210>
client = <cattle.Client object at 0x10b350710>, socat_containers = None

    def test_services_port_and_link_options(admin_client, client,
                                            socat_containers):
    
        hosts = client.list_host(kind='docker', removed_null=True, state="active")
    
        host = hosts[0]
        link_host = hosts[1]
    
        link_name = "WEB1"
        link_port = 80
        exposed_port = 9999
    
        link_container = client.create_container(
            imageUuid=LB_IMAGE_UUID,
            environment={'CONTAINER_NAME': link_name},
            name=random_str(),
            requestedHostId=host.id
            )
    
        link_container = client.wait_success(link_container)
    
        launch_config = {"imageUuid": SSH_IMAGE_UUID,
                         "ports": [str(exposed_port)+":22/tcp"],
                         "instanceLinks": {
                             link_name:
                                 link_container.id},
                         "requestedHostId": link_host.id,
                         }
    
        service, env = create_env_and_svc(client, launch_config, 1)
    
        env = env.activateservices()
        service = client.wait_success(service, 300)
    
        container_name = get_container_name(env, service, 1)
        containers = client.list_container(name=container_name, state="running")
        assert len(containers) == 1
        con = containers[0]
    
        validate_exposed_port_and_container_link(admin_client, con, link_name,
>                                                link_port, exposed_port)

test_services.py:355: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

admin_client = <cattle.Client object at 0x109243210>
con = {'tty': False, 'registryCredentialId': None, 'labels': {'io.rancher.project_service.name': u'test984407/test15193', 'i...ndex': 1, 'dnsSearch': [u'test984407.rancher.internal', u'test15193.test984407.rancher.internal', u'rancher.internal']}
link_name = 'WEB1', link_port = 80, exposed_port = 9999

    def validate_exposed_port_and_container_link(admin_client, con, link_name,
                                                 link_port, exposed_port):
        time.sleep(sleep_interval)
        # Validate that the environment variables relating to link containers are
        # set
        containers = admin_client.list_container(externalId=con.externalId,
                                                 include="hosts",
                                                 removed_null=True)
        assert len(containers) == 1
        con = containers[0]
        host = admin_client.by_id('host', con.hosts[0].id)
        docker_client = get_docker_client(host)
        inspect = docker_client.inspect_container(con.externalId)
        response = inspect["Config"]["Env"]
        logger.info(response)
        address = None
        port = None
    
        env_name_link_address = link_name + "_PORT_" + str(link_port) + "_TCP_ADDR"
        env_name_link_name = link_name + "_PORT_" + str(link_port) + "_TCP_PORT"
    
        for env_var in response:
            if env_name_link_address in env_var:
                address = env_var[env_var.index("=")+1:]
            if env_name_link_name in env_var:
                port = env_var[env_var.index("=")+1:]
    
        logger.info(address)
        logger.info(port)
        assert address and port is not None
    
        # Validate port mapping
        ssh = paramiko.SSHClient()
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        ssh.connect(host.ipAddresses()[0].address, username="root",
                    password="root", port=exposed_port)
    
        # Validate link containers
        cmd = "wget -O result.txt  --timeout=20 --tries=1 http://" + \
              address+":"+port+"/name.html" + ";cat result.txt"
        logger.info(cmd)
        stdin, stdout, stderr = ssh.exec_command(cmd)
    
        response = stdout.readlines()
>       assert len(response) == 1
E       assert 0 == 1
E        +  where 0 = len([])
```
Agent is populating the correct environmental variable to containers. It failed at accessing the port of that container, not sure if it is a known issue now.

**Comment by deniseschannon** [comment]
@alena1108 Based on my convo with @StrongMonkey this is not an agent bug.

**Comment by alena1108** [comment]
@deniseschannon note that we have a bug for container link being unresolvable. https://github.com/rancher/rancher/issues/6584. As container links are legacy, we've dropped it from our DNS. Any container in the environment is resolved by containerName.rancher.internal

**Comment by deniseschannon** [comment]
@sangeethah Can you re-test? According to @ibuildthecloud he was unable to reproduce.

**Comment by sangeethah** [comment]
Tested with v1.2.0-pre4-rc14

@ibuildthecloud @StrongMonkey , With the latest RC , I see that the following variables set:

```
declare -x WEB1_PORT_80_TCP="tcp://web1:80"
declare -x WEB1_PORT_80_TCP_ADDR="web1"
declare -x WEB1_PORT_80_TCP_PORT="80"
``` 

But the link name itself is not resolvable which is the similar issue tracked in https://github.com/rancher/rancher/issues/6584

```
root@e9b693005501:/# ping WEB1
ping: unknown host WEB1
root@e9b693005501:/# ping web1
ping: unknown host web1
root@e9b693005501:/#
```
