### ISSUE TITLE
Rancher breaking "hostname -f"

### ISSUE THREAD

**Issue by chickahoona** [rancher/rancher#7113]
**Rancher Version:**
1.2.0

**Docker Version:**
Docker version 1.12.5, build 7392c3b

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 LTS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher with internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create a Rancher stack with the following composer content:
```
test:
  image: ubuntu:14.04
  hostname: mail
  domainname: example.com
  stdin_open: true
  tty: true
```
Execute shell and type the following command:
```hostname -f```

**Results:** 
You will see something like:
```hostname: Name or service not known```

(this happens because rancher doesnt update /etc/hosts proper)

**Expected:**

I would expect to see something like
```mail.example.com```

(If you run the same composer file with docker-compose it works)

Alot of scripts / docker images rely that this command works and use it to configure services and other things.

**Comment by darrenscerri** [comment]
This may have been fixed by #6855.

**Comment by chickahoona** [comment]
I updated my server and could reproduce the problem with:
```
Rancher	v1.2.1
Cattle	v0.174.8
User Interface	v1.2.39
Rancher Compose	v0.12.1
```

**Comment by mcanevet** [comment]
@chickahoona you also have to upgrade the network-services infrastructure stack

**Comment by chickahoona** [comment]
@mcanevet Thanks for your reply. I upgraded the network-services infrastrucutre stack (now on v0.0.5) , rebooted my rancher server and sadly still see the same problem.

**Comment by leodotcloud** [comment]
@chickahoona Can you launch a new container and check if you are still having the issue? I checked on my end, I don't see this problem with the latest version on my setup. As mentioned by @darrenscerri the issue has been fixed.

**Comment by superseb** [comment]
Difference here is using the domainname parameter and the use of `hostname -f`. Other issue was focused on adding the container hostname to `/etc/hosts` and the use of `hostname`.

**Comment by chickahoona** [comment]
@leodotcloud Sadly not working, tried again just to make sure.
New container started in rancher with this composer:

```
test:
  image: ubuntu:14.04
  hostname: mail
  domainname: example.com
  stdin_open: true
  tty: true
```

And if I connect to the container I still see this:

```
root@mail:/# hostname -f
hostname: Name or service not known
root@mail:/# cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

**Comment by leodotcloud** [comment]
@chickahoona I believe you need  rancher/network-manager:v0.2.15 or higher.

I just tested on my end, just launched a new 1.2.1 cluster, created container with ubuntu:14.04.3.

```
root@d0ed005b6a15:/# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group defaul
t qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
3: eth0@if17: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
group default
    link/ether ce:a8:08:ff:41:91 brd ff:ff:ff:ff:ff:ff
    inet 10.42.107.127/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::cca8:8ff:feff:4191/64 scope link tentative dadfailed
       valid_lft forever preferred_lft forever
root@d0ed005b6a15:/# hostname -f
d0ed005b6a15
root@d0ed005b6a15:/# hostname
d0ed005b6a15
root@d0ed005b6a15:/#
```

**Comment by chickahoona** [comment]
Im already using rancher/network-manager:v0.2.17 so your solution does not help me.

I uploaded an image with Ubuntu 16.04 as host system, newest docker, newest rancher so you can try it out yourself.
https://drive.google.com/file/d/0B8uIz6FoHhrsRjgwRXp4SzJuQzQ/view?usp=sharing

username: test
password: test

**Comment by leodotcloud** [comment]
I used your image, had to delete and restart the agent/services as you had a different IP address. I created a new container from the UI, with hostname/domain specified in the fields. And the newly started containers are not having any problems. Also there was an upgrade option available for the network services before I re-registered the host.

```
root@ubuntu:~#
root@ubuntu:~# docker ps -a
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS                     PORTS                              NAMES
85c1b02ab0e5        ubuntu:14.04.3                    "/.r/r /bin/bash"        2 minutes ago       Up 2 minutes                                                  r-zulu-01f8d40d
e1542b45fb0c        ubuntu:14.04.3                    "/.r/r /bin/bash"        4 minutes ago       Up 4 minutes                                                  r-alpha-88dfe60b
a080c539b507        ubuntu:14.04.3                    "/.r/r /bin/bash"        4 minutes ago       Up 4 minutes                                                  r-test123-acf680bd
38bcbc75c3cb        rancher/net:v0.7.5                "/.r/r start.sh"         6 minutes ago       Up 6 minutes                                                  r-ipsec-ipsec-1-1408fc9d
bc7c12d01d0c        rancher/net:v0.7.5                "sh -c 'touch /var/lo"   6 minutes ago       Up 6 minutes                                                  r-ipsec-ipsec-cni-driver-1-6396bc58
32513cc1bed7        ubuntu:14.04                      "/.r/r /bin/bash"        6 minutes ago       Up 6 minutes                                                  r-test-test-1-69c83f41
7fa9f34d5341        rancher/dns:v0.11.0               "rancher-dns --metada"   6 minutes ago       Up 6 minutes                                                  r-network-services-metadata-dns-1-cdf32395
6add937bf979        rancher/network-manager:v0.2.17   "/usr/bin/start.sh pl"   7 minutes ago       Up 7 minutes                                                  r-network-services-network-manager-1-884439c4
98c376ceb80e        rancher/metadata:v0.6.8           "start.sh rancher-met"   7 minutes ago       Up 7 minutes                                                  r-network-services-metadata-1-a5cdc3d9
9b428f86dcd1        rancher/agent:v1.1.1              "/run.sh run"            7 minutes ago       Up 7 minutes                                                  rancher-agent
841b21d810a4        rancher/agent:v1.1.1              "/run.sh http://172.1"   7 minutes ago       Exited (0) 7 minutes ago                                      nostalgic_montalcini
cf0f5a97b392        rancher/server                    "/usr/bin/entry /usr/"   3 hours ago         Up 11 minutes              3306/tcp, 0.0.0.0:8080->8080/tcp   stoic_rosalind
root@ubuntu:~#
root@ubuntu:~#
root@ubuntu:~#
root@ubuntu:~# docker exec -it 85c1b02ab0e5 hostname
yankee.xray.com
root@ubuntu:~# docker exec -it 85c1b02ab0e5 hostname -f
yankee.xray.com
root@ubuntu:~# docker exec -it e1542b45fb0c hostname
bravo.charlie.com
root@ubuntu:~# docker exec -it e1542b45fb0c hostname -f
bravo.charlie.com
root@ubuntu:~#
```

**Comment by chickahoona** [comment]
Pure docker works fine. It only occures when the image is started by rancher. Please do the following:

a) Start my VM

b) Go to http://192.168.1.14:8080/ (replace 192.168.1.14 with your ip)
c) Then go to:
`Stacks -> All -> Add Stack`

c) Paste the following content into the "Optional: docker-compose.yml content" field:
```
test:
  image: ubuntu:14.04
  hostname: mail
  domainname: example.com
  stdin_open: true
  tty: true
```

It should look like this:
![rancher-bug](https://cloud.githubusercontent.com/assets/8075146/21369936/acd96ad8-c709-11e6-8d9a-3b83dc80d670.png)


Click on create. Afterwards go to the console ofthe server and do a:

`hostname -f`

You should see something now like this:

![image](https://cloud.githubusercontent.com/assets/8075146/21369992/ebbe6a32-c709-11e6-8480-ee204539a641.png)

I hope this helps to troubleshoot the problem

**Comment by leodotcloud** [comment]
Cool! Thanks for the instructions. I was doing things differently, now I am able to reproduce the problem.

Reopening the issue.

**Comment by chickahoona** [comment]
No problem. Im glad that you digged through and can now reproduce the problem.

**Comment by leodotcloud** [comment]
Notes:
Taking a quick look at the output of `docker inspect` I see things being populated differently in these two scenarios. 

If started from UI:
```
        "Config": {
            "Hostname": "yankee.xray.com",
            "Domainname": "",
```

If started using the compose file:
```
        "Config": {
            "Hostname": "mike",
            "Domainname": "november.com",
```

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
