### ISSUE TITLE
Heapster can't gather information about pods/namespaces

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#7387]
**Rancher Versions:**
Server: v1.3.1-rc2
healthcheck: rancher/healthcheck:v0.2.0
ipsec: rancher/net:holder, rancher/net:v0.8.1
network-services: rancher/metadata:v0.7.0 rancher/network-manager:v0.4.0
scheduler: rancher/scheduler:v0.5.1
kubernetes (if applicable): rancher/k8s:v1.5.1-rancher1-7

**Docker Version:**
1.12
**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu 16.04
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 1.5.1
**Steps to Reproduce:**

- Install heapster on kubernetes (using the catalog template or manually)
- Open Grafana

**Results:** 
There are no data gathered for the pods/namespaces by heapster, only nodes data points are gathered:
```
root@heapster-9rhr2:/go# curl localhost:8082/api/v1/model/debug/allkeys
[
  "node:hussein-ubuntu-10acre-2.c.rancher-qa.internal",
  "node:hussein-ubuntu-10acre-1.c.rancher-qa.internal",
  "node:hussein-ubuntu-10acre-3.c.rancher-qa.internal",
  "cluster"
 ]
``` 
I confirmed that cadvisor is up and running on each host:
![containers-cadviosr](https://cloud.githubusercontent.com/assets/3309968/21871460/ed81a4ac-d86a-11e6-8c8a-4c87d9e0d16b.png)

The heapster container doesn't show any errors.

This issue has been seen also on k8s 1.4

**Comment by dipayanbiswas** [comment]
Facing the exact same problem from the last version of k8s as well

**Comment by wlan0** [comment]
@dipayanbiswas The solution was to mount the sys fs inside the kubelet container. https://github.com/rancher/rancher-catalog/pull/416 It'll be fixed in v1.4.0 release

**Comment by wlan0** [comment]
@galal-hussein please retest this with v1.5.2-rancher1-2

**Comment by dipayanbiswas** [comment]
Retested its working fine for me , thanks a ton !

**Comment by weikinhuang** [comment]
I'm still having this issue within grafana. (I just updated to 1.4.0-rc2 & upgraded cluster). In kubernetes dashboard, i'm able to see pod & node stats, but in grafana I'm only able to see the node stats and the kube-system ns stats. It doesn't list any of my other namespaces and other pods show no metrics collected.

**Comment by galal-hussein** [comment]
@wlan0 I validated the fix on Rancher v.1.4.0-rc2 with k8s image v1.5.2-rancher1-2, Grafana was able to see *both* data about nodes and namespaces/pods, thanks!

![grafana](https://cloud.githubusercontent.com/assets/3309968/22161106/9095a624-df51-11e6-88a2-5eacd8a7e509.png)

**Comment by weikinhuang** [comment]
@galal-hussein Have you tried with pods outside the kube-system/default namespace?

**Comment by wlan0** [comment]
@weikinhuang I'll test that case and get back to you. It's a bug if we can't see stats outside of those two namespaces.

**Comment by wlan0** [comment]
@weikinhuang I can see stats outside of these two namespaces. Just tested it. Did you wait sometime for the stats to get filled up? It takes a few minutes before you can see stats.

**Comment by weikinhuang** [comment]
@wlan0 I just tried again (running overnight), still only the 2 namespaces listed, and no pod data (But it does list a **all** the pods)

**Comment by weikinhuang** [comment]
Hm, nevermind. It seems that grafana just doesn't list the namespaces properly, if you change the url to the proper namespace, you will see data. Thanks!
