### ISSUE TITLE
k8s 1.6 

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#7706]
We should start looking at k8s 1.6 upgrade path. See if there are any big changes in building/packaging that would require catalog changes

**Comment by alena1108** [comment]
As a part of upgrade to 1.6, could you also switch to using latest event-subscriber package? there are some bugs that were fixed in the latest.

**Comment by deniseschannon** [comment]
v1.6.1 is now available in the `v1.6.0-dev` branch of catalog

**Comment by thomasmodeneis** [comment]
hi, I'm struggling to figure out how to make use of 1.6 in rancher as well, is there any docs in regards to how to make use of the `v1.6.0-dev branch of catalog` ?
Thanks.

**Comment by deniseschannon** [comment]
@thomasmodeneis we really don't recommend using any of our dev branches in our catalog until we have released the infra template officially. It hasn't gone through testing and sometimes there may be parts of the catalog that will require specific rancher release.

For example, since I have made this comment, we have released Rancher 1.6 and the k8s 1.6.x template was not released with it. The dev version of our k8s 1.6.x template has moved to a different catalog branch and requires using specific rancher release and still requires some UI changes and is not ready for public consumption. It has not gone through our QA team for testing so upgrading hasn't been tested.

**Comment by deniseschannon** [comment]
@galal-hussein a new template for k8s v1.6.x is available in `k8s-1.6-dev` with all new images. 

Can you validate upgrade and general k8s testing for this version?

**Comment by galal-hussein** [comment]
Rancher server: v1.6.3-rc2

K8S 1.6.6 tested and verified including:

- Validation tests
- Upgrade tests
- HA upgrade tests
- Testing Addons

**Comment by thomasmodeneis** [comment]
@deniseschannon thanks for your answer. 
However I'm still a bit confused, is 1.6.6 released for public usage or still not available ? 

Cheers.

**Comment by deniseschannon** [comment]
Kubernetes 1.6 was released and available when starting Rancher v1.6.3. @thomasmodeneis Let me know if you have more questions.
